### ISSUE TITLE
ElmConfig.MeasureLimitMs not read

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#102]
[`ElmConfig.MeasureLimitMs`](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/Config.fs#L11) is only written to when defining [`ElmConfig.Default`](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/Config.fs#L13-L17) (where it is set to `1`) and is _never_ read.

Currently [`measure`](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/ViewModel.fs#L117-L126) and [`measure2`](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/ViewModel.fs#L128-L137) contain the line
```
if sw.ElapsedMilliseconds > 0L then
```

Are these lines suppose to be
```
if sw.ElapsedMilliseconds > int64 config.MeasureLimitMs then
```

If so, preserving the default behavior would include initializing `ElmConfig.Default.MeasureLimitMs` to `0`.

Furthermore, it would be convenient if the type of `MeasureLimitMs` were already `int64` in order to avoid the conversion.

**Comment by cmeeren** [comment]
Ah, thanks!

I'd rather keep the property as `int` to avoid users having to add `L` (and to avoid a breaking change). But `measure` and `measure2` should indeed be fixed.

If you want to make a PR, please go ahead, otherwise I'll fix this.

**Comment by bender2k14** [comment]
Sure, I will make this change
