### ISSUE TITLE
Nested voption in type of selected VM in SubModelSelectedItem

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#110]
I just noticed that the `selected` property in the case `SubModelSelectedItem` of the discriminated union `VmBinding<'model, 'msg>` contains nested `voption`s.

https://github.com/elmish/Elmish.WPF/blob/c0ec0d3a9a605054895d10e8ee0980cddbd44ed0/src/Elmish.WPF/ViewModel.fs#L60-L61

What does it mean when the outer `voption` is in the case `ValueSome` but the inner `voption` is in the case `ValueNone`?

**Comment by cmeeren** [comment]
The inner is part of the actual value (i.e.`null` or not), and the outer is whether it's been set/initialized at all. So `ValueSome ValueNone` means "this sub-model binding has a `null` value" and `ValueNone` means "this sub-model binding does not have a value".

**Comment by bender2k14** [comment]
Thanks for providing this short insight.

> It's probably more clear if you see where and how `SubModelSelectedItem` is used throughout that file. :)

I completely admit that I didn't look into how it was used.  I noticed it as I was working on logging and wanted to fire off this quick question instead of getting sidetracked.
