### ISSUE TITLE
Prepare for disappearance of withSyncDispatch

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#112]
Elmish.WPF currenting uses [`Elmish.Program.withSyncDispatch`](https://github.com/elmish/elmish/blob/26b9ae3cbb3484d9fd0dabb319f4ffcfa6740b84/src/program.fs#L115-L118) here

https://github.com/elmish/Elmish.WPF/blob/5df8514ce4452883a1e417c9f6f479f545339f9e/src/Elmish.WPF/Program.fs#L32

As I understand it, three goals are achieved with this code.
1. [`dispatch` calls `setState`](https://github.com/elmish/elmish/blob/26b9ae3cbb3484d9fd0dabb319f4ffcfa6740b84/src/program.fs#L149), which mutates UI state.  That mutation must occur on the UI thread (otherwise an `InvalidOperationException` will occur).
2. [`dispatch`](https://github.com/elmish/elmish/blob/26b9ae3cbb3484d9fd0dabb319f4ffcfa6740b84/src/program.fs#L139-L156) is not thread safe due to race conditions related to improper message processing.  Executing `dispatch` only on the UI thread avoids this issue.
3. `dispatch` (via [`setState`](https://github.com/elmish/Elmish.WPF/blob/5df8514ce4452883a1e417c9f6f479f545339f9e/src/Elmish.WPF/Program.fs#L17-L25)) and the user (through the UI thread) can modify the state of the view.  Even without using `withSyncDispatch`, WPF would synchronously call `dispatch`, which avoids "many" race conditions.  However, it is also possible to call `dispatch` on a different thread (such as within an asynchronous command), and this can cause a race condition as describe in detail by @cmeeren in https://github.com/elmish/Elmish.WPF/issues/40#issue-345225772.  By executing `dispatch` on the UI thread, the mutation to the model reference by `dispatch` and the mutation to the view state by the UI thread stay consistent.

Are there any more goals that I missed?

The third one is the most complicated, so please do correct me if I said anything wrong.

In https://github.com/elmish/elmish/issues/185#issuecomment-519520317, @et1975 says that `withSyncDispatch` will be removed in the next major release of Elmish.

How will Elmish.WPF be modified to handle this change?

**Comment by cmeeren** [comment]
Re. 3: I don't see async being part of the problem. IIRC the problem was that when the message loop (including `update`) did not run on the UI thread, there was a race condition between Elmish and the user in modifying the UI state. Running the loop on the UI thread blocks the UI, which solves the problem.

> How will Elmish.WPF be modified to handle this change?

At a high level, @et1975 can probably answer this better than I can. Hopefully only trivially, like with the change to `withSyncDispatch`.

**Comment by bender2k14** [comment]
> I don't see async being part of the problem. IIRC the problem was that when the message loop (including update) did not run on the UI thread, there was a race condition between Elmish and the user in modifying the UI state. Running the loop on the UI thread blocks the UI, which solves the problem.

Yes, you are correct.  I only meant to suggest asynchronous computations as a common example of how a user might introduce multithreading into their application, but I forgot to explicitly say the part about there being an additional thread.  I edited that part of my comment.  Hopefully it is clear now.

**Comment by TysonMN** [comment]
I think the solution might be to change
https://github.com/elmish/Elmish.WPF/blob/9a24da90ee7293ba1aff9a02b31469c91bf24757/src/Elmish.WPF/Program.fs#L27-L33
to
```fsharp
let runElmish () =
  program
  |> Program.withSetState setState
  |> Program.run

element.Dispatcher.Invoke runElmish
```

If so, then we can make this change now.

**Comment by et1975** [comment]
Synchronized/Serialized dispatch is not going away, but it's an implementation detail of the current dispatch loop. I'm removing it from the `Program` abstraction and taking it as the loop implementation argument - you still get to specify how the synchronization happens, but you do it by parametrizing the loop, not the `Program`.

**Comment by TysonMN** [comment]
Great.  Then we have nothing to worry about.

Thanks @et1975 :)
