### ISSUE TITLE
Best practices for mutable objects in model?

### ISSUE THREAD

**Issue by reinux** [elmish/Elmish.WPF#113]
I'm working with a text/code editor control called [AvalonEdit](http://avalonedit.net/), which has a `TextDocument` class that contains all the text as well as methods for manipulating the text and events for changes to the text/filename/etc.

I thought about just wrapping it in a control along with the editor, and binding to a collection of lines, but it turns out there's no way to two-way bind to a collection, which is sensible.

So now I'm putting the `TextDocument` inside the model, which means my model is now mutable. I have a few questions about this:

- What are the caveats to having a mutable object in the model?
- How do I subscribe to events coming from an object in the model?
- Is this the right approach overall? 

Thanks in advance.

**Comment by reinux** [comment]
Yeah, that seems to be the best approach. Haven't run into any horrible roadblocks yet.

Will post here if I notice anything that might be worth mentioning.

Thanks for all the input!

**Comment by JDiLenarda** [comment]
@reinux : can we have a feedback, please ? I’m interested to know how you dealt with it.

**Comment by bender2k14** [comment]
The general feedback would be not to do it.

Why are you considering using mutuality?

**Comment by JDiLenarda** [comment]
I genuinely don’t get if it’s a technical opinion or if I’m told I broke some etiquette. If so, I apologize.

**Comment by bender2k14** [comment]
Oh, sorry.  I thought you were requesting general feedback about having the model contain mutable data.  I was stating a technical opinion.  To be clear, you are welcome to ask any question.  We will do our best to answer it.

@reinux, do you have an update that you can share about your use of mutability in the model?

**Comment by JDiLenarda** [comment]
So you mean mutability, not mutuality ? This word lost me. No worry, though.

More specifically, I’d like to know how reinux dealt with its use of a third-party component.

**Comment by bender2k14** [comment]
Oh, yes.  I corrected my "mutuality" for "mutability" typo.  Thanks :)

**Comment by reinux** [comment]
@JDiLenarda I think I've stumbled on a few repeatable patterns for factoring mutable state out of the model and dealing with non-MVVM stuff in general. @bender2k14 would love to have your input to know if I'm on the right track.

The editor and the document live happily in XAML now, and there are no direct references to it in the model.

The general idea is that there are only a handful of reasons to interact with a mutable object, and only a handful of ways to deal with them:
- You need to instantiate it. Do it in XAML if possible, bind to it if possible, but otherwise instantiate after the window constructor and use `Program.withSubscription`.
- You need it to do something. That can be done with a `Cmd.OfFunc`, which can be given to the `update` function through a Msg constructor parameter when the object is initialized, and stored in the model for use later.
- You need to react to something that happened on the mutable object. This is pretty straightforward: if `Binding.twoWay` won't work, add an event handler in `Program.withSubscription`. In many cases, if you need to call a method on the mutable object immediately in response, you can just pass in a `Cmd.OfFunc` at that point, use it in the `update`, and never bother storing it in the model.
- You need to ask it something, i.e. you need a return value or a property value, and that value changes frequently. This is the hardest case. I think there are only two options:
  - Update the model each time there's a `PropertyChanged` or equivalent, which means a lot of `updates` and in the worst case, a lot of battery drain.
  - Update the model just before you need the value, by making a `Cmd.OfFunc` that'll do the query on the mutable and return a `Cmd.batch` that updates the model and then does the desired operation. That's two extra update/view calls. You also have to be aware that your model can potentially be stale, and you have to be careful not to call the Msg that does the operation without first updating it.

The last case was the big sticking point for AvalonEdit. I optimized the heck out of the update loop using lazy bindings. `refEq` is useful for this, since it's the fastest, and occasional false positives are relatively harmless, and false negatives will never occur as long as the field is immutable (i.e. use a list or map, not an array or dictionary).

Assuming this is the right way to think about the problem, I think a simple media player would be a good place to illustrate these ideas, since `MediaElement` has frequently updating state and isn't very MVVM-friendly. If there's interest, I think I can whip something up, and we can polish it into a useful sample.

Also, this is probably dangerous information, but it turns out that a giant performance bottleneck in WPF when you have a ton of elements bound to F# objects is accessibility, because it calls `Object.Equals` on everything, and F# does structural comparison by default. If you have even just a hundred items bound to single-field records, and something (Narrator, some UI automation program or, for whatever reason, Google Chrome) causes your program to load Accessibility.dll, certain controls, notably `ListView`, will slow to a crawl. Since my application will be of no use to the visually impaired anyway, I ended up using [this workaround](https://stackoverflow.com/a/26433762/388626) to disable it.

**Comment by BentTranberg** [comment]
I use DevExpress WPF components heavily, and have exactly these kind problems to solve, all the time. I mostly use EventToCommand and in a few cases also KeyToCommand in the XAML. There's also other tools form DevExpress, but there's no point mentioning them I believe.

```
xmlns:dxmvvm="http://schemas.devexpress.com/winfx/2008/xaml/mvvm"

    <dxmvvm:Interaction.Behaviors>
        <dxmvvm:EventToCommand EventName="Loaded" Command="{Binding WhenLoaded}"/>
        <dxmvvm:EventToCommand EventName="Closed" Command="{Binding WhenClosed}"/>
        <dxmvvm:KeyToCommand KeyGesture="F7" Command="{Binding ShowStopTime}"/>
    </dxmvvm:Interaction.Behaviors>
```

These are DevExpress specific helpers, but I believe similar functionality exists in some Microsoft library that I can't remember the name of right now, but it deals with MVVM. Also elsewhere I would guess it can be found.

**Comment by reinux** [comment]
That looks to be comparable to [Microsoft.Xaml.Behaviors](https://github.com/Microsoft/XamlBehaviorsWpf).

**Comment by cmeeren** [comment]
> false negatives will never occur as long as the field is immutable (i.e. use a list or map, not an array or dictionary).

In fact, it is sufficient that an object is never mutated. If you use Array.map etc. then it's no problem using an array.

> Assuming this is the right way to think about the problem, I think a simple media player would be a good place to illustrate these ideas, since MediaElement has frequently updating state and isn't very MVVM-friendly. If there's interest, I think I can whip something up, and we can polish it into a useful sample.

If you think that can be a useful sample, you're more than welcome to create a PR! 😊

> it turns out that a giant performance bottleneck in WPF when you have a ton of elements bound to F# objects is accessibility, because it calls Object.Equals on everything, and F# does structural comparison by default

How about not binding to F# records and using subModelSeq instead? Or alternatively only binding to specially designed F# records that use reference equality? I think that in general, it would not be wise to bind to domain objects of that's what was happening.

**Comment by reinux** [comment]
> How about not binding to F# records and using subModelSeq instead? Or alternatively only binding to specially designed F# records that use reference equality? I think that in general, it would not be wise to bind to domain objects if that's what was happening.

Huh, that worked. I would never have suspected `subModelSeq` would be faster, since it's an additional layer, but I guess it makes sense that it would do equality faster. Are there other reasons not to use `oneWaySeq` for model objects?

**Comment by cmeeren** [comment]
To be honest I'm not sure exactly why I created `oneWaySeq` or in which situations it's faster than `subModelSeq`. If you just need to bind to a single value for each item, then it may be useful, but `oneWaySeqLazy` may improve performance.

In any case, If each item has several bindings, then in general I would always reach for `subModelSeq` first.

**Comment by reinux** [comment]
> To be honest I'm not sure exactly why I created `oneWaySeq` or in which situations it's faster than `subModelSeq`. If you just need to bind to a single value for each item, then it may be useful, but `oneWaySeqLazy` may improve performance.

Ah, good to know.

Are there any plans for a `subModelSeqLazy`? Or I wonder if I could combine it with `oneWayLazy` somehow to achieve the same effect.

**Comment by cmeeren** [comment]
I literally just made an issue for it 😆 #143 

I personally have no immediate plans to implement it. Let me know in that issue if you have measured `subModelSeq` to be a performance bottleneck and need a lazy version.

**Comment by reinux** [comment]
Sweet :D

I'll have something working soon which will require 60fps rendering, with a 1000+ element list in the model which doesn't need too be updated all the time. I also happen to have a version that doesn't use Elmish, so I can get a pretty good comparison of real world-ish performance.

Will test it on my old-ish desktop and mid-range i5 Surface Book and get back to you.

But first, I'll get that MediaElement sample going.

**Comment by cmeeren** [comment]
> I'll have something working soon which will require 60fps rendering, with a 1000+ element list in the model which doesn't need too be updated all the time. I also happen to have a version that doesn't use Elmish, so I can get a pretty good comparison of real world-ish performance.

That's very, very interesting. Looking forward to hearing about it!

**Comment by reinux** [comment]
So now that I have a better grasp of Elmish, the media player sample I've been working on seems weirdly trivial. I'll probably return to it sometime if I can think of a way to make it more compelling.

Meanwhile, having 1000+ items bound using `subModelSeq` turns out to be prohibitively expensive, taking several hundred milliseconds on my machine.The slowdown happens even if the sequence isn't actually bound to anything in the xaml. The `update` is fine.

`Elmish.WPF.ViewModel`2[System.__Canon,System.__Canon]::updateValue` is on the hottest path, specifically the `Seq.find` call. I've used an int64 for the ID, so it's not the eq that's taking long. Maybe the `ObservableCollection` can be paired with a dictionary or something?

For the time being, I'll just not use a binding for the giant list.

**Comment by cmeeren** [comment]
@bender2k14, perhaps some of that magical fairy dust in #137 could help significantly here?

Also probably relevant: #143. Tips/PRs welcome.
