### ISSUE TITLE
Use of ObservableCollection<T>.Remove(T)

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#134]
As first stated in https://github.com/elmish/Elmish.WPF/issues/131#issuecomment-536340393, I think the use of [`ObservableCollection<T>.Remove(T)`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1.remove?view=netframework-4.8) (in three calls in `updateValue`) is a bug.  Instead of removing by item, I think the correct implementation is to remove by index via [`ObservableCollection<T>.RemoveAt(Int32)`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1.removeat?view=netframework-4.8).

This issue will serve as the tracking of this (potential) problem (instead of #131...that issue has enough going on in it :P ).

Here is the relevant part of that previous comment.

------------

Recall the update logic for the `OneWaySeq` case of `updateValue`.
https://github.com/elmish/Elmish.WPF/blob/8f78f833bef5c903e6947b23688cef30480ccf8b/src/Elmish.WPF/ViewModel.fs#L341-L343

I think that call to `Remove` contains a bug.  The precise thing to do is remove by index.  Removing by item means that the collection needs to find which item to remove.  The documentation for `ObservableCollection<T>.Remove` [says](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1.remove?view=netframework-4.8#remarks) it removes the first item it finds for which that item and the given item return `true` when passed into the default equality comparer of type `T`.  If `itemEquals` is not the same as this default equality comparer, then this call to `Remove` will not have the intended behavior.  I can create a test that exhibits this problem and a PR with a fix.

**Comment by cmeeren** [comment]
Thanks! Yes, that should be changed for the reasons you describe.

Of course, when removing items via index, one must take care when using subsequent indexes.

Thank you so much for your willingness to create a PR with a test/fix! Elmish.WPF is getting better by the day thanks to your efforts 🙏

**Comment by bender2k14** [comment]
> ...when removing items via index, one must take care when using subsequent indexes.

Indeed.  In #149, I removed in reverse order to ensure each index to remove at is still correct when removing at it.

I just remembered that I haven't added a test for this yet.  I will create one tomorrow morning.

**Comment by bender2k14** [comment]
Resolved by #149

> I think the use of `ObservableCollection<T>.Remove(T)` (in three calls in updateValue) is a bug.

Two of them are in the `OneWaySeq` case and one is in the `SubModelSeq` case.  The last one is not a bug because the item being removed is our `ViewModel<,>` type.  Its `EqualityComparer<>.Default` checks for reference equality, so it removes correctly.  In contrast, the two for `OneWaySeq` are for user-defined types, so they can do crazy things like I did in the two tests I added.

**Comment by cmeeren** [comment]
> Resolved by #149

If you intend for this issue to be closed when that PR is merged, you can add `Closes #134` or `Fixes #134`, then GitHub will do it automatically.

**Comment by bender2k14** [comment]
Oh, great.  Done :)

**Comment by cmeeren** [comment]
Released in 3.5.1.
