### ISSUE TITLE
Improve failwith calls in ViewModel by moving them to initialization of bindings

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#135]
There are four places in [ViewModel](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/ViewModel.fs) where an exception is thrown.  There of those are for the same reason:

1. In `updateValue`,
https://github.com/elmish/Elmish.WPF/blob/12ad75bd2d82398b11f5b4b7d0d60eb2909921be/src/Elmish.WPF/ViewModel.fs#L486

2. In `TryGetMember`, and
https://github.com/elmish/Elmish.WPF/blob/12ad75bd2d82398b11f5b4b7d0d60eb2909921be/src/Elmish.WPF/ViewModel.fs#L574

3. In `TrySetMember`
https://github.com/elmish/Elmish.WPF/blob/12ad75bd2d82398b11f5b4b7d0d60eb2909921be/src/Elmish.WPF/ViewModel.fs#L599

I think we can improve this by moving these three failure points to one failure point when the [bindings are initialized](https://github.com/elmish/Elmish.WPF/blob/12ad75bd2d82398b11f5b4b7d0d60eb2909921be/src/Elmish.WPF/ViewModel.fs#L303-L311).  When we create the binding for a `SubModelSelectedItem` case, we case locate and store the corresponding `SubModelSeq` binding.  If we can't locate the the binding, then we raise that same exception here.  We would also sort the bindings here to make sure all the `SubModelSeq` bindings are initialized before all the `SubModelSelectedItem` bindings.

...Except it would be more readable if the the type of each binding case were a separately defined record type instead of a tuple.

Is there any downside to refactoring the cases of [`VmBinding<,>`](https://github.com/elmish/Elmish.WPF/blob/12ad75bd2d82398b11f5b4b7d0d60eb2909921be/src/Elmish.WPF/ViewModel.fs#L13-L68) to be like [`BindingData<,>`](https://github.com/elmish/Elmish.WPF/blob/12ad75bd2d82398b11f5b4b7d0d60eb2909921be/src/Elmish.WPF/Binding.fs#L111-L122) where the type of each case is a previously defined record type?

I think the behavior would be identical, and I would find the resulting code more readable.

**Comment by cmeeren** [comment]
I agree. It has been on my mind, but I haven't prioritized it. Feel free to send a PR with the changes you propose! 👍
