### ISSUE TITLE
how to open a OpenFileDialog?

### ISSUE THREAD

**Issue by jchain** [elmish/Elmish.WPF#147]
I found it a very basic operation for any serious app but I can't find the answer/sample to do so. 
I know there is a sample showing modal/non-modal (XAML) window but what I'm looking for is the common ones, like OpenFileDialog, under Microsoft.Win32 namespace. Someone asked a similar questions in #96 but the answer is too terse to follow.

Can anyone provide a more complete sample?

Thanks,

**Comment by cmeeren** [comment]
We should definitely write a sample on this.

From the top of my head, I think you write it like this:

Given this message type:

```f#
type Msg =
  | FileSelected of path: string
  | FileSelectCanceled
```

You write a function like this:

```f#
let openFile () =
  Application.Current.Dispatcher.Invoke(fun () ->
    let dlg = Microsoft.Win32.OpenFileDialog ()
    let result = dlg.ShowDialog ()
    if result.HasValue && result.Value
    then FileSelected dlg.FileName
    else FileSelectCanceled
  )
```

Then you invoke it using a command:

```f#
let update msg model =
  match msg with
  | OpenFileSelect -> model, Cmd.OfFunc.perform openFile () id
```

If you don't want `openFile` to reference your message type, you can have it return another type and then replace the `id` parameter above with a function that maps the return type to the message type.

Alternatively, you can also let `openFile` accept dispatch:

```f#
let openFile (dispatch: Msg -> unit) =
  Application.Current.Dispatcher.Invoke(fun () ->
    let dlg = Microsoft.Win32.OpenFileDialog ()
    let result = dlg.ShowDialog ()
    if result.HasValue && result.Value
    then dispatch (FileSelected dlg.FileName)
    else dispatch FileSelectCanceled
  )
```

Then you invoke it using `Cmd.ofSub`:

```f#
let update msg model =
  match msg with
  | OpenFileSelect -> model, Cmd.ofSub openFile
```

Let me know if I got this right (again, it's from the top of my head).

**Comment by JDiLenarda** [comment]
If you want to run your dialog asynchronously (so that it won't block the Elmish dispatch loop, yet block the UI as a modal window) do it this way :

```
let openFile () =
  let guiCtx = System.Threading.SynchronizationContext.Current
  async {
    do! Async.SwitchToContext guiCtx
    let dlg = Microsoft.Win32.OpenFileDialog ()
    let result = dlg.ShowDialog ()
    if result.HasValue && result.Value
    then return (FileSelected dlg.FileName)
    else return FileSelectCanceled
  }
```

And then call it with `Cmd.OfAsyncImmediate`.

`MessageBox` from `System.Windows` can be use the same way.

**Comment by cmeeren** [comment]
I don't think that's right; AFAIK you still have to wrap it in `Application.Current.Dispatcher.Invoke` (otherwise `SynhronizationContext.Current may not be the UI context).

Also, if you have successfully captured the UI context outside of the `async` CE and switch to it first thing inside, I don't think you have to use the `OfAsyncImmediate` version. Please correct me if I'm wrong.

I can't test right now, but I think this would work:

```f#
let openFile () =
  Application.Current.Dispatcher.Invoke(fun () ->
    let guiCtx = System.Threading.SynchronizationContext.Current
    async {
      do! Async.SwitchToContext guiCtx
      let dlg = Microsoft.Win32.OpenFileDialog ()
      let result = dlg.ShowDialog ()
      if result.HasValue && result.Value
      then return (FileSelected dlg.FileName)
      else return FileSelectCanceled
    }
  )
```

**Comment by JDiLenarda** [comment]
@cmeeren : I just copied and pasted it from some code I wrote 2 months ago, and I was surprised to find out I didn't use `Dispatcher.Invoke` as well, but last time I checked this code works :D

If such a function is to be called only as Cmd, I see no reason to not be called from UI thread, but I may miss something. I'll try to dig a little on that today if I can.

**Comment by cmeeren** [comment]
> last time I checked this code works

I would expect it to be indeterministic; it might work often, but not always (or it might work always now, but not in the future after otherwise non-breaking library changes).
