### ISSUE TITLE
Get model of cmdParam bound to DataContext

### ISSUE THREAD

**Issue by KingKnecht** [elmish/Elmish.WPF#152]
If I have a button whose CommandParameter is bound to the actual data context like so:

 `<Button Command="{Binding CloseTab}" CommandParameter="{Binding}">X</Button>`

I receive an object as part of the message (param):

``Elmish.WPF.ViewModel`2[System.Object,System.Object]``

Is there a way to convert the received viewmodel back to something meaningful? To the underlying model?

**Comment by bender2k14** [comment]
Well, to answer your specific question, you should be able to use reflection to read the field [`currentModel`](https://github.com/elmish/Elmish.WPF/blob/789cbc304719f34f931a451dafa1b58141af833e/src/Elmish.WPF/ViewModel.fs#L119), and then cast it to your `'model` type.

However, I am suspect that we have an [XY problem](https://en.wikipedia.org/wiki/XY_problem) here.

What problem are you actually trying to solve?

**Comment by KingKnecht** [comment]
The problem comes from #148.
The solution provided there works. But it has a huge drawback: It always deletes the selected tab-item, even if a button is clicked which is not on the selected tab-item. Therefore I tried to bind to the viewmodel/datacontext instead of the selectedItem, to be able to delete the correct tab-item.

**Comment by cmeeren** [comment]
> Well, to answer your specific question, you should be able to use reflection to read the field [`currentModel`](https://github.com/elmish/Elmish.WPF/blob/789cbc304719f34f931a451dafa1b58141af833e/src/Elmish.WPF/ViewModel.fs#L119), and then cast it to your `'model` type.

While technically true, I just want to be clear that this relies on an implementation detail and may stop working at any time without warning.

> However, I suspect that we have an [XY problem](https://en.wikipedia.org/wiki/XY_problem) here.
> 
> What problem are you actually trying to solve?

Indeed. There should be no need to ever use reflection to mess around with Elmish.WPF's `ViewModel` implementation, or indeed use it directly at all. If a situation arises that truly requires this, a new API may be in order, such as was the case with `Binding.subModelSelectedItem`.

> Therefore I tried to bind to the viewmodel/datacontext instead of the selectedItem, to be able to delete the correct tab-item.

I don't fully understand what you're saying here, but have you checked out `subModelSelectedItem`? It may be just what you need. There's a sample dedicated to that binding you can check out.

**Comment by BentTranberg** [comment]
I'm going to explain how to solve the actual problem. Look for the answer over in issue [148](https://github.com/elmish/Elmish.WPF/issues/148). Give me a minute or five.

**Comment by KingKnecht** [comment]
`<Button Command="{Binding CloseTab}" CommandParameter="{Binding Tab}">X</Button>`
Binding to the tab is exactly what I was looking for! So easy...
