### ISSUE TITLE
Checkbox in a ListView binding question

### ISSUE THREAD

**Issue by jchain** [elmish/Elmish.WPF#155]
I found it very hard for me to figure out a way to bind a checkbox `IsChecked` in a ListView to the Model. 

Basically I want to make a GUI like this one
![2019-10-16 12_46_30-](https://user-images.githubusercontent.com/814893/66940524-14788b80-f013-11e9-8650-dc5c77828a6d.png)

It has a ListView showing a list of files and each row has a checkbox in the front to toggle the selection state.

I tried subModelSeq. If I bind one way, it works fine. But twoWay is beyond me.
The code I have is like this

```f#
type PDFFile = {
  Id: int 
  FilePath: string
  Selected: bool
}
```

```f#
type Model = { 
  PDFFiles: List<PDFFile>
}
```

```f#
let bindings () : Binding<Model, Msg> list = [

    "FileList" |> Binding.subModelSeq(
      (fun m -> m.PDFFiles),
      (fun e -> e.Id),
      (fun () -> [
        "FilePath" |> Binding.oneWay (fun (_, e) -> Path.GetFileName(e.FilePath))
        "FileCheckboxSelected" |> Binding.oneWay (fun (_, e) -> e.Selected)
        // "FileCheckboxSelected" |> Binding.twoWay ((fun (_, e) -> e.Selected), FileCheckboxClick )
      ])
    )
]
```

The hard part is the message `FileCheckboxClick`, it can pass `IsChecked` as bool by default but I think it also needs to pass the current `Id` in the ListView, which I don't know how to. [](url)

**Comment by cmeeren** [comment]
Could you post some code that you've tried, so we have a place to start?

**Comment by bender2k14** [comment]
I recommend making a (sub)Model and (sub)Msg type to model a row in your `ListView`.  See the `SubModel` sample.

**Comment by jchain** [comment]
> 
> 
> I recommend making a (sub)Model and (sub)Msg type to model a row in your `ListView`. See the `SubModel` sample.

Can you provide a bit more details on this? Being unable to get the current `Id` in the ListView still bothers me.

**Comment by bender2k14** [comment]
Did you look at the `SubModel` sample?

**Comment by jchain** [comment]
> 
> 
> Did you look at the `SubModel` sample?

I did but still don't have a clue. Sorry for being a novice.

**Comment by cmeeren** [comment]
The ID is automatically available when using `subModelSeq`.

No worries about not understanding it; `subModelSeq` (particularly when recursive) is easily the most complex part of Elmish.WPF.

**Comment by jchain** [comment]
It works perfect. Thank you so much! Please feel free to close the issue.

**Comment by bender2k14** [comment]
> I did but still don't have a clue. Sorry for being a novice.

That's ok.  We were all novices once :)

I was just trying to figure out more precisely what was giving you a hard time, so I could give your a more helpful response.  I am glad to see that @cmeeren was able to get you the help you needed.
