### ISSUE TITLE
OneWaySeq[Lazy] with equals = refEq and map = id

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#157]
This is my second attempt to improve the lazy bindings.  (The first was in #117.)  I have more experience with Elmish.WPF now, and I am more confident this time that what follows makes sense :)

I now believe that I see the great value in the `OneWaySeqLazy` binding (instead of just the `OneWaySeq` binding).  Every message results in a new model, and every new model is passed to `ViewModel<'model, 'msg>.Update`.  Within that method, each binding is inspected to see if its data needs to be updated.  If so, then the new data is passed to WPF through the appropriate changed events.

For a `OneWaySeq[Lazy]` binding, the appropriate changed notifications are raised by mutating an `ObservableCollection<>`.  Checking if the data needs to be updated in a collection like this can take a long time (though it now takes less time thanks to #149).  This is why `OneWaySeqLazy` exists; if `equals` returns `true`, then the user is telling us that we can skip doing all the work needed to check if any element involved in the `OneWaySeq` binding has changed.

https://github.com/elmish/Elmish.WPF/blob/4b4151b8ffcc97fdbcb8647acb1f337e301caf74/src/Elmish.WPF/Binding.fs#L419-L425

I was thinking about how to define `equals` and `map`.  A good choice seems to be
- `equals = refEq` and
- `map = id`.

If `get newModel` returns something that is reference equal to `get oldModel`, then clearly there are no changed notifications that need to be raised for the corresponding binding.   ..._Unless_ `get` returned a mutable data structure.  However, the user shouldn't be mutating, so this shouldn't happen.

As such, I suggest that we modify `Binding.oneWaySeq`, which is currently...
https://github.com/elmish/Elmish.WPF/blob/4b4151b8ffcc97fdbcb8647acb1f337e301caf74/src/Elmish.WPF/Binding.fs#L382-L393

...so that `equals = refEq` and `map = id`.  That way, the default/simplest way to create a `OneWaySeq` binding is also very efficient for the vast majority of cases (which is all the cases that are immutable).  If the user decides to play with the fire known as mutability, then they can create their binding using `Binding.oneWaySeqLazy` and pass in `equal = fun _ _ -> false` (like the current implementation of `Binding.oneWaySeq` does) or something else that makes sense in their case.

**Comment by cmeeren** [comment]
> A good choice seems to be
> 
>     * `equals = refEq` [...]
>
> If `get newModel` returns something that is reference equal to `get oldModel`, then clearly there are no changed notifications that need to be raised for the corresponding binding.

Apart from mutability, as you correctly mention, `refEq` is only useful if `'a` is a single item directly from the model. If `get` instead returns a tuple or record of multiple items from the model, `refEq` will always return `false` and you'll have to use `elmEq` to get the desired behaviour. (This is why we have both `refEq` and `elmEq`.)

> ...so that `equals = refEq`

I agree that this seems to be a good default, and (except in the case of mutable collections) better than always returning `false`. It is, strictly speaking, a breaking change (someone may already rely on this always returning `false`). But this is only for non-idiomatic usage. So I'm not sure whether this should bump the patch (implementation detail), minor (new feature), or major (breaking change) version. I'm leaning towards the latter, but am open to other opinions. Note that it should nevertheless be documented in the function docs that the whole update may be skipped if the references are equal.

> and `map = id`

I don't understand this. How would that work, given that `map` currently boxes each item separately, i.e. does "non-trivial" work not covered by `id`? Also, why would it be needed, given that `Get` (i.e. `box`) is a no-op for reference types (which are the only ones relevant as collections, and the only ones that can be passed to `refEq`)? As I understand it, just setting `Equals = refEq` should be enough to get the behaviour you're after.

**Comment by bender2k14** [comment]
> Apart from mutability (which you correctly mention), `refEq` is only useful if `'a` is a single item directly from the model. If `get` instead returns a tuple or record of multiple items from the model, `refEq` will always return `false` and you'll have to use `elmEq` to get the desired behaviour. (This is why we have both `refEq` and `elmEq`.)

Ok, but in the case of creating a `OneWaySeq` binding via `Binding.oneWaySeq`, the type of `get` is `'model -> #seq<'a>`, so it can't return a tuple or a record.  To be clear, I am suggesting that we change the implementation of `Binding.oneWaySeq`.  I think the implementation of `Binding.oneWaySeqLazy` is fine as is.

For the moment, let's suppose the `OneWaySeq` binding is created via `Binding.oneWaySeqLazy` and `get = fun m -> (m.A, m.B)`.  I don't see the advantage in defining `get` like that.  If the corresponding definition for `map` is `fun (a, b) -> f a b`, then instead just use
- `get = id`,
- `equals = refEq`, and
- `map = fun m -> f m.A m.B`.

The syntax is barely (or maybe even no) worse and the performance is significantly better.

Now let's consider the spirit of your quote for the case of `Binding.oneWaySeq`.  That could be if `get` is defined like `fun m -> m.Foo |> Seq.map f`.  Then, sure; my suggested change would be no help but it wouldn't hurt either.

> It is, strictly speaking, a breaking change (someone may already rely on this always returning `false`). But this is only for non-idiomatic usage. So I'm not sure whether this should bump the patch (implementation detail), minor (new feature), or major (breaking change) version. I'm leaning towards the latter, but am open to other opinions. 

I am indifferent to what version bump you pick, but I do want to make sure we understand and agree how this change impacts different cases.

I am still personally undecided about what I think the definition of "breaking change" should be.  This change is _not_ breaking in the sense that code written against the current version and code written against my proposed version will build (or not) just the same.  It _is_ a breaking change in the sense that the user can pass in (impure) functions and use their execution (or not) to determine which version (the current or my proposed) they are using as a dependency.

Any way, here is how I see this change impacting different cases.
1. If `'a` is a mutable or if `itemEquals` or `getId` are impure, then the user might have to change their code to compensate for the proposed change.
2. If `'a` is immutable and `'itemEquals` and `getId` are pure, then no change is required by the user.  Behavior (in terms of correctness) is preserved.  Furthermore,
   1. if `'a` is "computed", then performance will be essentially unchanged, but
   2. if '`a` is _not_ "computed", then performance would be significantly better (directly related to how many elements are in `'a`)

> Note that it should nevertheless be documented in the function docs that the whole update may be skipped if the references are equal.

Definitely.

> > and map = id
> 
> I don't understand this. How would that work, given that `map` currently boxes each item separately, i.e. does "non-trivial" work not covered by `id`? Also, why would it be needed, given that `get` (i.e. `box`) is a no-op for reference types (which are the only ones relevant as collections, and the only ones that can be passed to `refEq`)? As I understand it, just setting `Equals = refEq` should be enough to get the behaviour you're after.

Ah, sorry.  I had a particular implementation in my head that I didn't share.  I was thinking of implementing `Binding.oneWaySeq` by calling `Binding.oneWaySeqLazy` like this
```
static member oneWaySeq
    (get: 'model -> #seq<'a>,
     itemEquals: 'a -> 'a -> bool,
     getId: 'a -> 'id)
    : string -> Binding<'model, 'msg> =
  Binding.oneWaySeqLazy(get, refEq, id, itemEquals, getId)
```

This really should possible, but this implementation gives me a compile error that I don't immediately know how to fix.

Also, my hope is that #151 allows us to remove (almost?) all the boxing.

**Comment by cmeeren** [comment]
> Ok, but in the case of creating a `OneWaySeq` binding via `Binding.oneWaySeq`, the type of `get` is `'model -> #seq<'a>`, so it can't return a tuple or a record. To be clear, I am suggesting that we change the implementation of `Binding.oneWaySeq`. I think the implementation of `Binding.oneWaySeqLazy` is fine as is.

My bad, I got them mixed up.

> I am still personally undecided about what I think the definition of "breaking change" should be. This change is _not_ breaking in the sense that code written against the current version and code written against my proposed version will build (or not) just the same. It _is_ a breaking change in the sense that the user can pass in (impure) functions and use their execution (or not) to determine which version (the current or my proposed) they are using as a dependency.

Breaking changes certainly include behavioural/semantic changes, at least in the general sense. Of course, best judgement is always needed, because even bugfixes are breaking to some extent. (It's not uncommon for certain bugs to only be fixed on major versions because users depend on the current behaviour, so fixing it would break those clients.)

> This really should possible, but this implementation gives me a compile error that I don't immediately know how to fix.

I get no compile-time error using your code. Note that you need to move `Utils.fs` up above `Bindings.fs` to make `refEq` accessible.

---

Regarding my not understanding `map = id`: I understand it now; after you changed `obj` to generics in #123 the boxing is no longer needed here. This may actually be the case for other bindings, too.

---

If what you are suggesting is simply replacing the current `oneWaySeq` with the code you posted above, I'm good. Feel free to create a PR. :)

**Comment by bender2k14** [comment]
This will be resolved in v4.  Follow #253 for the progress of this.
