### ISSUE TITLE
Make use of Source Link

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#166]
We added [Source Link](https://github.com/dotnet/sourcelink) in PR #140.

Is this working?

I disabled [Just My Code](https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2019#targetText=Just%20My%20Code%20is%20a,C%2B%2B%2C%20and%20JavaScript%20projects.) and was then able to step into another NuGet package, but I am still unable to step into Elmish.WPF code.

I tried this after trying to add Source Link to a locally built and consumed NuGet package and being unable to step into that code as well.

**Comment by cmeeren** [comment]
There's several bugs if you're on .NET Core:

https://github.com/dotnet/core/issues/3587

https://github.com/dotnet/sdk/issues/1458

**Comment by cmeeren** [comment]
To be clear: Yes, there's PDBs in the Elmish.WPF nugets, and yes, they point to the correct files on GH. You can verify that by downloading it manually from NuGet, opening it in NuGet Package Explorer, double-clicking on the PDBs, and clicking the links that appear.

So this is not on us. :)

**Comment by bender2k14** [comment]
Ok, thanks.  It is always good to why you think you are going crazy :P

I will keeps those links in my notes.
