### ISSUE TITLE
Four times the search results?

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#173]
I have seen projects multitarget two targets before, and as a consequence have twice the number of symbolic search results.

Why do we (or just I?) have four times the number of symbolic search results?  For each target (`net461` and `netcoreapp3.0`), why do I have twice as many search results?

Is this happening for anyone else?

![Screenshot 2019-11-03 14 18 04](https://user-images.githubusercontent.com/34664007/68091407-e2558f00-fe44-11e9-85e9-78d5eefd2ccc.png)

**Comment by cmeeren** [comment]
I get the same. I expect it's a VS bug.

**Comment by bender2k14** [comment]
I reported it in the main F# repo: https://github.com/dotnet/fsharp/issues/9750
