### ISSUE TITLE
SubModelSelectedItem always returns true in updateValue

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#175]
The primary purpose of `updateValue` is to determine if a property change notification needs to be raised for the given binding.  This is achieved via a Boolean return value, where
- `true` means a property change notification is (possibly) needed and
- `false` means a property change notification is (definitely) _not_ needed.

https://github.com/elmish/Elmish.WPF/blob/ca67d13978e5284a8efbb5a213b96211cfe9f6d3/src/Elmish.WPF/ViewModel.fs#L410-L412

Some binding types compute their return value...
https://github.com/elmish/Elmish.WPF/blob/ca67d13978e5284a8efbb5a213b96211cfe9f6d3/src/Elmish.WPF/ViewModel.fs#L414-L417

...while others always return `false`...
https://github.com/elmish/Elmish.WPF/blob/ca67d13978e5284a8efbb5a213b96211cfe9f6d3/src/Elmish.WPF/ViewModel.fs#L476-L478

...but `SubModelSelectedItem` always returns `true`:
https://github.com/elmish/Elmish.WPF/blob/ca67d13978e5284a8efbb5a213b96211cfe9f6d3/src/Elmish.WPF/ViewModel.fs#L620-L624

I think we can do better.  The simplest approach is probably to compare IDs like
```f#
| SubModelSelectedItem b ->
    let v = getSelectedSubModel newModel b.SubModelSeqBinding.Vms b.Get b.SubModelSeqBinding.GetId
    log "[%s] Setting selected VM to %A" propNameChain (v |> ValueOption.map (fun v -> b.SubModelSeqBinding.GetId v.CurrentModel))
    let oldId = (!b.Selected) |> ValueOption.map (ValueOption.map (fun v -> b.SubModelSeqBinding.GetId v.CurrentModel))
    let newId = v |> ValueOption.map (fun v -> b.SubModelSeqBinding.GetId v.CurrentModel) |> ValueSome
    b.Selected := ValueSome v
    oldId = newId
```

Another approach might be (after checking for the correct `ValueOption` cases) to do a reference equality check on the `ViewModel<,>` instances...but I would have to think more carefully about that to be sure.

**Comment by cmeeren** [comment]
> Another approach might be (after checking for the correct `ValueOption` cases) to do a reference equality check on the `ViewModel<,>` instances

I think that would be the best choice.

---

Protip: If you suffix your start code fence with `f#` or `fsharp` (or other relevant "languages", e.g. `fsproj`, `xml`, `json`), you'll get syntax highlighting:

    ```f#
    let x = ...
    ```

**Comment by bender2k14** [comment]
Excellent.  Thanks :)

My suggested code above ignores the laziness of this binding.  Even though removing this laziness might be up for consideration (c.f. https://github.com/elmish/Elmish.WPF/pull/176#issuecomment-549292167), I will makes a PR for this change that preserves the current lazy behavior.

**Comment by bender2k14** [comment]
Wait a minute.  Not to "blame" others, but my suggested code above did not introduce the lack of laziness; it was already present.

https://github.com/elmish/Elmish.WPF/blob/ca67d13978e5284a8efbb5a213b96211cfe9f6d3/src/Elmish.WPF/ViewModel.fs#L620-L624

To preserve laziness, that call to `getSelectedSubModel` should only happen if `!b.Selected` is in the `Some` state.

I will also fix this.
