### ISSUE TITLE
On the laziness of SubModelSelectedItem

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#178]
This is a continuation of #176 

Quoting https://github.com/elmish/Elmish.WPF/pull/176#issuecomment-549292167.
> The rationale behind the existing design is that it's a lazy operation; if the UI doesn't need the selected item for some reason, it's not necessary to calculate it. Similar to e.g. `oneWayLazy`. (Though admittedly, I'm not sure how relevant/beneficial this really is for `subModelSelectedItem`.)
> 
> Does that change your view of this?

It certainly does change my view in the sense that I didn't realize that the laziness was intended.  To be clear, my PR removed the laziness and made `SubModelSelectedItem` strict/eager.

I thought the laziness was an artifact of the implementation that existed before PR #138 (where each `SubModelSelectedItem` binding was initialized without access to the corresponding `SubModelSeq` binding) instead of a feature that tangibly benefits the user.

The lazy behaviors of `SubModelSelectedItem` and `OneWaySeq` are similar in the sense that they are both forms of [non-strict evaluation strategies](https://en.wikipedia.org/wiki/Evaluation_strategy#Non-strict_evaluation), but I think the similarity ends there.  Instead, I think the lazy behavior of `SubModelSelectedItem` is similar to the behavior of the evaluation strategy [call by name](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_name) in the sense that the entire lifetime of the binding is like a single function call and some (user-provided) computation is skipped if the bound data is never requested.  If the bound data is ever requested, then the behavior of the binding "switches" to the strict/eager behavior explicit in my PR for all future interactions (which is really just the behavior in `updateValue` _after_ PR #177 is completed).

In contrast, I think the lazy behavior of `OneWaySeq` is similar to the [short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation) of most implementations of the logical operations `AND` and `OR`.  In this case, the possibility of skipping (user-defined) computation in the future is independent of the past.  This behavior is both similar to and a dual of the use of hash codes in equality functions as described in more detail in https://github.com/elmish/Elmish.WPF/issues/117#issuecomment-546344499:
> ...lazy bindings [like `OneWayLazy`] are able to short circuit computation when things are equal. In contrast, hashcodes are used in structural equality functions to short circuit computation when things are unequal.

So if `OneWayLazy` where lazy in the same way that `SubModelSelectedItem` was intended to be (and will be after PR #177 is completed), then the `OneWayBinding<,>` would contain a `ref` type that is checked and calls to `get` possibility skipped here:
https://github.com/elmish/Elmish.WPF/blob/c108336b28b1b4d70966660e88794cc7fb3ab621/src/Elmish.WPF/ViewModel.fs#L414-L417

> Though admittedly, I'm not sure how relevant/beneficial this really is for `subModelSelectedItem`.

I am not seeing the tangible benefit.  I suggest that we remove this lazy (aka non-strict call-by-name) behavior of `SubModelSelectedItem`.

I think we can add it back in a general way to all binding types just like previously discussed in https://github.com/elmish/Elmish.WPF/issues/143#issuecomment-546219080 for the lazy (aka short-circuit evaluation) behavior of `OneWayLazy`.  I just need to create one recursive binding first.  I think the only issue left is making `initializeBinding` recursive.  Ironically, it was PR #138 and specifically adding the `Dictionary<string, ViewModel<'model, 'msg>>` that is making things difficult.  What dictionary is supposed to be passed to the recursive call?  Not the same one because the `'model` type parameter is wrong.

**Comment by cmeeren** [comment]
> I thought the laziness was an artifact of the implementation that existed before PR #138 (where each `SubModelSelectedItem` binding was initialized without access to the corresponding `SubModelSeq` binding) instead of a feature that tangibly benefits the user.

That may very well be the case.

> I am not seeing the tangible benefit. I suggest that we remove this lazy (aka non-strict call-by-name) behavior of `SubModelSelectedItem`.

If it simplifies stuff, then sure. I guess that in 99% of cases the current laziness will have no effect since the binding is used anyway.

**Comment by bender2k14** [comment]
Actually, I think we were still missing the mark.  I think the indented lazy behavior was the same as the use of `Lazy<>` in the `OneWayLazy` binding.  That kind of lazy behavior is much more useful.

I will create a PR for this.

**Comment by cmeeren** [comment]
> Actually, I think we were still missing the mark. I think the indented lazy behavior was the same as the use of `Lazy<>` in the `OneWayLazy` binding. That kind of lazy behavior is much more useful.

What's the difference compared to the (now) previous behavior?

**Comment by bender2k14** [comment]
For reference, we are comparing the behavior before and after [this diff](https://github.com/elmish/Elmish.WPF/pull/179/files).

Specifically, here are the main differences.
```F#
// in definition of SubModelSelectedItemBinding<'model, 'msg, 'bindingModel, 'bindingMsg, 'id>
81 - Selected: ViewModel<'bindingModel, 'bindingMsg> voption voption ref
81 + Selected: Lazy<ViewModel<'bindingModel, 'bindingMsg> voption> ref
...
// in initializeBinding
390 - Selected = ref ValueNone }
391 + Selected = ref <| lazy (getSelectedSubViewModel b.Vms b.GetId get initialModel) }
...
// in updateValue
// main difference, see below
...
// in tryGetMember
676 - match !b.Selected with
677 - | ValueSome x -> x |> ValueOption.toObj |> box
669 + (!b.Selected).Value |> ValueOption.toObj |> box
```

# `updateValue`
## Before
```F#
| SubModelSelectedItem b ->
    let updateSelected (selected: ViewModel<obj, obj> voption) =
      log "[%s] Setting selected VM to %A" propNameChain (selected |> ValueOption.map (fun vm -> b.SubModelSeqBinding.GetId vm.CurrentModel))
      b.Selected := ValueSome selected
      true
    match !b.Selected with
    | ValueNone -> false  // never initialized, so no need to notify changed
    | ValueSome oldSelected ->
        let newSelected = getSelectedSubViewModel b.SubModelSeqBinding.Vms b.SubModelSeqBinding.GetId b.Get newModel
        match oldSelected, newSelected with
        | ValueNone, ValueNone -> false
        | ValueSome oldVm, ValueSome newVm ->
            if refEq oldVm newVm then false
            else updateSelected newSelected
        | _ -> updateSelected newSelected
```

## After
```F#
| SubModelSelectedItem b ->
    if b.Get newModel = b.Get currentModel then false
    else
      b.Selected := lazy (
        let selected = getSelectedSubViewModel b.SubModelSeqBinding.Vms b.SubModelSeqBinding.GetId b.Get newModel
        log "[%s] Setting selected VM to %A" propNameChain (selected |> ValueOption.map (fun vm -> b.SubModelSeqBinding.GetId vm.CurrentModel))
        selected)
      true
```

# Comparison

The way I see it, there are two ways that the new code avoids computation.  None of the computation avoided involves WPF; the interaction with the UI is exactly the same.  The computation avoided is either code written in Elmish.WPF (in the sense that there is now less of it) or computation provided by the user as functions (because there are now fewer calls to those functions).

## Fewer calls to `getSelectedSubViewModel`

The first is that `getSelectedSubViewModel` is called if and only if its output is required by the UI.  In `updateValue`, the previous code called `getSelectedSubViewModel` any time the outer `voption` was in the `ValueSome` state even if the return value would eventually be `false` (which means don't notify the UI because there is no change).

This is what I meant in the description of the PR when I said
> This PR replaces [the outer `voption`] with `Lazy<>` and uses it the same way that the `OneWayLazy` binding does.

## Less/Simpler change logic

The old code had two pattern matches and one `if` check in order to decide what Boolean value to return.  The new code has a single `if` check that compares the selected IDs of the old and new models.

This is what I meant in the description of the PR when I said
> This PR also optimizes `updateValue` by first comparing the selected IDs of `newModel` and `currentModel` and continuing if and only if this expression is `false`, which is also something that the `OneWayLazy` binding does.

--------------

In higndsight, I now see that I could have made these two changes in separate PRs.  When I started making this change, I had only intended to replace the outer `voption` with `Lazy<>`, which corresponds to the "fewer calls to `getSelectedSubViewModel`".  In the process of making that change, I noticed possibility of simplifying the change logic and made that change as well.

**Comment by bender2k14** [comment]
> I am not seeing the tangible benefit. I suggest that we remove this lazy (aka non-strict call-by-name) behavior of `SubModelSelectedItem`.

I also understand now what I was not seeing.

The outer `voption` was definitely useful in `tryGetMember`:
```F#
676 - match !b.Selected with
677 - | ValueSome x -> x |> ValueOption.toObj |> box
669 + (!b.Selected).Value |> ValueOption.toObj |> box
```

If the value wasn't cached (either previously in the `ValueSome` state of the outer `voption` or now in the `Lazy<>` instance), then every call to `tryGetMember` would have to call `getSelectedSubViewModel`, which has a linear runtime in the number of view-models.  Instead, accessing the cached value is constant time.

Where the outer `voption` wasn't much help was in `updateValue`:
```F#
    match !b.Selected with
    | ValueNone -> false  // never initialized, so no need to notify changed
    | ValueSome oldSelected ->
      // lots of computation
```

Being able to skip some computation because the `SubModelSelectedItem` binding has never been read by WPF is barely helpful.  It was this behavior in `updateValue` that made me think that the outer `voption` wasn't worth keeping.

Instead, the return value should be determined by the selected IDs (not by `Selected` as above) and `Selected` should only be assigned lazy computations.

**Comment by bender2k14** [comment]
With PR #179 merged, I am now very happy with the behavior of `SubModelSelectedItem`.
