### ISSUE TITLE
Question about Program.withSubscription()

### ISSUE THREAD

**Issue by jchain** [elmish/Elmish.WPF#182]
I have a question on how to implement this feature: when App starts, it checks the validity of a license while the main WPF window is not blocked from initialization. Checking the license will call a web api, so there is always some delay in seconds. Without some of asynchronous programming, the App startup wait is unpleasant. 

I checked out the timerTick example from the Doc/Examples and thought `withSubscription()` is a good place to do the license checking but I can't call `Application.Current.Dispatcher.Invoke` there b/c it throws null reference/object exception. I guess it was due to `MainWindow` was not ready yet so the UI thread which `Application.Current` is bound to is not available. 

Can anybody provide a way to call a time-consuming api there? Sample code is listed below

```fsharp
let checkLicense dispatch =
    // this throws excetion since Application.Current is null 
    // Is there a way to fix this? I don't want to block main UI 
    Application.Current.Dispatcher.Invoke(fun () ->
        printfn "checking license"
        check_license_webapi(...)
    )

let main argv =
    Program.mkProgramWpf init update bindings
    |> Program.withSubscription (fun m -> Cmd.ofSub checkLicense)
    |> Program.runWindowWithConfig
      { ElmConfig.Default with LogConsole = true; Measure = true }
      (MainWindow())
```

**Comment by cmeeren** [comment]
Just instantiate Application before calling the Program functions. That will set up Application.Current.

**Comment by jchain** [comment]
Thanks. For some reason, it still blocks the main UI with `Cmd.ofSub` in `withSubscription`

I ended up with `Cmd.OfAsync` like this
```
    |> Program.withSubscription (fun m -> Cmd.OfAsync.either checkLicense (Timeout) id (fun ex -> DoNothing))
```
`checkLicense` is something like this (there is no need to use `Application.Current.Dispatcher.Invoke()`)
```
let checkLicense ( msg) = async {
  ...
  webapi_here()
  ...
  return msg
}
```
It seems working but not perfect. At least I've found the child window is lagging for responding to `Close` event. Someone needs extra info can see here
[https://github.com/Zaid-Ajaj/elmish-wpf-template.git](https://github.com/Zaid-Ajaj/elmish-wpf-template.git)
It shows a `timeout` async call which I've found very helpful.

**Comment by cmeeren** [comment]
> For some reason, it still blocks the main UI with `Cmd.ofSub` in `withSubscription`

If you show me your subscription function, I might be able to tell you why the UI is blocked and how to avoid it.
