### ISSUE TITLE
Cache any of OneWay, TwoWay, and TwoWayValidate bindings?

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#184]
This is a spin-off of https://github.com/elmish/Elmish.WPF/pull/183#discussion_r344201451.

After PR #183, implementing caching for a binding will be a completely conceptual one-line change.

As such, it seem reasonable to me to consider if we should adding caching to more binding types.  The natural candidates appear to be the `OneWay`, `TwoWay`, and `TwoWayValidate` bindings.

I am indifferent at the moment (because there many more important improvements I want to make now).  I don't mind leaving this issue open for now.

**Comment by cmeeren** [comment]
Quoting my comment in that thread for convenience:

> I'm not sure if we should make all those bindings caching by default. There's some overhead involved in caching, and for trivial getters, non-cached bindings may be more performant. I have no idea how much overhead there is, though. As far as I know, it may improve performance, or it may not.

**Comment by bender2k14** [comment]
> We should conduct performance testing (e.g using BenchmarkDotNet) before doing this.

Definitely.

> I think that if we manage to create a single `Binding wrapper` for laziness/caching as suggested in https://github.com/elmish/Elmish.WPF/issues/143#issuecomment-546103655 and following comments, then this isn't needed, because users can easily control it themselves.

Sure.

Though, there is still the question of default behavior.  My impression with Elm is that they don't include such optimizations by default.  Generally speaking, it is easier to create an API that allows the user to add various effects than one that allows the user to remove such effects that are added by default.

**Comment by cmeeren** [comment]
> Generally speaking, it is easier to create an API that allows the user to add various effects than one that allows the user to remove such effects that are added by default.

Indeed.

**Comment by cmeeren** [comment]
If I read the discussion here correctly, this issue should be closed. Is that correct? Or would that only be if we had a generic caching wrapper?

**Comment by bender2k14** [comment]
Yes, we can close this issue.  If anyone wants different default caching behavior or the ability to caching effect to an existing binding, then they can comment here or open a new issue.
