### ISSUE TITLE
Different lazy behavior between OneWayLazy and OneWaySeq

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#186]
I just realized that there is a difference between the lazy behavior of `OneWayLazy` and `OneWaySeq`.  Consider how each case is implemented in `updateValue`.
https://github.com/elmish/Elmish.WPF/blob/7feeb9bc23e38334ea41bb36c2fbf334b7b04ba0/src/Elmish.WPF/ViewModel.fs#L418-L425

Both compute `not <| b.Equals (b.Get newModel) (b.Get currentModel)`.  The difference is that
- `OneWayLazy` directly returns this value while
- `OneWaySeq` does a more comprehensive diffing computation when this value if `false`.

The behavior of `OneWaySeq` is more like that of [Elm's `Html.lazy`](https://guide.elm-lang.org/optimization/lazy.html).  For `OneWayLazy` to be more like `Html.lazy`, the implementation should be
```F#
| OneWayLazy b ->
    if not <| b.Equals (b.Get newModel) (b.Get currentModel) then
      (b.Get >> b.Map) currentModel <> (b.Get >> b.Map) newModel
```

See the similarity with the `then` block and the implementation for the `OneWay`, `TwoWay`, and `TwoWayValidate` cases?

This is related to something that I said in https://github.com/elmish/Elmish.WPF/issues/117#issuecomment-546344499
> > ...and `(equal a1 a2) = equalB (map a1) (map a2)` holds for all instances `a1` and `a2` of type `'a`.
> 
> We don't want an "[if and only if](https://en.wikipedia.org/wiki/If_and_only_if)", we want an "[implication](https://en.wikipedia.org/wiki/Material_conditional)".  That is, we want that for all instances `a1` and `a2` of type `'a`, it follows that `equal a1 a2` implies `equalB (map a1) (map a2)`.  We want to short circuit computation if  `equal a1 a2` returns `true`.  If it returns `false`, then we can proceed with process of updating the binding.  It might be the case that that the view doesn't change--that we don't raise any change events.  That is ok.

The current behavior for `OneWayLazy` is "if and only if" instead of "implication".

**Comment by cmeeren** [comment]
Wouldn't that change mean `Map` is evaluated at least two times? (One in that branch of `updateValue`, and one when WPF retrieves the value, whereafter it's cached.)

**Comment by bender2k14** [comment]
Yes, that retrieval happening in `tryGetValue`.

There is something about the difference between WPF and our lazy behavior compared to Elm and its `Html.lazy` that is unclear to me.  I will keep thinking about this.

**Comment by cmeeren** [comment]
> I will keep thinking about this.

Looking forward to your thoughts. I would expect it to boil down to static vs. dynamic views. We simply have to do a lot of stuff differently. Mostly it's more cumbersome (internal acrobatics as well as less ergonomic APIs). It has its charms, though (as spelled out in the readme).

In any case, we can't evaluate `Map` two times since it's (almost by definition) expensive.

**Comment by cmeeren** [comment]
@bender2k14 Did you get further with this? Are there any problems/bugs here that should be solved?

**Comment by bender2k14** [comment]
I have not put any time into this.  I don't think there are any bugs here.  I will comment here if I have any new thoughts.
