### ISSUE TITLE
[Question] Can I return something from a window?

### ISSUE THREAD

**Issue by JordanMarr** [elmish/Elmish.WPF#190]
I am experimenting with introducing Elmish.WPF into a pre-existing MVVM style WPF project.  Is it possible to return the final state of the model after closing a view?  In the MVVM version of the view I would like to replace, I can inspect the state of the view-model after closing the view dialog.

**Comment by cmeeren** [comment]
It's not possible to "return" the state in the direct sense you ask, but what you're trying to do is possible using `Binding.subModelWin`. Check out the `NewWindow` sample for a demonstration, and let us know if you have problems with it.
