### ISSUE TITLE
Typo in tutorial?

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#192]
Looks like a typo in the tutorial: "The subModelWin binding is a variant of subModelOpt that allows you to control the opening/closing/hiding of new windows. It has the same overloads as subModel and subModelWin, with two key differences:"

Should that be "subModelOpt" instead of "subModelWin" at the end?

**Comment by cmeeren** [comment]
Thanks! Yes, that's correct. Will fix.
