### ISSUE TITLE
How to access non-bindable properties in window?

### ISSUE THREAD

**Issue by fuchen** [elmish/Elmish.WPF#194]
For example, I have PasswordBox in a login dialog. But the `Password` property is not bindable, and I cannot access the dialog instance in the binding functions, so how can I get the password?

**Comment by bender2k14** [comment]
Can you share a share a simple example of the issue that you are having?

I like the dialogs from [Material DesignInXAML](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit).  They are bindable.

**Comment by fuchen** [comment]
@bender2k14 See this link: https://www.wpf-tutorial.com/basic-controls/the-passwordbox-control/

> When you need to obtain the password from the PasswordBox, you can use the Password property from Code-behind. However, for security reasons, the Password property is not implemented as a dependency property, which means that you can't bind to it.

My workaround is keeping the child window in a mutable value when `getWindow` is called. It would be helpful if the `bindings` function could take an additional `window` parameter.

**Comment by bender2k14** [comment]
I think there are two issues here.  One is the use of an additional `Window`.  Another is the use of `PasswordBox`.

In the last few days, I have read about `PasswordBox`.  Its password isn't a dependency property in an attempt to improve security (as you quoted), but [it's password is already exposed as is](http://gigi.nullneuron.net/gigilabs/security-risk-in-binding-wpf-passwordbox-password/).  Even [Microsoft's `SecureString` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring) says ["Don't use `SecureString`"](https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md), which is the underlying type that is intended to improve the security of `PasswordBox`. (Instead, they want you to use alternative and stronger forms of authentication.)  I think the conclusion is to act as though `PasswordBox` only hides the password on the screen and nowhere else.

As such, if you want to use `PasswordBox`, then it is no worse to expose the password as a dependency property.  This can be done in many different ways (in the page to which you linked, links from there, and so on).

Now let's discuss the use of `Window`.  The ideal Elmish.WPF application only uses one `Window`.  My experience is that an additional `Window` is usually used to create a modal dialog.  This is unnecessary.  There are ways to create a modal dialog without also creating an additional `Window`.  When I last investigated this, I think my preferred approach was to use Material Design in XAML.  Here is a [post on that topic](https://intellitect.com/material-design-in-xaml-dialog-host/) that seems good; I didn't read it in detail.  (It might also be possible to do this in vanilla WPF.  I don't remember exactly.  I only looked into this enough to determine that it was possible; my application at work doesn't include any modal dialogs...yet.)

**Comment by cmeeren** [comment]
Thanks for the research, @bender2k14! 👍

I just want to add that while a single window is the easiest, Elmish.WPF exposes an API to make opening/closing/hiding of windows and dialogs fairly easy. See [this part of the tutorial](https://github.com/elmish/Elmish.WPF/blob/master/TUTORIAL.md#sub-model-window-bindings).

**Comment by fuchen** [comment]
I think what I need is `CommandParameter`. I see its usage in sample `UiBoundCmdParam`. I just need to add one line to my login button in XAML:
`CommandParameter="{Binding Password, ElementName=MyPasswordBox}"`

I will look into Material Design in XAML soon, it looks good! Thank you @bender2k14

**Comment by bender2k14** [comment]
Yes, I didn't mention the using a command parameter, but I think that is also a good way to obtain the password.
