### ISSUE TITLE
Put source in PDB file and put PDB file in DLL

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#196]
As an application of my [newly acquired knowledge](https://github.com/dotnet/sdk/issues/1458#issuecomment-576961024), I think we should include the Elmish.WPF source code in our generate PDB file and also include the PDB file (with source code) in our DLLs (there is a .NET Framework DLL and a .NET Core DLL).

I think @cmeeren is already [on board](https://github.com/dotnet/sdk/issues/1458#issuecomment-577292209) ;)

**Comment by cmeeren** [comment]
Yes, absolutely. I plan to do this for all my projects eventually. Feel free to send a PR adding the necessary fsproj elements and removing old SourceLink stuff. :)
