### ISSUE TITLE
Experience when targeting .NET Core 3.1 with VS 16.4

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#197]
It has been a few months now ([back in October](https://github.com/elmish/Elmish.WPF/issues/154)) since we last discussed the difference in the developer experience for WPF in Visual Studio when targeting either .NET Framework or .NET Core.  At the time, there were design-time bugs when targeting .NET Core 3.0.

Is anyone knowledgeable about the quality of the developer experience when using the latest Visual Studio (version 16.4.x) and targeting .NET Core 3.1?  How does it compare to targeting .NET Framework?

**Comment by BentTranberg** [comment]
I have moved all my source to .NET Core 3.1, and continuously update VS to the latest version. I use the Elmish.WPF based design time model all the time, and can't remember anything that should indicate the issue you're reffering to still exists. Either it has been fixed, or else something must have caused it to be considerably less noticeable. I haven't had time to verify it properly, through it's been on my mind constantly to do so. As for Core vs Framework in general, the quality of the developer experience seems to be exactly equal at this time. I use many components from DevExpress, and they too work exactly the same in the Core version. When moving to .Core, I also of course switched to the new project file format, which simplifies quite a few things for me.

**Comment by BentTranberg** [comment]
Spoke too soon. Hit me like a boomerang, and of course right after I say I don't see it. The issue is still there. But it does seem to be less intrusive in my design time design work. Btw runtime design in VS works well too, on Framework and Core.

**Comment by bender2k14** [comment]
> When moving to .Core, I also of course switched to the new project file format, which simplifies quite a few things for me.

I think the new project format can be used when building with `dotnet` even if still targeting .NET Framework.

> Spoke too soon.

Ok.  I will test myself sometime with the expectation that this bug still exists.

Thanks for the report :)

**Comment by BentTranberg** [comment]
> I think the new project format can be used when building with dotnet even if still targeting .NET Framework.

That's right, and I've used that fact to ease migration. First recreate the project file in the new project format while targeting Framework, and work through any problems with that. When done, switch target from Framework to Core, and work through any problems with that. Easy-peasy.

**Comment by cmeeren** [comment]
Is there any reason this issue should stay open?

**Comment by bender2k14** [comment]
This bug involves the WPF design-time in Visual Studio and .NET Core....nothing to do with Elmish.WPF, so we can close.  If anyone finds and shares the official issue tracking for this bug, that would be appreciated.
