### ISSUE TITLE
Q: How to bind to [mouse] events?

### ISSUE THREAD

**Issue by KingKnecht** [elmish/Elmish.WPF#199]
Hi,

I'm tyring to write some drawing application. Of course I would need to handle mouse events (move, button down, button up etc) in my message loop.
I have already discovered this issue https://github.com/elmish/Elmish.WPF/issues/33
with the awesome Fable [example](https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoBCIAeMaAUMSAA4wB2cAygJ5oAuMwZlNAYgIYBGsWAEoxuAYybtqcHvxhCR4rAAUAThRKkA2gB4AghCYgA8hwB8AXWKhIsOABEQwbihoBeUsThwdAORABhR3JuFXQQKgtPOCZ6SjglEBcmOHcvLwBvOHwALjgAMygQbgk0tPpcgqLkgF8or2ZilFE4YFZeGBU4AAoAagBKbvIARgAaOHIAJgHXOEz8FPGhrHme8YnlgG44egXhrB3Vyf24WtKGpiaWto7u-sGxtFFuKBDp2azd5bhVx+eQrZ2M3Ixx+TxenVOaXOl1awHanS6AFoBl1hmNJm85rslvNEWtNttscc8UcdpD6kxGs1YfDusj7nBfuDMR8gV88Uz-oS2TsOWCQic6ozKRdqdcEQAqFHkB78lQs+Zs+YSxlygGfHYqzkQoXQsVwm5dKWDUZrBVE5X4-DqoFLTX4sm6kUw8XdAD00tNGIWWNtXzdVpti2OAdJgrOzv1tK6HoZ2vNSrgAe1QeBO2TcsFURicTw+AAkmAFgBxCAoMCkLxu6twXRUUQYECdFQwF4XABu8EMcF4BDgEHIlE6sDyJWisXgeeEbZQnbrDabCwSSQ8Xhzk77qTSmXLuTzhaFXgHQ4AMjBR7ll1Qx2cUAAvGAVQrFQ9wUQgQoqXLMUJUADmWZRNY0AboqlZpLAySiC2xTwF0ojUCwX7xIk14DGg97wO+n4pK+O5FjMpbllgPgwAA7kRYBdH0r5HoOHRnqOCwIdeNx4l0GEPkmcDrDRpS3lxMycTAtFvh+i4zNhi61EKkEtCAnY4DsYAJGgPabnh6nzGRKBMBg-b0SojHJDMvb4Fgx4MeeySrCpIBqTJpRyS2wlKfkYiGAi3D1o2yFXkwAxmbh-FwM5rbzr5CxdN5C6dHiZkWYZxkDAGCXCa+YXCWAeY+lpcA6XpjKYQsaXFSqeQedJGUwMkLZQBFTbCFlUUxZF8UEIlp7WSlcAuZh2UdelIVyXZakzF0dUNSoTX9XAeKTT5TYDCqfUPgN5lDfxmSrTA635bp+mWUZ1klR1R3Gd8cCjYBa4TnAeYABIoB0IQNoCQqZGZRC5AAstw5DaPuYBjHmpivg2KBQGAAAqIBKCEiG-f9gMEIWIOo2ApheDJQHgCB90EE9L0qG9uGyTVb4YJDYCFmgRh5OMCPXoWcBU8TpNbqUbMqK9GD0FgENQ7D8Mtter4AD5Y39wJ5JDSHdHkEA0AA+uM5ZzVj5Dq0CTNMIWfH8ZLcDS1ghgnugN5pEb5vMFgTjkPkzDgV4cmC2Aov04zot60W3O8+9IV+yTfMS1jbu057wTeweIXWxbAuNvZ8BB29WBfWgWDQyo9CcC4Fbk7VMDNAVGB2EQLFgN5PtqSnfNe4hLOc2kUcNxWIXZLkXSs89PPB-QolW2HVNQxHDMt8zbchaUce29hsDiN0Jdl481CVxPNc9-7Aw0QX0QUGenZQHmRDd+zddN14tf8+nofG-9WCy1A8tdIrNBmSzquIljVAgMk2ji6fXuqc3bC11lgQI15nBUDQAAaRgDsd+YADbTylvfM2Ftb42yYHbf6jIqD5ychTbgYA9pBSvsFLagD-b7UKunBYV804ECIFgXQJCugJXLGMMyAxHIQQpi2UAnYADqB1l4VyrmpRBVC+4UMIckQwwhBHwFMhjOARsl7l1XlXWm0jSZG1oDVLAIA8hYM0uQkuA8tInwvlPBhN8p6G1QTLOWhpX49nVp-b+v84D-z3oohScgIGUhcJI8syCp4gLhrrWRDjdF8wTtTUB3tLFeCNibR+z83HhyLOPH2GsUn8R-n-ABCjWABPAeEYJ0DKbUxjrEkKAAyBpcAik+JKSAfxnYKmQJCfXCeBTwnY2dqFCmaAaqw3IAfVsWkWbkJsZkcxB0alCyid7ehm8+4JJWSLRCainFYAEQEmZRZeEuwpko45LTyKqV6q2Roc5FqdDma+JwTAGxxOvkwjOWcc550uRY2OcA-BUHgF-D5Es6COHgEFL+li5LljQLDH6RyVHmXVuo0Rmj8HaLABvM+Ox9GGOMaY+pI0bkzBBWRG57VzLnROvNO5HYYBTThRTAclcWDrWsQUuxXyClpPvvbBWSs4CqxhWDepIUUAMwRUi8pQSoGSI6urPS1ACkhSCkbPMdsAluVGuqtIrYxlaQGZYhZGzSY0P0nQmY7LYJcocsMuSYymDTkaOETAKAHbZL6Xk55IVzX4qtcsmGqzdkzAYZEnZ14WFsOyeiXW+ssxyNucJS5FVxCLj4GgD8BhmWPI+TEs5yRZUdKIMVVFLMMV6TEVo9ehbCXYOJRggNhaAWxJtTyi18T7GSoFcCIVL8RVir7LCyV-FpVwFLTNB83SqlKrRUWVVVADWlE1VjbVO03IZs8nAbNuaWAsvHaUI10KCCmpCjjHQ+hDAmGoJEYCtgfrtggMisA0z3DZjum+j9H0Pl7kJt2-uIVQAQDGapS8qFLZeHdtwP8f4XB-k7kDOAKopyMtnPm2KAwKAXHCK+JWYAQC-XANMqALb+ItiIyR99UBQoW2TSMktVBdLdGmLvcsQwSxljACRcilFqIcbABMbjxFSIUR44JlN5YADMonePiYE+E+FYAAAs8m+MSfLFJ7chabEZCsWNApmgDXpG1lOsAQwth0qYjMX0PEAAMWAgwTCcycLYaaZiuac1sKSnQZgACIqMBfJJKszBELMTGs0lE6dnWRwCGA5nz3IEtJawO5oqgk4AAFZkt+YWAFv8LZqAhdM+Z2T0Wuq2feIqOAqm0tBnq256oHmK2Oby+JfzcAAv8AgDAUrx7ZjlbU5Vqy1X7O5eS4CHLaWMuebgAADg6zhQL9BWyFDIgNyVlhx0z2wYOtxvANY9iwJwnsgyp79qMSYijDio3RJmCbVg5AYixqouWCYYxON9De10csqmvtgBkzwl5IAwMwHJTVhYU3ofpdCzBnm8HEMLGBSJEKhGQALE0Dtyju1MczGx4x+FaA7CI4Q-+S51hf2lCp1ALAsGkf-iFEbEweGqA4IdkOmg7CzvKwGGC3g5nEHhJZy9lA4R6fnm4NAJgAA1Z4fX3JQDGeBEaahvXDxpjkxNRZacxMyHr9tIUGfk4AjMVHok5nyVo1gchWrAP4qwC6t1bPPUa9qdr6OJzVf8O8hFwQfvHCCaiHJYhYAA-4McDlFi8s9dN2dW1nm+C+P4CYF0erYxvMDCNpUF8Kb8szFoEwX8f4sCcCbK8roAWADE6QHPZAABoADZqgBbGEnhTMBU9dAc-gRLSWB99GUxTIKMxtXQRECwN8iEbhpr83+w3Syre09t0BvZBN8BEyAfEsPOUgpXr0AYYwZhLCPvgM+iAABVcgHLlHgXXMbNAZvmfxCaAAa2v3AYxG+WZoYIC7zDI9K2ewdXIwKgHKb-IGF-UnCgMAhAYAF7YDYA-wGCFgcTL-BmfyaA1sGqeASAjGF-YsNQMiDAn-SeVJOgDAX8N-UgqA6eY2MHMZZFTsUgrA+gy-SPF-YQIjVcJjAyW-FoJ-a3anNIV5d5YAIQixF-JQd-T-dhDGdvDDB5bDfJBxA3UjOjI3WJE3ZHQvKFboRBRQmcZQ3yC7QONfGYFfO3DdB3bffmF1CZKZOjRBApDHBYPXDuYQunDHApKjfHbwcwRjCgmA8gMAnKXJFmMdKeFfHQpnBxUXNnDnYVbneNUVfnLGd2CgENFmCI3XDQsw9fVncXdnd9CqGXeXKARXWnYZABEIuAhAmIY7dQ2jYNWIs3IFcIeAU5NROAFAyfGAdAmPNiCVKeZo6ZLQhxNwywjQuATwlfHw8dPwrHQI+HQePdEhCPIjYAaPGfFQGo+wHAqfKRKI1tRfPSLtINaYm3awjfLff2A5MpYRTFFebFa8BdOpepKYrw2Y3IeYzgxYvHZYoInoogkAEg44kY04mYiY2xCwrw1fINe3TfIDB4tNKRJYLjFfUDcDeyVwyPdwmYuYjQiyf4yVJYgnFY-Y2gKglwGgiE0SMYzQg6C4uwgk64tfJEu4zZHaS5LoJYN0DEgYLExgiHXE8dL4jw344khYskwEik4EgBZFcHZg+ASlalSEyhM4jAApbE0UsaK5KlMUyVf1Y9MQ-SGIsnZHGE+IjokFY7KwoDA1ABWgfQ+QgsYGPdR5dI+Em4x6FEi5KRNU+yT02KUSbogBDgojVQ6I4ocQ6U-E60nownMFaom0jAEQIsTw4JOjMFBZDM4NL47MrYck74okm3JY8MuAbgzHE4-iM0+EpYxMgBZMrGVMy7VmfMrM5wHMrGPM4hYNEsos-sfEq46ZMs1sEkqMg-G9Y-e9U-PGJ9F9WXZ6Egz9YtW5ZoMyERPSfwTXUWb4sAdAYIN5fSJsFAcnPKePCmNohYdAUnODU3LSU7PI2jIUQ89sbwV8OBHYDiYvZHDhJBV8fwF4NANSHrAgALV8MApUsZBwMibnNxGAD82sk9dsLAcgFsTsa8MuMop+HTEKJCp3QwcgVQCgODd1KgfCus2M-SQi3gAwQwGgJsuANzMFN058sYYU8HalJ8mzAKdfGQ0QD-B2I2Q8tAY8hsUSABJYY7MuSCM9RddfMSiS7Um0zxNjC7aCkUuQxC5CjU1C9CzCxCHC6XPCgowi5gCgUi4IP8Ciqi0oOo8AvsACpSo8mizSqgIRdM6ZLnOAJC6MgitCjCpC4yqXGXeyw1NCyyki9XcitnCKrwSdQi2jSkAATR8RYvS2XTgFBPBOVSLFErcpPNElbCSrQpSu4HSqxjc2yupOoKfPRQyKKobAuyL3oFsBMwcRETAFoUGkwlEgehgHPIwGSFKgfFEgmQMLOhi1HGJC-1CHJ32AKIunYr4vZHmvPJcGWAKJwDEDfyKzB3wUCBwgSnnwcQAC18x8Eu9uhJ0bzsqRNT0EsCiTAxBdIfy7rLSKdsqnMAB2Py5XeAJYAomsUiTsToP8+DG4cgKDG4EK68boOQUvK6dXHDGgUQCAFQb2KAZSL6gCMyDYUSGsOSEFVPUKbgNbCGhav8G4VVPyrC6DNIfyDoBABmtSP7Bme69MmgALH+EFALAG41ALaXQwALC7HHLwQIzqus4kq+W+P0x3N2D2BmACzBeOQdLcg6Xc6mfcvXZSmi3imagKW+ZtJ2UoSwEPCmdsFcg85q-SJud8z8kKYC7gUC7rJwFwREd8HpEFFQSCkKLS8HOChCkVfylCyKwy+GpgEy8Kgo+suihi8IK1KSzK47Po2CdA+zQimymABvIMbOuDGAdK6oVy8SmilO9S6iDymCmAHS0OvS+myOhmmOsyrYfWk8kA2AqgeAxA6ukUlU5I+mgK-iGugerOoKwuvOlLAumm4u0ulS8JKW18R26W52kCsCkJYvCAcQYotAf2qeQOpgo5XysOrGCy4i6yuK4oqu0SQ+mAYOwe0+xu6Ky+2y+KofW+qgGuuumgJ+8+qy2Kt+6+j+kKJehxB2QnTQYUToALe8-GvsbsJRAWiW-iCBqW6B7rOBvKEJcsPA1VToIKbsF1PdNSN2ZB0SNB7wDBgLYyL28jISvyhonYBGbgPeN8VA1U8iLSch8BgIqhn8brH6csMAWAOh9-PKbsQ5TsHhqeShqBgRgLWgaCD8ZwhBzHHaGRjVROmgVeg+qgYC8R3y9S9u95SMkAAorwOwdAPgWAF8icjHLAfMNAHumIUSdBhRsx7oALLYYxK65IP4ojLAM8f8PSDzYvbrPoTR-ieipgRip22JMAgxhhox47Ex-Sasix+wax2QOxunPwxx5xphtx-h8JgLasrxnxvIPxhsvHIJ6gP8UJ6hyJuAFByW0Hdk-FeW2w+44ipw4+EgWOLGLBJIt07cjAbWqGXWmYtJmrVwKbOZuHC7I2U2y2C2yQGgJAVATAdZxAZAdAbAYQDyUgUiorbgYAO2N-WgFABA2wFwVjO1Kfa28iYgI2E5nmc5kuQ58QBgHyNQH+MDbrf6cgSC15tQU585lQJWYgIAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGjbu+5rG1vuO6QTSpcMM0rLaELwiBUkFgcCAA&css=BYFwtgNgNABARgewCYE8YG8BQMbAKYCWA5qAFwwCMADFQKQDc2MYAhgE5EEB25VjOCAG542AMwgIA7uWAEkSPF0YBfTJgDELAA5aMTfMTKUaDTKswA6VtwC0AYwRcQLbiL04DJEOWp1+8FjsAayI2BABXLiR7BAk2cjgIQKCVNQtEAA93GC0EAGcCEAJHchY4PNjwkDx-IRFxKRk5BSUzNMzSYDq2bIiQCFcfLSzJWWqYCoGkVMtuPJA2cLsixzzs3IKVnhhRAgy8aaYQBC1efzZDbxg+Jjhk0IiomLjyUcKapkk5EGByACYaMN-KJHCAbAUAF54Hx-IFMEFOGyiFhgAgQFDkPIsLh5cEiAiifxaFjybhEcgAVjh5gscwWSy2azgVWOPF2bHmNgQohsIBQWjw2VYHFsFy8Pio1MwQA)

How would I do that in Elmish.WPF? From the issue mentioned, it's not clear for me how to accomplish that.
It would be ok for me to write my own Canvas which provides commands instead of events. Is that the way to go or is there another/better solution?
Thx.

**Comment by cmeeren** [comment]
Check out [the bottom of the readme](https://github.com/elmish/Elmish.WPF#can-i-bind-to-events-and-use-behaviors) which points to the EventBindingsAndBehaviors sample. Let me know if you still have questions. :)

**Comment by bender2k14** [comment]
Hello @KingKnecht.  I asked a related question #191.  I have learned something things since then, so I just updated that issue with some more information.  Like @cmeeren said, let us know if you have any questions.
