### ISSUE TITLE
Problem when opening a subModelWin window as the initial command

### ISSUE THREAD

**Issue by mbenoni7** [elmish/Elmish.WPF#200]
Straightforward repro: in the NewWindow sample, if I submit the ShowWin1 message in the init function, an exception is thrown and the message is swallowed.

More specifically, I change `mkSimpleWpf` to `mkProgram` or `mkProgramWPF`, fix up the signature of the `bindings` function, add `, Cmd.none` to each branch of the `update` function, and then change the `init` function to
```
  let init () =
    { Win1State = WindowState.Closed
      Win1Input = ""
      Win2 = None }, Cmd.ofMsg ShowWin1
```

**Comment by bender2k14** [comment]
I think I understand your description.  To be sure though, could you make those changes in a branch on GitHub and link to it from here?

**Comment by mbenoni7** [comment]
Fairly new to github, so let me know if this is not what you meant:
ef4e52000e33fd

**Comment by bender2k14** [comment]
Technically I was asking for [this link](https://github.com/mbenoni7/Elmish.WPF/tree/initial-cmd-bug), but your link was also got me what I wanted, which was to pull your code to my local repo instead of having to write it myself based on your description.  Thanks! :)

And thank you for finding and reporting this bug.  PR #201 fixes it.

**Comment by mbenoni7** [comment]
Looks like we're not quite out of the woods. I get another exception when the initial command is ShowWin2 instead of ShowWin1, due to the fact that the subModelWin binding for "Win2" references Application.Current, whereas the binding for "Win1" doesn't:

```
"Win1" |> Binding.subModelWin(
      (fun m -> m.Win1State), fst, id,
      (fun () -> [
        "Input" |> Binding.twoWay((fun m -> m.Win1Input), Win1Input)
      ]),
      Window1
    )

"Win2" |> Binding.subModelWin(
      ...
      (fun () -> Window2(Owner = Application.Current.MainWindow)),
      onCloseRequested = Win2CloseRequested,
      isModal = true
    )
```

Failing code can be found [here](https://github.com/mbenoni7/Elmish.WPF/tree/init-cmd-bug-pt-2).

**Comment by bender2k14** [comment]
This issue is more complicated.  I just opened #206 as a new issue for it.
