### ISSUE TITLE
Print preview?

### ISSUE THREAD

**Issue by wangjian30** [elmish/Elmish.WPF#219]
Can any one give me some idea about print preview?

Thanks

**Comment by bender2k14** [comment]
Can you elaborate?  Do you know how to do this in WPF without using Elmish.WPF?

**Comment by wangjian30** [comment]
I want print some control in my window, I have did it without using Elmish.WPF.  But with Elmish.WPF, I can't find a method to get the control.

**Comment by bender2k14** [comment]
Can you share branch with a minimum worming example of a print preview screen using WPF without Elmish.WPF?

**Comment by bender2k14** [comment]
Were you able to solve your problem?
