### ISSUE TITLE
Correct assertions in merge tests

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#229]
Quoting myself in https://github.com/elmish/Elmish.WPF/pull/214#issuecomment-630856228
> Here are some potential ways I see to improve the relevant tests.
> 1. The tests that consider many different cases only check if an event of the correct type was raised.  The assertion could be strengthened to verify that the correct number of events were raised and that they contain the correct data.
> 2. Tests considering the many different cases could also verify that the elements in the `ObservableCollection<>` end up in the correct order.  There are some general tests like this, but I am not completely convinced of their thoroughness.
> 3. We could add tests specifically for `elmStyleMerge` instead of higher up for `OneWaySeqBinding` or `SubModelSeqBinding`.  Such tests could, for example, count how many times `update` is called and assert that it is the correct number.
> 
> Overall, I am currently satisfied with the existing tests, but I can add some if there is something specific that you want tested.

Well, I am no longer satisfied.  That didn't take long!

One advantage to `elmStyleMerge` (cf PR #214) compared to my previous idea (cf PR #165) is that the behavior exposed by `ObservableCollection<>` is sufficient; we don't need to extend `ObservableCollection<>` or write something from scratch...both of which would need testing.  We are now sticking with `ObservableCollection<>`, and we don't need to test `ObservableCollection<>`.  We can trust that it is bug free.

> 2. Tests considering the many different cases could also verify that the elements in the `ObservableCollection<>` end up in the correct order.  There are some general tests like this, but I am not completely convinced of their thoroughness.

I now see this as a serious issue.  Our tests should confirm that our merge algorithm is correct, which mostly means that the items in the `ObservableCollection<>` after calling merge matches the items in the merged array.
1. If the items in the array differ from the items in the `ObservableCollection<>` before merging and
2. if the items in the array "equal" the items in the `ObservableCollection<>` after merging,

then if must be that some `CollectionChanged` event was raised (because we are assuming that `ObservableCollection<>` is bug free--that its implementation matches its specification).

Therefore, most of our tests that only assert that a nonzero number of `CollectionChanged` events were raised should be strengthened to assert that the items in the `ObservableCollection<>` after merging are correct.

I don't mind having one or two high-level tests that assert that a nonzero number of `CollectionChanged` events were raised.

Other useful tests related to `CollectionChanged` events are ones that assert that there were `0` `CollectionChanged` events or there were a nonzero number of `CollectionChanged` events of a particular type (and possibility with particular data).  We have both kinds of tests.

I am going to work on this now.

**Comment by cmeeren** [comment]
Excellent and good catch!

> I am going to work on this now.

Thank you so much!

**Comment by bender2k14** [comment]
> Here are some potential ways I see to improve the relevant tests.
> 1. The tests that consider many different cases only check if an event of the correct type was raised.  The assertion could be strengthened to verify that the correct number of events were raised and that they contain the correct data.
> 2. Tests considering the many different cases could also verify that the elements in the `ObservableCollection<>` end up in the correct order.  There are some general tests like this, but I am not completely convinced of their thoroughness.
> 3. We could add tests specifically for `elmStyleMerge` instead of higher up for `OneWaySeqBinding` or `SubModelSeqBinding`.  Such tests could, for example, count how many times `update` is called and assert that it is the correct number.

PR #230 resolved item 2 and PR #231 (essentially) resolved item 3.

Item 1 would be to ensure our merge algorithm is efficient in the `CollectionChanged` events that it raises.  I will keep this in mind.  In the meantime, I satisfied with closing this issue.
