### ISSUE TITLE
Form1 and Form2 in SubModelOpt sample both visible in XAML designer when either visible

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#252]
In the `SubModelOpt` sample, when looking at `MainWindow.xaml` in the XAML designer, if either of `Form1` or `Form2` is supposed to be visible, then both of them are visible.

Why is that?

This feels like a XAML designer bug.

## Steps to reproduce

In the `SubModelOpt` sample,
1. change `init` to
```F#
let init () =
    { Dialog = Some <| Form1 Form1.init }
```

2. open `MainWindow.xaml` in the XAML designer.

## Actual result

It looks like this.  Notice that only `Form1` should be visible, but `Form2` is also visible below `Form1`.

![2020-08-05_11-27-30_226_devenv](https://user-images.githubusercontent.com/34664007/89439222-7c69a100-d70f-11ea-9c5a-cf0316a5a78b.png)

## Expected result

I expected the XAML designer to look the same as when `Form2` isn't mentioned in `MainWindow.xaml`.

![2020-08-05_11-27-50_227_devenv](https://user-images.githubusercontent.com/34664007/89439297-9c00c980-d70f-11ea-8dec-69cd1670dfdc.png)

**Comment by cmeeren** [comment]
I see `AncestorType=Window`. Didn't we find out in #251 that `Window` caused problems?

**Comment by bender2k14** [comment]
Excellent static analysis! :D  That change works.
