### ISSUE TITLE
UI Blocking on subModelSeq?

### ISSUE THREAD

**Issue by MicaelMor** [elmish/Elmish.WPF#267]
Hi,

I have run into an issue, and I am unsure if this is normal behaviour or if I am doing something wrong, I have the following binding:

> "Transactions" |> Binding.subModelSeq (
>                 (fun m -> m.Transactions),
>                 (fun e -> e.Id),
>                 (fun () -> [
>                             "Posto" |> Binding.oneWay (fun (_, e) -> e.Posto)
>                             "Data" |> Binding.oneWay (fun (_, e) -> e.Data)
>                             "Matricula" |> Binding.oneWay (fun (_, e) -> e.MatriculaCartao)
>                             "Litros" |> Binding.oneWay (fun (_, e) -> e.LitrosArredondado)
>                             "TipoCombustivel" |> Binding.oneWay (fun (_, e) -> e.TipoCombustivel)
>                             "Kms" |> Binding.oneWay (fun (_, e) -> e.Kms)
>                             "NumeroFatura" |> Binding.oneWay (fun (_, e) -> e.NumeroFatura)
>                             "NumeroRecibo" |> Binding.oneWay (fun (_, e) -> e.NumeroRecibo)
>                             "ValorUnitFinal" |> Binding.oneWay (fun (_, e) -> e.ValorUnitFinal)
>                             "Total" |> Binding.oneWay (fun (_, e) -> e.Total)
>                 ]))

A datagrid connects to it with the following code:

>      <DataGrid ItemsSource="{Binding Transactions}" Height="326">
>         <DataGrid.Columns>
>             <DataGridTextColumn Binding="{Binding Posto}"></DataGridTextColumn>
>             <DataGridTextColumn Binding="{Binding Data}"></DataGridTextColumn>
>             <DataGridTextColumn Binding="{Binding Matricula}" Width="1"></DataGridTextColumn>
>             <DataGridTextColumn Binding="{Binding Litros}"></DataGridTextColumn>
>             <DataGridTextColumn Binding="{Binding TipoCombustivel}"></DataGridTextColumn>
>             <DataGridTextColumn Binding="{Binding Kms}"></DataGridTextColumn>
>             <DataGridTextColumn Binding="{Binding NumeroFatura}"></DataGridTextColumn>
>             <DataGridTextColumn Binding="{Binding NumeroRecibo}"></DataGridTextColumn>
>             <DataGridTextColumn Binding="{Binding ValorUnitFinal}"></DataGridTextColumn>
>             <DataGridTextColumn Binding="{Binding Total}"></DataGridTextColumn>
>             </DataGrid.Columns>
>     </DataGrid>

When the datagrid starts trying to retrieve values from it the UI blocks for a second or two as can be seen here https://i.imgur.com/OLsGEVm.gif by the spinning load image at the bottom.

This is not happening in the data retrieval (which I am running on a Cmd.OfAsync and does not block the UI thread), it only happens when the datagrid is binding to the values.

I have seen that there are some performance upgrades in progress for subModelSeq, so is this normal behavior on Elmish.WPF 3.5.6 or am I doing something wrong?

Thank you.

**Comment by bender2k14** [comment]
I didn't notice any problems from a static analysis.  Seems to me like you are going everything correctly.

In appears that you are experiencing slow performance during the initial load.  The recent performance improvements to the `SubModelSeq` sample are for computing an update.  So I don't think those improvements would help you.

When you created that GIF, what was the length of `m.Transactions`?

Can you share a branch that demonstrates this issue?  Then I could do a runtime analysis and quickly determine the problem.

**Comment by MicaelMor** [comment]
The length of m.Transactions was just 264 records.

I have created a branch of bare bones version of it using the same record type I am using for my data (But with fake test data), the branch is here https://github.com/MicaelMor/Elmish.WPF/tree/speed_problem_with_submodelseq the modifications were done in the SubModelSeq sample (to make it easier to get going on my part).
I have increased the record count to 5000 just to make the problem more obvious, the branch also has 2 commits, the first one doesn't have a busy indicator only the value being passed to a textbox, and the second I added some controls from nuget to be able to use a busy indicator which makes the problem more apparent.

While I have increased the number of records to make it more obvious, you should be able to see that the blocking still happens with lower amounts (like the 264 records I had), and it does get worse when I use another more complex datagrid instead of the default wpf datagrid, like say with syncfusion sfdatagrid, the time increases a bit.

Thank you.

**Comment by bender2k14** [comment]
That is excellent.  Thanks.

The performance is significantly better when the performance logging is turned off.
```F#
let main mainWindow =
    Program.mkProgramWpf App.init App.update Bindings.bindings
    //|> Program.withConsoleTrace
    |> Program.runWindow//WithConfig
        //{ElmConfig.Default with LogConsole = true; Measure = true}
        mainWindow
```

Side note: it will be easier to disable logging by commenting out a single line when version 4 is released (c.f. #253).

After logging is disabled, do you still think that your application is slow?

**Comment by cmeeren** [comment]
I just want to add that you should always check performance **in release mode** and, as @bender2k14 says, **without any kind of verbose logging**.

**Comment by cmeeren** [comment]
Also note that AFAIK due to the nature of the .NET runtime (whether Core or Framework), apps may feel a bit slow after startup because the JIT compiler is still compiling code paths the first time they're called. Not sure if that is relevant for your specific problem, but it may be.

**Comment by MicaelMor** [comment]
Thanks for taking a look at it.

Hadn't remember to test without logging on the datagrid, had only done it in sfdatagrid (have an #if debug mode on my project to make it easier to test on release), and yeah in the sample it is indeed much better, and a complete non issue.
It only starts being an issue on collections of a larger length, but one assumes that collections in the dozens to hundreds of thousands of rows are likely read only, and probably better candidates for OneWaySeq instead, not to mention probably something where one would be using structs instead of records.

Still, have a bit of a speed bump in my own non-sample project, where the thread is blocked for about 1.5 seconds, but it is clear now that the speed issue on that project is down to sfdatagrid, not necessarily Elmish.WPF, since besides it being fast with few records on datagrid, when bumping the count significantly (100k) the time the thread is blocked almost doubles in sfdatagrid in comparison to datagrid, going from about 4 seconds to 8 seconds.

So will close this issue down, Elmish.WPF may play a role in the performance problem because sfdatagrid has some issues with f#/elmish, like ItemsSourceChanged gets triggered once for each record of the collection, I would consider this a WPF control issue instead.

Thanks for your help on this issue.

> Also note that AFAIK due to the nature of the .NET runtime (whether Core or Framework), apps may feel a bit slow after startup because the JIT compiler is still compiling code paths the first time they're invoked (and possibly optimizing them later if they're called often). Not sure if that is relevant for your specific problem, but it may be.

Thanks for that info, something I hadn't even considered.

**Comment by cmeeren** [comment]
Glad it got better!

> be using structs instead of records

Not sure what you mean, and I realize this is off-topic, but I'd just like to clarify that structs/records are different kinds of things. F# supports struct records (just add the `[<Struct>]` attribute).

> So will close this issue down, Elmish.WPF may play a role in the performance problem because sfdatagrid has some issues with f#/elmish, like ItemsSourceChanged gets triggered once for each record of the collection, I would consider this a WPF control issue instead.

@bender2k14 I don't follow everything here, but do you think this is something we can and should improve?

**Comment by MicaelMor** [comment]
> Glad it got better!
> 
> > be using structs instead of records
> 
> Not sure what you mean, and I realize this is off-topic, but I'd just like to clarify that structs/records are different kinds of things. F# supports struct records (just add the `[<Struct>]` attribute).
> 
> > Elmish.WPF may play a role in the performance problem because sfdatagrid has some issues with f#/elmish, like ItemsSourceChanged gets triggered once for each record of the collection
> 
> @bender2k14 I don't follow everything here, but do you think this is something we can and should improve?

I am under the impression (could be wrong) that structs are more performant than records, hence my comment on its use for very large collections in situations where performance is important, although have never personally tested, or had the need for it, there are a few articles mentioning the use of structs for the purpose of gaining performance https://theburningmonk.com/2011/10/fsharp-performance-test-structs-vs-records/
Should be stressed that the article is very old, so even the example posted there might not even be true anymore, as with everything regarding performance it is always best to test for specific use case.

As for my comment on the problem with sfdatagrid, please disregard, after checking with c# code, I was wrong about what the expected behaviour of ItemsSourceChanged event was, it behaves exactly the same in F# with Elmish.WPF as it does in C#, I had merely misunderstood the way it worked.

**Comment by bender2k14** [comment]
Thanks for the updates @MicaelMor.  Glad everything is working well (enough) for you now.

> ...one assumes that collections in the dozens to hundreds of thousands of rows are likely read only, and probably better candidates for `OneWaySeq` instead...

The initial load time for `OneWay` and `OneWaySeq` bindings should be about the same.  The advantage of a `OneWaySeq` binding is that it is more efficient to update than a `OneWay` binding.

**Comment by cmeeren** [comment]
> I am under the impression (could be wrong) that structs are more performant than records, hence my comment on its use for very large collections in situations where performance is important, although have never personally tested, or had the need for it, there are a few articles mentioning the use of structs for the purpose of gaining performance https://theburningmonk.com/2011/10/fsharp-performance-test-structs-vs-records/
> Should be stressed that the article is very old, so even the example posted there might not even be true anymore, as with everything regarding performance it is always best to test for specific use case.

Sorry, I should be clearer that I was being pedantic: Records can be structs, so the correct distinction is between struct (value/stack) records and normal (reference/heap) records. The article you link to is very old; at that time, records probably didn't supports the `[<Struct>]` attribute. Nowadays you can just slap `[<Struct>]` on any record definition (and even discriminated union definition) to make it a struct (value/stack type).

> I am under the impression (could be wrong) that structs are more performant than records

AFAIK this is certainly not a categorical truth. Structs *can* be more performant, but they can also be less performant, since they have to be copied on the stack all the time instead of just referenced on the heap. It depends to a large extent on the size of the struct (the number of fields) and how it's used. In any case, the primary rule is, always measure the performance when optimizing, e.g. using [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet).

> As for my comment on the problem with sfdatagrid, please disregard, after checking with c# code, I was wrong about what the expected behaviour of ItemsSourceChanged event was, it behaves exactly the same in F# with Elmish.WPF as it does in C#, I had merely misunderstood the way it worked.

Gotcha.
