### ISSUE TITLE
TabControl: Difficulty with DataTemplate?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#268]
I'm a newbie. I do not know if this is my ignorance or an issue but would really appreciate some help .   The error from Visual Studio is:

> System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''ContactDetails' (HashCode=-728639187)'. BindingExpression:Path=Name; DataItem='ContactDetails' (HashCode=-728639187); target element is 'TabItem' (Name=''); target property is 'Header' (type 'Object')

Problem: How do I get WPF to see the  "Name" property on ContactDetails?

All suggestions are appreciated.

My WPF XAML is:

```xaml
<TabControl Grid.Row="1" ItemsSource="{Binding Details}">
            <TabControl.ItemContainerStyle>
                <Style TargetType="{x:Type TabItem}">
                    <Setter Property="Header" Value="{Binding Name}" />
                </Style>
            </TabControl.ItemContainerStyle>
            <TabControl.Resources>
                <DataTemplate DataType="{x:Type vm:ContactDetail}">
                    <vi:ContactDetailsView />
                </DataTemplate>
                <DataTemplate DataType="{x:Type vm:Internet}">
                    <vi:InternetView/>
                </DataTemplate>
                <DataTemplate DataType="{x:Type vm:PhoneNumber}">
                    <vi:PhoneNumbersView/>
                </DataTemplate>
                <DataTemplate DataType="{x:Type vm:Address}">
                    <vi:AddressesView/>
                </DataTemplate>
            </TabControl.Resources>
        </TabControl>
```

My Elmish.WPF code is:

```f#
namespace Models

open Elmish.WPF
open Elmish
open System
open System.Windows

type ContactDetail = { Name: string; Content: string; Text: string }
type Internet      = { Name: string; Content: string; Text: string }
type PhoneNumber   = { Name: string; Content: string; Text: string }
type Address       = { Name: string; Content: string; Text: string }

    module FrontOffice =    
        type Details =
            | ContactDetails of ContactDetail 
            | Internet       of Internet      
            | PhoneNumbers   of PhoneNumber   
            | Addresses      of Address       
    
        let contactDetail  : ContactDetail = { Name="Contact Detail"; Content="Content for Contact Detail"; Text="here is the contact detail text" }    
        let internet       : Internet = { Name="Internet"; Content="Content for Internet"; Text="here is the internet text" }
        let phoneNumber    : PhoneNumber =  { Name="Phone Number"; Content="Content for phone number"; Text="here is the phone number text" }
        let address        : Address = { Name="Address"; Content="Content for Address"; Text="here is the Address text" }
       
        let details   = [ContactDetails contactDetail
                         Internet internet
                         PhoneNumbers phoneNumber
                         Addresses address
                         ]

        type Model = {
          ClickCount: int
          Message: string
          Details: Details seq
          ContactDetails: ContactDetail
        }

        let init() = 
           {
              ClickCount = 0
              Message = "Hello Elmish.WPF"
              Details = details
              ContactDetails = contactDetail
           }
    
        type Msg =
          | ButtonClicked
          | Reset

        let update (msg: Msg) (model: Model) =
          match msg with 
          | ButtonClicked -> {model with ClickCount = model.ClickCount + 1}
          | Reset -> init()

     
        let bindings(): Binding<Model, Msg> list =
            [
              // One-Way Bindings
              "ClickCount" |> Binding.oneWay (fun m -> m.ClickCount)
              "Message" |> Binding.oneWay (fun m -> m.Message)
              "Details" |> Binding.oneWay (fun m -> m.Details) 
              "ContactDetails" |> Binding.oneWay (fun m -> m.ContactDetails) 
    
              // Commands
              "ClickCommand" |> Binding.cmd ButtonClicked
              "ResetCommand" |> Binding.cmd Reset
            ]

   
        let entryPoint (mainWindow: Window) =    
            Program.mkSimpleWpf init update bindings
            |> Program.runWindowWithConfig
                       { ElmConfig.Default with LogTrace = true; Measure = true; MeasureLimitMs = 1 }
                       mainWindow
```

**Comment by awaynemd** [comment]
@bender2k14 -- I would love to leave a branch--but don't know how. Where do I find the instructions?

**Comment by bender2k14** [comment]
I think the simplest way is to
1. fork this repository on GitHub,
2. clone your fork to your local machine,
3. create a branch,
4. change one of the Elmish.WPF samples to use your code and reproduce the behavior you describe,
5. push your branch to your fork, and
6. share the link to that branch on your fork with us here.

I can explain some parts in more details if you get stuck.

**Comment by awaynemd** [comment]
I have been working with the above problem. I have now changed the bindings to:

let bindings(): Binding<Model, Msg> list =
            [
              // One-Way Bindings
              "ClickCount" |> Binding.oneWay (fun m -> m.ClickCount)
              "Message" |> Binding.oneWay (fun m -> m.Message)
              "Details" |> Binding.subModelSeq((fun m -> m.Details), (fun detail -> detail.id), fun () ->
                  [
                      "Id"   |> Binding.oneWay (fun (_, detail) -> detail.id)
                      "Name" |> Binding.oneWay (fun (_, detail) -> detail.name)
                      "Content" |> Binding.oneWay (fun (_,detail) -> detail.content)
                  ])

              
              // Commands
              "ClickCommand" |> Binding.cmd ButtonClicked
              "ResetCommand" |> Binding.cmd Reset
            ]

Where Details is:
 
let details   = [ContactDetail (contactDetail,Guid.NewGuid())
                         Internet      (internet,Guid.NewGuid())
                         PhoneNumber   (phoneNumber,Guid.NewGuid())
                         Address       (address,Guid.NewGuid())
                         ]

and the Model is:

type Model = {
          ClickCount: int
          Message: string
          Details: Details list
        }

However, now the issue has changed to: 

Elmish.WPF.ViewModel'2[System.Object.System.Object] 

is what the WPF DataTemplate is receiving for the x:Type

I think I will post this as a separate issue.

**Comment by bender2k14** [comment]
> I think I will post this as a separate issue.

Try to include a branch with that new issue.

**Comment by cmeeren** [comment]
Note @awaynemd that it's easier to read the code if you format it properly, like this:

    ```f#
    let x = 2
    ```

**Comment by bender2k14** [comment]
Here is [the branch](https://github.com/awaynemd/Elmish.WPF/tree/Failing-resolution-of-TabControl) that @awaynemd shared in PR #273.

**Comment by bender2k14** [comment]
You just copy-pasted your files into the root of the repository.  Can you put them in a project so that I can run them and see the behavior that you are seeing at runtime?
