### ISSUE TITLE
Best approach at debug?  "Object is Null"

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#277]
Hi All:

I'm coming from C# with little experience in F#.  My current  problem in writing F# is:
 
"Object is Null" and I have no idea why. The stack trace seems useless (to me) and the error message is not very helpful.

In C# (visual studio) I have grown used to having the Output window clearly show what bindings (from xaml) are in error  and the stack output also shows clearly where I made a mistake.  I don't seem to be getting this when writing code in Elmish.WPF.

I'm afraid my coding skills leave a lot to be desired. 

Can anyone suggest a good method to debug code in F#/Elmish/Elmish.WPF?

TIA

**Comment by bender2k14** [comment]
Can you share the code in question (either as a ZIP or a branch in a GitHub repository)?  Also, can you give a specific sequence of steps that causes this behavior?

> In C# (visual studio) I have grown used to having the Output window clearly show what bindings (from xaml) are in error and the stack output also shows clearly where I made a mistake. I don't seem to be getting this when writing code in Elmish.WPF.

Elmish.WPF does not prevent anything sent to the Output window in Visual Studio from reaching it.  What you are used to seeing will still be there.

Elmish.WPF currently supports two logging sinks: [console and trace](https://github.com/elmish/Elmish.WPF/blob/63ad86ab1af44a8ebbc8eed710dbdf62b865ccc1/src/Elmish.WPF/Config.fs#L14-L15) (i.e. the Output window in Visual Studio).  Looking ahead, the [next version of Elmish.WPF will support structured logging to any sink](https://github.com/elmish/Elmish.WPF/issues/253#:~:text=PR%20%23255%20%2D%20Support%20logging%20to%20any%20sink%20(c.f.%20%23105)).

The use of adverb "clearly" is subjective.  I am not impressed with the information that WPF gives when there is a binding error.  I think the information given by Elmish.WPF is more helpful.

**Comment by awaynemd** [comment]
@bender2k14 I'll be happy to. But I'll need to get home first (about 5hrs). In times of past, I'll usually see "Error: ..." when the binding cannot find its source in the datacontext..  I don't seem to be seeing this?? From memory, I'm getting the error in the use of subModel

**Comment by awaynemd** [comment]
@TysonMN I can't explain it. Replicating the solution to issue #270 /#274 with subModels in my application, it failed with "Object is Null" when running the bindings.  That resulted in this question. 

However, my visual studio uses the old non-sdk framework.  So I remade the entire solution and applied the new sdk wizard before attempting transport to Github. It too failed on the F# project saying something about FSharp.Core not targeting .Net Framework 4.7.2 (only .Net 4.0). So failing on this, I made another solution with a combination of the WPF projects (with the newer sdk framework, and the original F# project.    ....And now for reasons I can't understand all is working correctly.

It is frustrating not knowing why it didn't work originally or what in particular I did to fix it.  In either case, it is working (at this time).  

Thanks.  BTW, I still would be interested in an example of usage on console and trace.

**Comment by awaynemd** [comment]
@TysonMN Also any Idea on how to change the default template on Visual studio 2010 to be sdk compliant?

**Comment by TysonMN** [comment]
> any Idea on how to change the default template on Visual studio 2010 to be sdk compliant?

No.  Are you able to new a newer version of Visual Studio?  That version is very old.  (So old that is it is [no longer being supported](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History).)

> It too failed on the F# project saying something about FSharp.Core not targeting .Net Framework 4.7.2 (only .Net 4.0).

I think you might have gotten this backwards.  [Visual Studio 2010 only supports targeting up to .NET Framework 4.0](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History), so the error was probably that you can't have your project in Visual Studio 2010 depend on a version of `FSharp.Core` that targets .NET 4.7.2.  [Elmish.WPF requires version 4.6.2+ of FSharp.Core](https://github.com/elmish/Elmish.WPF/blob/bd74fd68dcc5cdbf12f98341c76945c663d837bf/src/Elmish.WPF/Elmish.WPF.fsproj#L50), which constrains the version of .NET Framework to be at least 4.5+.  Then Elmish.WPF strengthens this constraint further by [constraining the version of .NET Framework to be at least 4.6.1](https://github.com/elmish/Elmish.WPF/blob/bd74fd68dcc5cdbf12f98341c76945c663d837bf/src/Elmish.WPF/Elmish.WPF.fsproj#L4).

> I still would be interested in an example of usage on console and trace.

All the samples log to console.

**Comment by awaynemd** [comment]
@TysonMD Ooops! I'm usiing 2019...Sorry.
