### ISSUE TITLE
how is an Indexed-Binding made for a DataGrid?  (Binding to an element of a list)

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#279]
Thanks for any help or suggestions.

In the below UserControl for a DataGrid, the line:.

`<customcontrols:AppointmentListView ItemsSource="{Binding columns[0].appointmentKeys}" Height="140" Background="Bisque">`

performs a binding to a column by its index, how is this binding made in Elmish.WPF?

In F#,  a Row is:
type Row =
     { RowTime: string 
       Columns: Cell List }

Assuming the DataContext for this line is Rows, in C# the Row is defined as:

```
public class Row : IRow
    {
        public string rowTime { get; set; }          
        public List<ICell> columns { get; set; }     
        private const int columnCount = 4;

        public Row(int rowNumber, string rowTime)
        {
            this.rowTime = rowTime;
            this.columns = new List<ICell>();

            for (int i = 0; i < columnCount; i++)
            {
                var t = TimeSpan.FromMinutes(i * 15);
                columns.Add(new Cell(rowNumber, i, t));
            }
        }

        public Row()
        {
        }

        // Indexer declaration. If index is out of range, the rows array will throw the exception.
        public ICell this[int index]
        {
            get { return columns[index]; }
            set { columns[index] = value; }
        }
    }
```
Thanks in Advance!

In full disclosure, here is the full UserControl XAML:
```
<UserControl x:Class="FrontOffice.AppointmentsView"
             x:Name="root"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:FrontOffice"
             xmlns:customcontrols="clr-namespace:CustomControls;assembly=CustomControls"
             mc:Ignorable="d" 
             d:DesignHeight="800" d:DesignWidth="1200">
   
```
```

<!--
        Assign the ROOT element of a user control a name. Usual name is LayoutRoot or Root. This will be used as reference with 
        ElementName. Do not set the DataContext of a usercontrol 
    -->

    <UserControl.Resources>
        <local:IsNullConverter x:Key="isNullConverter"/>

        <!-- DataContext is AppointmentKey -->
        <Style TargetType="{x:Type ListViewItem}">
            <Style.Triggers>
                <DataTrigger Binding="{Binding tservice,  Converter={StaticResource isNullConverter}}" Value="False">
                    <Setter Property="Background" Value="LawnGreen" />
                </DataTrigger>
            </Style.Triggers>
        </Style>
    </UserControl.Resources>

    <Border  BorderBrush="Black" BorderThickness="4" >
        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="Auto"/>
                <ColumnDefinition/>
                <ColumnDefinition/>
                <ColumnDefinition/>
                <ColumnDefinition/>
                <ColumnDefinition Width="Auto"/>
                <ColumnDefinition Width="Auto"/>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition  Height="30"/>
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
                <RowDefinition />
            </Grid.RowDefinitions>

            <!--The DataContext for this user control is the AppointmentEditor. 
                A customcontrol for the DataGrid is being used to listen for events from the selected item. Selecting an item raises an 
                custom routed event from the customcontrols:AppointmentListView. The Cells of the datagrid consists of AppointmentListViews -->
            <TextBlock Grid.Row="0" Grid.Column="1" Grid.ColumnSpan="4" Text="{Binding SelectedAppointmentDate, StringFormat=D}" 
                               FontSize="24" FontWeight="ExtraBold" TextAlignment="Center"/>

            <TextBlock Grid.Row="0" Grid.Column="6" x:Name="CurrentTime" Width="60"
                   HorizontalAlignment="Right" Margin="2" FontWeight="SemiBold" FontSize="14"/>

            <!-- 
                A customcontrol for the DataGrid is being used to listen for events from the selected item. Selecting an item raises a 
                custom routed event from the customcontrols:AppointmentListView. The Cells of the datagrid consists of AppointmentListView.
                customcontrols:AppointmentListView.ScheduledAppointment is defined as a routed event. This syntax attaches the routed event
                to the AppointmentDataGrid_ScheduledAppointment handler found in the code-behind. The AppointmentListView is being attached
                to each Cell of the AppointmentDataGrid.
            -->
            <customcontrols:AppointmentDataGrid x:Name="AppointmentTable" Grid.Row="1" Grid.Column="1" Grid.ColumnSpan="4" Grid.RowSpan="6"
                      ItemsSource="{Binding Rows}" AutoGenerateColumns="False" 
                      CanUserAddRows="False"  AlternationCount="2" AlternatingRowBackground="LightYellow"
                      customcontrols:AppointmentListView.ScheduledAppointment ="AppointmentDataGrid_ScheduledAppointment" 
                      SelectedItem="{Binding SelectedRow}"                          
                      >

                <DataGrid.Columns>
                    <!--The DataContext for DataGrid Columns is from the itemsSource Rows.
                        The Syntax is to address the content objects within a cell is Row[columindex] or Row["column header"]  -->
                    <DataGridTextColumn Header="Time" Binding="{Binding RowTime}" />

                    <DataGridTemplateColumn Header="0:00" Width="354" IsReadOnly="True">
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="HorizontalAlignment" Value="Center"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <!--A custom control is required here to detect mouse events and raise a routed event. A Behavior cannot raise a routed event.-->
                                <!--The DataContext here is from the ItemsSource Row-->
                                <customcontrols:AppointmentListView ItemsSource="{Binding columns[0].appointmentKeys}" Height="140" Background="Bisque">
                                    <ListView.View>
                                        <GridView>
                                            <GridViewColumn Header="First"     DisplayMemberBinding="{Binding firstName}" Width="100"/>
                                            <GridViewColumn Header="Last"      DisplayMemberBinding="{Binding lastName}"  Width="120"/>
                                            <GridViewColumn Header="BirthDate" DisplayMemberBinding="{Binding birthDate, StringFormat=d}" Width="100"/>
                                        </GridView>
                                    </ListView.View>
                                </customcontrols:AppointmentListView>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

                    <DataGridTemplateColumn Header="0:15" Width="354" IsReadOnly="True">
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="HorizontalAlignment" Value="Center"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <customcontrols:AppointmentListView ItemsSource="{Binding columns[1].appointmentKeys}" Height="140" Background="Bisque">
                                    <ListView.View>
                                        <GridView>
                                            <GridViewColumn Header="First"     DisplayMemberBinding="{Binding firstName}" Width="100"/>
                                            <GridViewColumn Header="Last"      DisplayMemberBinding="{Binding lastName}"  Width="120"/>
                                            <GridViewColumn Header="BirthDate" DisplayMemberBinding="{Binding birthDate, StringFormat=d}" Width="100"/>
                                        </GridView>
                                    </ListView.View>
                                </customcontrols:AppointmentListView>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

                    <DataGridTemplateColumn Header="0:30" Width="354" IsReadOnly="True" >
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="HorizontalAlignment" Value="Center"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <customcontrols:AppointmentListView ItemsSource="{Binding columns[2].appointmentKeys}" Height="140" Background="Bisque">
                                    <ListView.View>
                                        <GridView>
                                            <GridViewColumn Header="First"     DisplayMemberBinding="{Binding firstName}" Width="100"/>
                                            <GridViewColumn Header="Last"      DisplayMemberBinding="{Binding lastName}"  Width="120"/>
                                            <GridViewColumn Header="BirthDate" DisplayMemberBinding="{Binding birthDate, StringFormat=d}" Width="100"/>
                                        </GridView>
                                    </ListView.View>
                                </customcontrols:AppointmentListView>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

                    <DataGridTemplateColumn Header="0:45" Width="354" IsReadOnly="True">
                        <DataGridTemplateColumn.HeaderStyle>
                            <Style TargetType="{x:Type DataGridColumnHeader}">
                                <Setter Property="HorizontalAlignment" Value="Center"/>
                            </Style>
                        </DataGridTemplateColumn.HeaderStyle>
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <customcontrols:AppointmentListView ItemsSource="{Binding columns[3].appointmentKeys}"  Height="140" Background="Bisque">
                                    <ListView.View>
                                        <GridView>
                                            <GridViewColumn Header="First"     DisplayMemberBinding="{Binding firstName}" Width="100"/>
                                            <GridViewColumn Header="Last"      DisplayMemberBinding="{Binding lastName}"  Width="120"/>
                                            <GridViewColumn Header="BirthDate" DisplayMemberBinding="{Binding birthDate, StringFormat=d}" Width="100"/>
                                        </GridView>
                                    </ListView.View>
                                </customcontrols:AppointmentListView>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>
                </DataGrid.Columns>
            </customcontrols:AppointmentDataGrid>
        </Grid>
    </Border>
</UserControl>
```

**Comment by TysonMN** [comment]
I gave you lots of feedback in https://github.com/elmish/Elmish.WPF/issues/274#issuecomment-688019614.  Before we consider another issue, can you make improvements based on that feedback?  The first thing I suggested there was to use the new SDK-style format for your project files.  Is there anything preventing you from using that file format?

**Comment by awaynemd** [comment]
@TysonMN  I tried to convert the solution with dotnet migrate-2019 wizard. The C# projects seem to convert well, but the F# project failed.. I have no idea why.   :(

I will try again.  Any better suggestions?  Thanks.

**Comment by awaynemd** [comment]
@TysonMN  Ran it again, all the C# projects are now in sdk format.   However, the F#/Elmish project (did convert) but gave the following errors. Please Advise, Thanks.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package FSharp.Core 4.7.2 is not compatible with net40 (.NETFramework,Version=v4.0). Package FSharp.Core 4.7.2 supports:
  - net45 (.NETFramework,Version=v4.5)
  - netstandard2.0 (.NETStandard,Version=v2.0)	FrontOfficeModels	C:\StargateXII\StargateXII\FrontOfficeModels\FrontOfficeModels.fsproj	1	

Error	NU1202	Package Elmish.WPF 3.5.6 is not compatible with net40 (.NETFramework,Version=v4.0). Package Elmish.WPF 3.5.6 supports:
  - net461 (.NETFramework,Version=v4.6.1)
  - netcoreapp3.0 (.NETCoreApp,Version=v3.0)	FrontOfficeModels	
C:\StargateXII\StargateXII\FrontOfficeModels\FrontOfficeModels.fsproj	1
	
Error	NU1202	Package Elmish 3.1.0 is not compatible with net40 (.NETFramework,Version=v4.0). Package Elmish 3.1.0 supports:
  - net461 (.NETFramework,Version=v4.6.1)
  - netstandard1.6 (.NETStandard,Version=v1.6)
  - netstandard2.0 (.NETStandard,Version=v2.0)	FrontOfficeModels	C:\StargateXII\StargateXII\FrontOfficeModels\FrontOfficeModels.fsproj	1	


Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Elmish.WPF 3.5.6 is not compatible with net40 (.NETFramework,Version=v4.0). Package Elmish.WPF 3.5.6 supports:
  - net461 (.NETFramework,Version=v4.6.1)
  - netcoreapp3.0 (.NETCoreApp,Version=v3.0)	FrontOfficeModels	C:\StargateXII\StargateXII\FrontOfficeModels\FrontOfficeModels.fsproj	1

**Comment by awaynemd** [comment]
> @TysonMN  BTW, after conversion it no longer compiles... :(

**Comment by TysonMN** [comment]
I have never used a conversion tool.  I recommend just recreating the projects and adding what is needed.  That is what I did in [these](https://github.com/TysonMN/awaynemd_274/commit/81238b6a3b88d805fccd76a27d28c3ad2c345afd) [commits](https://github.com/TysonMN/awaynemd_274/commit/23262ccfad254eb3f79b0feba947e03774716cf7).

**Comment by awaynemd** [comment]
@TysonMN Sorry for my ignorance.  Recreate projects using what Framework? I'm guessing not .net framework 4.7.2 ???

**Comment by TysonMN** [comment]
You can target .NET Framework 4.7.2 if you want.  [Elmish.WPF supports .NET Framework 4.6.1+ and .NET Core 3.0+](https://github.com/elmish/Elmish.WPF/blob/bd74fd68dcc5cdbf12f98341c76945c663d837bf/src/Elmish.WPF/Elmish.WPF.fsproj#L4).

**Comment by awaynemd** [comment]
@TysonMN That's what I did twice before.. Visual Studio 2019 Community does not build to sdk by default. (If it does, I do not know how to make it...Sorry.. This old dog can't seem to hunt anymore. :(  )

**Comment by TysonMN** [comment]
I didn't think using the Community edition of Visual Studio should make a difference.

> Do you use project type .NET CORE?

I think you are asking this: when picking a template for a new project in Visual Studio, should you pick one that says it is for .NET Core?  Yes, always.  If you want to target .NET Framework, you can easily change that after.  The reason to do this is because the .NET Framework project templates in Visual Studio use the old (non-SDK-style) format for the project files while the .NET Core project templates use the new (SDK-style) format for the project files.

**Comment by awaynemd** [comment]
@TysonMN  Yep! That explains it! Reformatting now...Please stay tuned.  Thanks :)

**Comment by awaynemd** [comment]
@TysonMN Got it! (I Think). 

Try [https://github.com/awaynemd/StargateXII](url)

The startup file is: FrontOffice  (it didn't come through).  Please ignore all the unused (as yet) xaml files....Back to the central question: how is binding done for columns[1].appointmentKeys?

Thanks.

BTW, this was unnecessarily _difficult_, for others following my learning curve:
 1.  To use the desired sdk platform, the initial project creation must be of .Net Core -- not .Net Framework!
 2.  For projects within the the visual studio solution, all must use the same target framework ( 4.7.2 in my case).
 3. There are many videos and instructions on using visual studio with github on the internet. After spending _all day_ on this,, **NONE** of the ones I found were of any use in getting the solution _AND_ all of its subfolders (if any) pushed to github.  This, even after, installing the github extension and github for windows.
 4. Before adding the Elmish.WPF/Elmish packages by github, select and compile the desired target framework. (If I didn't do this, I kept getting an "Object is Null" on the F# code).
5. Ultimately, after correctly obtaining the solution and all its projects in sdk format, simply copying the solution and its subfolders to an empty directory and manually entering the github commands (there is only 4 or 5 needed), the solution and its subfolders are _easily_ transferred to github.

Much learned, but I'm afraid the internet was more of a hinderance than a help.

**Comment by TysonMN** [comment]
Great!  Now that you have shared your code as a GitHub repository, I can easily provide changes to you as pull requests, and you can easily incorporating my changes by completing the pull requests.

Your linking markdown in...
> Try [https://github.com/awaynemd/StargateXII](url)

...is...
```
[https://github.com/awaynemd/StargateXII](url)
```

...but it should be
```
https://github.com/awaynemd/StargateXII
```

I edited your comment to correct this.

**Comment by TysonMN** [comment]
> Please ignore all the unused (as yet) xaml files...

This is not the correct mindset.  When asking others for help, you should be respectful of their time by trying to make it as easy as possible for them to help you.  The gold standard is to share code that is a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).  That Wikipedia article is short, but it has external links to much longer explanations.

Now that you are managing versions of your code with git, you should remove all code that is not necessary to ask your question and then commit that change.  None of the removed code is lost.  You can easily checkout the commit before you removed this code to get it all back.

**Comment by awaynemd** [comment]
@TysonMN Sorry...Will do so..._No disrespect was intended!_ Thanks.

**Comment by TysonMN** [comment]
> No disrespect was intended!

Yep, that is what I both assumed and "know" ;)

> I guess I'll remove it for now until it meets the standard :(

We can keep the question open.  It just won't be solved as quickly as it would if your code was in better shape.

Don't worry though.  I am committed to helping you.

I just noticed that you deleted your repository at https://github.com/awaynemd/StargateXII.  As I said in https://github.com/elmish/Elmish.WPF/issues/279#issuecomment-694851318, when your code is in a GitHub repository, I can easily provide changes to you as pull requests, and you can easily incorporating my changes by completing the pull requests.  You should recreate that GitHub repository with the code in it.

**Comment by TysonMN** [comment]
> > Please ignore all the unused (as yet) xaml files...
>
> This is not the correct mindset. When asking others for help, you should be respectful of their time by trying to make it as easy as possible for them to help you.

I said this because I wanted you to delete the unused XAML files, not because I wanted you to delete your git repository.  I will help you improve your code in your git repository.  That is why I had created a PR in your repository.

**Comment by awaynemd** [comment]
@TysonMN 
Got it!  Try:  https://github.com/awaynemd/MyDataGrid

This is my first attempt at a date in an appointment book. The logic is that a DataGrid consists of "Rows" -- a list of 10 Row types (always). Each Row then consists of a list of 4 Cells -- one cell per column (always). Each cell is displayed in a ListView and consists of 0 to 4 possible appointment names (i.e., Visit). Each Row and Cell is assigned a time on the specified date. (All appointments within a cell have the same time).

_My initial problem of using an index [] in xaml of: "{Binding Columns[0].AppointmentKeys}" seems to have been resolved when recreating the problem in for this demo!_

However, I still have some major glaring problems with F# e.g.: FirstName should be "FirstName1" and not "Some(FirstName1)". LastName should be "LastName1" and not "Some(LastName1)".  BirthDate should be "09/14/2020" and not "Some(09/14/2020 00:00:00)"

Also, I would have thought that the binding to Rows should be a Binding.subModel, so even though "Rows" |> Binding.oneWay( fun m -> m.Rows) seems to work, is it the best way to do this?

Lastly, at some point the appointment names will be edited/added/deleted etc (say as from a database) -- will this update the UI?  What is the best way to update the UI when a "Visit" within a cell has been changed or deleted?

Thanks for any thoughts and all your help. :)

TIA

**Comment by TysonMN** [comment]
Why did you close this issue?
