### ISSUE TITLE
Confusion on using subModel with a WPF indexed list

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#280]
Source code at: https://github.com/awaynemd/DatagridWithSubModel

After attempting to make the "Rows" of a datagrid a submodel, I successfully confused the h*l out of my self and failed miserably.

How is a binding made to a "Row list"?  Please see the source code.

Much Thanks for any help.

**Comment by TysonMN** [comment]
When you need help with Elmish.WPF, please continue to ask for help in this GitHub repository by creating a new issue or commenting on an existing issue.  It is more difficult for me to help you when you post your questions on StackOverflow.

**Comment by TysonMN** [comment]
I created two issues in your repository.  Do you think you can do what they request?

**Comment by TysonMN** [comment]
My impression is that this issue has been subsumed by issue #281.  Please reopen if I am mistaken.
