### ISSUE TITLE
How to use subModelSelectedItem on level 2 or level 3 submodel

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#281]
As a newbie, I'm trying to understand F# and Elmish.wpf.  My newest issue is in using subModelSelectedItem. I can not seem to get the F# code to compile when I use subModelSelectedItem on level 2 or level3 submodels. This error, I'm sorry to say, I do not understand:

_FS0001: Type mismatch. Expecting a 'string -> Binding<(Model * 'a), b>' 
but given a
  'string -> Binding<Model,Msg>'.
The type 'Model * 'a' does not match the type 'Model'_ 

Who is expecting what? And how do I fix it?  

Thanks for any help.

Full source code at: https://github.com/awaynemd/DatagridWithSubModel.git

**Comment by cmeeren** [comment]
The model you pass to `subModelSelectedItem` has to be the same type as the model in your corresponding `subModel` binding.

For example, the `"SelectedRow"` binding references the `"`Rows"` binding. For the overload you are using, the `"Rows"` binding produces the model type `Model * Row.Model`. This is described [here in the tutorial](https://github.com/elmish/Elmish.WPF/blob/master/TUTORIAL.md#level-1-no-separate-message-type-or-customization-of-model-for-sub-bindings):

> In other words, inside the sub-bindings, the model parameter (in each binding) is a tuple with the parent model and the sub-model.

You use this model type correctly on [this line](https://github.com/awaynemd/DatagridWithSubModel/blob/668466f95fd117763d597ab4cd8a2faf40ed510d/DataGrid/Program.fs#L105), though you need to replace [this line](https://github.com/awaynemd/DatagridWithSubModel/blob/668466f95fd117763d597ab4cd8a2faf40ed510d/DataGrid/Program.fs#L107) with `(fun (_,r) -> r.Columns)`.

In the `subModelSelectedItem` binding, you need to use the same model type (tuple):

```f#
"SelectedRow" |> Binding.subModelSelectedItem("Rows", (fun (m, _) -> m.SelectedRow), SetSelectedRow)
```

**Comment by awaynemd** [comment]
@cmeeren  Thank you for your help. It is truly appreciated. 

After making the changes, I am still getting:

Line: 109 Cell.bindings
   now reports: val bindings: unit -> Binding<Cell.Model * 'a), Cell.Msg>list
Generic parameters: 'a is 'b
The type 'a * Model' does not match the type 'Cell.Model'

Line: 146
"SelectedRow" |> Binding.subModelSelectedItem("Rows", (fun (m,_) -> m.SelectedRow), SetSelectedRow)
now reports:
Type mismatch. Expecting a 'string -> Binding<Model, Msg>'
but given a
 'string -> Binding<Model * 'a), Msg>'
The type 'Model' does not match the type 'Model * 'a'

Suggestions?

**Comment by TysonMN** [comment]
Can you push those changes to your repository?

**Comment by awaynemd** [comment]
@TysonMN Yes :) Just did so.  (Still have same error though :( ).

**Comment by awaynemd** [comment]
@cmeeren Have now made a few more changes -- only one error:

val bindings: unit -> Binding<('a * Row.Model), Cell.Msg> list

Generic parameters: 'a is Model
Full name: MyDataGrid.DataGrid.Row.bindings

FS0001: The type 'Msg' does not match the type 'Cell.Msg'

```
let bindings () : Binding<Model, Msg> list = [
  "SelectedAppointmentDate" |> Binding.twoWay( (fun m -> m.AppointmentDate), SetAppointmentDate)

  "Rows" |> Binding.subModelSeq(
                                 (fun m -> m.Rows),
                                 (fun r -> r.Id),
                                  Row.bindings
                               )                          
                    
  "SelectedRow" |> Binding.subModelSelectedItem("Rows", (fun m -> m.SelectedRow), SetSelectedRow)
]
```

Huh? How is this fixed? Thanks.

**Comment by cmeeren** [comment]
Baserd on the error message you quote, I guess you need to use another overload of `subModelSeq` that accepts a function to map your message type from `Cell.Msg` to the `Msg` type used in the binding list you show above. I recommend you take a look at [this section of the tutorial](https://github.com/elmish/Elmish.WPF/blob/master/TUTORIAL.md#sub-model-bindings) which goes through the different variants of `subModelSeq`. In particular, it's the "level 2" variant that's relevant here.

**Comment by TysonMN** [comment]
I just created PR https://github.com/awaynemd/DatagridWithSubModel/pull/4 that gets your F# code to compile.  It is not perfect, but hopefully it helps you make progress.

I still don't understand what you are trying to do.  I am concerned that we are currently involved in an [XY Problem](https://en.wikipedia.org/wiki/XY_problem).

Can you tell us what you are trying to achieve?  (Instead of how you are trying but failing to achieve it.)

**Comment by awaynemd** [comment]
@TysonMN  Sure.  I'm trying to achieve several different things. The application using the datagrid will eventually be an appointment book. I'm hoping to understand F# better to convert--in the best way possible--a working appointment book that I wrote in C#. So the second thing I'm trying to understand is how to think in F#, which implies the third thing of understanding the approach Elmish.WPF takes in working with the UI. I hope this is not a discouragement to you all, but the books I have encountered (so far) do not seem to address my real-life problems. I would be nowhere without you all, so really appreciate the help! Is this an XY problem--probably. However, when your a newbie like myself, formulating the exact appropriate question can be hard when your new to the topic. (Give me a question in physics and I would be happy to formulate the exact question--F# not so much, yet :)

**Comment by TysonMN** [comment]
The main thing that I find useful is playing with the sample projects.  Have you done that?  Run all of them.  Interact with everything.  Change the code a bit, run again, and see how it changes.  Break something on purpose (like change the name of a binding or remove a conversion...as long as the F# code still complies) and see in what precise way the applications fails at runtime.

Operationally, I suggest starting slower because you are doing this for the purpose of learning.  Only add something to your project if you understand what it does and it makes the project strictly better.  This is not how real applications need to be developed.  In that case, we often need to be more pragmatic and add code that implements only 80% of some feature and might introduce some bug.
