### ISSUE TITLE
Recommended way to use RadioButton

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#283]
I just realized something that seems obvious in hindsight.  I think the correct way to use a `RadioButton` with Elmish.WPF is to do a `OneWay` binding to the `IsChecked` property and then use a `Cmd` binding to the `Command` property to handle click events.

I created [this repository](https://github.com/TysonMN/Elmish.WPF_RadioButtons) to demonstrate this approach, which I called `SetViaCommand`, and contrast it with the two other approaches that I have used.

Below is a somewhat rambling explanation of the issue with using `TwoWay` bindings to the `IsChecked` properties.  Then I close with short paragraph and some questions for discussion.

---------------------

For a long time now, I have been using a `TwoWay` binding to the `IsChecked` property of `RadioButton`.  In my model, I store the state of the radio button group as a single instance of a discriminated union: one case for each radio button.  If the use case allows no radio button to be selected, then I make the discriminated union optional in the model.

If the discriminated union is optional, then there is no issue.  But what if you want to model a discriminated union that is not optional?

Suppose the XAML look like this.
```fsharp
<StackPanel Orientation="Vertical">
  <StackPanel Orientation="Horizontal">
    <RadioButton IsChecked="{Binding IsA}" GroupName="DU"/>
    <TextBlock Text="A"/>
  </StackPanel>
  <StackPanel Orientation="Horizontal">
    <RadioButton IsChecked="{Binding IsB}" GroupName="DU"/>
    <TextBlock Text="B"/>
  </StackPanel>
</StackPanel>
```

Now compare these two cases.

**Case 1:**
State: `B` is selected.
User interaction: `A` is clicked.
WPF behavior:
1. Binding for `IsChecked` of `A` is set to `true`
2. Binding for `IsChecked` of `B` is set to `false`

**Case 2:**
State: `A` is selected.
User interaction: `B` is clicked.
WPF behavior:
1. Binding for `IsChecked` of `A` is set to `false`
2. Binding for `IsChecked` of `B` is set to `true`

Suppose the DU is optional.  Then when `false` is set for some binding, I check if the DU is in the case corresponding to the binding.  If so, then I set the optional DU to `None`.  If not, then I leave the DU unchanged.

What if the DU is not optional?  Then when `false` is set for some binding, it should always be a no-op.  I achieved this via an explicit `NoOp` message that returns the model given as input.  As I type this, another idea that comes to mind is to adjust the message that sets the DU to have an optional instance of the DU.  Then if I want the behavior to be a no-op, I could pass in that message containing the value `None`.

----------------------

However, none of these compromises is ideal.  For performance reasons but more importantly for the experience during debugging or when reading logs, it is preferable to not have no-op behavior.  Let me say that another way.  Instead of dispatching a message that when handled by `update` causes the same model to be returned as the one given, it is preferable to not have dispatched a message at all.  That is what my new approach to using `RadioButton`s does.

How obvious is this to others?  Am I the only one who didn't think (until now) of this approach to using `RadioButton`s?  Is there an even better way to use `RadioButton`s that I still haven't thought of?

**Comment by cmeeren** [comment]
Makes sense to me. I just had a quick look at your solution, and I noticed that the Command version did not use `GroupName`, contrary to the snippet you provided above. Does that influence the behavior? I can't research it right this moment, but I can imagine that removing `GroupName` means that the radio buttons are not linked and you won't get a `false` message when you select another button.

In any case, I think you could also use a `twoWayOpt` binding and only dispatch whatever you want when the value received from WPF is `true`.

**Comment by TysonMN** [comment]
> I just had a quick look at the SendViaCommand part of your repo, and I noticed that it did not use `GroupName`, contrary to the snippet you provided above. Does that influence the behavior? I can't research it right this moment, but I can imagine that removing `GroupName` means that the radio buttons are not linked and you won't get a `false` message when you select another button.

If `GroupName` is not explicitly set, then it is implicitly set to an empty string, so all `RadioButton`s are in the same group by default.  The behavior you described would be achieved by setting each `GroupName` to a unique string.

Quoting the [`GroupName` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.radiobutton.groupname):
> The name that specifies which `RadioButton` controls are mutually exclusive. The default is an empty string.

**Comment by TysonMN** [comment]
> ...I think you could also use a `twoWayOpt` binding and only dispatch whatever you want when the value received from WPF is `true`.

How?

Here is the relevant code.
https://github.com/elmish/Elmish.WPF/blob/fe96ce4b0f149f6d16cc8d52ba0b6180259a8227/src/Elmish.WPF/ViewModel.fs#L410-L415
https://github.com/elmish/Elmish.WPF/blob/fe96ce4b0f149f6d16cc8d52ba0b6180259a8227/src/Elmish.WPF/ViewModel.fs#L754-L758
https://github.com/elmish/Elmish.WPF/blob/fe96ce4b0f149f6d16cc8d52ba0b6180259a8227/src/Elmish.WPF/ViewModel.fs#L809-L819

If the binding exists (which it does in the case we are considering), then the only way to avoid calling `dispatch` is to either throw an exception or use the `wrapDispatch` feature to suppress the no-op message.  Of course we plan to remove that refeature in the next major release (c.f. #235).  Even so, this approach still isn't great because you still have to create a message to be suppressed by `wrapDispatch`.  I would prefer this message not even exist.

Is there another possibility that I a missing?

**Comment by cmeeren** [comment]
> > ...I think you could also use a `twoWayOpt` binding and only dispatch whatever you want when the value received from WPF is `true`.
> 
> How?

By bad; the `Opt` part of `twoWayOpt` is for the getter, not the setter. I was thinking of something like `cmdIf` where you can return `'msg option`. But we don't have that.

I like the Command approach. Perhaps we should have a sample with it? You can add a comment referring to this issue for alternate approaches and tradeoffs.

**Comment by TysonMN** [comment]
> Perhaps we should have a sample with it?

Yes, I would like that.  It doesn't have to be a big deal though.  I could add this to the samples that have the ability to toggle between UTC and local time.

**Comment by cmeeren** [comment]
> I could add this to the samples that have the ability to toggle between UTC and local time.

Are you referring to replacing the toggle button with two radio buttons? That could work well. 👍

**Comment by TysonMN** [comment]
Yep.  Great.  I will do that.

**Comment by TysonMN** [comment]
One minor correction.

In the `SetViaCommand` case (which is the one that we think is best), the binding to `IsChecked` needs to be set to `OneWay` in the XAML.  I didn't notice that leaving it as a `TwoWay` binding (the default) was causing WPF to try to set it.  (In my application at work, I display these errors as a popup, so I can't miss them there.)

I fixed this in [this commit](https://github.com/TysonMN/Elmish.WPF_RadioButtons/commit/519d7ec3603472a8185ec256f3a949e509e2d4e8).

**Comment by TysonMN** [comment]
FWIW, I also added the `UniqueGroupNames` example.
