### ISSUE TITLE
How to use SubModelSelectedItem on a level 3 submodel?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#284]
Hi All!

I have a datagrid defined as:

```
<Window x:Class="DataGrid2.View.MainWindow" 
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        WindowStartupLocation="CenterScreen"
        Title="SubModelSelectedItem"
        Height="350"
        Width="500" 
        mc:Ignorable="d"
        >

    <Grid>
        <DataGrid Name = "dataGrid" AlternatingRowBackground = "LightBlue"  
         AlternationCount = "2" AutoGenerateColumns = "False"
         ItemsSource="{Binding Rows}">

            <DataGrid.Columns>
                <DataGridTextColumn Header="Time" Binding="{Binding RowName}" />
                
                <DataGridTemplateColumn Header="0:00" Width="354" IsReadOnly="True">
                    <DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <ListView ItemsSource="{Binding Columns}" SelectedItem="{Binding SelectedEntity}" HorizontalContentAlignment="Center">
                                <ItemsControl.ItemTemplate>
                                    <DataTemplate>
                                        <StackPanel Orientation="Horizontal">
                                            <TextBlock Text="{Binding CellName}" />
                                            <TextBlock Text="{Binding SelectedLabel}" />
                                        </StackPanel>
                                    </DataTemplate>
                                </ItemsControl.ItemTemplate>
                            </ListView>
                        </DataTemplate>
                    </DataGridTemplateColumn.CellTemplate>
                </DataGridTemplateColumn>
            </DataGrid.Columns>
            
        </DataGrid>
    </Grid>

</Window>
```

where "Columns" is defined as:
      Columns: Cell.Model list

So I am trying to have the "SelectedEntity" allow the user to select a specific "Cell" from the ListView ItemsSource and show that cell as selected by displaying the "SelectedLabel".  (Currently the selectedlabel displays "Hi!". When this works correctly, I want the SelectedLabel to be empty --not show anything--except for the cell that was actually selected.  My problem is how to catch the selectedEntity and update the UI accordingly.

Full Source Code at: https://github.com/awaynemd/subModelSelectedItem-2

Thank you for any help or suggestions!

**Comment by TysonMN** [comment]
FYI: I fixed the link in your markdown by replacing
```
[https://github.com/awaynemd/subModelSelectedItem-2](url)
```

with
```
https://github.com/awaynemd/subModelSelectedItem-2
```

**Comment by TysonMN** [comment]
Can you add a `.gitignore` file to that repository?  It is just like you did in https://github.com/awaynemd/DatagridWithSubModel/issues/2.

**Comment by awaynemd** [comment]
@TysonMN Just caught it, Thanks.

**Comment by awaynemd** [comment]
@TysonMN Hm...How do I add a .gitignore file??  Easiest way?

**Comment by TysonMN** [comment]
Copy it from that repository where we previous added it, paste it into the root of your local copy of this repository, commit that change, push the commit.  You should also delete the files that would have been ignored in your first commit had this `.gitignore` file already existed.

**Comment by TysonMN** [comment]
Have you looked at the `SubModelSelectedItem` sample for how to use the binding with the same name?

**Comment by awaynemd** [comment]
@TysonMN  I have studied it many, many times.  I can't seem to execute code from the point of receiving a 
"selectedEntity" in the Row module to its point of execution in the Cell module.  Thanks.

**Comment by awaynemd** [comment]
@TysonMN .gitignore now add :)

**Comment by TysonMN** [comment]
Great job.  Can you now delete the auto generated files (which are also now ignored because of the `.gitignore` file)?

Also, you have done a great job asking this question.  Your code is very small, and I know exactly what you to achieve.  I will get you an answer shortly.

**Comment by awaynemd** [comment]
@TysonMN Thanks! Not to sound terribly stupid (although that would be easy for me), is there a quick method to delete the .vs files from the GitHub repository?  Thanks.

**Comment by TysonMN** [comment]
When files are checked into a git repository and (then) also added to the `.gitignore` file, then changes to those files are ignored but (I think) deletions are not.

It only takes a few seconds to manually navigate your repository and delete generated files and directories.  That is what you should do.

A systematic solution is to create a second repository containing the files in the first repository.  Commit all the changes.  Deletes all the tracked files and directories.  Use git to discard those deletions.  (This deletes the files that were both committed and ignored in the first repository.  Maybe there is a git command that can also directly do this.)  Then delete all the tracked files and directories in the first repository, copy the tracked files and directories from the second repository to the first repository, then commit the deletions (of the ignored files).

**Comment by awaynemd** [comment]
@TysonMN  Outside of the .vs folder, what other folders/files should be deleted/kept? (There has to be a simple way to do this :) Thanks.

**Comment by TysonMN** [comment]
They are listed in the `.gitignore` file that you added

**Comment by TysonMN** [comment]
I nearly have it, but when lists are nested, the inner `SelectedItem` property doesn't get set.  The click event is being handled by the outer list.  Other people have this problem with WPF.  I am trying to find a workaround now.

**Comment by TysonMN** [comment]
Got it.  Wow.  Finding the right WPF code there was hard.

I believe [this PR in your repository](https://github.com/awaynemd/subModelSelectedItem-2/pull/1) contains that answer you want.  I will now close this issue, but please reopen or just continue to comment if needed.

I am not completely sure of the exact issue.  I think it has to do with nested instances `System.Windows.Controls.Primitives.Selector`.  In this case, the exact nested types are `DataGrid` and `ListView` (which are both derived from `Selector`).  Then the `SelectedItem` property of the inner `Selector` doesn't update when changed.  It was easy enough to debug and verify that the `SelectedItem` property was changing.   WPF just didn't update the binding.

The fix was to add `UpdateSourceTrigger=PropertyChanged` to the binding.  The whole binding is now...
```xaml
SelectedItem="{Binding SelectedInnerRow, UpdateSourceTrigger=PropertyChanged}
```

...and [the whole line is here](https://github.com/TysonMN/subModelSelectedItem-2/blob/f4a3db13d74629df9c1cc2cd417583af80dbca74/DataGrid2.View/DataGrid2.View/MainWindow.xaml#L23).

**Comment by TysonMN** [comment]
Also, [this is the StackOverflow answer](https://stackoverflow.com/questions/16537270/listbox-selecteditem-get-working-but-set-not-working-in-mvvm/37476941#37476941) where I found that fix.  Please go and up vote that answer.

**Comment by awaynemd** [comment]
@TysonMN Wow!  I never would have figured this out. Thanks much! 

This is off topic, but I still haven't figured out how to debug this -- even in visual studio. For one, I can't seem to get a terminal window to receive the Elemish.wpf  trace  -- my visual studio must not be set up correctly.  Thanks again.

**Comment by TysonMN** [comment]
Your program was logging to console fine for me.  I described some of my debug process in #286.
