### ISSUE TITLE
Minor logging improvements: consistent use of double quotes

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#285]
Here are two lines printed the console when using the `SubModelSelectedItem` sample.
```
[main.Entities.0] PropertyChanged "SelectedLabel"
[main.Entities.0] TryGetMember SelectedLabel
```

I prefer if they both used double quotes or neither used double quotes.  My preference is for neither to use double quotes.

**Comment by cmeeren** [comment]
I assume you're talking about the v4 branch? This is relevant for other log statements, too. Feel free to remove the quotes (there are some single quotes, too).

**Comment by TysonMN** [comment]
This is on `master`.  I didn't think to check if we changed this in the `v4` branch.  I will do that.

> Feel free to remove the quotes (there are some single quotes, too).

Great, I will do that.

**Comment by TysonMN** [comment]
Replaced by #287
