### ISSUE TITLE
Override object.ToString() on ViewModel<,>

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#286]
Quoting https://github.com/elmish/Elmish.WPF/issues/284#issuecomment-705916110
> It was easy enough to debug and verify that the `SelectedItem` property was changing.

I subscribed to `OnSelectedItemChanged`, added a breakpoint, and inspected the arguments.  That is ok to do once, but I quickly got tired of it.  As I was rapidly trying different ideas, I wanted to print something to the console to quickly confirm that the correct value was being selected.

The easiest way I found to do this was replace the NuGet package reference to Elmish.WPF with a direct reference to my local clone, override `object.ToString()` on `ViewModel<,>` to return `sprintf "%A" currentModel`, and then print the returned value to the console when `OnSelectedItemChanged` fires.

@cmeeren, what do you think about overriding `object.ToString()` on `ViewModel<,>` in this way?  The purpose is strictly for debugging as I just did.  I don't even think we would need to advertise this "debugging feature".  People can just discover that it exists when they are in some intense debugging session like I just was and be grateful that it exists.

**Comment by cmeeren** [comment]
Sure, go ahead! 👍
