### ISSUE TITLE
Minor logging improvements

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#287]
Here is a list of minor logging improvements I would like to see.  Since logging is changed quite a bit in branch `v4` compared to `master`, I will just make these changes in `v4`.

- [x] Remove all (single and double) quotes (c.f. #285)
- [x] Split log statement about `SubModelSelectedItem` binding being unable to find correct `SubModelSeq` binding into two statements: (1) no binding by that name and (2) binding by that name but wrong type. (c.f. [these two lines](https://github.com/elmish/Elmish.WPF/blob/ff1794eacf29fb16224e676da0eac52cdb93ab2f/src/Elmish.WPF/ViewModel.fs#L297-L298))
- [ ] Remove the duplication from (almost!) every log message template starting with the binding name chain (or decide that this isn't possible)...which, most importantly, will make sure that every log message includes the binding name chain.

**Comment by cmeeren** [comment]
Not sure how you can remove the name chain in a sane way. AFAIK it simply must be part of the logging statement. If you factor it out from the string, then you are splitting the knowledge of which placeholders the strings contain from which parameters the string needs.

In any case, please go ahead!

**Comment by TysonMN** [comment]
Given a Serilog logger, this is mostly be achieved by a line like this
```fsharp
let logger = logger.ForContext("BindingNameChain", propNameChain)
```

The main difference is that the message (template) is different.  When using `Serilog.Sinks.Console`, the information provided in that line isn't include in the output by default.

**Comment by TysonMN** [comment]
Still don't know how to do the last item in the checklist.  I don't much about it at the moment, so I will close this issue (for now).
