### ISSUE TITLE
Suggest change to the Elmish.WPF intro document

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#288]
I'm a newbie to Elmish.WPF.  Following exactly the introduction document, shows #8 as 

```
[<EntryPoint; STAThread>]
let main argv =
  Program.mkSimpleWpf init update bindings
  |> Program.runWindow (MainWindow())
 
```

Leads to an error when it can't find "MainWindow". 

It might be useful to other newbies, that the statement in #7 of
 "add a reference to this project from your Elmish project,"  be expanded a bit to include the "open" for the namespace of the C# MainWindow, e.g. "open namespace".  

For real new beginners to F#, like myself, this could save hours of fumbling around :)

Just a thought.

**Comment by cmeeren** [comment]
Thanks, added now.
