### ISSUE TITLE
Difficulty using Binding.subModelSelectedItem with multiple sub levels

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#289]
I've been trying to extend a list item selection down several levels using this code:

```
 <DataGrid Name = "AppointmentTable" 
         AlternatingRowBackground ="LightYellow" 
         AlternationCount = "2" AutoGenerateColumns = "False"
         ItemsSource="{Binding Rows}" SelectedItem="{Binding SelectedRow}">
            <DataGrid.Columns>
                <DataGridTextColumn Header="Time" Binding="{Binding RowTime}" />

                <DataGridTemplateColumn Header="0:00" Width="354" IsReadOnly="True">
                    <DataGridTemplateColumn.HeaderStyle>
                        <Style TargetType="{x:Type DataGridColumnHeader}">
                            <Setter Property="HorizontalAlignment" Value="Center"/>
                        </Style>
                    </DataGridTemplateColumn.HeaderStyle>
                    <DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <ListView ItemsSource="{Binding Columns[0].InnerRows}" 
                                      SelectedItem="{Binding SelectedInnerRow, UpdateSourceTrigger=PropertyChanged}" HorizontalContentAlignment="Center">

                                <ListView.View>
                                    <GridView>
                                        <GridViewColumn Header="First"     DisplayMemberBinding="{Binding LastName}" Width="100"/>
                                        <GridViewColumn Header="Last"      DisplayMemberBinding="{Binding SelectedLabel}"  Width="120"/>
                                    </GridView>
                                </ListView.View>
                            </ListView>
                        </DataTemplate>
                    </DataGridTemplateColumn.CellTemplate>
                </DataGridTemplateColumn>

         --- more columns

```
All will display correctly.

However, upon selecting a specific item from one of the ListViews gives the following errors:

```
Cannot get 'SelectedInnerRow' value (type 'Object') from '' (type 'ViewModel`2'). BindingExpression:Path=SelectedInnerRow;
Cannot save value from target back to source. BindingExpression:Path=SelectedInnerRow; 
```

This newbie is learning, but I'm afraid I do not know how to debug this or solve the issue.

Thanks for any help with this.

Full code at: https://github.com/awaynemd/DataGrid4

**Comment by TysonMN** [comment]
I created [this PR](https://github.com/awaynemd/DataGrid4/pull/1) to help debugging this problem.  See if you can make progress now.  If not, come back here and ask for help again.

**Comment by awaynemd** [comment]
@TysonMN Thanks! (I think I got this repository stuff down :) )

**Comment by TysonMN** [comment]
Ah, yes.  I forgot to compliment you on that.  It is perfect.  Great job! :)

**Comment by awaynemd** [comment]
@TysonMN Thanks! :)  

Playing around with this shows that "SelectedInnerRow" is recognized when this line is added to the "OuterRow" Bindings:
           "SelectedInnerRow" |> Binding.oneWay (fun (b, _) -> if b then " - Selected" else "")
Ofcourse it fails being read only -- but the binding is recognized at least.

I do not understand.  Looking at the WPF XAML, I would think it should be part of the "Columns" binding since the DataContext is actually "InnerRows" as in "<ListView ItemsSource="{Binding Columns[0].InnerRows}" .."

What am I misunderstanding?

Terribly confused. Thanks.

**Comment by TysonMN** [comment]
I edited your previous comment to add markdown to make it easier to read the code.

**Comment by TysonMN** [comment]
The smallest fix is to change `SelectedInnerRow` to `Columns[0].SelectedInnerRow`.

The proper fix is to change
```xaml
<ListView ItemsSource="{Binding Columns[0].InnerRows}" 
          SelectedItem="{Binding SelectedInnerRow, UpdateSourceTrigger=PropertyChanged}"
          ...>
    ...
</ListView>
```

to something like

```xaml
<Grid DataContext="{Binding Columns[0]}">
    <ListView ItemsSource="{Binding InnerRows}" 
              SelectedItem="{Binding SelectedInnerRow, UpdateSourceTrigger=PropertyChanged}"
              ...>
        ...
    </ListView>
</Grid>
```

Do you understand why each of these fixes the problem?

**Comment by TysonMN** [comment]
I only changed the XAML, so this is independent of Elmish.WPF.

**Comment by awaynemd** [comment]
@TysonMN  I think I got it.   The toBindingModel parameter of  Binding.subModelSeq function is what the next lower level bindings receives.  This is working now (with understanding--I think). I much appreciate the help. Thanks.
