### ISSUE TITLE
Missing Terminal Window in Visual Studio 2019 Community Version 16.8.0 ?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#290]
I'm currently using Visual Studio 2019 Community Version 16.8.0 Preview 4.0. I seem to have lost the black terminal window used for logging Elemish.WPF from 
`|> Program.runWindowWithConfig
        { ElmConfig.Default with LogConsole = true }`

Any ideas?

Thanks.

**Comment by TysonMN** [comment]
What is inside `OutputType` in the project file of the project you are executing?

**Comment by awaynemd** [comment]
@TysonMN 
`<OutputType>Exe</OutputType>`

**Comment by TysonMN** [comment]
That is "correct".  When it is `WinExe`, then I expect no terminal.

If you share the full repository, then I can test with my copy of Visual Studio Enterprise.

**Comment by awaynemd** [comment]
@TysonMN Hi!  Full repository at: https://github.com/awaynemd/DataGrid4

**Comment by TysonMN** [comment]
The terminal shows up for me.  You might try asking about this issue in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).

**Comment by awaynemd** [comment]
@TysonMN Seeing as how I need the terminal window --(I need all the help I can get!)--I uninstalled Visual Studio 16.8 and reinstalled version 16.7.6.  

All works correctly now.  Thanks.

**Comment by TysonMN** [comment]
I am glad that you were able to find a workaround.  Sorry that the Elmish.WPF logging is so restricted.  In addition to the console, you can also log to Visual Studio's output window.  Then next major version will allow you to log anywhere.

**Comment by awaynemd** [comment]
@TysonMN how do I log to the output window?  Thanks.

**Comment by TysonMN** [comment]
```fsharp
Program.runWindowWithConfig
    { ElmConfig.Default with LogTrace = true }
```
