### ISSUE TITLE
How to fire an adorner with PreviewMouseLeftButtonUp in a  ListView

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#292]
Looking at my C# code, I find examples of triggering an Adorner by selection of a list view item. The WPF/XAML reads essentially as:

`<ListView ...... PreviewMouseLeftButtonUp="ListView_PreviewMouseLeftButtonUp">`  

and the code-behind reads (C#) as

```
 private void ListView_PreviewMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            var item = (sender as ListView).SelectedItem;  
            if ((IVisit)item != null)
            {
               ... creates the adorner using the (IVisit)item as the data and the sender as the reference object....
            }
        }
```

When working with Elmish.WPF/F#,  the item resolves to:

`object {System.Tuple<bool, DataGridWithAdorner.Cell.Model>}`

But if I do this:

       if (item is DataGridWithAdorner.Cell.Model)   is always false -- shouldn't it be true?

and, when sourced from F#, do I really need to cast it at all?

(Are there any examples of adorners with Elmish.WPF?)

Thanks in advance.  TIA

**Comment by TysonMN** [comment]
> Are there any examples of adorners with Elmish.WPF?

I didn't think so.

Can you share a MWE that uses C# and code behind to do what you want?  And then can you also share the F# / Elmish.WPF code in which you want to achieve a similar thing?

**Comment by awaynemd** [comment]
@TysonMN Sure...I'll be happy to. But it might take a day or two on the C# code as it appears to be fairly convoluted.  I'm pretty much stuck in the F# code as above cause I can't figure out how to cast the list view item, or even if I need to?  :)

**Comment by TysonMN** [comment]
If you want, you can share your F# code now your C# code when that becomes ready.

In the meantime, I quickly looked at adorners in WPF.  Maybe one example in Elmish.WPF is the display of validation errors in the `Validation` sample.

**Comment by awaynemd** [comment]
@TysonMN I through together this in C#. It has the basic setup I'm working with. I'm sure it can be improved :) (It's been awhile since I worked in C#). I believe it meets the MWE standard. Of note, bindings are created in the adorner between the viewmodel and the control.  I have no idea how to perform the same functions in Elmish.WPF nor even how to get past the first casting in the preview mouse down event handler (the code behind).  Any suggestions or help would be most appreciated.

Thanks!

C# code at: https://github.com/awaynemd/DataGridWithAdorner_CSharp

**Comment by TysonMN** [comment]
I created [this PR](https://github.com/awaynemd/DataGridWithAdorner_CSharp/pull/1) with two small simplifications.

Can you modify your code so that the project using the new SDK-style project format?

**Comment by awaynemd** [comment]
@TysonMN Don't know (I tried initially and ran into some problems :(  ) .  

BTW, this is as far as I've gotten with F#: https://github.com/awaynemd/DataGridWithAdorner

**Comment by TysonMN** [comment]
Thanks for the F# application.  That might be enough.  You can pause efforts to change the C# project to use the SDK-style project format.

One part of the solution will be the ability to convert an event into a command.  Look at the first sample.  See how it pass in the event arg and that the event arg contains a reference to the sender.

(I will edit this to add the name of the sample and a link.)

**Comment by awaynemd** [comment]
@TysonMN New project format in C# at: https://github.com/awaynemd/DataGridWithAdornerInCSharp2

Thanks.

**Comment by TysonMN** [comment]
I created [this PR](https://github.com/awaynemd/DataGridWithAdornerInCSharp2/pull/1) in your new C# repo to simplify the code.  I will pause my efforts looking into that repo until you confirm that this simplification is behavior preserving.

**Comment by TysonMN** [comment]
I think it would be helpful if I could look at code in which the andorner displayed at design time.

**Comment by awaynemd** [comment]
@TysonMN Hi! I might have screwed this up, but the C# code does (or least did) work. Just click on a listview item :)

**Comment by TysonMN** [comment]
> I might have screwed this up...All works well.

What did you think you screwed up.  I also think your example is good.

**Comment by TysonMN** [comment]
I created [this PR](https://github.com/awaynemd/DataGridWithAdorner/pull/2) in your F# repo.  It maps the mouse event to a command as I mentioned above.  You should be able to make progress on this repo now.

It still isn't perfect though.  I path forward that I currently see is to continue as you did in your C# code of not using Elmish.WPF.  I will continue to think about that part.

**Comment by awaynemd** [comment]
@TysonMN Putting all this together, I still have a very basic problem: Even though the WPF xaml may be the driver, the driving code is from the F# project. Hence, the adorner (in C#) does not have access to the classes (e.g., innerrow) that are defined in the F# project? Yet, but using the command, I will need to start the adorner from the F# code. In short, there are a bunch of cross-links here that I do not know how to resolve.   :(     Thanks again for your efforts.

**Comment by TysonMN** [comment]
> the adorner (in C#)...

You could write that in F#.

Even if you kept it in C#, it is possible to add a layer of infection to deal with these "cross links".  It is not ideal though, so it is not worth considering yet.

I created a PR to simplify the C# code further.  There is still work left.  I am trying to figure out how Elmish.WPF can be put in charge of those bindings you created in C#

**Comment by awaynemd** [comment]
@TysonMN Thanks...Good luck. I'm betting since WPF must clearly add those bindings to the Dispatcher, that Elmish probably will handle it already. My problem is pulling the Cell or InnerRow type from the F# code into the C# code that builds the adorned control.

**Comment by TysonMN** [comment]
Another PR for the C# code https://github.com/awaynemd/DataGridWithAdornerInCSharp2/pull/3

**Comment by awaynemd** [comment]
@TysonMN Looks great! Thanks. I guess for completeness sake, I should add the adorner close when "Save" is pressed -- not a big deal.

Thanks again for all your efforts!

**Comment by TysonMN** [comment]
I created [this draft PR](https://github.com/awaynemd/DataGridWithAdornerInCSharp2/pull/4) in which I have attempted to move the XAML in `Generic.xaml` into a new file called `DataGridAnnotationControl.xaml`, but I have been unable to preserve behavior.

**Comment by awaynemd** [comment]
@TysonMN Hi! How well does Elmish.WPF play with FsXaml?

**Comment by TysonMN** [comment]
I have heard of FsXaml but never tried it.

**Comment by awaynemd** [comment]
@TysonMN Time to rest. Will play with the new draft tomorrow :) Thanks.

**Comment by awaynemd** [comment]
@TysonMN How do I review the draft without merging it?  Thanks.

**Comment by TysonMN** [comment]
You can add my repository as a remote to your local clone of your GitHub repository.  Then you can checkout my branch.

**Comment by awaynemd** [comment]
@TysonMN Will do.

**Comment by awaynemd** [comment]
@TysonMN I'm still trying to figure out how to download the draft :( (its not as obvious as you might think.) Anyway, if you are having to move the custom control out of Generic.xaml, does that not defeat the purpose of a custom control in the first place?

**Comment by TysonMN** [comment]
> f you are having to move the custom control out of Generic.xaml, does that not defeat the purpose of a custom control in the first place?

I am not sure what you mean.  It is still a custom control.

> I'm still trying to figure out how to download the draft :( 

Execute these commands one at a time
```
git remote add TysonMN https://github.com/TysonMN/DataGridWithAdornerInCSharp2.git
git fetch --all
git checkout --track TysonMN/XAML_for_DataGridAnnotationControl
```

**Comment by awaynemd** [comment]
@TysonMN Great! Thank you.

I believe I now have this set up correctly, but get the error: 

Unknown build error, 'Could not find a part of the path 'C:\Practice\DataGridWithAdornerInCSharp2\DataGridWithAdornerInCSharp\DataGridWithAdornerInCSharp\Themes\Generic.xaml'.'   

I believe I can fix that, but do you get that error. (If not, I screwed something up!).

Thanks.

**Comment by awaynemd** [comment]
@TysonMN Removing the 

DefaultStyleKeyProperty 

from the control stops it from looking in Generics.xaml, but it definitely has the wrong behavior!

**Comment by TysonMN** [comment]
> In my original code, the `DataGridAnnotationControl` (in c#) inheritied from:
`: Control, INotifyPropertyChanged`, not `UserControl`. (Probably makes no difference).

I made that change in the previous PR.  The behavior is preserved with that change.  Even so, maybe it has something to do with behavior not being preserved in the current draft PR.

**Comment by awaynemd** [comment]
@TysonMN I am by no means an expert, but clearly there is something about overriding the controltemplate in the original custom control that gave the desired behavior???

**Comment by TysonMN** [comment]
Yes, that seems like it could be the source of my mistake.  I am reading about the differences [here](https://stackoverflow.com/q/11247708/741786).

**Comment by awaynemd** [comment]
@TysonMN Just read through that reference. To this newbie, it wasn't very helpful :(. As an aside, I have always liked custom controls. I usually would have their bindings explicit in  the usercontrol which used them. This made it very obvious what was going on. And its hard to beat their flexibility.  Just a thought.

**Comment by TysonMN** [comment]
I previously asked about how to display the adorner on a selected cell at design time.  Maybe a [trigger](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/control-authoring-overview) would help with this.
> A trigger enables you to change property values or take actions based on the value of a property.

**Comment by awaynemd** [comment]
@TysonMN Hi! Just scanning stackoverflow does show a few cases of using a  DataTrigger to show the adorner. I'm really not clear how doing so will advance the cause.  

BTW, thanks for your answer on StackOverflow. Anyway to get Elmish.wpf to return more than just "object" ?

**Comment by TysonMN** [comment]
> I'm really not clear how doing so will advance the cause.

I think it helps by reducing the set of potential solutions to consider since I think the correct solution will be able to show the adorner at design time.

> Anyway to get Elmish.wpf to return more than just "object" ?

Of course.  Use one of the Elmish.WPF bindings.

**Comment by TysonMN** [comment]
> > I'm really not clear how doing so will advance the cause.
>
> I think it helps by reducing the set of potential solutions to consider since I think the correct solution will be able to show the adorner at design time.

And design time is important because it reduces the feedback loop.

**Comment by awaynemd** [comment]
@TysonMN In all honesty, I have not been successful in using the design time abilities of Elmish--I don't know how :(  Anyway, wouldn't a simple approach be to move the "InnerRow" and its interface definition to another F# project; then define the InnerRow as a Class (not record) which can be used by both the F# code and C# code?  (Seems the easiest?)  Can Elmish.wpf use classes in place of records?  Just a thought.

**Comment by TysonMN** [comment]
> I have not been successful in using the design time abilities of Elmish--I don't know how :(

Design time views exist for every sample.  The main thing you would need to change in your code is having the C# project be the executable project instead of the F# project.

>...wouldn't a simple approach be to move the `InnerRow` and its interface definition to another F# project; then define the `InnerRow` as a Class (not record) which can be used by both the F# code and C# code? (Seems the easiest? No cross-links?) Can Elmish.wpf use classes in place of records?

Elmish.WPF has no dependency on records.  Programmers in F# tend to use records over classes because it is easier to create a bug-free programs with them.

> How does a binding return the object for use in code-behind?

It doesn't.  The goal is to have no code for bound data in the code behind.  This might not be possible now; we might have to expand the Elmish.WPF binding API to add support for adorners.  I haven't gotten that far yet.

**Comment by awaynemd** [comment]
@TysonMN Thanks for all your help. I didn't mean to be such a pain. I don't know what your regular work is, but you are a great teacher!  Time for me to learn about F# interfaces... :)

**Comment by TysonMN** [comment]
You are welcome for the help, and you are not a pain.  In fact, I am quite happy to work on this issue.  How to use an adorner with Elmish.WPF is an excellent question.  I was not able to formulate that question but you were.

Why did you close the issue?

**Comment by awaynemd** [comment]
@TysonMN I did not want to waste anybody's time with my ignorance.

BTW,   this code:

```
let handlePreviewMouseLeftButtonUp (obj: obj) (a, c) =
      let e = (obj :?> MouseButtonEventArgs)
      let listView = e.Source :?> ListView
      let grid = listView.Parent :?> Grid

      let selectedItem = c.InnerRows.[c.SelectedInnerRow.Value]

      MessageBox.Show("I can start the adorner from here now that I have the ListView, Grid, and SelectedItem!") |> ignore
      NoOp

```
Fails in the DataGridWithAdorner when an item is selected in any outerrow past the first.  The "index is out of range". :(

**Comment by TysonMN** [comment]
You are not wasting my time.  Your question about Elmish.WPF support for adorners is the most interesting "Elmish.WPF support" question I have seen since I joined the project.

> Fails in the `DataGridWithAdorner` when an item is selected in any outerrow past the first. The "index is out of range". :(

Sure.  Change
```fsharp
c.InnerRows.[c.SelectedInnerRow.Value]
```

to
```fsharp
c.InnerRows |> List.filter (fun r -> Some r.Id = c.SelectedInnerRow) |> List.head
```

**Comment by awaynemd** [comment]
@TysonMN Now works correctly. Thanks.

**Comment by TysonMN** [comment]
I just made some progress on the C# code.  Nothing to share right now, but I will soon.

**Comment by TysonMN** [comment]
[This PR](https://github.com/awaynemd/DataGridWithAdornerInCSharp2/pull/4) (that used to be a draft PR) is now ready for review.

**Comment by awaynemd** [comment]
@TysonMN Trying to learn F#. I added an F# library project with IInnerRow interface to be used by both the F# projects and C# projects.  I'm not sure how to call a C# method from F#. In particular, I tried to call and open the adorner from the F# command you provided. Nothing seems to happen :(        But it does compile!

Please take a look:  https://github.com/awaynemd/DataGridWithAdorner2

Where did I go wrong?  Thanks.

**Comment by awaynemd** [comment]
@TysonMN Great Job! Your PR works correctly. Thanks. I didn't realize that a "partial" class was needed :)

**Comment by TysonMN** [comment]
The way to realize that is to create a new `UserControl` in Visual Studio.  The starting template has the code behind use a partial class.

**Comment by awaynemd** [comment]
@TysonMN  When I make the following definition inF#:

```
type IInnerRow =
   abstract member Id: int with get
   abstract member CellName: string with get
 

module Cell =

    type Model =
       {Id: int
        CellName: string}

       interface IInnerRow with
            member this.Id with get() = this.Id 
            member this.CellName with get() = this.CellName
   
    let init i j k =
            { Id = i*100 + j*10 + k
              CellName = sprintf "CellName %i  %i  %i" i j k }

    let bindings() = [
        "LastName" |> Binding.oneWay(fun (_, c) -> c.CellName)
        "SelectedLabel" |> Binding.oneWay (fun (b, _) -> if b then " - Selected" else "")
    ]
    
```
Then use the IInnerRow interface in C# as:

  `var selecteditem = (IInnerRow)s.SelectedItem;
`

everything compiles without error. However, when an item is actually selected it crashes with:

`System.InvalidCastException: 'Unable to cast object of type 'Elmish.WPF.ViewModel`2[System.Object,System.Object]' to type 'DataGrid4.Library.IInnerRow'.'
`

Suggestions?  Thanks.

**Comment by TysonMN** [comment]
Certainly.  You can't cast the internal `View Model<,>` of Elmish.WPF to anything.  You need to bind to the data you want.

I will take a look.

**Comment by awaynemd** [comment]
@TysonMN _bind to the data you want._   Huh? Please elaborate.  How do I get data from the View Model to C# code? Thanks.

**Comment by TysonMN** [comment]
> You can't cast an instance of the internal `View Model<,>` of Elmish.WPF to anything.

Oh, I think I am mistaken.  Our view model inherits from [`DynamicObject`](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject).  Try casting to that and then calling [`TryGetMember`](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject.trygetmember).

However, this is _**NOT**_ the recommended approach.

**Comment by TysonMN** [comment]
[This PR](https://github.com/awaynemd/DataGridWithAdorner/pull/3) in your F# repo gets the adorner working just as well as in your F# code.

I am still curious about displaying the adorner at design time, but I think this progress addresses the primary problem in this issue.

**Comment by awaynemd** [comment]
@TysonMN I haven't figured out how to make a branch off a repository I own, so I created another repository (before reading your above PR).  Please take a look at it. My problem is that the code to installAdorner does not remove the previous adorner. Also, it seems their should be a better way of dealing with AdornerLayer when it has no adorner (I'm thinking F# option or something similar). Basically, I do not know how to implement the _closeAdorner Delagate Action as demonstrated in the DataGridAdornerInCSharp.

Please review:  https://github.com/awaynemd/DataGrid5

I really appreciate all your help!  Thanks.

**Comment by awaynemd** [comment]
@TysonMN Well, it looks like I'm being stupid again :)  Your PR already answered my question.  I believe that completely answers this issue.

I can't thank you enough!  

Just a thought, you have taught many things in this issue. I would strongly suggest incorporating some version of this into the tutorial for other newbie's like myself :)  Thanks again.

**Comment by TysonMN** [comment]
You're welcome :)

What information did you think should be added to the tutorial?  Feel free to send over some pull requests when any changes.

For adorners specifically, I am not satisfied enough yet with my understanding.  I would like more practice with them, more examples, and be able to display them at design them.
