### ISSUE TITLE
Telerik RadWindow and Elmish.WPF

### ISSUE THREAD

**Issue by Evangelink** [elmish/Elmish.WPF#293]
Hi there,

I am new to Elmish.WPF and I am having some problems with integrating the Telerik RadWindow. 

I have a C# project with the views and the rest of the code in F# projects. In the C# project I am following Telerik guidelines (e.g. https://www.telerik.com/support/kb/wpf/window/details/how-to-use-radwindow-as-main-window) where I explicitly create and show the main window from the `OnStartup` event handler. If I am doing so and then call `main(Application.Current.Window)`

```
let main window =
    Program.mkProgramWpf init update bindings
    |> Program.withConsoleTrace
    |> Program.runWindowWithConfig
        { ElmConfig.Default with LogConsole = true; Measure = true }
        window
```

it fails. The error makes sense but I am a little stuck around the fact that Telerik window is special and need to be instantiated in a non regular way and Elmish sort of also need a special access.

Let me know if I can provide some extra info.

**Comment by TysonMN** [comment]
Hello @Evangelink.  Can you provide a GitHub repo that exhibits the behavior that you describe?

**Comment by TysonMN** [comment]
I tried the attached ZIP at the link you provided.  However, the code assumes that several Telerik DLLs exist at the relative path `..\..\..\WPF_Scrum\Current\Binaries\WPF`, which is false for me.  I don't see a way to obtain those DLLs without signing up with Telerik.

Looking at the code though, I wonder if `RadWindow` _doesn't_ inherit from `Window`.  I have been looking through the documentation, but I can't find a definitive answer on this.

Does `RadWindow` inherit from `Window`?

**Comment by TysonMN** [comment]
> Does `RadWindow` inherit from `Window`?

If it does, then I think the normal way to start a WPF application should work when using `RadWindow` (instead of the way that Telerik has show in that ZIPed code).

**Comment by Evangelink** [comment]
Indeed `RadWindow` does not inherit from `Window`. Basically when you call `RadWindow.Show()` it sets under the hood the `Application.Current.MainWindow` somehow. I will create a simple github repo and link it here (ps: I will add the dlls so you can compile and test.

**Comment by TysonMN** [comment]
Interesting.  Elmish.WPF currently depends on `Window`.  Off the top of my head, the dependencies are to set its view model and show it.  These could be abstracted to functions though.

Thanks for the attached code.  I will take a look.

Could you are provide an example that uses Telerik (without Elmish.WPF) to implement some simple behavior like it the `SingleCounter` sample?

**Comment by Evangelink** [comment]
I am trying to migrate from regular MVVM C# to MVU F# so I am totally sure what you want for the case without Elmish. I would create a `MainViewModel` and set it as the `DataContext` of the `MainWindow`, then I would change the current view model on the `MainViewModel` and have the UI to reflect the changes through data templates and other UI controls. Do you want an example of this?

**Comment by TysonMN** [comment]
Yes, an example of that using Telerik (where `MainWindow` extends `RadWindow`).

I looked at your attached code.  The DLLs were not included.  How did you want to give those to me?

**Comment by Evangelink** [comment]
Dlls are available in the bin folder but you are right that I have kept the nuget in the projects, let me sort that out for you.

**Comment by TysonMN** [comment]
Ah, I didn't noticed that.  It works after I replaced the package references with assembly references.

**Comment by Evangelink** [comment]
With the code as-is (replacing the nuget with the dlls), you should see the main window popping and if you put a breakpoint before and after `mainWindow.Show();` you will see that `Application.Current.MainWindow` was `null` and is now set to something. The problem is that after the call to `Show` everything is already up and running causing Elmish to fail.

**Comment by TysonMN** [comment]
Indeed.  You are calling `Program.runWindowWithConfig`.  The function does four things.
https://github.com/elmish/Elmish.WPF/blob/d91c4790a3f57e2f87a6bfee57b29a2d1ce2f0ac/src/Elmish.WPF/Program.fs#L47-L51

You definitely need to call `Program.startElmishLoop`.  However, I don't think you need the other three things.  The failure occurs on line 51.

I looked at `RadWindow`.  Its inheritance hierarchy involves some Telerik classes before extending [`System.Windows.Controls.HeaderedContentControl`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.headeredcontentcontrol), which includes `FrameworkElement` element in its inheritance hierarchy.  I said all that to say that `Program.startElmishLoop` only needs an instance of `FrameworkElement` (not `Window`), so you can call that function.

Based on what you said in https://github.com/elmish/Elmish.WPF/issues/293#issuecomment-718002548, I think you should provide your instance of `MainWindow` as the `FrameworkElement`.  I could be more confident and verify this if you shared an example program like the `SingleCounter` sample that used Telerik, C#, XAML, and traditional MVVM bindings.

**Comment by Evangelink** [comment]
Brilliant! I have simply changed the main function in fsharp to be

```fsharp
let main element =
    Program.mkProgramWpf init update bindings
    |> Program.withConsoleTrace
    |> Program.startElmishLoop
        { ElmConfig.Default with LogConsole = true; Measure = true }
        element
```

and it worked!

**Comment by TysonMN** [comment]
No worries.  Glad to help.  I was also curious to see if the design of Elmish.WPF is compatible with Telerik.

Sure, a PR to improve the documentation would be great.

Feel free to ask another question here or in a new issue if you have any more problems.
