### ISSUE TITLE
subModelSelectedItem not working with Telerik RadListBox

### ISSUE THREAD

**Issue by Evangelink** [elmish/Elmish.WPF#297]
Hi there,

I have been banging my head for quite some time trying to get the `Binding.subModelSelectedItem` to work on my project to finally realize that the use is fairly simple with a regular `ListBox` but seems to be broken with the `RadListBox`.

I am enclosing a zip with a repro case, I know that the default values for the binding are different between Telerik and WPF listboxes and as far as I remember Telerik is maintaining some internal copy which might be the root of the issue. As you will the window is composed of the 2 lists, on the left the Telerik `RadListBox` and on the right side the regular `ListBox`, if you put a breakpoint (or message) in the setter you will see it's called only for `ListBox`. 

Let me know if there is something I can help with.

[DemoElmishTelerik.zip](https://github.com/elmish/Elmish.WPF/files/5552266/DemoElmishTelerik.zip)

**Comment by TysonMN** [comment]
For some reason that I do not understand, you need to explicitly set the `SelectedItem` binding of `RadListBox` to have mode `TwoWay`.  That is, replace
```xaml
<telerik:RadListBox ItemsSource="{Binding RecentItems}" SelectedItem="{Binding SelectedItem}">
```
with
```xaml
<telerik:RadListBox ItemsSource="{Binding RecentItems}" SelectedItem="{Binding SelectedItem, Mode=TwoWay}">
```

I read the documentation about [`RadListBox` Selection](https://docs.telerik.com/devtools/wpf/controls/radlistbox/features/selection) but didn't see anything about the default mode of a binding to `SelectedItem` being something other than `TwoWay`.  More generally, I don't know why any binding has a default mode that is not `TwoWay`.  Explicitly setting the mode of a binding to `TwoWay` was also needed in some of the code that @awaynemd was writing and I helped with.  (I can't find that code now; I think I deleted it.)

For what it's worth, here is a zip containing modifications I made to your code before I figured out the solution.  In particular, I added a design-time view model.

[DemoElmishTelerik.zip](https://github.com/elmish/Elmish.WPF/files/5553796/DemoElmishTelerik.zip)

**Comment by Evangelink** [comment]
I am pretty sure I did tested that but I guess not or there was another modification I reverted too... Anyways thanks!

Regarding the change of default mode, the `SelectedItem` is more often used as a two-way that's why it's the default for Telerik but the two-way binding is more costly than a one-way binding that's why most bindings are set to one-way by default.

**Comment by TysonMN** [comment]
You're welcome :)

> ...the `SelectedItem` is more often used as a two-way that's why it's the default for Telerik...

Are you saying that the default binding mode for `RadListBox.SelectedItem` is `TwoWay`?  My impression is that this is not the case.

**Comment by Evangelink** [comment]
> Are you saying that the default binding mode for `RadListBox.SelectedItem` is `TwoWay`? My impression is that this is not the case.

Indeed that's a stupid comment, not sure why I wrote that...

**Comment by TysonMN** [comment]
lol, no need to be so hard on yourself :)
