### ISSUE TITLE
How to keep popup open while typing filter query?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#298]
(Newbie question :).  Sorry, this got duplicated. )

I am having difficulty getting my wpf popup to stay open with Elmish.wpf. 

Actually, I have several issues:
♦ Issue with Popup staying open or reopen
♦ How to set a property from xaml? (i.e isOpen). WPF defines IsOpen as {get; set:} directly from the XAML code. How can I wire IsOpen from the XAML code to directly set this property in my Elmish Model?

Also how do I match on an empty string?

Thanks for any help or suggestions.

Full Code found at: https://github.com/awaynemd/Popup

**Comment by TysonMN** [comment]
For starters, you have binding errors.  Either look at the console to read the errors as reported by Elmish.WPF or look at the Output window in Visual Studio to see the errors as reported by WPF.

> Issue with Popup staying open...

If you want the `Popup` to stay open, then why do you have [`StaysOpen="False"`](https://github.com/awaynemd/Popup/blob/261c43afacdf8f72a149a189606d62c0a0806872/AutoCompleteComboBox.Views/AutoCompleteTextBox.xaml#L52)?

> Issue with Popup...reopen

What do you want to cause the `Popup` to reopen?

> How to set a property from xaml? (i.e isOpen).

There are some ways.  I have seen it done with triggers.  I strongly suspect that your question is asking how to implement a particular solution.  You should instead tell us about actual problem.  An answer to the previous question should help with this.  See [XY Problem](https://en.wikipedia.org/wiki/XY_problem) for more on this.

> How can I wire IsOpen from the XAML code to directly set this property in my Elmish Model?

Use a Two-Way binding.  Currently [you are using a One-Way binding](https://github.com/awaynemd/Popup/blob/261c43afacdf8f72a149a189606d62c0a0806872/AutoCompleteComboBox/AutoCompleteComboBox/Program.fs#L69).

> how do I match on an empty string?

```fsharp
match someString with
| "" -> printf "The user gave us an empty string; how rude."
| _ -> printf "The user gave us the string %s" someString
```

**Comment by awaynemd** [comment]
@TysonMN Thanks. Your are correct. 

My goal is to type in a text string and have the popup list all matches to that string.  I updated the repo to do that. However, the popup closes of itself -- I only want the popup to close when an item is selected (or the user leaves the textbox).  Reviewing the console output, for some reason the IsOpen property is called three or four times (for no reason I can think of).

Why is the popup closing? and how to stop it from closing?

Repo has been updated with all changes. Thanks.

**Comment by TysonMN** [comment]
Much better.

Any reason you are trying to use a `ListBox` inside of a `Popup` instead of a `ComboBox`?

**Comment by awaynemd** [comment]
@TysonMN Not particularly. Just trying to keep things as simple as possible. If memory serves, a combobox is alot more complicated. In any event, the problem would remain the same.

**Comment by TysonMN** [comment]
I created PR https://github.com/awaynemd/Popup/pull/1 as an answer to your question.  There might be some remaining edge cases where the behavior is a bit weird, but the core functionality is correct.

Does this answer your question?

Here is some general feedback that might also be helpful for others working with Elmish.WPF.

1. I recommend using design-time view models.  It shortens the feedback loop when editing the XAML.  You can read about how to do that with Elmish.WPF [here](https://github.com/elmish/Elmish.WPF#can-i-use-design-time-view-models).  I added one in my PR.
2. As can be seen in the `EventBindingsAndBehaviors.Views` sample, `Microsoft.Xaml.Behaviors.Wpf` is a great dependency that converts an event into a command, which can then be associated with a binding.  However, you were doing this for changes to the UI that already exposed through bindings, so I removed all your uses of `Microsoft.Xaml.Behaviors.Wpf` in my PR.
3. When using Elmish.WPF, almost never is the correct solution to use code behind.  You had lots of non-trivial code behind, and I deleted all of it in my PR.

**Comment by awaynemd** [comment]
@TysonMN Thanks again! You're a life saver! The code-behind was from a C# project I wrote to get an initial idea of what I wanted to happen--I fully intended on removing it once  I had a workable F# version. Thanks.

I am looking forward to seeing how this should be done--I've got lots to learn. Thanks again.

**Comment by TysonMN** [comment]
> The code-behind was from a C# project I wrote to get an initial idea of what I wanted to happen--I fully intended on removing it once I had a workable F# version.

If you had a program that did exactly what you wanted but didn't use Elmish.WPF, then you should have shared that.  That would have allowed you to completely avoid the XY problem.

When you share your partial work towards a goal and request help, remember that you are trying to share [minimal (working) example](https://en.wikipedia.org/wiki/Minimal_working_example).  If you know that some code is not part of the solution, then it should not be included.  I spent some time thinking about what that code did and why you would add it.  I would have preferred for you to save me time by not including it.

**Comment by awaynemd** [comment]
@TysonMN Sorry. Lesson learned.

**Comment by TysonMN** [comment]
Keep up the hard work!  I am very excited that you are using Elmish.WPF :)
