### ISSUE TITLE
Failing to build tests with .NET 5.0.100 SDK

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#301]
I think our test project fails to build when using the .NET 5.0.100 SDK.  There are 15 of the same error.
> FS1230 Inner generic functions are not permitted in quoted expressions. Consider adding some type constraints until this function is no longer generic.

**Comment by cmeeren** [comment]
I'll try to look at it during the weekend. Maybe we can upgrade the samples and readme/docs to `net5.0` at the same time. And maybe also add `net5.0` as a target since it is the de-facto .NET target going forward.

**Comment by cmeeren** [comment]
Fixed. Now also targeting .NET 5, and the samples are updated. The Getting Started instructions are also updated for the most recent tooling. (For reference, read more about <DisableWinExeOutputInference> [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/5.0/automatically-infer-winexe-output-type)).
