### ISSUE TITLE
subModelOpt shows sub-model briefly when starting

### ISSUE THREAD

**Issue by cmeeren** [elmish/Elmish.WPF#303]
In the `SubModelOpt` sample, when starting the app, the modal window is briefly visible before disappearing. It would be best if we can avoid this.

(This is not critical and not something I will prioritize looking into myself.)

**Comment by TysonMN** [comment]
I have similar behavior in my single-window application at work.  My coworker solved that issue by making the window hidden until loading finished and then masking it visible.

I wonder if these two cases have the same cause.

If not, I should try to reproduce my issue from work.  The tricky part is that the behavior is time sensitive.  I will have to find a way to artificialmy delay the loading to make it easy to see things during the loading that shouldn't be visible.

**Comment by TysonMN** [comment]
Commit https://github.com/elmish/Elmish.WPF/commit/36133901ab66daa707daa17adabd056283759768 fixes the issue, but I would prefer if there were a global fix to change the default fallback for every `Visibility` binding.

**Comment by TysonMN** [comment]
I do think this is the same issue we had in my application at work.  Here is the workaround we are using there.

```csharp
public MainWindow() {
  /*
   * Start minimized and then maximize after the content is rendered
   * to avoid seeing the content of all Controls at the same time.
   * 
   * This happens because Visible is the default Visibility of all Controls.
   * Each Control is created in its default state and then any bindings are read.
   * When our bindings are read, most of the Visibility properties get changed to Collapsed.
   */
  WindowState = WindowState.Minimized;

  InitializeComponent();
}

protected override void OnContentRendered(EventArgs e) {
  WindowState = WindowState.Maximized;
  base.OnContentRendered(e);
}
```

I am not 100% sure if that explanation is exactly correct, but it is consistent with the observed behavior.

**Comment by cmeeren** [comment]
Thanks, I see.

> I would prefer if there were a global fix to change the default fallback for every `Visibility` binding.

That is not something we can do in Elmish.WPF, am I right?

**Comment by TysonMN** [comment]
Exactly.  I didn't test, but I expect that I could reproduce this behavior without Elmish.WPF.

**Comment by TysonMN** [comment]
If this understanding is correct, then adding a delay (or even a breakpoint) in the `Visibility` binding would make it easier to see the control being `Visible` before being `Collapsed`.  And this can be done in a reproduction that doesn't use Elmish.WPF too.
