### ISSUE TITLE
Stringly-typed vs statically-typed bindings

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#312]
One of the disadvantages of using Elmish.WPF compared to the more traditional MVVM approach is the use of "stringly-typed" bindings.

When creating a binding with Elmish.WPF, a string is given as its name.  Then that same string appears in the XAML bindings.  If some string in a XAML binding does not exist in the corresponding Elmish.WPF view model, then an error occurs when attempting to read or write to that binding at runtime (as well as logging by WPF to the corresponding `PresentationTraceSource` and by Elmish.WPF).

With the traditional MVVM approach, Visual Studio IntelliSense in the XAML helps to ensure that those binding strings are correct, especially via support for auto completion.

I am creating this issue now because @bent-rasmussen is considering using Elmish.WPF.  He likes the advantages that come with statically-typed bindings.  He created [this sample](https://github.com/bent-rasmussen/FsharpWpf) as an example of a WPF application using F# that includes static bindings.

Thinking about this tradeoff and looking at that code gives me some new ideas and motivates me to share some existing ideas.

--------------------------------------

The sample is only a single F# project, and I see that the XAML designer is basically working.  However, the sample doesn't try to include a design-time model, and there doesn't seem to be any corresponding code-behind class.  I wonder if it is possible to have an F# project with a XAML file, a code-behind class, and a design-time view model.  (I almost never use the code-behind class, but it does have its advantages.)

--------------------------------------

I prefer the tradeoff of stringly-typed bindings in exchange for complete control over communication (including mutations) with WPF.  To compensate for stringly-typed bindings, I have done three things in my project at work.

1. I have a test that instantiates my `MainWindow`.  Some problems in XAML don't show up when building the application (i.e. they do not cause `dotnet build` to fail) but do cause `MainWindow` to crash when its constructor is called.

2. I have a test that instantiates my `MainWindow`, runs the dispatcher, and then stops the test when it becomes inactive.  While running, the dispatcher tests most the bindings in my application.  The test fails if WPF logs to any `PresentationTraceSource`.  The bindings that are missed are those "behind" a `SubModelOpt` binding or an empty `SubModelSeq` binding when using the same root-level view model that I use for design time.  This test is essentially the same as running the application (but not interacting with it) and verifying that there are no binding errors.

And related to those two, I have a branch policy that requires all tests to pass in order to complete a pull request into `develop`.

3. While running my application in `debug` mode, if WPF logs to any `PresentationTraceSource`, then I have a pop-up appear with the data being logged.  This way, no developer will ever miss a broken binding while manually testing the application.  I also send this logged data to [`Serilog.Sinks.Seq`](https://github.com/serilog/serilog-sinks-seq) so that the information is automatically recorded (instead of having to "read" and manually capture any details in the pop-up).

By combining all three, my large application at work probably contains no broken bindings (...waiting to reveal themself at runtime).

(So that I finish this comment before 2020 is over!) I have left out many details in those three descriptions.  It is in my queue of blog post ideas to write about each of them with all the useful details that I am currently omitting.

--------------------------------------

Although I have a preference in this tradeoff, I don't like tradeoffs themselves.  Can we have it all??

@cmeeren, could Elmish.WPF be more like your new [Facil](https://github.com/cmeeren/Facil) project?  Specifically, instead of generating the view models at runtime, could we generate F# source code at (pre-)compile time?  Then we would have all the current advantages of Elmish.WPF as well as statically-typed bindings.

**Comment by cmeeren** [comment]
> With the traditional MVVM approach, Visual Studio IntelliSense in the XAML helps to ensure that those binding strings are correct, especially via support for auto completion.

Isn't this supported in Elmish.WPF when using design-time view models?

> I wonder if it is possible to have an F# project with a XAML file, a code-behind class, and a design-time view model.

I think XAML in an F# project is problematic for the following reasons:
* Code-behind requires partial classes, which F# doesn't support (there might be a workaround by inheriting from the XAML class)
* The F# tooling can't compile XAML anyway (FsXaml seems like abandonware, so I'm not sure there's a workaround)

> @cmeeren, could Elmish.WPF be more like your new [Facil](https://github.com/cmeeren/Facil) project? Specifically, instead of generating the view models at runtime, could we generate F# source code at (pre-)compile time? Then we would have all the current advantages of Elmish.WPF as well as statically-typed bindings.

Hmm. Haven't considered that. I'll have to give that some thought before I can reply with anything useful. I guess that right now, I'm confused about exactly what you mean would be generated, what the generated code would be based on (i.e. the "schema", so to speak), and how it would be used (internally by Elmish.WPF and by the user's XAML, though I expect the latter is simple).

**Comment by TysonMN** [comment]
> > @cmeeren, could Elmish.WPF be more like your new [Facil](https://github.com/cmeeren/Facil) project? Specifically, instead of generating the view models at runtime, could we generate F# source code at (pre-)compile time? Then we would have all the current advantages of Elmish.WPF as well as statically-typed bindings.
> 
> Hmm. Haven't considered that. I'll have to give that some thought before I can reply with anything useful. I guess that right now, I'm confused about exactly what you mean would be generated, what the generated code would be based on (i.e. the "schema", so to speak), and how it would be used (internally by Elmish.WPF and by the user's XAML, though I expect the latter is simple).

Oh, maybe not a "pre"-compilation step.  Maybe a post-complication step.

I was thinking of taking `Binding<'model, 'msg> list` as input (i.e. schema) and returning as output the source code for a view model.  For example, on input
```fsharp
[ "WorldName" |> Binding.oneWay (fun m -> m.WorldNameOnModel) ]
```

where `type Model = { WorldNameOnModel: string }`, the output would be something like

```fsharp
type ViewModel (initialModel: Model, worldNameBinding: Binding<Model, _>) =
    inherit ViewModelBase()
    let mutable currentModel = initialModel
    member this.WorldName = tryGetMember currentModel worldNameBinding
```

where that last line is essentially the same as
https://github.com/elmish/Elmish.WPF/blob/db20825cc2057b9b464fe56a5752639dd7d9a480/src/Elmish.WPF/ViewModel.fs#L806

Instead of looking for each binding in a dictionary, which can fail at runtime...
https://github.com/elmish/Elmish.WPF/blob/db20825cc2057b9b464fe56a5752639dd7d9a480/src/Elmish.WPF/ViewModel.fs#L799-L807

...the idea is to instead generate F# code containing the backing property on a view model class.

**Comment by TysonMN** [comment]
> > With the traditional MVVM approach, Visual Studio IntelliSense in the XAML helps to ensure that those binding strings are correct, especially via support for auto completion.
> 
> Isn't this supported in Elmish.WPF when using design-time view models?

No.  Here are videos for comparison.

## In the sample by @bent-rasmussen, which is not using a design-time view model.

![2020-12-17_13-02-09_425](https://user-images.githubusercontent.com/34664007/102531709-60382200-4068-11eb-990b-b1092ac2f1d3.gif)

## In the `SimpleCounter` sample, which is using a design-time view model.

![2020-12-17_13-02-59_429](https://user-images.githubusercontent.com/34664007/102531726-6b8b4d80-4068-11eb-8c80-e47f854475a2.gif)

**Comment by TysonMN** [comment]
> * The F# tooling can't compile XAML

Visual Studio is using some compiler in the sample by @bent-rasmussen.  That solution contains a single F# project, XAML files, and can run a WPF application whose appearance is defined in those XAML files.

**Comment by cmeeren** [comment]
> I was thinking of taking `Binding<'model, 'msg> list` as input (i.e. schema) and returning as output the source code for a view model. For example, on input

That sounds very challenging. In Facil, I connect to a DB and run queries to fetch the schema I need. Parsing this is, if not trivial, then at least not terribly more complicated than parsing any other database results. In this case however, it seems that you are talking about taking F# source code as input, converting it to an AST, and parsing that. Am I right?

> No. Here are videos for comparison.

Hm, it could seem that the designer runs the project code to display the data, but the XAML editor uses reflection on the target type.

> Visual Studio is using some compiler in the sample by @bent-rasmussen. That solution contains a single F# project, XAML files, and can run a WPF application whose appearance is defined in those XAML files.

I see, thanks for putting me right.

**Comment by TysonMN** [comment]
> it seems that you are talking about taking F# source code as input, which would require it to be converted to an AST, and then working with that. Am I right?

I don't have a precise implementation in mind.  Totally brainstorming here.

I am imagining that we could write a (pure) function like
```fsharp
let bindingsToSourceCode (bindings: Binding<'model, 'msg> list) : string = ...
```

where the output is F# code (or C# or MSIL, whatever) that is a view model with a property of the right name for each binding in the list.

------------------------

My team at work includes a UI/UX expert that creates icons in his preferred designer tools.  He exports those as SVGs.  I looked into SVG to XAML converters, but none of them inspired me with confidence.  Instead, we noticed that the generated SVGs included at most two "shapes" or schemas.  I created two instances of F#'s XML type provider for these two schemas.  At runtime, I try first one and then the second one if the first fails.  Then given a successful parse, I create a string representing a `System.Windows.Style`.  All the strings of successful parses are combined into one string representing a `ResourceDictionary`.  Then the program finishes by logging any parsing errors and replacing the contents of a certain file with the created string.

Then we use this workflow.
1. Export all the SVG from his designer program into our repository (for future reference)
2. Run the program described above
3. Commit the changes, which are the SVG files (added, removed, or modified) and the modified file containing the `ResourceDictionary`.

-------------------

Implementing the pure function `bindingsToSourceCode` would be hard enough.  To start, the rest of the workflow (executing it and commit the results) could be done manually like above.  Improving the automation in those parts is "just" technical challenges.

In contrast, these seem to be the hard parts to me.
1. Bindings currently exist in a lazy form as the return value of a function.  I make use of this sometimes and pass specific instances of UI elements into some binding functions.
2. Recursive bindings.  Though, I don't have any in my application at work.  I think it would be reasonable to see in which special cases we could generate view models.

**Comment by cmeeren** [comment]
I see.

Feel free to look into this if you have the time. Unfortunately I don't currently have the capacity for this.

As for the fundamental premise, though: Is it really that much safer to have autocomplete in XAML? XAML is stringly typed anyway, isn't it? AFAIK typos in bindings are entirely possible. But perhaps one can configure this to raise compilation errors.

Also, I just thought of something: We don't really need to generate static view-models in order to get auto-complete. We only need to generate a "shell" that has the right properties (possibly with the right types, though I'm not sure that's relevant). A type definition, if you want. Perhaps a simple record definition suffices. Then this can be set as the design-time view-model. (Though, come to think of it, this would get you autocomplete but not real data in the designer.)

**Comment by bent-rasmussen** [comment]
Interesting discussion.  A few comments:

> Code-behind requires partial classes, which F# doesn't support (there might be a workaround by inheriting from the XAML class)

Correct, though a lot can be done with MVVM to avoid having code behind, especially with behaviors (System.Windows.Interactivity).

>The F# tooling can't compile XAML anyway (FsXaml seems like abandonware, so I'm not sure there's a workaround)

As mentioned, it somehow can. FsXaml is able to work with the XAML files it seems but you are right that it looks like abandonware and Microsoft appears to have no plans for creating a type provider for WinUI 3. I have only tested that the type provider is able to access names in a XAML file - but not that it actually works at runtiime, it could be broken with .NET 5.

It would be cool if one was able to get compile-time errors from binding failures but apparently the binding failures are only detected at runtime which kind of makes sense (it's not static x:Bind after all) were it not for design-time Intellisense checking that does some kind of static check - but I know of no way to hook into that check as a post-compilation step.

As for code generation - perhaps [Myriad](https://github.com/MoiraeSoftware/myriad) can be of use. It seems code generation and metaprogramming is about to become hugely important in the .NET ecosystem.

**Comment by TysonMN** [comment]
Oh, yes.  I had forgotten about Myriad.  I looked into it a few months ago but never tried it.  It looks good though.

**Comment by TysonMN** [comment]
> Is it really that much safer to have autocomplete in XAML? XAML is stringly typed anyway, isn't it? AFAIK typos in bindings are entirely possible. But perhaps one can configure this to raise compilation errors?

This is a very good question to ask.  To be honest, my intuition is that it is not worth it.

I just put an incorrect string into the binding in the sample by @bent-rasmussen.  I saw no indication of my mistake (except for the the auto complete no longer highlighting an option).  I tested using C# as well.  Same behavior.

When using C#, one can "Go To Definition" on a XAML binding and Visual Studio takes you to the property on the view model.  When using F# in the sample by @bent-rasmussen, that doesn't work (just like so many other uses cases of "Go To Definition" in F# c.f. #311).

**Comment by TysonMN** [comment]
@bent-rasmussen, did we miss any advantages of having a static view model?  Here are the ones that I know.  (I will update this comment as we identify more.)

**Advantages of a static view model**
- Both C# and F#
  - Auto completion of binding names
- C# only
  - "Go To Definition" support on binding names

**Comment by bent-rasmussen** [comment]
Yes, that's the primary thing. I can't provoke the tooling to give any design-time binding warnings.

**Comment by TysonMN** [comment]
I will close this for now.  We can reopen if anyone has an idea of how to achieve either of the static advantages to our dynamic approach.
