### ISSUE TITLE
Entry point

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#313]
My application at work has binding errors like those shown in issue https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2196.  I would love to understand why those binding errors are happening.  In the meantime, I want a workaround.

I think a contributing factor to those binding errors is that the entry point of my application is through a `static Main` method instead of the more traditional approach of using `Application.StartupUri`.  In this case, it is a bit awkward to initialize the `Resources` of `Application`.

This makes me think of three questions.
1. Is it possible to use Elimish.WPF with `Application.StartupUri` as the entry point?
2. Does anyone else try to initialize the `Resources` of `Application`?
3. Is anyone concerned about high memory usage cause by loading the same resources multiple times?  (I saw people discussing this while I was searching for answers to the first two questions.  I think the memory usage is high for my application at work.  I will try and investigate that tomorrow.)

**Comment by cmeeren** [comment]
Have a look at [this commit](https://github.com/cmeeren/Elmish.WPF/commit/2d79fd829ef1d5f6d91120562b3c465d73ac30a4), which rewrites the SingleCounter sample to use App.xaml, which you can use as you'd normally do by setting up resource dictionaries. The samples uses MaterialDesignInXamlToolkit, and I have also set up a global event handler in the App code-behind to demonstrate that it works like you'd expect for any non-Elmish.WPF app.

**Comment by TysonMN** [comment]
Thanks for the suggestion.  It is similar to things I have tried but not exactly the same.  I will try this tomorrow in my application at work.

**Comment by TysonMN** [comment]
I made that change in my reproduction, but the binding errors still occur.  See the branch [cmeeren/App.xaml](https://github.com/TysonMN/MaterialDesignInXaml_DataGrid_reproduction/tree/cmeeren/App.xaml).

**Comment by TysonMN** [comment]
I simplified my reproduction.  The problem still happens when the entry point is completely through `App.xaml` when using `Appplication.StartupUri`, so starting the application through a `static main` method (as we do with Elmish.WPF) is not a contributing factor.
