### ISSUE TITLE
System.MissingMethodException when starting basic application

### ISSUE THREAD

**Issue by KingVanti** [elmish/Elmish.WPF#317]
I have built a very basic application based on the Getting Started section of the readme. It is pretty much copied. When I start my application I get the following exception:

```
System.MissingMethodException: Method not found: 'Elmish.Program`4<System.__Canon,!!2,System.__Canon,!!3> Elmish.ProgramModule.withSyncDispatch(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,Microsoft.FSharp.Core.Unit>,Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,Microsoft.FSharp.Core.Unit>>, Elmish.Program`4<System.__Canon,!!2,System.__Canon,!!3>)'.
   at Elmish.WPF.Program.startElmishLoop[model,msg](ElmConfig config, FrameworkElement element, Program`4 program)
   at Elmish.WPF.Program.runWindowWithConfig[a,b](ElmConfig config, Window window, Program`4 program) in C:\projects\elmish-wpf\src\Elmish.WPF\Program.fs:line 50
   at Elmish.WPF.Program.runWindow[a,b](Window window, Program`4 program) in C:\projects\elmish-wpf\src\Elmish.WPF\Program.fs:line 58
```

I can't really tell what's going on and have not found any information about this. If you need more info about my project I am happy to give it. Thanks for your help.

**Comment by cmeeren** [comment]
Are you using the most recent version of Elmish.WPF from NuGet?

Can you also try installing Emish (not Elmish.WPF) v3.0.3 and see if that solves the problem?

**Comment by KingVanti** [comment]
@cmeeren I have 3 properties with the following packages:

- Core: Elmish 4.0.0-aphla-2
- Entry: Elmish 4.0.0-aphla-2, Elmish.WPF 3.5.6, FSharp.Core 5.0.0
- WPF: -

Packages are all up to date as far as I can see

**Comment by cmeeren** [comment]
Elmish.WPF is built against Elmish 3.x. There are apparently binary breaking changes in Elmish 4.x, which cause the symptoms you observe.

I'm not sure what tooling or configurations you have, but in my experience, NuGet in VS should by default not install prerelease dependencies unless you explicitly enable it. So when you install Elmish.WPF, it should pick the most recent non-prerelease Elmish, i.e. 3.1.0.

**Comment by TysonMN** [comment]
As can be seen on [the page for Elmish.WPF on nuget.org](https://www.nuget.org/packages/Elmish.WPF/), the dependency on Elmish from Elmish.WPF is stated to be strictly less than version 4.0.0.

**Comment by cmeeren** [comment]
Hm, then AFAIK it shouldn't even be possible to install both Elmish.WPF and Elmish 4.x. Strange.

**Comment by TysonMN** [comment]
To investigate, I just used Visual Studio to upgrade `Elmish` in my application at work to the latest pre-release.  There were no warnings during that process saying that I was doing anything wrong.

I was prevented from investigating further because I had compiler errors that I didn't feel like fixing.

If I were able to continue, I expect that there would have been a build warning as described in the [nearest wins rule](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#nearest-wins) of NuGet package dependency resolution.

**Comment by KingVanti** [comment]
I am using Rider and was given no indication that I should use a specific version of any package. I also did not have any compile-time issues. The above exception only occurred on start of the application.

**Comment by cmeeren** [comment]
I don't use Rider, but it could seem that there's a bug in its NuGet implementation. Elmish.WPF requires Elmish < 4, so it should never install any 4.x version when you install Elmish.WPF. Perhaps there's a bug where Rider regards 4.0.0-prerelease as < 4 and thus as satisfying the version constraint.

**Comment by TysonMN** [comment]
> Perhaps there's a bug where Rider regards 4.0.0-prerelease as < 4 and thus as satisfying the version constraint.

That makes sense. Maybe the same for Visual Studio.
Maybe changing the upper constrain to something ridiculous like `3.99]` would work better.

**Comment by cmeeren** [comment]
> Maybe changing the upper constrain to something ridiculous like `3.99]` would work better.

Until we release `3.100` 😉

IN all seriousness and frankness, though: The Rider bug (if it is that) is not our problem and not something we can or should fix.

**Comment by TysonMN** [comment]
> Until we release `3.100` 😉

Until Elmish releases `.3100`.

> Perhaps there's a bug where Rider regards 4.0.0-prerelease as < 4

[This behavior is intentional semantics by NuGet](https://github.com/NuGet/Home/issues/6434#issuecomment-358782297), so I don't think it is a bug in Rider.  More information is available in the [package versioning documentation for NuGet](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning). especially the section on [version ranges](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges).

The only workaround I see is to do something like `3.99]`.

**Comment by cmeeren** [comment]
> Until Elmish releases `3.100`.

Of course, my bad.

> [This behavior is intentional semantics by NuGet](https://github.com/NuGet/Home/issues/6434#issuecomment-358782297), so I don't think it is a bug in Rider. More information is available in the [package versioning documentation for NuGet](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning). especially the section on [version ranges](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges).

Thanks for looking into this. From the linked comment:

> At a low level VersionRange/VersionSpec behavior has never changed, `[1.0.0, 2.0.0)` has always allowed `2.0.0-alpha` and I've verified this all the way back to NuGet 2.2.0

Just ranting here: Is it me, or does that behavior just seems horribly counter-productive? If using a version range like `[1.0.0, 2.0.0)`, the intention is that in any `2.x` release, _including pre-releases_ there may be breaking changes.

> The only workaround I see is to do something like `3.99]`.

Yes, though perhaps `4.0.0-a` will work and communicates the intent more clearly?

Another solution would be for Elmish 4.0.0 to be released soon, and then we update. @et1975 Any chance of that happening in the foreseeable future? I see that `4.0..0-alpha-1` was released more than a year ago.

**Comment by TysonMN** [comment]
> > The only workaround I see is to do something like `3.99]`.
> 
> Yes, though perhaps `4.0.0-a` will work and communicates the intent more clearly?

Oh, yes.  Great point.  Actually, some others in that issue mentioned using `4.0.0-0` as a workaround.  This seems like a better workaround because `0` comes lexicographically before most other printable characters.  However, they also said NuGet didn't like that as a version.

Now that version `4.0.0-alpha-1` of Elmish exists, we could change it to `4.0.0-alpha-1)`.  That would certainly solve the current problem.

**Comment by cmeeren** [comment]
Done. I don't think we need to release a new package just for this, but feel free to disagree.

**Comment by cmeeren** [comment]
Actually, [the build fails](https://ci.appveyor.com/project/cmeeren/elmish-wpf/builds/37199727). Any (other) ideas?

> error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Elmish [3.0.3, 4.0.0-alpha-1)" or update the version field in the nuspec.

**Comment by cmeeren** [comment]
For now I've used `3.99]` as per your suggestion.
