### ISSUE TITLE
Efficient ResourceDictionary loading

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#318]
# Background

Every one of our sample projects explicitly defines its own entry point.  Eventually [`Program.runWindow[WithConfig]`](https://github.com/elmish/Elmish.WPF/blob/2895f1b08ad630cbd184054eff942614191ad341/src/Elmish.WPF/Program.fs#L47) is called, which executes
```fsharp
if isNull Application.Current then
  Application () |> ignore
  Application.Current.MainWindow <- window
window.Show ()
startElmishLoop config window program
Application.Current.Run window
```

The function `startElmishLoop` mostly executes code unique to Elmish and Elmish.WPF.  One important line is when the view model [is assigned to the `DataContext`](https://github.com/elmish/Elmish.WPF/blob/2895f1b08ad630cbd184054eff942614191ad341/src/Elmish.WPF/Program.fs#L22) of the main window.  Also observe that there is no `App.xaml` file in any of these sample projects.

Contrast this with the template code provided by Visual Studio when creating a new WPF application.  The entry point is generated based on the presence of `App.xaml` and the line `StartupUri="MainWindow.xaml"`.  That generated entry point contains the code
```csharp
WpfApp1.App app = new WpfApp1.App();
app.InitializeComponent();
app.Run();
```

(This duplicate code can be found in both of the files `App.g.cs` and `App.g.i.cs` in the directory `obj/debug/TARGET_FRAMEWORK/`.)

# Goal

I want to combine these two approaches.  I want to have an `App.xaml` file the sets `StartupUri`.  I also want to start the Elmish dispatch loop and set the view model to the `DataContext` of my main window at the right time.

# Motivation

My application at work is rather large now.  We have defined many things in `ResourceDictionary`s, especially [Material Design in XAML](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit).  Because we don't have an `App.xaml` file, we essentially reference a `ResourceDictionary` containing a reference to Material Design in XAML in every one of our `UserControl`s.

[This StackOverflow answer](https://stackoverflow.com/questions/13965694/does-each-reference-to-a-resourcedictionary-create-a-new-instance-or-do-resourc/13965987#13965987) says that each reference to a `ResourceDictionary` turns into a unique instance at runtime.  Using Visual Studio's ability to take a memory snapshot (in the Diagnostic Tools window), view the heap, and sort by inclusive size, I have confirmed that that answer is correct.

All those `ResourceDictionary` instances have significantly increased our memory usage and load times.  The load times are long both when starting the application and when viewing a `UserControl` in the designer.

# Solution??

I have tried some to achieve my goal but have yet to succeed.  The current state of my attempts is saved in [this branch](https://github.com/TysonMN/Elmish.WPF/tree/more_traditional_startup).

I will be attempting to achieve my goal again soon.  (Like like later today and later this week.)  I would greatly appreciate any idea that might help...or certainly complete answers as well.

**Comment by cmeeren** [comment]
What about what I linked to in https://github.com/elmish/Elmish.WPF/issues/313#issuecomment-748617313? Works fine for me. ResourceDictionary in `App.xaml`

**Comment by TysonMN** [comment]
Excellent!  I think that does exactly what I need.  None of my attempts included adding `<StartupObject>SingleCounter.Views.Program</StartupObject>` to the project file.

I will make this change to my application at work and then report back.

I think I forgot about that comment of yours because at the time I was focused that other issue.

**Comment by TysonMN** [comment]
Indeed, that worked perfectly!

This morning my application was using 680 MB.  There was a `ResourceDictionary` containing a reference to Material Design in XAML as well as styles for 92 `PathGeometry`s that we converted from SVG files.  That `ResourceDictionary` was loaded 16 times.  Now it is loaded once in `App.xaml`, and the application is only using 180 MB.

The images below show the heap in a snapshot while sorting by inclusive size.  The first image certainly shows lots of memory being used, but I don't understand how the sizes are calculated.  The first three items are _each_ over 1 GB, but the total shown in the Diagnostic Tools window is only 436 MB.

# Before
![2021-01-13_23-13-58_472_devenv](https://user-images.githubusercontent.com/34664007/104547927-536e0600-55f5-11eb-8334-e3386208b139.png)

# After
![2021-01-13_23-15-22_473_devenv](https://user-images.githubusercontent.com/34664007/104547943-59fc7d80-55f5-11eb-8890-3bc2c44d8ed1.png)

**Comment by cmeeren** [comment]
I think it would be good to have a sample that demonstrates this. For example the one from my commit, perhaps renamed and added as a new sample.

We could also consider rewriting all samples to match this. I personally think this _could_ be a good idea. The only difference is the addition of a simple `App.xaml` with code-behind, a call to `App()` in `Program.Main`, and a `<StartupObject>` element in the `csproj`. I think it's (slightly) easier to tell people to remove those files/lines than to add them if they really don't need them, but they don't hurt much just by being there, and it makes it easier to start using resource dictionaries and app-level event handlers etc. if the need comes up.

If we do this, we might also consider adapting the "getting started" section of the readme.

Thoughts?

**Comment by TysonMN** [comment]
My first thought is also to add a new sample that makes these changes.  However, the more I think about it, the more I like the idea of making this change to every sample.  First, the change is very small, so it doesn't add much complexity.  Second, it is somewhat closer to what is typically done when developing a WPF application (specifically the existence of `App.xaml` is similar while the absence of `StartupUri="MainWindow"` and the addition of `<StartupObject>` is different).  Third, it doesn't need to be removed if it is not needed.  The only advantage of removing it is barely simpler code to read.  There is no advantage to removing at runtime.

In addition to whatever sample changes, we should add a section to the readme and/or tutorial about this.

**Comment by cmeeren** [comment]
I agree. I'll see if I can create a PR tonight.
