### ISSUE TITLE
OneWay vs TwoWay and Binding.id

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#322]
We have several binding types that cannot be set.  They return `false` in this mattern match.
https://github.com/elmish/Elmish.WPF/blob/7d841f20983020fbe1cb841abbb1ffac87eb94a4/src/Elmish.WPF/ViewModel.fs#L764-L772

Cases that return `false` log that they cannot be set.
https://github.com/elmish/Elmish.WPF/blob/7d841f20983020fbe1cb841abbb1ffac87eb94a4/src/Elmish.WPF/ViewModel.fs#L809-L812

I think we can reduce the number of cases a bit.  For example, we could implement a `OneWay` binding by a `TwoWay` binding that logs and returns `false` like above.  I think this could even be done without hurting the performance of the happy paths (by partially applying the `propNameChain` and `binder.Name` arguments into the setting for the `OneWay` binding.

To be clear, the change I am thinking of here would be completely internal.  There would be no change to the API.

**Comment by cmeeren** [comment]
I don't really see the problem here. We have a number of semantically separate bindings. IMHO it's clearer to actually keep them separate. If we remove OneWay and implement it via a TwoWay where the setter logs, then 1) I think that's less clear, and 2) we now log "set failed" in two places (in the setter itself for some bindings, and in the existing place for other bindings).

**Comment by TysonMN** [comment]
It certainly might be less clear.  What excited me was the thought that it _could_ be done.  I think it is important to consider all (reasonable) options and intentionally pick one.  The alternative is to think there is only one option and feel like things must be that way.  Even if it is the best option, I find it helpful to know about alternatives, because the best option probably isn't the best in every possible way, and I think it is helpful to know about the tradeoffs.

I definitely wouldn't implement it so that it logs twice.  I think I would only implement this if I made the same change to all those non-settable bindings.

**Comment by cmeeren** [comment]
> I definitely wouldn't implement it so that it logs twice.

I didn't mean that it logs twice; I meant that some bindings was logged here while other bindings were logged there.

> I think it is important to consider all (reasonable) options and intentionally pick one.

I agree. I think the current implementation is better than the suggestion. However, I may of course be missing something. Feel free to clarify if you think that is the case.

**Comment by TysonMN** [comment]
> I didn't mean that it logs twice; I meant that some bindings was logged here while other bindings were logged there.

I would only consider this if that logging code was not duplicated.

> I think the current implementation is better than the suggestion. However, I may of course be missing something. Feel free to clarify if you think that is the case.

I definitely think it is better now.  I am wondering if this suggestion would be better when `v4` is nearly completion.

**Comment by TysonMN** [comment]
Or instead of implementing `OneWay` via `TwoWay`, maybe the right idea is to implement `TwoWay` via `OneWay`.  Something like this.
```fsharp
"MyTwoWayBinding" |> Binding.Oneway get |> Binding.withSetter set
```

**Comment by cmeeren** [comment]
I like the underlying composable idea, but it seems weird to me to say that you set up a one-way binding and then add a setter. Perhaps `Binding.get get |> Binding.set set` is better, at least as far as naming goes?

It may sound like nitpick at this point, but the difference may amount to an important difference in our understandings of the underlying concept and what is actually attempted by such an API, so I thought I'd put it out there.

**Comment by TysonMN** [comment]
Not a nitpick at all.  [Naming is impossibly hard](https://tysonwilliams.coding.blog/2020-07-15_naming_is_impossibly_hard) ;)

I like those names.  I am excited to implement this.  A lot work remains to finish the composable API.

**Comment by cmeeren** [comment]
I'm looking forward to it. Might even be the spark I need to pick up Elmish.WPF again and actually use it for a hobby project 😅

**Comment by TysonMN** [comment]
> instead of implementing `OneWay` via `TwoWay`, maybe the right idea is to implement `TwoWay` via `OneWay`.

Yes, I think implementing `TwoWay` via `OneWay` is the correct direction.  The argument that convinced me is that the simplest possible binding, one in which no arguments are needed (other than `unit` so that F#'s type inference works correctly), one which corresponds to identify function `id`, is a `OneWay` binding.

https://github.com/elmish/Elmish.WPF/blob/da4f9767fe8a66a3ba29704b1cba3d79616d1bd5/src/Elmish.WPF/Binding.fs#L905-L910

**Comment by cmeeren** [comment]
> other than `unit` so that F#'s type inference works correctly

Perhaps adding explicit type parameters also does the trick? `static member internal id<'model, 'msg>`

**Comment by TysonMN** [comment]
Ah, yes.  I forgot about that workaround.

Run into another restriction.  Properties cannot introduce type parameters.

Instead, I figured out how to improve the order of our helper functions (in https://github.com/elmish/Elmish.WPF/commit/1e1d7a07601df72630544295997ba94c946c10cf and https://github.com/elmish/Elmish.WPF/commit/24088bfb821191f2b0ac6317428c99e5a982fba2) and then made our `id` binding into a value in the `Binding` module in https://github.com/elmish/Elmish.WPF/commit/2d2cd49c02a396b3f7e2ea37390b73e6eadd3616.

**Comment by TysonMN** [comment]
> Yes, I think implementing `TwoWay` via `OneWay` is the correct direction. The argument that convinced me is that the simplest possible binding, one in which no arguments are needed [...], one which corresponds to identify function `id`, is a `OneWay` binding.

I am less confident about that now.  We could also define an `id`-like binding as
```fsharp
{ Get = id
  Set = id }
|> TwoWayData.box
|> TwoWayData
```

We could also define wrappers to convert a `OneWay` binding to a `TwoWay` binding and vice versa.

Maybe we should have `Binding.OneWay.id` and `Binding.TwoWay.id`.

**Comment by TysonMN** [comment]
I have created separate functions `Binding.OneWay.id` and `Binding. TwoWay.id` as well as `Binding.OneWayToSource.id`.  There is currently little to no shared code among them, and I am satisfied with this (for now).
