### ISSUE TITLE
Rename sample C# projects

### ISSUE THREAD

**Issue by cmeeren** [elmish/Elmish.WPF#323]
With the changes from #320, I feel it might be better for the C# projects to be suffixed `.App` instead of `.Views`. Thoughts?

**Comment by TysonMN** [comment]
I still like `Views`.

One advantage I see with `App` is that it is clearer which project is the primary entry point.  However, I already convey that by having that project be the default startup project (by having it appear first in the solution file).

**Comment by cmeeren** [comment]
> One advantage I see with `App` is that it is clearer which project is the primary entry point.

That is exactly my point. IMHO, the current `.Views` suffix seems to indicate it's a "helper" project.

> However, I already convey that by having that project be the default startup project (by having it appear first in the solution file).

Yes, though IMHO that does not alleviate the "helper" project feeling.

We can leave it as it is, but I just thought of another option I like even better: Remove the `.Views` suffix entirely, and add a suffix to the F# projects instead. `.Core` comes to mind, but I'm sure there are better alternatives. Thoughts?

**Comment by TysonMN** [comment]
> Remove the `.Views` suffix entirely, and add a suffix to the F# projects instead. `.Core` comes to mind, but I'm sure there are better alternatives. Thoughts?

Yes.  This sounds good to me.
