### ISSUE TITLE
Rename FileDialogs.CmdMsg sample to FileDialogsCmdMsg

### ISSUE THREAD

**Issue by cmeeren** [elmish/Elmish.WPF#324]
Currently, the naming of the `FileDialogs.CmdMsg` sample breaks the pattern in the (alphabetically sorted) solution explorer (and any file explorer):

![image](https://user-images.githubusercontent.com/7766733/106195149-0b7fdf00-61b0-11eb-8d8e-c9ff19e895f1.png)

Renaming to `FileDialogsCmdMsg` solves this:

![image](https://user-images.githubusercontent.com/7766733/106195083-facf6900-61af-11eb-95c8-e62634d2f98f.png)

@TysonMN Thoughts?

**Comment by TysonMN** [comment]
I like that change.

**Comment by cmeeren** [comment]
Great, I'll just commit it directly to `master` after #320 is merged.
