### ISSUE TITLE
Design time models are broken

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#326]
Downloaded the source, and wanted to compile the samples, but I'm having some problems.

The change from #323 has caused the design time views to fail. The problem is that ".Core" hasn't been added to the assembly name of the vm assignments in XAML files. Compiling doesn't reveal this. Opening the XAML's do. Design time view in VS fails to show entirely until the problem is corrected.

**Comment by TysonMN** [comment]
Thanks for letting us know.

While we are on the topic, does anyone know how to programmatically detect this?

I have a test that instantiates my main window.  That catches some errors, like XAML syntax errors.  I have that allows the dispatcher to process all messages.  That catches some more errors, like some broken bindings.  (Eventually I will create blog posts sharing how I do this.)  Neither of these would detect this problem.

Some documentation on this that I think is helpful is the different types of errors and XAML code can have.
https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-errors-warnings

**Comment by cmeeren** [comment]
Thanks for the notice. I have fixed it. Feel free to continue the discussion.

**Comment by BentTranberg** [comment]
A rocket, because that was quick!

I was also thinking about how to catch this. Can the vm somehow be used by C# or F# source, so that compilation fails? Guess not. Will google.

**Comment by BentTranberg** [comment]
It looks like binding through code (C#/F#?) is one way, but I guess we don't like that. I think this suggestion to create/use a tool is probably a better way, but I haven't studied this particular suggestion. See the accepted answer:

https://stackoverflow.com/Questions/12350109/Compile-time-Checking-of-bindings

**Comment by BentTranberg** [comment]
Can we create a tool that will open some assembly with the XAML, and some other assembly with the Elmish.WPF design time model, somehow get at this, perhaps instantiate it, then somehow determine that it works?

I am thinking this could be a command line tool that would take the assembly names as parameters, and also the stuff to look for in the assemblies. The tool I guess will have to load assemblies dynamically, and use reflection to find stuff.

**Comment by TysonMN** [comment]
> I think this suggestion to create/use a tool is probably a better way, but I haven't studied this particular suggestion. See the accepted answer:
> 
> https://stackoverflow.com/Questions/12350109/Compile-time-Checking-of-bindings

My test is similar to that answer.  More specifically, my test is equivalent to running the application and letting it reach an "equilibrium state" (i.e. when the dispatcher's queue is empty).
