### ISSUE TITLE
Sample Validation won't compile

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#327]
I get a compile time error when trying to compile the Validation sample with Elmish.WPF 3.5.6 (currently the latest) from NuGet. I think a screenshot is the easiest way to show the interesting parts.

![image](https://user-images.githubusercontent.com/15068882/106667504-49627600-65a9-11eb-931b-ce686888c64e.png)

**Comment by cmeeren** [comment]
It builds and runs fine for me, even after a `git clean -dfx`. I suggest you try the same.

**Comment by BentTranberg** [comment]
My mistake. I'm not thinking straight today. Of course the samples from master - which is ongoing work - can't be expected to compile with Elmish.WPF 3.5.6 from NuGet. I'm closing this then.

**Comment by BentTranberg** [comment]
Reopening, because of #329.

**Comment by TysonMN** [comment]
#329 was resolved by releasing [version 3.5.7](https://www.nuget.org/packages/Elmish.WPF/3.5.7).  I think this also resolves this issue.  Feel free to reopen if there is still some issue.
