### ISSUE TITLE
Switch DevOps to GitHub Action

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#332]
I would prefer to to have the automated builds run by GitHub.  `fsharp-hedgehog` and `fsharp-hedgehog-experimental` use a certain Action that works very well.

**Comment by cmeeren** [comment]
Could you briefly describe why? Is it just preference (which is OK, I always use AppVeyor because that's what I always have done, and I find it simple), or are there any benefits to be gained from switching to GH Actions?

**Comment by TysonMN** [comment]
I do think it is mostly preference.  I like the idea of tighter integration.  The code is on GitHub, and now GitHub also supports these automated DevOps behaviors under the name GitHub Actions.  I find it convenient that the executions of the Actions are easily available at the top of the page under "Actions".  A small simplification is that the particular GitHub Action that I have in mind automatically creates the tag when the version in the project file changes.

**Comment by cmeeren** [comment]
Sure, please go ahead. :)
