### ISSUE TITLE
INotifyDataErrorInfo.HasErrors incorrect

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#339]
We currently implement `INotifyDataErrorInfo.HasErrors` like this.
https://github.com/elmish/Elmish.WPF/blob/7764e9cedde2f1c34334ef01ac140416dcb63882/src/Elmish.WPF/ViewModel.fs#L569-L570

This is not perfectly correct because of the way we cache errors.  If some binding used to have errors and no longer has errors, then this dictionary contains the value `[]` for that binding.

If logging is added to that method, then these are the log events when there are no errors and a character is added to the password.
```
[08:11:18 VRB] [main] PropertyChanged "Password"
[08:11:18 VRB] [main] TryGetMember Password
[08:11:18 VRB] [main] HasErrors
[08:11:18 VRB] [main] GetErrors Password
```

If the implementation is
```fsharp
member __.HasErrors =
  log.LogTrace("[{BindingNameChain}] HasErrors", propNameChain)
  errorsByBindingName
  |> Seq.map Kvp.value
  |> Seq.filter (not << List.isEmpty)
  |> (not << Seq.isEmpty)
```
then these are the log events when there are no errors and a character is added to the password.
```
[08:06:17 VRB] [main] PropertyChanged "Password"
[08:06:17 VRB] [main] TryGetMember Password
[08:06:17 VRB] [main] HasErrors
```

**Comment by cmeeren** [comment]
Seems like a very simple fix. Feel free to fix and release.
