### ISSUE TITLE
Any plans to port work on dynamic views from Elmish.XamarinForms to WPF??

### ISSUE THREAD

**Issue by Zaid-Ajaj** [elmish/Elmish.WPF#34]
So much interesting stuff going on the [Elmish.XamarinForms](https://github.com/fsprojects/Elmish.XamarinForms) now especially with dynamic views which is starting to look a lot like Elmish/React with Fable, any plans on porting it here too?

**Comment by dsyme** [comment]
See also prior discussion in https://github.com/Prolucid/Elmish.WPF/issues/29

@et1975 The approach taken by Elmish.XamrinForms as of today is essentially the one outlined by you in that thread. However a code generator is currently used based on a bindings.json, rather than a type provider. We could consider changing to a type provider but there are a number of syntactic code generation hacks used at the moment

**Comment by 2sComplement** [comment]
Definitely would love to port dynamic views over here. @dsyme I also wonder if it would be possible to separate the "binding engine" from the view implementation. The view libraries could then sit on top of the binding engine and be brought in as needed depending on which framework is being targeted.

**Comment by Zaid-Ajaj** [comment]
>  Probably the biggest downside is that 3rd-party controls need non-trivial work to work with dynamic views. 

@dsyme Can you please elaborate on the non-trivial work needed to integrate 3rd-party libraries? I am assuming it is just some type of glue code that to make the view DSL nicer. We are pretty much used to writing such glue with Fable to make React libraries work with Elmish so it is not *that* bad.

**Comment by Zaid-Ajaj** [comment]
Also, please consider the portability to [Avalonia](https://github.com/AvaloniaUI/Avalonia), a cross-platform WPF implementation. It is still beta but works really nice and easy on linux/mac.

**Comment by albertwoo** [comment]
Using Type Provider sounds more exiting and easier to port to different framework like WPF, Avalonia or [Uno](http://platform.uno/ ).

**Comment by dsyme** [comment]
> @dsyme Can you please elaborate on the non-trivial work needed to integrate 3rd-party libraries? I am assuming it is just some type of glue code that to make the view DSL nicer. We are pretty much used to writing such glue with Fable to make React libraries work with Elmish so it is not that bad.

3rd party Xamarin.Forms libraries don't come with incremental-update by default.  However it is not too hard to write such interop code. I'm going to put together some samples today

**Comment by et1975** [comment]
I think we can safely close this, as [Uil](/elmish/Uil) aims to accomplish that independently.
