### ISSUE TITLE
Composable stickiness

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#340]
Currently, the only binding that can be sticky is `SubModelOpt`.
https://github.com/elmish/Elmish.WPF/blob/8f50a7c7742a5978305d3c919cc31bb9fe1ed3cb/src/Elmish.WPF/Binding.fs#L1719-L1723

I would like to have a sample called `Sticky` that shows how to use this behavior.  According to this documentation, this sample could include animation.

After this sample exists, I will add [stickiness as a general binding effect](https://github.com/elmish/Elmish.WPF/issues/295#issuecomment-748106400) and add an example of that to the Sticky sample.

**Comment by TysonMN** [comment]
I had intended to wait to include that code until we had a `Sticky` sample.  Instead I accidently included that code in commit https://github.com/elmish/Elmish.WPF/commit/f8ae19d095ad385212002599221a8c3ad9777484 (and then modified in https://github.com/elmish/Elmish.WPF/commit/fb18a564c208802675a15ebe1df1a431ce9061e5 and https://github.com/elmish/Elmish.WPF/commit/871e17188e0eb8ead32c6d1607b93bc283edb03d).

The code now looks like this.
https://github.com/elmish/Elmish.WPF/blob/da4f9767fe8a66a3ba29704b1cba3d79616d1bd5/src/Elmish.WPF/Binding.fs#L511-L523

**Comment by TysonMN** [comment]
It is interesting that stickiness can be implemented in that way.  However, it can also be implemented as a special case of laziness (i.e. a short-circuit of the [`updateBinding` function](https://github.com/elmish/Elmish.WPF/blob/a72c80949869aba531eb7596b2d0829a2f9e2c8e/src/Elmish.WPF/ViewModel.fs#L303)).  The latter would be more efficient.

Furthermore, it is interesting to consider exposing both concepts.  On the one hand, it is helpful that these concepts have different names because that makes it easy to define functions matching their behavior (as opposed to only using one name and method overloading).  On the other hand, it might be a bit confusing that such similar concepts would be exposed by such syntactically different names.

**Comment by TysonMN** [comment]
I added a sample in https://github.com/elmish/Elmish.WPF/commit/52d1363bde87b0948c3182025f478ef2e225f0a6

**Comment by cmeeren** [comment]
I haven't run the sample, but at first sight it looks like SingleCounter with the change that the count is sticky for every other number. That sounds like a good demonstration.

**Comment by TysonMN** [comment]
I have not yet removed the custom stickiness in the `SubModelOpt` binding. I want a manual test to cover that case first (i.e. adding sucha binding to this sample).  Of course I would also like automated tests eventually as well.

**Comment by TysonMN** [comment]
Still haven't added any new tests, but the "sticky" is now added to the `SubModel` binding but using the lazy effect instead.

**Comment by TysonMN** [comment]
Although there is some more work to be done, I will close this issue.
