### ISSUE TITLE
To cache or not to cache

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#342]
I would like some feedback on whether we should cache or not by default and if we should also support the non-default choice.  Here are some examples.

- For validation, we cache errors and do not support not caching them.  See [this code](https://github.com/elmish/Elmish.WPF/blob/637d7c7166834e77b4acdffc91cc394cab7376fb/src/Elmish.WPF/ViewModel.fs#L580-L591).
- `SubModelSelectedItem` uses caching and we do not support not caching.  See [this code](https://github.com/elmish/Elmish.WPF/blob/637d7c7166834e77b4acdffc91cc394cab7376fb/src/Elmish.WPF/ViewModel.fs#L281-L289), especially [line 288](https://github.com/elmish/Elmish.WPF/blob/637d7c7166834e77b4acdffc91cc394cab7376fb/src/Elmish.WPF/ViewModel.fs#L288).
- `OneWayLazy` uses caching and we do support not caching via a `OneWay` binding.  See [this code](https://github.com/elmish/Elmish.WPF/blob/637d7c7166834e77b4acdffc91cc394cab7376fb/src/Elmish.WPF/ViewModel.fs#L191-L199), especially [line 198](https://github.com/elmish/Elmish.WPF/blob/637d7c7166834e77b4acdffc91cc394cab7376fb/src/Elmish.WPF/ViewModel.fs#L198).

I am considering changing `Command` to take a single function in place of the two functions `execute` and `canExecute` like our API supports.  However, our API just executes the function twice: once to compute `canExecute` and once to compute `execute`.  The ability to cache in this case exists by using [this overload](https://github.com/elmish/Elmish.WPF/blob/44674cea739547fa88f9b9d3667d6068e38db7d5/src/Elmish.WPF/Binding.fs#L1474-L1479) instead.
https://github.com/elmish/Elmish.WPF/blob/44674cea739547fa88f9b9d3667d6068e38db7d5/src/Elmish.WPF/Binding.fs#L1491-L1495

Elm doesn't do caching everywhere by default.  For example, it is up to the user to call [`HTML.lazy`](https://guide.elm-lang.org/optimization/lazy.html).

I think caching is typically the correct choice when the user's types are immutable and functions are pure.  Caching might not be correct for those with mutable types or impure functions.  Maybe there is a case with only immutable types and pure functions in which caching would make things worse.  However, I don't know of such a case.

**Comment by TysonMN** [comment]
For example, we have a cache for errors.
https://github.com/elmish/Elmish.WPF/blob/953457d9e77f971347093b83d96a452cf427c70f/src/Elmish.WPF/ViewModel.fs#L107
https://github.com/elmish/Elmish.WPF/blob/953457d9e77f971347093b83d96a452cf427c70f/src/Elmish.WPF/ViewModel.fs#L192-L193
https://github.com/elmish/Elmish.WPF/blob/953457d9e77f971347093b83d96a452cf427c70f/src/Elmish.WPF/ViewModel.fs#L311-L321
https://github.com/elmish/Elmish.WPF/blob/953457d9e77f971347093b83d96a452cf427c70f/src/Elmish.WPF/ViewModel.fs#L572-L583

We could also have a cache for the `bool`s corresponding to the `CanExecute` method of a `Command`.

We might even be able to have a cache of the values for bindings than can raise a `PropertyChanged` event.

**Comment by cmeeren** [comment]
I'm not sure, but I think caching (assuming immutable types/logic) is generally a good thing. I think (but I'm not sure) WPF may retrieve bindings, check `CanExecute` etc. quite a lot depending on what happens in the UI.

**Comment by TysonMN** [comment]
I think the method-based binging API can cache by default for whatever else seems to typically be a good idea.  The function-based binding API will make no such choices
