### ISSUE TITLE
Composable validation

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#343]
I just pushed three commits...
1. https://github.com/elmish/Elmish.WPF/commit/59c655f059331f4d603fae83504aeb57130e843d,
2. https://github.com/elmish/Elmish.WPF/commit/8845514c166d7188ccc0e702ce1cd244f3d3476a, and
3. https://github.com/elmish/Elmish.WPF/commit/71795ec6bbd817d1acafac5b78588de36006cf6c

...that add composable validation.  The primary purpose of this issue to announce this new feature.  Feel free to provide feedback by commenting.

The first commit actually adds composable validation.  I think it is working perfectly.

The second commit removes `TwoWayValidate`.  I didn't think too much about the tests.  Instead, I commented out the ones that didn't make sense any more.  This should be cleaned up at some point.  This would probably include creating a generator for `BindingData<_, _>`.  I would prefer to leave this issue open until this issue with the tests is resolved.

The third commit modifies the `Validation` sample to (explicitly) use composable validation.  I added validation to a `OneWay` binding, something that was not possible before.  The sample could be further expanded.  For example, it could include a sequence that has a validation error unless the items it contains are in sorted order.

Here is one thing to keep in mind as the composable API is increased.  I think the composable API benefits from being curried functions instead of uncurried methods.  This is differs from the binding API in v3 that exclusively uses uncurried methods.

**Comment by cmeeren** [comment]
Looks very good! Thanks! 😀

**Comment by TysonMN** [comment]
As @cmeeren pointed said in https://github.com/elmish/Elmish.WPF/commit/71795ec6bbd817d1acafac5b78588de36006cf6c#r47168898, the alignment can be improved in the `Validation` sample.
