### ISSUE TITLE
Composable laziness

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#344]
See previous discussion in #143.

I added composable laziness in https://github.com/elmish/Elmish.WPF/commit/66f3fd7138832c8d659aefa1b1bef0bc9eed87ea.

Still need to make a sample and convert the existing bindings.

**Comment by TysonMN** [comment]
To pick up the naming from #143...

I am thinking about #333.  What if we have the default behavior be laziness everywhere in the style of [Elm's `HTML.lazy`](https://guide.elm-lang.org/optimization/lazy.html)?

Then we can have functions
```fsharp
Binding.replaceLazy : ('model -> 'model -> bool) -> Binding<'model, 'msg> -> Binding<'model, 'msg>
```
and
```fsharp
Binding.removeLazy : Binding<'model, 'msg> -> Binding<'model, 'msg>
```
that replaces an existing lazy predicate (if one exists or adds one if one doesn't exist) and removes an existing lazy predicate (if one exists).  We could also have
```fsharp
Binding.addLazy : ('model -> 'model -> bool) -> Binding<'model, 'msg> -> Binding<'model, 'msg>
```
as well.

One the one hand, this optimizes the code for lots of short circuiting and allows us to avoid the desire to have a function named `lazy`.  On the other hand, is allows users to override the filtering logic like would be helpful with the impure case described in #333.

**Comment by cmeeren** [comment]
That may be a good idea. We should, however, think about the implications of having everything be lazy by default. The overhead (memory/CPU) may not be worth it for the majority of bindings. If that is the case, we may consider having non-lazy be the default, and allowing users to use `addLazy` wherever they think it is needed.

**Comment by TysonMN** [comment]
Another naming idea is `Binding.lazyWhen`

**Comment by TysonMN** [comment]
I like now like the idea of
1. being non-optimized (like Elm) by default (because this is safer) and then
2. exposing each effect via a function that starts with `add`.

So for laziness, the function name would be `addLazy` while other names would be `addValidation` and `addSticky`.  This makes it clear that each of these is an effect that can be added to any binding.

**Comment by TysonMN** [comment]
Although there is some more work to be done, I will close this issue.
