### ISSUE TITLE
Elmish.WPF app hung during startup

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#345]
UPDATE: I've had my first indication that this was wrong. The application still hangs after my attempt at the described fix. Closing since the problem is then very likely not related to Elmish.WPF.

After changing my Elmish.WPF app to be more like the examples, I've had a problem on my (by far) fastest machine. It would hang during debug startup in VS. The GUI would not appear, and either nothing would show in Task Manager, or it would eventually show up far down in the list, apparently dead. In VS it would still be running, but with no threads or tasks or anything that I can see. It would also sometimes block the following attempt to run, so the former application had to be killed first.

These hangs would happen so frequently that it was easy to reproduce. It seems I've solved the problem now, but I don't quite understand why.

Please note that I don't have sufficient statistics yet to affirm that the issue is actually solved, though it looks very good at first attempts. This issue report is more of a question whether you know why such a change might work.

The changes are all in App.xaml.cs. These are snippets of the original code.

        public App()
        {
            ....
            this.Activated += StartElmish;
        }

        private void StartElmish(object sender, EventArgs e)
        {
            this.Activated -= StartElmish;
            TdKlient.Models.Program.main(MainWindow, () => new TdKlient.Views.LogWindow());
        }

And this is after the modification that possibly solved the issue.

        bool oneShot = false;

        protected override void OnActivated(EventArgs e)
        {
            base.OnActivated(e);
            if (!oneShot)
            {
                oneShot = true;
                TdKlient.Models.Program.main(MainWindow, () => new TdKlient.Views.LogWindow());
            }
        }

I was skeptical the first time I saw how the Activated handler was used, based on past experiences. Unfortunately these experiences are so far back in time that I can't remember exactly what problems there were - if I ever got to the bottom of it. In any case that's why I have since always in similar cases used this technique you see with the oneShot variable, and why I thought it was worth a shot (pun intended) here too.

My hunch is that the problem surfacing has something to do with the machine being fast, because that's often the kind of thing that brings threading issues and similar issues to the surface. Also the problem don't appear on all other machines this software runs on - slower machines.

I don't have this problem with the examples. Only with my business application at work, which now has lots of Elmish.WPF GUI and lots of other stuff.

**Comment by TysonMN** [comment]
As usual, if you can provide a MWE, I would be happy to investigate.  I know how hard that can be though.

> It would hang during debug startup in VS. The GUI would not appear, and either nothing would show in Task Manager, or it would eventually show up far down in the list, apparently dead. In VS it would still be running, but with no threads or tasks or anything that I can see. It would also sometimes block the following attempt to run, so the former application had to be killed first.

In this case, did you pause Visual Studio and look at the parallel stacks window?

> My hunch is that the problem surfacing has something to do with the machine being fast, because that's often the kind of thing that brings threading issues and similar issues to the surface. Also the problem don't appear on all other machines this software runs on - slower machines.

Sometimes you can test and verify hunches like this by adding in explicit delays with `Thread.Sleep`, Task.Delay`, or `Async.Sleep` to force certain parts to be slow and allowing other parts to be fast.

**Comment by BentTranberg** [comment]
Several times I paused and looked in all debugging panes I could find for something, but they were usually blank. There was a stack sometimes, in various standard libraries that didn't seem relevant. Yesterday I had these on another machine too. The frequency of these incidents has fortunately been quite low lately, so it's no big deal in that sense. Also it's only a problem in VS. Right now my prime suspects are 1) a recent change of Akka to NetMQ, which was superb but certainly brought with it a lot of weird issues. 2) Enabling asynchronous logging in SmartInspect, which in the past I've also had issues with. 3) The "architectural change" in the use of Elmish.WPF, but as already stated I no longer believe this is the actual cause of the problem. Unless the problem just disappear as the result of me improving things, unfortunately I will have to let this issue lie idle for some weeks or months before I can get back to it, since as usual I've got too much to do. Thanks for the advice.

**Comment by TysonMN** [comment]
Are you able to consistently reproduce the hanging during startup or is the hanging during startup an intermittent problem (i.e. sometimes it happens and sometimes it does not)?

> Sometimes you can test and verify hunches like this by adding in explicit delays with `Thread.Sleep`, `Task.Delay`, or `Async.Sleep` to force certain parts to be slow and allowing other parts to be fast.

For an example of this, see PR #350.

**Comment by BentTranberg** [comment]
It's intermittent, and does not appear as frequently as it used to. Thanks for the link. I'll try out various things when I get a chance.

**Comment by TysonMN** [comment]
If possible, the best thing you can do make it more consistent.

Good luck!

**Comment by BentTranberg** [comment]
Just FYI: I'm reasonably sure I've fixed this problem once and for all today. It's been bothering me until now. Just started development of another, so far tiny, application that behaved in the same way, consistently. Since it was tiny, it was easy to debug. The practical solution was to explicitly shut down SmartInspect, the log system, with `SiAuto.Si.Enabled <- false` before exiting the application. I am quite sure I'm not doing anything wrong with SmartInspect, though something I do when configuring SmartInspect cause it to hang the application on exit in VS debug, and block/hang the next invocation on startup, even though the former is forcefully shutdown in VS and/or Task Manager.

**Comment by TysonMN** [comment]
Wow, to have _and find_ a problem that exists over restarts is exceedingly hard.  Hopefully you really have tracked down this issue.

P.S.
Thanks for using Elmish.WPF and for all your help and support of both Elmish.WPF and myself :)
