### ISSUE TITLE
Entity-level errors?

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#348]
When `""` or `null` is given to [`INotifyDataErrorInfo.GetErrors(string)`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifydataerrorinfo.geterrors#System_ComponentModel_INotifyDataErrorInfo_GetErrors_System_String_), the result is supposed to be entity-level errors.  Elmish.WPF doesn't support entity-level errors (in particular, `ErrorsChanged` is never raised for `""` or `null`) and we are consistent with this by returning an empty `IEnumerable` if the input were ever `""` or `null`.

Is this something we could or should support?

I don't care myself.  I happened to see this documentation and wanted to make a note of it.

**Comment by cmeeren** [comment]
If anyone needs it, we can add it. I don't even know what it's used for.
