### ISSUE TITLE
How to trigger form refresh when changing tabs?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#351]
Simple question. 

My application is divided into multiple wpf tabs.  Is there an event I can use to signal Elmish.wpf when user has changed tabs so that I can refresh the tab being viewed?

Thank you.

**Comment by TysonMN** [comment]
Can you share a GitHub with an example that needs such a trigger when changing from one tab to another?

**Comment by awaynemd** [comment]
Well, sure :) But I was hoping for a simple answer.

**Comment by TysonMN** [comment]
The simple answer is that such a "trigger" should already be happening.  So either you found a bug, which I would only be able to fix after looking at a reproduction, or I don't understand what you are asking, which would be clarified with a minimal working example.

**Comment by awaynemd** [comment]
@TysonMN 

Hi! Upon changing the view tabitem, I need to update the screen with whatever actions had occurred since its last refresh. 

BTW, simple answer is that WPF provides a property binding to "Selector.IsSelected" (boolean) that binds easily with the bindings.  

Example XAML:
    ```
 ```
        TabItem Header="Doctor" Selector.IsSelected="{Binding DoctorTabSelected}">
                    <local:DoctorView/>
        TabItem
```
```

Example binding:
     let bindings () : Binding<Model,Msg> list = [  
  
     "DoctorTabSelected" |> Binding.twoWay((fun m -> m.DoctorTabSelected),  SetDoctorTabSelected)
    ]  

Anyway, if there is a better way, I'm completely open to suggestions. :)

Thanks.

**Comment by TysonMN** [comment]
> Upon changing the view tabitem, I need to update the screen with whatever actions had occurred since its last refresh.

I don't know what you mean by "actions".  Can you share a GitHub repo with an executable example that involves such actions?

> simple answer is that WPF provides a property binding to "Selector.IsSelected" (boolean) that binds easily with the bindings.

I am not sure of the best way to do native WPF tabs.  I use the solution for tabs from [Material Design in XAML](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit), which is to use `RadioButton`s that get styled to look like tabs.  This works like a charm when following the "recommended way to use `RadioButton`" (c.f. #283 and the `SubModel` sample, which uses `RadioButton`s).
