### ISSUE TITLE
TaskCanceledException on program end in timerTick in FileDialogsCmdMsg.Core

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#353]
I get this from time to time, in FileDialogsCmdMsg.Core, when I shut down the demo.

![image](https://user-images.githubusercontent.com/15068882/109411922-83a31580-79a5-11eb-8042-9736f764520f.png)

I guess fixing this is as simple as somehow disabling the timer before exiting, or tell it not to call dispatch perhaps. I'd do it using the Closing event of the window, because my intuition and experience with that sort of thing tells me that doing it later can cause a mess. (But if using Closing then we're back to the considerations of issue #330.)

**Comment by TysonMN** [comment]
This was fixed in [`4.0.0-beta-40`](https://www.nuget.org/packages/Elmish.WPF/4.0.0-beta-40) and then a rather serious bug introduce in `4.0.0-beta-40` was fixed in [`4.0.0-beta-41`](https://www.nuget.org/packages/Elmish.WPF/4.0.0-beta-41).
