### ISSUE TITLE
ItemsSource, ItemTemplateSelector and bindings

### ISSUE THREAD

**Issue by Evangelink** [elmish/Elmish.WPF#356]
Hi there,

I have fully read (and globally got all parts) of the discussion that happened in #270. But there are still some open questions for me and I'd like to get your input.

Let's say I have the following type

```fsharp
type TimelineItem =
    | Clip of ClipModel
    | PlaybackCursor of TimeSpan
    | SpecialTime of TimeSpan
```

as the data-type of my sequence which is bound to the `ItemsSource` property. My understanding is that I have two options:

1. Use `oneWaySeq` or `oneWay` but then how can I bind the properties/fields I am interested in on my `ClipModel` type?

2. Use `subModelSeq` in which case I will need a converter in addition to the `DataTemplateSelector` to avoid the `Elmish.WPF.ViewModel'2[System.Object.System.Object]` type. In the list of bindings declared I will have to declare a bunch of bindings where some are only "valid" in some cases (it's easy to provide default values).

Did I get things right? Do you confirm that in this case, as I have different types, I need to go with the `subModelSeq`?

Thank you

**Comment by Evangelink** [comment]
Looks like I read too fast, the converter option wasn't for unwrapping the elmish viewmodel so I am kinda stuck.

**Comment by TysonMN** [comment]
Yes, use `SubModelSeq`.

Do you know how to create bindings and a view for a single instance of `TimelineItem`?

**Comment by Evangelink** [comment]
I have 3 data templates (the 3 cases of the DU) and a `DataTemplateSelector` but it's not working as the type is Elmish `ViewModel2`.

template selector:
```csharp
 public override DataTemplate? SelectTemplate(object item, DependencyObject container)
        {
            if (item is TimelineItem timelineItem)
            {
                if (timelineItem.IsClip)
                {
                    return ClipTemplate;
                }
                else if (timelineItem.IsPlaybackCursor)
                {
                    return PlaybackCursorTemplate;
                }
                else if (timelineItem.IsSpecialTime)
                {
                    return SpecialTimeTemplate;
                }
            }

            return base.SelectTemplate(item, container);
        }
```

So there is still one missing piece in the architecture.

**Comment by TysonMN** [comment]
I would create three views, one for each case data. For bindings, I would create two bindings for each case: a `One Way` binding for `Visibility` (either `Visible` or `Collapsed`) and a `SubModelOpt` binding. Then the view for a single `TimelineItem` would look like this.
```xaml
<Grid>
  <Grid Visibility={Binding ClipVisibility}>
    <local:Clip DataContext={Binding Clip}/>
  </Grid>
  // the other two cases
</Grid>
```

**Comment by TysonMN** [comment]
(To be clear...)

Unlike the code in your comment, I have no code-behind / C# code (which is a goal).

**Comment by Evangelink** [comment]
Oh I see! So basically we never use template selector with Elmish WPF and probably also rarely use converters at all as we can have the "right" value directly.

Just to be sure, in the example you gave, `Clip` and `ClipVisibility` are both sub-bindings of `SubModelSeq`, right?

**Comment by TysonMN** [comment]
> Just to be sure, in the example you gave, `Clip` and `ClipVisibility` are both sub-bindings of `SubModelSeq`, right?

Correct.  That is why I asked how you would display a single `TimelineItem`.  That is the hard part.

> So basically we never use template selector with Elmish WPF and probably also rarely use converters at all as we can have the "right" value directly.

I never liked converters even before I used Elmish.WPF.  I think their syntax is extremely verbose, and I think they move logic into the view / code-behind / C#.

I think of `DataTemplateSelector` as a "pattern match" in XAML.  Just like "pattern matching" in C#, it is not currently possible to know if the match is exhaustive.  Instead, I think it is better to move this pattern matching into F# where it can be exhaustive.

**Comment by Evangelink** [comment]
> I think of `DataTemplateSelector` as a "pattern match" in XAML. Just like "pattern matching" in C#, it is not currently possible to know if the match is exhaustive. Instead, I think it is better to move this pattern matching into F# where it can be exhaustive.

I understand and I think it makes sense but it'd be nice to have maybe something more convenient than X tuplet of visibility and sub-binding.

**Comment by TysonMN** [comment]
> [...] it'd be nice to have maybe something more convenient than X tuplet of visibility and sub-binding.

I know what you mean.  I have thought about this some, but I don't have an idea for a better solution at this time.

I think a potential creativity block for me is both lacking a fully composable binding API and the second is being aware of the remaining effort required to complete that API.  As such, I want to primarily focus on finishing that API.

**Comment by Evangelink** [comment]
> As such, I want to primarily focus on finishing that API.

Makes sense to me. Once the new API is around we can see if/what could be improved.

Thank you for your time.
