### ISSUE TITLE
Latest prerelease 4.0.0-beta-1, not beta-3

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#367]
When creating a new F# library project for .NET 5.0 in VS 2019 v 16.9.0, and adding Elmish.WPF in "Manage Packages for Solution", the version listed by default is "Latest prerelease 4.0.0-beta-1". This in spite of 4.0.0-beta-2 and 4.0.0-beta-3 being listed as alternatives.

It seems obvious that the chosen version names do not conform to the expected pattern when sorting versions on NuGet.

I have seen similar naming schemes fail in various ways in the past in other projects. E.g. 0.0.0.0-beta10 is seen as earlier than 0.0.0.0-beta2 through 0.0.0.0-beta9. (edit: This example doesn't make sense to me right now, but it was something like this - that the 10 came earlier than the single-digit ones in some naming scheme.)

A guess is that the following example of change in naming scheme might work well for future releases, also in regards to properly succeeding existing releases starting with 0.0.0.0-beta  Please understand it's just a guess.

4.0.0.1-beta
4.0.0.2-beta
4.0.0.3-beta
4.0.0.4
4.0.0.5
4.0.0.6

edit: Ouch! Just now noticed it was 4.0.0-beta... with just three numbers. Maybe it will take 4.0.1.0-beta to succeed it properly.

**Comment by TysonMN** [comment]
Thanks for reporting this.

I think the format I want is like
```
4.0.0-beta+4
```

I will investigate in a few hours.

https://saebamini.com/how-to-version-your-net-nuget-packages-libraries-and-assemblies-azure-yaml-pipelines-example-using-net-core-cli/

**Comment by TysonMN** [comment]
This feels like a bug with Visual Studio.

When first installing, Visual Studio gives conflicting reports.  On the one hand, the search results on the left say that `4.0.0-beta-3` is the latest prerelease version.  On the other hand, the details on the right default to `4.0.0-beta-1` as you reported, and the dropdown suggests that the version order among the betas is the opposite of what I intended.

![1](https://user-images.githubusercontent.com/34664007/110419810-a5646280-805f-11eb-9a27-d55d55771651.png)

Then after first installing, Visual Studio immediately says there is an update available to version `4.0.0-beta-3`.

![2](https://user-images.githubusercontent.com/34664007/110419873-bf9e4080-805f-11eb-943e-29481834469c.png)

@BentTranberg, do you mind submitting a bug report about this through Visual Studio?
![3](https://user-images.githubusercontent.com/34664007/110420191-713d7180-8060-11eb-9d91-33acf33b6879.png)

**Comment by cmeeren** [comment]
IIRC we will likely also get into a problem where `4.0.0-beta-1` -> `4.0.0-beta-10` -> `4.0.0-beta-2`.

**Comment by BentTranberg** [comment]
I reported it through Visual Studio / Report a Problem. That's a really lousy system where I never get to see my issues except for a few of them at random whenever I report a new issue. So I took a screenshot before I pressed the send button.

![image](https://user-images.githubusercontent.com/15068882/110443920-bc856d80-80bc-11eb-95fe-b953f9efd31e.png)

**Comment by TysonMN** [comment]
Maybe we could use `4.0.0-beta-010`

**Comment by cmeeren** [comment]
That gives `4.0.0-beta-010` -> `4.0.0-beta-1` -> ...

I see these options:
* Release 4.0.0 final before we hit `beta-10`
* Since we're currently at `4.0.0-beta-3`, make the next version `4.0.0-beta-40`, and then we can do `41`, `42`, etc. (Or use three digits if there's a chance we'll hit `99`, but I doubt it).
* Do something funky like `4.0.0-gamma-01` (not a fan)

**Comment by TysonMN** [comment]
I like `4.0.0-beta-40`

**Comment by cmeeren** [comment]
Yep, seems the lesser evil.

**Comment by BentTranberg** [comment]
Darn, I should have linked to this issue in the report I sent, but I added a comment there now, with a link to this issue. Not that it's terribly important, but always nice to let them know we're here.

**Comment by TysonMN** [comment]
Here is a link to that VSDC issue
https://developercommunity.visualstudio.com/t/Visual-Studio-Package-Manager-dont-agre/1362486

**Comment by TysonMN** [comment]
Hopefully this bug gets fixed. Feel free to continue the discussion here if there is anything else add.

**Comment by BentTranberg** [comment]
The VSDC issue I created has been closed as a duplicate, and the first reported has been closed because it has been fixed I assume, since it links to a fix. There is some milestone information that makes me wonder why we don't already have the fix. Or maybe I do, in the VS I downloaded earlier this week.

**Comment by BentTranberg** [comment]
Ah! So that's what I almost remembered ... #82  _Déjà vu_

**Comment by TysonMN** [comment]
That's funny.

Glad we are getting a fix soon.

**Comment by BentTranberg** [comment]
Long time no see. I'm not sure where we ended on this, but I fell into the trap again. Still not fixed in VS 16.9.3. Just for the record, no action needed here. This is what the list looks like now, in a new solution.

![image](https://user-images.githubusercontent.com/15068882/114153538-b1be3280-991f-11eb-85c0-8fc83f3265f8.png)

**Comment by TysonMN** [comment]
> I'm not sure where we ended on this...

Just waiting for the bug fix to make it way downstream.  I just asked when we can expect to see it in https://github.com/NuGet/Home/issues/10532#issuecomment-816767394.
