### ISSUE TITLE
Question: Can Elmish.WPF be used from a C# project, without F#?

### ISSUE THREAD

**Issue by ngbrown** [elmish/Elmish.WPF#372]
Sorry if this was mentioned somewhere, I didn't find it. I've used a lot of React and C#, so am familiar with them. Recently C# has added records.

So, if I want a MVU framework for WPF, Elmish.WPF seems to be the main way. [Comet](https://github.com/dotnet/Comet) is written in C# but is focusing on dynamic view construction. This project has indicated that there are problems with dynamic WPF and with the static views, is already production ready.

All the C# code in this repository's samples seems to be just the views and there are no C# code samples in the Elmish repository.

Can one use this as a .NET library and do everything in C#? What would the experience be like?

**Comment by TysonMN** [comment]
I think the main difficulty would be that the API of Elmish.WPF includes many types specific to F# such as curried (F#) functions and `Option<_>`.

In general, I think the worst thing about C# is its lack of a sum type (what F# calls a discriminated union).  This would be especially painful when using C# to create an MVU application.

This library is indeed production ready.  I am using it in my application at work.  I can tell how dynamic views would be better, but I don't know how to make that work, and static views are only a small compromise.  Most of the benefits of the full MVU architecture remain.

Do you have the option to use F#?

**Comment by ngbrown** [comment]
Concept wise, it would be very doable, but when trying to convert the `SingleCounter.Core` sample, I ran into `FSharpFunc` <=> `Func` and `FSharpList` <=> `List` (or `ImmutableList` if you prefer) interrop issues. And finally the C# compiler couldn't find the extension methods to make `Binding.cmd` work.

Initially, I was looking at the decompiled version:
```cs
// DotPeek decompiles it something like this:
// Extensions.Binding.cmd.Static<Msg, Model>(new Msg.Increment()).Invoke("Increment");
Extensions.Binding.cmd.Static<Msg, Model>(new Msg.Increment()),
//         ^ error CS0117: 'Extensions' does not contain a definition for 'Binding'
```

But got almost entirely working without using the message discriminator tags. It's probably less efficient though.

```cs
using System;
using System.Windows;
using Microsoft.FSharp.Collections;
using Microsoft.FSharp.Core;
using Serilog;
using Serilog.Events;
using Serilog.Extensions.Logging;

namespace Elmish.WPF.Samples.SingleCounter
{
  public static class Program
  {
    public record Model
    {
      public int Count { get; init; }
      public int StepSize { get; init; }
    }

    public static Model Init => new() {Count = 0, StepSize = 1};

    public record Msg
    {
      public record Increment() : Msg;
      public record Decrement() : Msg;
      public record SetStepSize(int StepSize) : Msg;
      public record Reset() : Msg;
    }

    public static bool CanReset(Model m) => !Init.Equals(m);

    public static Model Update(Msg msg, Model m)
    {
      return msg switch
      {
        Msg.Increment => m with {Count = m.Count + m.StepSize},
        Msg.Decrement => m with {Count = m.Count - m.StepSize},
        Msg.SetStepSize setStepSize => m with {StepSize = setStepSize.StepSize},
        Msg.Reset => Init,
        _ => throw new ArgumentOutOfRangeException(nameof(msg), msg, "Unhandled message")
      };
    }

    public static FSharpList<Binding<Model, Msg>> Bindings() =>
      ListModule.OfArray(
        new []
        {
          Binding.oneWay<Model, int, Msg>(FuncConvert.FromFunc((Model m) => m.Count)).Invoke("CounterValue"),
          Binding.cmd(FuncConvert.FromFunc<Model, Msg>(m => new Msg.Increment())).Invoke("Increment"),
          Binding.cmd(FuncConvert.FromFunc<Model, Msg>(m => new Msg.Decrement())).Invoke("Decrement"),
          Binding.twoWay(
            FuncConvert.FromFunc<Model, float>(m => (float) m.StepSize),
            FuncConvert.FromFunc<float, Model, Msg>((v, _) => new Msg.SetStepSize((int) v))
            // TODO: set is never called, so message not sent
          ).Invoke("StepSize"),
          Binding.cmdIf(
            FuncConvert.FromFunc<Model, Msg>(m => new Msg.Reset()),
            FuncConvert.FromFunc<Model, bool>(CanReset)
          ).Invoke("Reset"),
        }
      );

    public static readonly object DesignVm = ViewModel.designInstance(Init, Bindings());

    public static void Main(FrameworkElement window)
    {
      var logger =
        new LoggerConfiguration()
          .MinimumLevel.Override("Elmish.WPF.Update", LogEventLevel.Verbose)
          .MinimumLevel.Override("Elmish.WPF.Bindings", LogEventLevel.Verbose)
          .MinimumLevel.Override("Elmish.WPF.Performance", LogEventLevel.Verbose)
          .WriteTo.Console()
          .CreateLogger();

      WpfProgram.startElmishLoop(window,
        WpfProgram.withLogger(new SerilogLoggerFactory(logger),
          WpfProgram.mkSimple(FuncConvert.FromFunc(() => Init),
            FuncConvert.FromFunc<Msg, Model, Model>(Update),
            FuncConvert.FromFunc(Bindings))));
    }
  }
}
```

I couldn't get the `Binding.twoWay` to work in the set direction though. The function was simply not called.

As far as using F#, I would like to re-use a lot of existing C# code. I would also have to learn F# while I'm already very familiar with C#. No-one else on the team knows F# either.

These interop issues don't seem very convenient either.

**Comment by TysonMN** [comment]
> As far as using F#, I would like to re-use a lot of existing C# code.

What does that C# code do?

**Comment by TysonMN** [comment]
Hopefully interoperability with C# will be better when version 4 is done.

**Comment by TysonMN** [comment]
Choosing due to inactivity. Feel free to reopen.
