### ISSUE TITLE
Error with text in TextBox marked like UpdateSourceTrigger=PropertyChanged

### ISSUE THREAD

**Issue by eu-genes** [elmish/Elmish.WPF#373]
Hi, new day and new strange bug with `4.0.0-beta-40`:

Run SubModelOpt sample, open Form2, input text to TextBox and result text will be written from right to left

![textbox](https://user-images.githubusercontent.com/1961507/110834002-b69eb080-82a5-11eb-8827-b2301205ab8d.gif)

**Comment by TysonMN** [comment]
lol

**Comment by TysonMN** [comment]
Thanks again for reporting another issue @eu-genes.

PR #374 fixes this bug.  Once it is reviewed and completed, I will create a new release.

**Comment by TysonMN** [comment]
Fixed in [4.0.0-beta-41](https://www.nuget.org/packages/Elmish.WPF/4.0.0-beta-41).
