### ISSUE TITLE
App became really slow after migrating to v3.5.7

### ISSUE THREAD

**Issue by Evangelink** [elmish/Elmish.WPF#376]
I have tried to upgrade from `Elmish.WPF` v`3.5.6` to `3.5.7` and I have noticed that most of the actions that used to be instant are now having lag and this lag seems to accumulate over time.

I haven't seen much difference in memory consumption nor in CPU so I am a bit clueless on what else I could provide to help you understanding the issue.

**Comment by Evangelink** [comment]
Just did a quick test and it seems that the problem is not present on `4.0.0-beta-41`.

**Comment by TysonMN** [comment]
It could be `ViewModel<_,_>.ToString` that I added.  Someone else reported it being slow in #370 and I removed it in `4.0.0-beta-40`.

(I didn't realize that overriding `object.ToString` would decrease performance.)

**Comment by Evangelink** [comment]
Interesting, I will try to get the repo at the `3.5.7` release and just remove the `ToString` method to see if that solves the issue.
