### ISSUE TITLE
How to correctly append two lists when working with subModels?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#385]
Lets say I have the following definitions:

```
 type Model =
       {  NewPrescriptions: Rx list                 
          CurrentPrescriptions: Rx list   }

```

```
 let bindings () : Binding<Model, Msg> list = [

"CurrentPrescriptions" |> Binding.subModelSeq(
               ( fun m -> m.CurrentPrescriptions),
               ( fun e -> e.Id),
               ( fun () -> [
                           "TRx"     |> Binding.oneWay (fun (_,e) -> e.TRx)      
                           "Medname" |> Binding.oneWay (fun (_,e) -> e.Medname)     
               ]))

           "SelectedCurrentPrescription" |> Binding.subModelSelectedItem("CurrentPrescriptions", (fun m -> m.SelectedCurrentPrescription), SelectedCurrentPrescriptionMsg)

           "NewPrescriptions" |> Binding.subModelSeq(
              ( fun m -> m.NewPrescriptions),
              ( fun e -> e.Id),
              ( fun () -> [
                          "TRx"     |> Binding.oneWay (fun (_,e) -> e.TRx)      
                          "Medname" |> Binding.oneWay (fun (_,e) -> e.Medname)     
              ]))

           "SelectedNewPrescription" |> Binding.subModelSelectedItem("NewPrescriptions", (fun m -> m.SelectedNewPrescription), SelectedNewPrescriptionMsg) 
]
```
Where each subModel is the DataContext for a list in the XAML.  What is the method to correctly add both lists together and replace an existing list (and have the user interface be updated) ? 

That is,  doing this results in the XAML losing its connection to the submodels:

`{ m with NewPrescriptions = List.append m.NewPrescriptions m.CurrentPrescriptions}`

Thank you for any help in this matter.

**Comment by TysonMN** [comment]
> What is the method to correctly add both lists together and replace an existing list (and have the user interface be updated) ?

Does the code that you shared...
```fsharp
{ m with NewPrescriptions = List.append m.NewPrescriptions m.CurrentPrescriptions
```

...not work?

Can you share a repo with you best attempt to achieve your desired behavior?

**Comment by awaynemd** [comment]
@TysonMN The code seems to work on the Elmish.wpf side of things, but the XAML bound to NewPrescriptions never gets updated.  (Not real sure how to send you a repo as the project has grown very large). Thanks.

**Comment by TysonMN** [comment]
> Not real sure how to send you a repo as the project has grown very large

Create a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) and put that in a repo.

**Comment by awaynemd** [comment]
@TysonMN (Easier said then done). What is really strange is that I have this exact same setup on another tabitem in the XAML that works perfectly with another DataContext and this one works perfectly as long as the "NewPrescriptions" list is empty before the append. Strange.

**Comment by awaynemd** [comment]
@TysonMN After some further research, the problem may be in the xaml tabcontrol itself (not Elmish.wpf)--I'm still looking into this. Can I assume that the viewmodels generated internally by Elmish.wpf implement INotifyPropertyChanged with lists in an ObservableCollection? Thanks.

**Comment by awaynemd** [comment]
@TysonMN Got it -- but I have no idea why. Any appending to the list being updated will fail. That is,
{ m with NewPrescriptions = f(NewPrescriptions) } 
will fail if NewPrescriptions is being replaced by records with the same Id's.  However, if a copy of the NewPrescripitions is made with new Id's, then all works as above.  Any idea why?

**Comment by TysonMN** [comment]
> > > Not real sure how to send you a repo as the project has grown very large
> > 
> > Create a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) and put that in a repo.
> 
> Easier said then done

I agree, but I find that it is often necessary.  When these extremely perplexing issues arise, it is my experience every detail matters.

> Got it -- but I have no idea why. [...] Any idea why?

No.  I think I would need a minimal working example.

Glad to hear that you fixed your problem though.

**Comment by awaynemd** [comment]
@TysonMN Last thoughts. (I haven't studied the Elmish code--yet). After some sleep, it seems I'm getting the following behavior with this submodel application. 

The statement 

`{ m with NewPrescriptions = f(NewPrescriptions) }`

performs as an _update_ to existing items in NewPrescriptions. As long as the replacement objects in f(NewPrescriptions) use _any_ of the already existing objects in NewPrescriptions (as given by the Id's), the  _original_ viewmodel/submodel will be _kept_ (with the existing objects probably being updated)--but is NOT adding any new items.

Only when there is no longer any existing objects from the original NewPrescriptions in use will the original viewmodel --i.e., the submodel --of NewPrescriptions be rebuilt with the new objects.

Am I close?

So the question is, how do I add a new object to the existing NewPrescription viewmodel/submodel?

Thanks for any help or insight on this!

**Comment by TysonMN** [comment]
> Am I close?

Close to what?

> The statement
> 
> `{ m with NewPrescriptions = f(NewPrescriptions) }`
> 
> performs as an _update_ to existing items in NewPrescriptions. As long as the replacement objects in f(NewPrescriptions) use _any_ of the already existing objects in NewPrescriptions (as given by the Id's), the _original_ viewmodel/submodel will be _kept_ (with the existing objects probably being updated)--but is NOT adding any new items.
> 
> Only when there is no longer any existing objects from the original NewPrescriptions in use will the original viewmodel --i.e., the submodel --of NewPrescriptions be rebuilt with the new objects.

If what you say is true and if I understand you correctly, then this would be a serious bug.  However, I don't see how both of those can be true.  I have copious [tests ensuring that merge is working correctly](https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF.Tests/MergeTests.fs); I can't reproduce this behavior in any of the samples;  I can't reproduce this behavior in my application at work; and I can't see any bug when I statically analyze the code.

I think you severely underestimate how valuable a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) is.  Don't just read that Wikipedia article; also read all four of the references.

I don't see how I can make any progress on this issue without a minimal working example.  On the other hand, if you provide a minimal working example, then I will absolutely get to the bottom of this issue.

**Comment by awaynemd** [comment]
@TysonMN Thanks. I will study the tests. On a _very quick glance_, however, it seems that the tests are generating _new_ id's, within the test. This is exactly as I have found to be necessary in building the NewPrescription list :)  Thanks.

**Comment by TysonMN** [comment]
> [...] it seems that the tests are generating _new_ id's, within the test.

Some tests do and some tests don't.  Look at all the tests with "call update exactly once" in their name.

And this test ensures that adding an items works.
https://github.com/elmish/Elmish.WPF/blob/21c98b43700bfc5a1e3d71a755b461be6cddcdbb/src/Elmish.WPF.Tests/MergeTests.fs#L78

> I will study the tests.

A better use of your time is to create a minimal working example.  I am unsure how to more strongly convey this.

**Comment by awaynemd** [comment]
@TysonMN     I agree; but I'm under a hard deadline. For what its worth, I'm adding a list to a list, not an item to a list. That maybe the difference. I don't know. :)

**Comment by TysonMN** [comment]
> “Dress me slowly, I'm in a hurry.”

**Comment by TysonMN** [comment]
> I changed my procedure to only add ONE item at a time (not an entire list at once), _and all works correctly as expected :)_

I just modified the `OneWaySeq` sample to double the size of the list with each button click.  The behavior is as expected.

A MWE will tell us what is really going happening.
