### ISSUE TITLE
Failure to get multiple window example from Elmish.WPF to  work correctly

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#388]
As stated in the previous issue of getting a checkbox to work correctly, the bigger issue is my inability/ignorance/dumbness of getting the Example of multiple windows to run correctly. I keep getting a null reference on window 2. 

Please see this github repro -- it will run until it crashes. 

https://github.com/awaynemd/My-CheckBox

Any help is most appreciated.

Thanks.

**Comment by TysonMN** [comment]
I will take a look next week.

**Comment by TysonMN** [comment]
Quoting parts of #387
> This is a close copy of the "NewWindows" sample in Elmish.WPF. I made very few changes to the original sample of NewWindows as I could NOT get even the sample (as I have it) to run.....
> [...]
> Remember, this is essentially just the multiple window example from the Elmish.WPF repository.

Not close enough ;)

Remove [this occurrence of `<OutputType>Exe</OutputType>`](https://github.com/awaynemd/My-CheckBox/blob/86d4a8854d7e34f7cf04a5ebecff6df5e71ab798/CheckBox/CheckBox.fsproj#L4) or change `Exe` to `Library`.

You would have been more likely to be able to solve your own problem if the warning proposed in https://github.com/dotnet/fsharp/issues/1371 already existed.
