### ISSUE TITLE
Discussion on Integrating ElmishWPFLearning project to Elmish.WPF

### ISSUE THREAD

**Issue by Lleutch** [elmish/Elmish.WPF#39]
I have been working on a project called ElmishWPFLearning, which purpose is to learn more about MVU paradigm, and how it can be applied to WPF, by doing the implementation of everything from scratch.

The current implementation can be simplified to be as followed : 
- An opinionated DSL on top of the WPF API, where I have selected a subset of the WPF Elements accessible that I thought were enough to have something nice working, to handle the View, so that means we have dynamic views.
The way you define a WPF Element is with 4 criteria : 
     - what it is. For instance a button, a textbox ...
     - the information specific that it tries to relay. For instance it's content, if the checkbox is checked or not ...
     - It's style. For instance, it's background is blue ...
     - The events related to user interactions. For instance, the clicked event, when the user has clicked on a button... (To also know the handling of events is a bit particular in that DSL, you can ask me more about them if that interest you)
- A treediff algorithm which finds a set of difference to be applied to the old tree in order to update the UI to represent the new view. It is not the minimal set of difference, because if that was the case, then in fact, I would argue that finding that minimal set of difference would take much longer than applying those difference (might not be true in the case that we have to do big layout change, as the UI might take time rendering those updates. I haven't came across that situation yet, with my tree diff algorithm.)
- 2 mailboxprocessors, (1 handling the whole loop and switching the UI thread only for updating the UI with the updates. The other 1 handling the different subscriptions.)
- A "virtualDom" for handling the WPF tree, with virtual events, virtual properties, default values in case we don't set a property any longer...

There are things I have forgotten, but if you have any question about anything do not hesitate to ask!!

I have to add 1 thing, there are problems that I haven't handled yet but I wanted to handle in the near future, and I have an idea on how to do that, or at least I think it should be feasible: 
- 3rd party control (but we lose low-level tree diff granularity, if I want to do it in a simple manner)
- something I call EtVL(Event trigger View Loop, or call it the way you want it, I am trying to be fancy with the name here 😄 ), which consist in updating the UI without going through the whole MVU loop, when you only do something, on the UI, that doesn't impact your model. For instance, when you hover over a button and you want to update the button style, without updating the model...

Finaly, bear in mind the implementation is not perfect at all, there is a lot of small, just started, projects, next to the project called **Elmish**, which are just small experiment on either implementing a small library on top of the DSL (Algae,ElmishStyle), or small exemples of the usage of the library (simpleApplication,SoundProcessing).

After a proposal from @et1975 to possibly contribute with that work, I came here to engage a discussion to see if my approach on the problem fits Elmish.WPF approach, or if it is not the case and we should think about something else. So I hope we can start the discussion on that 😄 .

Thank you everyone.

**Comment by Lleutch** [comment]
@et1975 So, I have looked a bit at Elmish.WPF, and how the message loop is implemented, and it turns out that it needs some things to support the DSL + tree diff thingy. 
https://github.com/Lleutch/ElmishWPFLearning/blob/master/Elmish/ElmishProgram.fs#L157 
As you can see in that piece of code I need to have the previous Virtual tree and the newly generated virtual tree, and find the diff to then apply on the UI thread.
So is it something that will need to be implemented in Elmish.WPF? or is it already there and I am probably not aware of it? Or I should find a way to handle that with the current state of Elmish.WPF?

Otherwise, I am ok with creating a separate lib, but also be aware I have implemented it WPF dependant. Should that DSL + tree diff be implemented in a platform independent way ? this might not be possible, but I have had the chance to think about that.

**Comment by et1975** [comment]
I see what you mean, the custom dispatch loop replaces Elmish's implementation here and the current version doesn't provide for `setState`. It's solvable, I think, but I'm starting to doubt if "static" and "dynamic"  approaches are in fact complementary. I'd still be interested in establishing elmish as the core dependency for both and seeing what needs to be modified to support that. @2sComplement any thoughts?

**Comment by 2sComplement** [comment]
@Lleutch thank you for starting this discussion.
Both static/dynamic approaches have benefits, but I also do not see them as complementary. One requirement of dynamic views in my mind is having the ability to integrate with third party libraries through generated code or (even better) a type provider. Keeping elmish as the core dependency is a good idea, since that would enable easy ports to other platforms while keeping model/update code the same.

**Comment by et1975** [comment]
So, how is this: @Lleutch  when you are ready feel free to create a repo in the elmish org (I sent you the invite) for the work to implement "dynamic" WPF views, and we'll go from there? Note that the Elmish nuget targeting non-fable platforms is already available to take as a dependency.

**Comment by Lleutch** [comment]
Sorry for the late reply, quite busy week.
So yes I will do that. I will probably start from this Friday hopefully (maybe a bit before...), and I'll start from scratch, such that people can follow the flow, and jump on it easily if they want to :smiley: 
By the way, I might ask you guys some question during the work if that's ok with you ?
I will open tickets there with the different questions that I am wondering (from the experiment project!).
Such that we do not forgot about those questions during the design/implementation of the DSL.
In any case, thank you guys for the discussion, really appreciate it :smiley:
