### ISSUE TITLE
Any examples using Elmish.WPF with dragAndDrop?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#390]
Hi All:

I have the setup where my views (wpf/xaml) are in C# with (almost) no code-behind. The backend support is Elmish.wpf. 

Does anybody have a working example of how to implement DragAndDrop?

Thanks.

**Comment by TysonMN** [comment]
None of our samples include drag and drop.  I just read a bit, and it seems easy enough.  If you share a simple example of drag and drop working without Elmish.WPF, then I will change it to use Elmish.WPF.

**Comment by awaynemd** [comment]
@TysonMN 

Please see: https://github.com/awaynemd/DragAndDrop

The listbox should be filled with the available printer ques when the Refresh button is pressed. Once filled, the goal is to drag a printer (i.e., listboxitem) to the grid and display it in a textblock.  It works when the printers class is defined in C#. Here it fails when Printer is in F#.

P.S. This setup has some additional problems:
1. Closing the window leaves you with console window. It would be nice if closing the window also terminated the console window.

P.S.S If you can think of a better way to get the printer queues , I'd sure be interested. :)

Thanks.

**Comment by TysonMN** [comment]
> It works when the printers class is defined in C#. Here it fails when Printer is in F#.

Can you also share this C# version?  I also want to see it working.

**Comment by awaynemd** [comment]
@TysonMN Yes --

Please see:  https://github.com/awaynemd/DragAndDropV2

Hope it helps. (Drag from the printer list to the grid).

**Comment by awaynemd** [comment]
@TysonMN Got it to work!  (But I'd sure be interested to see how someone who knows what there doing accomplishes this!).

Following the suggestions of @FoggyFinder and @cmeeren on a previous post, I made a few changes:
1. In the XAML, changed the grid display to use a ContentControl instead of textblock for the drop target, 
2. Changed the code behind to:
      ```
            private void listBox1_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            object item = listBox1.SelectedItem;

            if ( item is Printer  printer)
            {
                DataObject _data = new DataObject("PRINTER", printer);
                DragDrop.DoDragDrop(listBox1, _data, DragDropEffects.Copy);
            }
        }

        private void grid1_Drop(object sender, RoutedEventArgs e)
        {
            ContentControl cc = e.Source as ContentControl;
            DataObject item = (((DragEventArgs)e).Data) as DataObject;
            var printer = item.GetData("PRINTER") as Printer;
            cc.Content = printer;
        }
```
3. Moved the definition of "Printer" to a separate project to which both the C# project and the main F# project could reference. This to avoid a circular dependency between the F# project and the C# visuals.

It now works as expected!

Any suggestions ?

**Comment by TysonMN** [comment]
> Any suggestions ?

Yes. Instead of only describing your changes in prose, please also provide a link to a simple example of your working solution.
