### ISSUE TITLE
Is there a way to pass both the EventArgs and a Parameter to Elmish.wpf?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#392]
In my xaml code, I have:

```
<ContentControl AllowDrop="True" ContentTemplate="{StaticResource Printer2}" Content="{Binding PrescriptionPrinter}" >
                    <i:Interaction.Triggers>
                        <i:EventTrigger EventName="Drop">
                            <i:InvokeCommandAction PassEventArgsToCommand="True" Command="{Binding DropEventForPrescriptionPrinter}" CommandParameter="PrescriptionPrinter"/>
                        </i:EventTrigger>
                    </i:Interaction.Triggers>
                </ContentControl>
```

With the corresponding binding of:

` "DropEventForPrescriptionPrinter" |> Binding.cmdParam handleDropEventForPrescriptionPrinter`

Where,

```
  let handleDropEventForPrescriptionPrinter (obj: obj)  =
     let e = (obj :?> DragEventArgs)
     let item = e.Data :?> DataObject
     let printer = item.GetData("PRINTER") :?> Printer

     e.Handled <- true
     SetPrescriptionPrinter (Some printer)
```

This works correctly until a CommandParameter is added to the InvokeCommandAction as which time the "obj" resolves to a string (not the DragEventArgs).  

How is a CommandParameter sent with the DragEventArgs?  (The documentation seems a bit thin for this novice).

Thanks.

**Comment by TysonMN** [comment]
Is it possible to do this without using Elmish.WPF?

**Comment by awaynemd** [comment]
@TysonMN Yes :) The  RelayCommand<T> in C# can. 

Thanks.

**Comment by TysonMN** [comment]
Can you share a minimal working example of this in action?

**Comment by TysonMN** [comment]
Choosing due to inactivity. Feel free to reopen.
