### ISSUE TITLE
How to update the WPF GUI without blocking using a background Async process?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#394]
(I've also posted this on SO).  

In the following project, I have attempted to create a spinning list that "should" start spinning when the "Refresh" button is clicked and stop spinning when the background procedure has finished updating the spinning list. The goal is to keep the list spinning while the long procedure is working.

I have failed :(.   I do not understand how to get the "printers" once discovered to update the list without a context violation.

Any help would be most appreciated.  Thanks.

Please see:  https://github.com/awaynemd/AsyncAndElmish

**Comment by TysonMN** [comment]
> I've also posted this on SO

 Link?

**Comment by awaynemd** [comment]
Great! Thank you. The Solution as posted on SO works well.  Thanks.

**Comment by TysonMN** [comment]
> The Solution as posted on SO works well.

Link?

**Comment by awaynemd** [comment]
@TysonMN Hmmm.... Examination of the above code does show that it does not crash; However, studying the thread Id's shows that all computations are staying on the main thread ( printfn "%i" Thread.CurrentThread.ManagedThreadId ) -- which is why it is not crashing, but freezes up just before publishing the new printers. :(. So, how do I run the Async on a separate thread? Thanks.

**Comment by awaynemd** [comment]
@TysonMN I made a few changes. The printers are now being read on a separate thread. What do you think?

```
| GetPrintersMsg ->
    let getPrinters () = async {
        printfn "1: %i" Thread.CurrentThread.ManagedThreadId  

        let getprinters = async {
            printfn "11: %i" Thread.CurrentThread.ManagedThreadId  
            use ps = new PrintServer()
            return
                ps.GetPrintQueues [| EnumeratedPrintQueueTypes.Local; EnumeratedPrintQueueTypes.Connections |]
                |> Seq.cast<PrintQueue>
                |> Seq.toList
                |> List.map (fun pq ->
                    {
                        Id = Guid.NewGuid()
                        fullname = pq.FullName
                        comment = pq.Comment
                        defaultPrintTicket = Some pq.DefaultPrintTicket
                        description = pq.Description
                        isInError = pq.IsInError
                        isOffline = pq.IsOffline
                    }) }
        let! d = getprinters |> Async.StartChild
        return! d
        }
    m, Cmd.OfAsync.either getPrinters () OnPrintersResult OnPrintersError
```

**Comment by TysonMN** [comment]
> What do you think?

I think you should share the link to the cross posted question on SO.

**Comment by awaynemd** [comment]
@TysonMN Huh? Sorry for my stupidity, please explain "cross posted question" ?  I did post my changes on SO--is that what you mean?

**Comment by TysonMN** [comment]
Yes, I will explain more after you share the link to the version of your question on SO.

**Comment by awaynemd** [comment]
@TysonMN Is this what you mean:

https://stackoverflow.com/questions/67711311/how-to-update-the-wpf-gui-from-non-blocking-async-methods-in-f

**Comment by TysonMN** [comment]
> Is this what you mean [...]

Yes.  What else did you think I could have meant?

**Comment by Evangelink** [comment]
I have noticed that `Cmd.ofAsync.XXX` functions are not run on different threads so I have defined the following helpers:

```fsharp
[<RequireQualifiedAccess>]
module Dispatch =
    let funcOnMainThread (f: 'T1 -> 'T2) (arg: 'T1) =
        Application.Current.Dispatcher.Invoke (fun () ->
            let guiCtx = Threading.SynchronizationContext.Current

            async {
                do! Async.SwitchToContext guiCtx
                return f arg
            })

    let funcOnThreadPool (f: 'T1 -> 'T2) (arg: 'T1) =
        Application.Current.Dispatcher.Invoke (fun () ->
            async {
                do! Async.SwitchToThreadPool()
                return f arg
            })

    let asyncOnThreadPool (a: Async<'a>) : Async<'a> =
        Application.Current.Dispatcher.Invoke (fun () ->
            async {
                do! Async.SwitchToThreadPool()
                return! a
            })
```

**Comment by Evangelink** [comment]
@TysonMN This thread makes me wonder a couple of things:

1. Maybe some of the helpers should be part of the framework (signature could be different, and maybe they should be part of the `Cmd.XXX` modules).

2. How many people are using `Cmd.ofAsync` with the expectation to have things run in the same thread. Maybe it would feel more natural to have a thread switch by default.

**Comment by TysonMN** [comment]
Yes, I know what you mean.  I found it rather awkward and error prone to get this right.

Let `f : unit -> Async<unit>`.be a function that "actually" executes asynchronously.  Then composing with
```fsharp
let inThreadPool ma = async {
  do! Async.SwitchToThreadPool ()
  return! ma
}
```
gets the job done (i.e. `f >> inThreadPool` will execute asynchronously on a background thread).

Now let `f' : unit -> unit` and
```fsharp
let success a =
  async { return a }
```
Then `g = f' >> success` has the same signature as `f` but `g >> inThreadPool` still executes synchronously on the UI thread because `g` is not "actually" asynchronous.

I execute a synchronous function on a background thread by composing
```fsharp
let fromFunc f a =
  async { return f a }
```
with `inThreadPool` (i.e. `f' |> fromFunc >> inTheadpool`).  I put all of these functions in in a module named `Async` so this final code actually likes like `f' |> Async.fromFunc >> Async.inTheadpool`.
