### ISSUE TITLE
Model returned from update different from model received in next update

### ISSUE THREAD

**Issue by Evangelink** [elmish/Elmish.WPF#396]
Hi!

I am experimenting an absolutely weird and total nonsense error on my production code. In one of my messages, I return an updated model (`update`) function and the model passed to the next call to the `update` is different from the one returned previously. Data is F# immutable record so it's pretty sure it's not another thread mutating some data.

Could you think of anything that would cause such scenario?

I have a repeatable case but I haven't been able to create a repro I could share here. I am absolutely fine to debug Elmish.WPF and give you results or do some screen-share with you if it may help. 

EDIT:
Problem is with `Elmish.WPF` version `3.5.8` and is still present in `4.0.0-beta-41`.

**Comment by TysonMN** [comment]
I think this could happen if your call to update is returning a `Cmd<'msg>` and it throws an exception when executed.  I created [this issue](https://github.com/elmish/elmish/issues/186) about that problem.  It was eventually fixed, but I don't recall now or can easily see if the fix exists in some release.

An easy way to check if an exception is being thrown is to subscribe to [`FirstChanceException`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.firstchanceexception).

If this is your issue, then [Elmish would let the `onError` handler know](https://github.com/elmish/elmish/blob/ae20c1e1ac14fa16b8b66d31a728fbc63a5077b5/src/program.fs#L153), so also provide one of those handlers.

**Comment by Evangelink** [comment]
Thank you for the pointer! 

Using `FirstChanceException` I do see a `An item with the same key has already been added.` exception being thrown but it does not seem to be cause by a `Cmd<'msg>` as I have removed all `CmdMsg` in this path. Doing multiple F10, it seems that somethings happen either during one of the binding evaluation or in the elmish part itself.

**Comment by TysonMN** [comment]
> I return an updated model (`update`) function and the model passed to the next call to the `update` is different from the one returned previously.

So a call to `update` is given a model `m1` and returns a model `m2`.  Then the next call to `update` is given some model `m3` such that `m2 <> m3`.

Is `m1 = m3`?  That seems most likely to me (and would be the case it the execution of some `Cmd<_>` where throwing an exception while using a version of Elmish that doesn't include that fix).

**Comment by TysonMN** [comment]
Also, try reproducing the problem without any exceptions being thrown.

**Comment by Evangelink** [comment]
> Is `m1 = m3`? That seems most likely to me (and would be the case it the execution of some `Cmd<_>` where throwing an exception while using a version of Elmish that doesn't include that fix).

Yes that's the case! As I said, when reaching the point after which we will have the exception, I have made sure to return an empty list of `CmdMsg` so no `Cmd<_>` should be executed and the issue still happens.

Looking at `External Code` in the stack trace, it seems that the duplicate key exception is thrown in `ViewModel.fs` either in the call to `recordRemoval` or `recordAddition` (see screenshot below)

![image](https://user-images.githubusercontent.com/11340282/124886330-6a097e80-dfd4-11eb-8108-bbdffc0a9913.png)


> Also, try reproducing the problem without any exceptions being thrown.

The app is working properly for all files we work with except for one particular file in which we were seeing a state not changing and the debug is showing this weird behavior.

**Comment by Evangelink** [comment]
That might not be related but I have also seen an exception in `GetErrors` of `INotifyDataErrorInfo` https://github.com/elmish/Elmish.WPF/blob/7abde5cbd97c3f71e015306ce716c2e4f2572a9f/src/Elmish.WPF/ViewModel.fs#L824-L828

when `propName` is `null`. You are handling the case for the `log` but not for the `match`.

**Comment by Evangelink** [comment]
I have made a small tweak in the library and I can confirm that the issue comes from `recordAddition`:

![image](https://user-images.githubusercontent.com/11340282/124889858-c752ff00-dfd7-11eb-8dcf-f7097141e2e9.png)

Hope this will give you some idea.

**Comment by TysonMN** [comment]
Good find.  Yes, an exception thrown from Elmish.WPF like this has the same effect as a exception thrown from executing a command (when using a version of Elmish that doesn't include the fix).   In both cases, the model returned from `update` is not saved.

I will think about what charge to make. At the very least, I will add logging here.  It might be that throwing an exception is the correct behavior (though the message could be better).

On your end, you should not have items in a `SubModelSeq` binding with duplicate IDs.

The exception thrown from `GetErrors` is not as serious. It just prevents WPF from knowing about model-level errors, which Elmish.WPF doesn't support anyway.  Also, that log statement was getting called too much, so I removed it.

**Comment by Evangelink** [comment]
I guess now I need to play find the duplicated ID game :)

Thank you so much for your help!

**Comment by TysonMN** [comment]
> If this is your issue, then [Elmish would let the `onError` handler know](https://github.com/elmish/elmish/blob/ae20c1e1ac14fa16b8b66d31a728fbc63a5077b5/src/program.fs#L153), so also provide one of those handlers.

Are you providing an error handler to Elmish?  This is a great way to be alerted to potential problems.

**Comment by Evangelink** [comment]
I don't but I will give it a go.

So far I have only handled:

```fsharp
AppDomain.CurrentDomain.UnhandledException
|> Event.add onAppDomainUnhandledException

Application.Current.DispatcherUnhandledException
|> Event.add onAppDispatcherUnhandledException

Application.Current.Dispatcher.UnhandledExceptionFilter
|> Event.add onAppFilterDispatcherException

TaskScheduler.UnobservedTaskException
|> Event.add onTaskSchedulerUnobservedTaskException
```

**Comment by TysonMN** [comment]
For version 3.x of Elmish.WPF, add `|> Program.withErrorHandler onError` to the construction of your Elmish/Elmish.WPF program.

**Comment by Evangelink** [comment]
I have managed to get over the issue. For some cases, I had a duplicated time (acting as a key) for some items in my timeline.

Maybe we could update the code to throw a specific exception telling the user to check the ids of the `subModelSeq` bindings.

**Comment by TysonMN** [comment]
> Maybe we could update the code to throw a specific exception telling the user to check the ids of the `subModelSeq` bindings.

Indeed.  That is what I meant by this.

> I will think about what change to make. At the very least, I will add logging here. It might be that throwing an exception is the correct behavior (though the message could be better).

**Comment by Evangelink** [comment]
I probably won't bring much value but if you want me to help there, let me know.

**Comment by TysonMN** [comment]
Here are a couple ways you can help.
1. How were you rearranging the elements in your list?  I am curious to know of a "real" use-case that is a contributing factor to this issue.  Of course the main issue is duplicate IDs, but it is possible to have duplicate IDs without triggering this issue.
2. Can you still reproduce this issue?  If so, then you can test when I provide a fix/improvement.

I have been thinking about the best way to handle this situation:
- throw an exception or not?
- log or not? (but probably log)
- continue with the merge (and how) or not?

I have always been a bit annoyed about needing to have IDs for the elements in a `SubModelSeq` binding.  This is not necessary in Elm.  By default in Elm, `update` is called on each target element at index `i` given the `model` at index `i` (and then additions or removals are handled at the end).  It is a _potential_ optimization (in less runtime and less objects to garbage collect) to do this more complicated merge where each element has an ID.  This optimization is "enabled" in Elm by calling `HTML.keyed`.

First, I want this behavior in Elmish.WPF: the ability to create a `SubModelSeq` binding without needing element IDs.  Then, if this more complicated version of merge that uses IDs discovers that the user has failed to satisfy the precondition that IDs are unique, then we should first log this and then fallback to a version of merge that doesn't require elements to have IDs.  I like this solution because it means that the state of the UI is correct.  In contrast, the behavior you were experiencing @Evangelink is that the UI was not correct because the merge stopped before it was finished.

I don't think I will add this behavior to the 3.x branch though.

**Comment by Evangelink** [comment]
> 1. How were you rearranging the elements in your list?  I am curious to know of a "real" use-case that is a contributing factor to this issue.  Of course the main issue is duplicate IDs, but it is possible to have duplicate IDs without triggering this issue.

I have a kind of timeline control (home made) where we display files ordered by some time. Our model contains list of files and the `subModelSeq` is reordering into a new type for the UI. It is actually "mapped" into timeline items and timeline dates and that's the later that was causing the exception (so duplicated dates). That's why we had the issue only for a specific case (that wasn't anticipated): duplicated dates.


> 2\. Can you still reproduce this issue?  If so, then you can test when I provide a fix/improvement.

Issue is fixed but I can always get back to before the fix to check the fix. And I will be pleased to do so and give you any detail you want.

> I have always been a bit annoyed about needing to have IDs for the elements in a `SubModelSeq` binding.

I have had unexpected behaviors with the ID (a bit like if it is not handling F# types), especially with tuples and anonymous types. I was expecting to be able to use `id` but it doesn't seem to be working properly all the time. I don't know if I am doing something wrong or if that's just not expected.

> In contrast, the behavior you were experiencing @Evangelink is that the UI was not correct because the merge stopped before it was finished.

Yes! The biggest problem was that without your help I would have probably spent ages finding the root of the issue. So, all of your suggested options (logs, throw, or no-id) would provide a better experience.

> I don't think I will add this behavior to the 3.x branch though.

No worries :) Any idea of some ETA or some left to do for v4? Also, are there some APIs for which you would like feedback? I'd be happy to make some test with the v4 beta. So far, updating to v4 and simply changing `Program` to `WpfProgram` and everything worked well.

**Comment by TysonMN** [comment]
> I have had unexpected behaviors with the ID (a bit like if it is not handling F# types), especially with tuples and anonymous types. I was expecting to be able to use `id` but it doesn't seem to be working properly all the time. I don't know if I am doing something wrong or if that's just not expected.

I wonder if that is because the ID is being used as the key to a `Dictionary<_, _>`.  The `GetHashCode` function needs to work.  (c.f. https://github.com/elmish/Elmish.WPF/issues/139#issuecomment-878242012)

> Any idea of some ETA or some left to do for v4?

After having no time for Elmish.WPF for several weeks, I am making lots of progress again.  I don't know how much longer it will be though.  I really want to finish it because it will be _so_ much better.

The organization of what is left to do isn't great, but I have it all in my head.

> Also, are there some APIs for which you would like feedback? I'd be happy to make some test with the v4 beta. So far, updating to v4 and simply changing `Program` to `WpfProgram` and everything worked well.

Indeed.  I have been using the beta in my project at work (or, at least, I was, but now [I have changed jobs!](https://twitter.com/tyson_mn/status/1413504143726161922)...which is partly why I have had less time for Elmish.WPF).  Some users have reported some minor bugs that I quickly fixed.  Overall, the beta is stable.  The purpose of continuting to release new packages as prereleases is to maintain the possibility of making changes to the new public API.

I just pushed commit https://github.com/elmish/Elmish.WPF/commit/f809c84f13a40e5d38b66da772363dfdb174c8a3 that adds support for a `SubModelSeq` binding that doesn't involve IDs.  I proved to myself that it works by [converting the `SubModelSeq` sample to use this new binding](https://github.com/elmish/Elmish.WPF/commit/4c9af5dffd0b06d47227cdc3ab217d9a879ae046).

You could try testing this binding as well.  If you want, I can create a prerelease containing this new feature.  If you are up for it, you could also add some tests for `Merge.unkeyed` and maybe some `ViewModel<_. _>` tests for this new binding.  I would expect such tests to mostly be simplifications of the `ViewModel<_, _>` for the `SubModelSeq` binding with IDs.  (I am not a huge fan of the `Binding` tests.  I think they are too tightly coupled to the implementation of what they are testing.)

Next I will try to add a composable binding effect that creates a `SubModelSeq` binding that uses IDs from one that doesn't use IDs.  Then I can add the fallback behavior from `Merge.keyed` to `Merge.unkeyed` if `Merge.keyed` detects duplicate IDs.

**Comment by TysonMN** [comment]
I just pushed commit https://github.com/elmish/Elmish.WPF/commit/59236acb54bbbd7d456c0d4f16510cafbfd1b52c to `master`.  Now if the keyed variant of `SubModelSeq` detects duplicate IDs, the code
1. avoids causing .NET library code from throwing an exception (as was happening to you),
2. throws and then catches its own exception (so subscriptions to [FirstChanceException](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.firstchanceexception) will be alerted),
3. logs to the "Elmish.WPF logger" supplied by `WpfProgram.withLogger`, and
4. continues the update by using the unkeyed merge (so the UI will be correct).

> > 2. Can you still reproduce this issue?  If so, then you can test when I provide a fix/improvement.
> 
> Issue is fixed but I can always get back to before the fix to check the fix. And I will be pleased to do so and give you any detail you want.

Can you test now and provide feedback?

**Comment by Evangelink** [comment]
I confirm that the code does fix the issue properly (UI is still working) and I got the following two exceptions through the `FirstChanceException` mechanism:

```
- Elmish.WPF.Merge.DuplicateIdException
  HResult=0x80131500
  Message=In the Source sequence, the elements at indices 4 and 6 have the same ID 00:07:21.8660000
  Source=Elmish.WPF
  StackTrace:
   at Elmish.WPF.Merge.recordAddition@59.Invoke(Int32 curSourceIdx, s curSource, id curSourceId) in C:\Src\Elmish.WPF\src\Elmish.WPF\Merge.fs:line 63
```

```
Elmish.WPF.Merge.DuplicateIdException
  HResult=0x80131500
  Message=In the Target sequence, the elements at indices 6 and 8 have the same ID 00:06:21.6330000
  Source=Elmish.WPF
  StackTrace:
   at Elmish.WPF.Merge.recordRemoval@53.Invoke(Int32 curTargetIdx, t curTarget, id curTargetId) in C:\Src\Elmish.WPF\src\Elmish.WPF\Merge.fs:line 57
```

I am also posting here another exception that gets raised in Elmish.WPF (when testing the new code), in case that's something "unexpected":
![image](https://user-images.githubusercontent.com/11340282/125652755-5528359b-c8f4-4103-b982-dd0336fffc72.png)

```
Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Elmish.WPF.InternalUtils.IReadOnlyDictionary.tryFind[a,b](a key, IReadOnlyDictionary`2 d) in C:\Src\Elmish.WPF\src\Elmish.WPF\InternalUtils.fs:line 71
```

**Comment by TysonMN** [comment]
> I don't know if you are able to retrieve the binding name at this location but that would be the cherry on the cake to be able to debug such kind of problems :)

Ah, yes.  Great feedback.  I definitely forgot tot add that information.  I never even thought about it.

I just added that information to the log event.  I also improved the full name of the exception by removing `Merge`.

Do you mind testing again?

**Comment by TysonMN** [comment]
> I am also posting here another exception that gets raised in Elmish.WPF (when testing the new code), in case that's something "unexpected":

Yes, definitely unexpected.  I think this is the same issue as #397, right?  That issue is now fix in `master` as well.

**Comment by Evangelink** [comment]
> Yes, definitely unexpected. I think this is the same issue as #397, right? That issue is now fix in `master` as well.

Yes that's fixed now!


> Ah, yes. Great feedback. I definitely forgot tot add that information. I never even thought about it.
> 
> I just added that information to the log event. I also improved the full name of the exception by removing `Merge`.
> 
> Do you mind testing again?

I think you took the "wrong" variable for the binding name, here are the messages raised. I was expecting to see (if possible of course) `'TimelineTimes'` for an error on the following binding `"TimelineTimes" |> Binding.subModelSeq`

```
'In the Source sequence, the elements at indices 4 and 6 have the same ID 00:06:21.2830000'
'In the Target sequence, the elements at indices 6 and 8 have the same ID 00:06:21.2830000'
'In the Source sequence, the elements at indices 4 and 10 have the same ID 00:06:21.5960000'
```

**Comment by TysonMN** [comment]
Is that text from the exception message or the Elmish.WPF logger?  I think it is from the exception message.  The throwing context doesn't have the binding name and chain.  The log event sent to the Elmish.WPF logger should have "all the information" now.

**Comment by Evangelink** [comment]
I have added the following `WpfProgram.withLogger (new Extensions.Logging.SerilogLoggerFactory(Log.Logger))` to my code. Then reproduced the issue and looking at the logs I have some difficulties to understand what I am expected to see/find.

Do I have to turn on something?

**Comment by TysonMN** [comment]
I just tested myself.  I think everything is working (after I just pushed a small fix to the order of the data in the log event).

Here is how I tested.  Change the line...
https://github.com/elmish/Elmish.WPF/blob/600ec39421f3f3d964cc920113e1e8b75e6e55b8/src/Samples/SubModelSeq.Core/Program.fs#L195

...to
```fsharp
{ Id = Guid ()
```

Then this is the behavior:
![2021-07-15_17-22-28_652](https://user-images.githubusercontent.com/34664007/125865348-2bfed006-fed2-4353-bd7f-d30e72b4cd69.gif)

**Comment by TysonMN** [comment]
> ...looking at the logs I have some difficulties to understand what I am expected to see/find.
> 
> Do I have to turn on something?

So the previous comment is what you should see.

I am also knowledgeable in Serilog, but there are many things that could be the problem.  Want to share more about what you set to `Log.Logger`?

**Comment by Evangelink** [comment]
All good, it seems that I just cannot read logs :)
