### ISSUE TITLE
`GetErrors` of `INotifyDataErrorInfo` should handle null property name

### ISSUE THREAD

**Issue by Evangelink** [elmish/Elmish.WPF#397]
That might not be related but I have also seen an exception in `GetErrors` of `INotifyDataErrorInfo` https://github.com/elmish/Elmish.WPF/blob/7abde5cbd97c3f71e015306ce716c2e4f2572a9f/src/Elmish.WPF/ViewModel.fs#L824-L828

when `propName` is `null`. You are handling the case for the `log` but not for the `match`.

_Originally posted by @Evangelink in https://github.com/elmish/Elmish.WPF/issues/396#issuecomment-876232437_

**Comment by Evangelink** [comment]
If you confirm that this issue should be fixed, I am more than happy to provide the PR fix.

**Comment by TysonMN** [comment]
I think I removed this logging after someone reported that it happens too often.  I will double check later.

**Comment by TysonMN** [comment]
Fixed in https://github.com/elmish/Elmish.WPF/commit/8e57f80e365d241e98560f736e9ab1e170f1495a

**Comment by Evangelink** [comment]
I am copying the message from the other issue here just for the sake of easy finding in case of future lookup:

I am also posting here another exception that gets raised in Elmish.WPF (when testing the new code), in case that's something "unexpected":
![image](https://user-images.githubusercontent.com/11340282/125652755-5528359b-c8f4-4103-b982-dd0336fffc72.png)

```
Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Elmish.WPF.InternalUtils.IReadOnlyDictionary.tryFind[a,b](a key, IReadOnlyDictionary`2 d) in C:\Src\Elmish.WPF\src\Elmish.WPF\InternalUtils.fs:line 71
```

And I confirm that this issue is correctly fixed.
