### ISSUE TITLE
How binding to TreeView?

### ISSUE THREAD

**Issue by eu-genes** [elmish/Elmish.WPF#399]
I can't deal with SubModelSeq. That's an complex example.
Such as SubModelSelectedItem looks like "elementary school", but SubModelSeq like "high school ".
Need a more simpler example of working with TreeView.
For example, how bind data like this?
```fsharp
type Person = {Id: int; Name: string}
type Tree = {Node: Person; Childrens: Tree list}
```
My try: https://github.com/eu-genes/simpletreeview

**Comment by TysonMN** [comment]
Sorry that the sample is so complex.  Improving the samples, including this one, is on my list of things to do.

I just pushed commit https://github.com/elmish/Elmish.WPF/commit/58623d0d4ef9e4d6a68269aad3691ca501d00f80 that simplifies the `SubModelSeq` sample a bit by having it use the recently simplified API for creating a `SubModelSeq` binding.  Maybe that helps a bit.

I will look at your repo now.

**Comment by TysonMN** [comment]
> I just pushed commit [58623d0](https://github.com/elmish/Elmish.WPF/commit/58623d0d4ef9e4d6a68269aad3691ca501d00f80) that simplifies the `SubModelSeq` sample a bit by having it use the recently simplified API for creating a `SubModelSeq` binding. Maybe that helps a bit.

Except I think that new API doesn't exist in a prelease yet.  I can create a new prerelease if you want.

**Comment by TysonMN** [comment]
I think PR https://github.com/eu-genes/simpletreeview/pull/1 is the primary fix for your code.  They key thing you were missing is that the bindings need to be recursive.

One issue remains in your code, but it isn't your fault.  The `SubModelSelectedItem` binding isn't properly working with `TreeView`.  I don't immediately see an easy fix, so I created issue #400.

**Comment by eu-genes** [comment]
Thx, "recursive binding" looks like an obvious idea. Sorry, I didn't notice that.

> I just pushed commit [58623d0](https://github.com/elmish/Elmish.WPF/commit/58623d0d4ef9e4d6a68269aad3691ca501d00f80) that simplifies the `SubModelSeq` sample a bit by having it use the recently simplified API for creating a `SubModelSeq` binding. Maybe that helps a bit.

cool, new API more compositional

> I can create a new prerelease if you want.

 I don't want that.

>  I don't immediately see an easy fix

Oh, this so sad. My real project needs select items in TreeView. How can I do this functionality without `SubModelSelectedItem `?

**Comment by TysonMN** [comment]
> > I don't immediately see an easy fix
> 
> Oh, this so sad. My real project needs select items in TreeView. How can I do this functionality without `SubModelSelectedItem `?

You can use the `SelectedValue` and `SelectedValuePath` properties of `TreeView` along with a `TwoWay` binding to obtain the ID of the selected item.  See https://github.com/eu-genes/simpletreeview/pull/2.

**Comment by eu-genes** [comment]
Wow thank you very much! I think this issue can be closed.

**Comment by TysonMN** [comment]
As a great start to a major improvement to the samples, I added a pair of projects called `Capabilities` with a single screen called `Selection` and one of the two examples is binding to `TreeView.SelectedValue`.  It was added in commit https://github.com/elmish/Elmish.WPF/commit/52c9a6871711043e3b743b60ac3f3104baa8c5f7.
