### ISSUE TITLE
Logger might be having an issue

### ISSUE THREAD

**Issue by Evangelink** [elmish/Elmish.WPF#401]
Hi there,

I have switched my app to Elmish.WPF v4.0.0-beta-41 and some features (mainly the clip player) started to freeze the app. After a couple of hours I have noticed this is linked to the logging capability.

I don't know if there is a bug or if it's a configuration issue on my side so I am posting here.

Serilog configuration:

```fsharp
Log.Logger <-
        LoggerConfiguration()
            .MinimumLevel.Verbose()
            .Destructure.FSharpTypes()
            .Enrich.WithProcessId()
            .Enrich.WithProcessName()
            .Enrich.WithThreadId()
            .WriteTo.File(
                Path.Combine(xxxAppDataPath, "Logs", "XXXX.log"),
                outputTemplate= "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}",
                restrictedToMinimumLevel= LogEventLevel.Information,
                fileSizeLimitBytes= 50_000_000L,
                rollOnFileSizeLimit= true,
                shared= true)
            .WriteTo.File(
                Path.Combine(xxxAppDataPath, "Logs", "XXXX-verbose.log"),
                outputTemplate= "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] <{ProcessName}({ProcessId})|{ThreadId}> {Message:lj}{NewLine}{Exception}",
                fileSizeLimitBytes= 50_000_000L,
                rollOnFileSizeLimit= true,
                retainedFileCountLimit= 2,
                shared= true)
            .CreateLogger()
```

and the code to plug the logger in Elmish is:

```fsharp
|> WpfProgram.withLogger (new Serilog.Extensions.Logging.SerilogLoggerFactory(Log.Logger))
```

**Comment by TysonMN** [comment]
> I don't know if there is a bug or if it's a configuration issue on my side so I am posting here.

I don't see any problem with your logging configuration, but maybe I am missing something.

I think I will need more information to identify the problem.  I suppose you can't share a reproduction, huh?

> After a couple of hours I have noticed this is linked to the logging capability.

Can you elaborate on this?  What makes your suspect the logging?

**Comment by Evangelink** [comment]
> I suppose you can't share a reproduction, huh?

Best I could offer is to do some screenshare with you some time. I know that's not ideal, trust me...

> Can you elaborate on this? What makes your suspect the logging?

That's easy, when it's there the UI is frozen when clicking the play button, when the line is out there is no problem :)

I suspect the messages are too big (and maybe written too often) when written in the log so it freezes the UI. I know that in our app, I had to "dispatch" all loggings in a async call so that it doesn't slow down the app.

**Comment by TysonMN** [comment]
> After a couple of hours I have noticed this is linked to the logging capability.

1. After a couple hours of debugging you suddenly noticed the connection to the logging and can now instantly breproduce the problem?
...or
2. The application is fast and responsive just after starting and then it becomes progressively shower over time so that after two hours of running you can easily cause noticable temporary freezes?

**Comment by Evangelink** [comment]
Sorry I wasn't clear (I mean it was clear in my head but not in my words :))...

It just took me way too much time of debugging the sudden performance issue (UI freeze) before thinking "oh let me try to remove the call to the logs I added when moving to the beta version".

The problem is direct: I open the app, load the clip, click play and boom the app is unresponsive.

**Comment by TysonMN** [comment]
Ah, I original thought you meant that the problem slow worsened over time.

Now that I know the problem happens immediately, then yes, I think the problem is probably with your configuration in that you are logging all verbose events.  There are probably too many verbose events to handle efficiently.  In my application at (my previous) work, the logging defaulted to `Information`.  I would temporarily change it to `Debug` or `Verbose` if I was debugging something (and I thought that information would be useful).

**Comment by Evangelink** [comment]
> then yes, I think the problem is probably with your configuration in that you are logging all verbose events

I made a test using the `.MinimumLevel.Debug()` instead of `Verbose()` and everything seems to be working properly.

Our app is still in some kind of beta mode so I wanted to make sure to have as many detailed log as possible in the event of something unexpected/some exception occurring. That's also why I have put a small limitation to the number of "debug log" files we allow.

Anyways, sorry for the trouble and have wasted some of your time! Thanks again for the support.

**Comment by TysonMN** [comment]
> Anyways, sorry for the trouble and have wasted some of your time! Thanks again for the support.

No worries.  I am happy to help :).

Glad you got everything straightened out.
