### ISSUE TITLE
Use subModelSeq for array with duplicate values

### ISSUE THREAD

**Issue by eu-genes** [elmish/Elmish.WPF#402]
I don't understand how to write `subModelSeq  getId` function in this case?
As an alternative, indexed list not suitable due to low performance.

**Comment by TysonMN** [comment]
In what case?  Can you share a reproduction?

**Comment by TysonMN** [comment]
In `master`, I have added support for a `SubModelSeq` binding that doesn't need a `getId` function.  I think it will solve your problem.

Can you try that and report back?

If it would help, I can create pre-release to make this easier.
