### ISSUE TITLE
Opt-in to synchronous Cmd dispatch

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#407]
I used to be that all messages were dispatched synchronously. PR #374 changed this to dispatch UI messages synchronously and all other messages (i.e. those from commands or subscriptions) asynchronously.

Could the user opt-in to synchronous dispatch?

(c.f. issue 403)

**Comment by TysonMN** [comment]
This might be possible, but I will have to take a closer look to get a better sense of things.

**Comment by TysonMN** [comment]
Quoting @Evangelink in https://github.com/elmish/Elmish.WPF/issues/403#issuecomment-896822393
> Is it possible to force one `CmdMsg` to be now processed synchronously?

What is your use case for wanting synchronous command processing?

**Comment by Evangelink** [comment]
> What is your use case for wanting synchronous command processing?

Honestly, that's more of a curiosity question. I originally went with passing an observable to avoid bringing all the Telerik dependencies on the model side only to reference this event arg. 

Giving some thoughts about it, the only scenario I could think of, is where I would have created a UI component from F# code, and I would subscribe to some specific event where I would want to have the code to be dispatched synchronously. I am not sure if the best would be to use `Cmd.ofSub` or to think of some way to plug the bindings onto objects created from F#.

**Comment by TysonMN** [comment]
Ok. Thanks for those thoughts.

Since there is no immediate need, I will close the issue.  Feel free (anyone) to share a use case for this feature.
