### ISSUE TITLE
Utilize multiline code blocks in XML documentation

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#417]
I want to put a multiline code block into this XML documentation.
https://github.com/elmish/Elmish.WPF/blob/9608bb1c3586fe9bf1e421711d1e26ed250d56a1/src/Elmish.WPF/Binding.fs#L795-L809

However, it doesn't look so good.  I want each line of code to be on its own line when displayed, no blank line between them in the display, and indented properly in the display.
![2021-08-24_22-58-16_677_devenv](https://user-images.githubusercontent.com/34664007/130724298-a978a5f5-038b-403c-80eb-870395505276.png)

Is it possible to achieve this?

**Comment by Evangelink** [comment]
It seems to be a bug with Visual Studio. [Documentation](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation#recommended-tags) says that `<code>` is supposed to handle multiline code samples.

Besides, ionide in VS Code renders the documentation correctly:

![image](https://user-images.githubusercontent.com/11340282/132983708-38c9817d-3b28-44b5-8ade-e13583378a47.png)

**Comment by TysonMN** [comment]
Thanks for looking into this.

Has this bug been reported?  Can you try and find an existing issue?  I think the right place is the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).

I am glad the Ionide looks correct.  The is just one small issue there.  It has `Binding<'model 'a>` but should be `Binding<'model, 'a>` (i.e. a comma is missing).  Can you also see if an issue exists for that?

**Comment by Evangelink** [comment]
Here is the VS issue: https://developercommunity2.visualstudio.com/t/Xml-documentation-code-section-does-not/1528203 and regarding ionide the GitHub ticket is linked before.

**Comment by Evangelink** [comment]
![image](https://user-images.githubusercontent.com/11340282/133317415-02a3002e-d206-44b9-b938-5fff5b59aec2.png)

Pasting the link here for convenience: https://github.com/ionide/ionide-vscode-fsharp/issues/1583

**Comment by TysonMN** [comment]
Thanks so much your reporting those issues!

> [...] but correctly in the over tooltip.

Did you mean to say "incorrectly" there?

**Comment by Evangelink** [comment]
If you look at the screenshot you will see that the ionide tooltip is correct (left part of the screenshot) and only the description in the info panel is incorrect (right side).

**Comment by TysonMN** [comment]
Ok, I understand now. Thanks for the extra clarification.
