### ISSUE TITLE
CompositeMsg in SingleCounter, with no explanation.

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#421]
I suspect the CompositeMsg in the SingleCounter demo was accidentally left behind after some experimenting. Doesn't seem to have any purpose there. If it's supposed to be there, then a comment in the source about its purpose would be nice.

**Comment by TysonMN** [comment]
Yes, that was an accident.  Thanks for reporting.

Removed in d9d978ac36611156949fb93dfb8ff9bd57d3a1c7
