### ISSUE TITLE
Add WpfProgram wrapper for Program.withErrorHandler

### ISSUE THREAD

**Issue by cmeeren** [elmish/Elmish.WPF#426]
I would like to display a message to the user when there's an exception in the Elmish loop. Based on the name and the signature, `Program.onError` seems to fit the bill, though the description says "For library authors only", so I'm not 100% sure it's what I'm after.

In any case, I can't use `Program.onError` (or anything else in Elmish's `Program` module) because the `WpfProgram` fields are internal, and the `WpfProgram` module doesn't expose any function that wraps `onError` or allows mapping `Program`. (Allowing users to map `Program` could be a more general solution, though it would be possible to shoot oneself in the foot.)

**Comment by TysonMN** [comment]
Does `Wpf.withLogger` do what you want?

We use that logger to subscribe to Elmish errors
https://github.com/elmish/Elmish.WPF/blob/master/src/Elmish.WPF/WpfProgram.fs#L100

**Comment by cmeeren** [comment]
No, I don't just want to log them; I actually want to display a dialog to the user with details about the error. The user should know that something bad happened and be advised on how to proceed.

**Comment by TysonMN** [comment]
You can do that with a particular implementation of that logger interface.  That is what I did in the project at my previous work.

Would you like to see a demo, or do you think you can figure it out?

**Comment by cmeeren** [comment]
That seems like a _very_ heavy-handed way of doing things.

In order to do that, I have to implement an `ILoggerFactory`, which means I need to implement `AddProvider`, `CreateLogger`, and `Dispose`. For `AddProvider`, I have to know what to do with the added provider (ignore it?). For `CreateLogger`, I have to again determine what to do with the `categoryName` (ignore it?), and then return a suitable `ILogger` that implements `BeginScope`, `IsEnabled`, and `Log`. Plenty of unnecessary parameters in those methods, too, and I expect I have to remember to check that the exception is not `null`. Lots of docs to read to fully understand this.

The only thing I want is a function `exn -> unit` (or even better, `exn -> 'msg`, though I can get to that myself using e.g. subscriptions and events).

I was wrong when I said `Program.onError`; the correct function is `Program.withErrorHandler`, which is intended for public consumption.

I am more than happy to create a PR that adds a `WpfProgram.withErrorHandler` that wraps `Program.withErrorHandler`.

**Comment by TysonMN** [comment]
I don't think it is heavy at all.  Not in code and not in performance.

To the issue of code, you are (unknowingly) exaggerating how difficult it is.  See the branch [demo/Elmish_exn_handling](https://github.com/TysonMN/Elmish.WPF/tree/demo/Elmish_exn_handling).  The diff adds less than 30 lines of code; all easy to read in my opinion.  This is the exception handling behavior that I designed and implemented for the application at my previous job.  Here is what it looks like.

![2021-09-09_20-07-35_682](https://user-images.githubusercontent.com/34664007/132782773-f303e07f-0c46-4281-9ee4-047cfea9cc8b.gif)

To the issue of performance, exceptions rarely happen, so performance doesn't really matter.

Does this change your mind?

**Comment by cmeeren** [comment]
Thank you for the demo! That helped a lot. You said "a particular implementation of that logger interface", but I see now that you meant a sink that outputs to a message box.

To be clear, I was never worried about performance.

I still think that it makes sense to add `withErrorHandler` so that dispatch loop exceptions may be handled without having to go through a specific logging framework (Serilog in this case). This is what I'm suggesting we add to `WpfProgram`:

```f#
/// Uses the specified handler for dispatch loop exceptions.
let withErrorHandler onError program =
  { program with ElmishProgram = program.ElmishProgram |> Program.withErrorHandler onError }
```

With this, your `MessageBox` sink can be replaced by this:

```f#
let errorHandler (msg, exn) =
  logToMessageBox "Elmish.WPF" msg
```

(For my use-case I would also render the exception stack trace, but the above corresponds to the functionality you demoed, and the addition of the stack trace is trivial using e.g. interpolated strings.)

This is simpler in the following ways:
* The solution is more "direct" and easily discoverable than having to realize one can use a custom sink to send exceptions to a message box
* 2 trivial lines instead of 8 lines requiring knowledge about logging framework internals (I had no idea `MessageTemplateTextFormatter` even existed, and would have had to research how to create Serilog sinks if you hadn't shown me)
* No need to format the log message

Furthermore, I see no compelling reason to prevent users from making use of `Elmish.withErrorHandler`, which after all is intended to be user-facing.

If you want `withErrorHandler` added, I can create a PR. If not, I won't push this further; feel free to close the issue in that case.

**Comment by TysonMN** [comment]
You can add this function.

What should be the behavior if a user calls both `withErrorHandler` and `withLogger`?

**Comment by cmeeren** [comment]
Both should be called, don't you agree?

In other words, the implementation I shared above is too simple. Though it won't be significantly more complex.

**Comment by TysonMN** [comment]
Yes, I agree.

In general, I would like the behavior to not (fundamentally) depend on the order.  (By fundamentally there, I mean I don't care about the order in which the agreements of those two functions are called.)
