### ISSUE TITLE
How use async commands in subModels?

### ISSUE THREAD

**Issue by eu-genes** [elmish/Elmish.WPF#427]
Hi, copied load file code from FileDialogs sample to my subModel ([repo](https://github.com/eu-genes/elmishclosewindow/tree/async_cmd)), but async commands not called.
I suppose problem with `SubModel.update`, how can fix this?
```fsharp
| SubMsg msg' -> 
                {m with Id = m.Sub.Id; Sub = SubModel.update msg' m.Sub |> fst}
```

**Comment by Evangelink** [comment]
Hi @eu-genes,

You need to make sure that the `SubModel` cmds are actually flowing up to the elmish loop. So instead of taking `SubModel.update msg' m.Sub |> fst` you will need to keep both return types and map the `Cmd<SubModel.Msg>` into a `Cmd<ModalWin.Msg>` and then do the same thing for the module `Main`.

**Comment by eu-genes** [comment]
> Hi @eu-genes,
> 
> You need to make sure that the `SubModel` cmds are actually flowing up to the elmish loop. So instead of taking `SubModel.update msg' m.Sub |> fst` you will need to keep both return types and map the `Cmd<SubModel.Msg>` into a `Cmd<ModalWin.Msg>` and then do the same thing for the module `Main`.

Thanks! i.e. all project models update functions must return tuple Model * Cmd<Msg> ?

**Comment by Evangelink** [comment]
> Thanks! i.e. all project models update functions must return tuple Model * Cmd ?

At least the ones that are on the path from where you want to have the `Cmd` up to the elmish loop. 

Feel free to ping here when you have made some changes and if you get stuck somewhere in the process.
