### ISSUE TITLE
There is no 4.0.0-beta-42 on GitHub, only in the release notes

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#428]
I wanted to compile the latest Samples with the latest beta on GitHub, which is 4.0.0-beta-41. I get a whole bunch of compile errors. In the release notes there is a 4.0.0-beta-42, but this release is not on GitHub. The release notes for 4.0.0-beta-42 also seems to explain the errors I've got. Can we have the 4.0.0-beta-42 on GitHub?

**Comment by TysonMN** [comment]
Yep. Let's see if I can do this on my phone (using FastHub).

**Comment by TysonMN** [comment]
Ah, not this time at least.  I (or someone else in the organization) needs to enable data access for this non-OAuth app.

**Comment by BentTranberg** [comment]
I'm in no hurry. It can wait. Just passing some time during the weekend. Thanks for trying.

**Comment by TysonMN** [comment]
Oh, this app does use OAuth, but it needs to be explicitly granted access.  I have done that now, so hopefully next time I can release wherever I am.

[4.0.0-beta-42](https://www.nuget.org/packages/Elmish.WPF/4.0.0-beta-42) is now available.

**Comment by BentTranberg** [comment]
Thanks a lot. It compiles.
