### ISSUE TITLE
Getting started outdated with PR #320

### ISSUE THREAD

**Issue by MatthijsPrent** [elmish/Elmish.WPF#433]
Well, as the title says. The documentation is outdated since PR #320 . Especially the startElmishLoop does not work anymore.

Edit: please pardon my to quickly opened Issue. after Further research, I concluded that the "Getting started" is not up to date with the latest stable NuGet package.

**Comment by TysonMN** [comment]
Yes, the getting started had been updated to to describe our 4.0 pre-release.  You can look at the version of the documentation before PR #337 to find the information you seek.

The current 4.0 pre-release is much better than the latest 3.* release.  In particular, I believe that it contains fewer bugs, so it is stable in that sense.  What is unstable is that I might make minor changes to the API that would introduce compiler errors.
