### ISSUE TITLE
Is it correct to use Control in Model and mutable Command in MVU?

### ISSUE THREAD

**Issue by RickyYCheng** [elmish/Elmish.WPF#437]
I'm not sure about what are the correct ways to achieve these things in MVU.  :(
In XAML, I've bound the CONTENT property of a frame, then I map the WebView2 control from the model to the content. 

Second thing is that I used a lot of code that executes the command by just change the state of the property of the model(MainWebView), and I don't know how to achieve that because in this case you've seen, we need to get the sender of an event as well as the event args, seems that maybe F# cannot do it. 

Third, seems like there's no idea to transforms this slice of code to F#:
```C#
if(e.ClickCount == 2)
            {
                if (this.WindowState == WindowState.Normal)
                    this.WindowState = WindowState.Maximized;
                else this.WindowState = WindowState.Normal;
            }
            this.DragMove();
```
I can obviously transform the event to a command, but I can never call the DragMove() method of the window because I cannot get the instance of it in F# code.  I still cannot do the same thing as I did before because the MainWindow is the TOP control and there's no parent for it. 

```F#
 // ... //
let init =
    {
        MainWindowState = WindowState.Normal
        MainWebView = 
            let foo = new WebView2(Source = Uri "https://www.bing.com") 
            foo.CoreWebView2InitializationCompleted.Add(fun e -> 
                foo.CoreWebView2.NewWindowRequested.Add(fun e -> 
                    e.Handled <- true
                    foo.Source <- Uri e.Uri))
            foo
    }

let update msg m = 
    match msg with 
    | ChangeState s -> { m with MainWindowState = s }
    | ExitApp -> m
    | Reload -> m.MainWebView.Reload(); m
    | ToHome -> m.MainWebView.Source <- Uri "https://www.bing.com"; m
    | GoBack -> m.MainWebView.GoBack(); m
    | GoForward -> m.MainWebView.GoForward(); m

let bindings () : Binding<Model, Msg> list = 
    [
        "ExitApp" |> Binding.cmdParam (fun obj -> Environment.Exit 0; ExitApp)
        "MainWindowState" |> Binding.oneWay (fun m -> m.MainWindowState)
        "ChangeSizeCmd" |> Binding.cmd (fun m -> 
            match m.MainWindowState with 
            | WindowState.Normal -> ChangeState (WindowState.Maximized)
            | _ -> ChangeState (WindowState.Normal))
        "ToMinus" |> Binding.cmd(fun m -> ChangeState (WindowState.Minimized))
        "MainWebView" |> Binding.oneWay(fun m -> m.MainWebView)
        "ReloadCmd" |> Binding.cmd Reload
        "ToHome" |> Binding.cmd ToHome
        "GoBack" |> Binding.cmd GoBack
        "GoForward" |> Binding.cmd GoForward
    ]
```

![image](https://user-images.githubusercontent.com/77863853/136239918-ac10f0fd-cf72-4ae9-96cd-c8d79b3e2843.png)

// command just change the property of web-view in model and return nothing but model that never rebuilt. 

For whoever wants to have a look at my code: :) 
https://github.com/RickyYChan/Elmish.WPF-WebView2-Terrible
Maybe this problem is a good sample for beginners just like me and maybe I did the wrong thing. 
Hope to see a perfect answer! :) Appreciate!

**Comment by TysonMN** [comment]
I have started to look at your code.  I will help you get it all working well, but it will takes several days as I find the time.

For today, I have contributed [this PR](https://github.com/RickyYChan/Elmish.WPF-WebView2-Terrible/pull/1) that improves some DevOps-y things and does some minor clean up.

**Comment by RickyYChan** [comment]
> I have started to look at your code. I will help you get it all working well, but it will takes several days as I find the time.
> 
> For today, I have contributed [this PR](https://github.com/RickyYChan/Elmish.WPF-WebView2-Terrible/pull/1) that improves some DevOps-y things and does some minor clean up.

Very appreciate for what you did! :) 
I'm not in a hurry, because this is just a noob case for learning Elmish.WPF. 
If the project changes well enough, I guess that maybe it can be used as a sample of Elmish.WPF(LOL).

**Comment by RickyYChan** [comment]
> > 1. Content property is bindable, that's all right.
> 
> I know you can, but I don't think you should. I think it is more idiomatic to define the `WebView2` instance in the XAML.
> 
> > [...] but how to `DragMove`?
> 
> Similar to how I handled going home, back, and forward. Do you think you can do the same for `DragMove`?
> 
> > [...] removes the init event of the webview, and that will cause the webview to open the default browser on your PC to open the link which will open a new tab(because the NewWindowRequested event has not to be handled).
> 
> I understand now. Sorry that I didn't understand yesterday, in which case, I would have preserved this behavior in my second PR.
> 
> However, I also know now that the fix is simple. Similar to how I handled going home, back, and forward as well as how you should handle `DragMove`, add a case to the `Cmd` DU that you return from `init`. In `toCmd`, have this case subscribe to the event as you wrote above. Is that clear?

Appreciate! 👍  💯 🥇  I've understood everything! :) 
Actually, I'm considering writing an UserControl as a wrapper to achieve this...
Thanks for your help!
Sorting these kind of stuff(the repo and another app just like this, but a multipage app) should be the recent task of me. 
If the demo isn't too bad I'll consider posting them to the Elmish.WPF sample as small practice material.  :)
Good luck.

**Comment by RickyYChan** [comment]
I'll close this issue. And if any1 is interested in my stupid solution, here is the sample. 
```xaml
<UserControl x:Name="selfControl"
             x:Class="WPFBrowser.CustomWebView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:wv="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
             xmlns:local="clr-namespace:WPFBrowser"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800"
             Loaded="selfControl_Loaded"
             >
    <wv:WebView2 x:Name="selfWebView" Source="{Binding ElementName=selfControl, Path=Address}"/>
</UserControl>
```
```C#
using System.Windows;
using System.Windows.Controls;

namespace WPFBrowser
{
    /// <summary>
    /// CustomWebView.xaml 的交互逻辑
    /// </summary>
    public partial class CustomWebView : UserControl
    {
        public string Address
        {
            get { return (string)GetValue(AddressProperty); }
            set { SetValue(AddressProperty, value); }
        }

        // Using a DependencyProperty as the backing store for Address.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty AddressProperty =
            DependencyProperty.Register("Address", typeof(string), typeof(CustomWebView), new PropertyMetadata("https://www.bing.com"));
        static void OnAddressChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            CustomWebView s = sender as CustomWebView;
            s.Address = e.NewValue as string;
        }
        public static readonly RoutedEvent initCustomWebView =
                EventManager.RegisterRoutedEvent("InitCustomWebView", RoutingStrategy.Bubble, typeof(RoutedEventHandler), typeof(CustomWebView));
        public event RoutedEventHandler InitCustomWebView
        {
            add
            {
                AddHandler(initCustomWebView, value);
            }

            remove
            {
                RemoveHandler(initCustomWebView, value);
            }
        }
        public CustomWebView()
        {
            InitializeComponent();
        }

        private void selfControl_Loaded(object sender, RoutedEventArgs e)
        {
            RoutedEventArgs args = new(initCustomWebView, selfWebView);
            RaiseEvent(args);
        }
    }
}

```
USE:
```xaml
        <local:CustomWebView Grid.Row="1" InitCustomWebView="CustomWebView_InitCustomWebView"/>
```
```C#
// you can translate this into command in F#, isn't it?
private void CustomWebView_InitCustomWebView(object sender, RoutedEventArgs e)
        {
            var wv = e.OriginalSource as WebView2;
            wv.CoreWebView2InitializationCompleted += (sender, e) =>
            {
                wv.CoreWebView2.NewWindowRequested += (sender, e) =>
                {
                    e.Handled = true;
                    wv.Source = new(e.Uri);
                };
            };

        }
```
LOL
