### ISSUE TITLE
remove SubModelSeq item will always remove last one 

### ISSUE THREAD

**Issue by RickyYChan** [elmish/Elmish.WPF#438]
Trying to convert a simple multiple pages WPF browser to an elmish program. 
But when removing an item in ItemsSource, the views will give different behaviors.

I've traced back to the commit when the problem first came out, codes like this:
```F#
// In module App
let update msg m = 
        match msg with 
        | AddTab -> { m with Tabs = m.Tabs |> IList.add { Content = $"Hello {m.Tabs |> len}" } }, 
                    Cmd.ofMsg (Select m.Tabs.Count)
        | Select i -> { m with SelectedId = i }, Cmd.none
        | RemoveSelected -> (if m.Tabs.Count = 0 then m else { m with Tabs = m.Tabs |> IList.rmat m.SelectedId }), 
                            Cmd.ofMsg (Select (m.Tabs.Count - 2))
    
    let bindings () : Binding<Model, Msg> list = 
        [
            "AddTabCmd" |> Binding.cmd AddTab
            "RmTabCmd" |> Binding.cmd RemoveSelected
            "TabSource" |> Binding.subModelSeq(
                (fun m -> m.Tabs |> Seq.indexed), 
                (fun (i, t) -> i), 
                (fun () ->  [
                        "TabContent" |> Binding.oneWay(fun (m, (i, t)) -> t.Content) 
                        "SelectItem" |> Binding.cmd(fun (m, (i, t)) -> Select i)
                        "TabBg" |> Binding.oneWay(fun (m, (i, t)) -> 
                            if i = m.SelectedId then accent else transparent)
                        "DoubleClickCmd" |> Binding.cmd RemoveSelected
                    ]))
            
            "ViewBorder" |> Binding.subModelSeq(
                (fun m -> m.Tabs |> Seq.indexed),
                (fun (i, v) -> i),
                (fun () -> [
                    "DBGC" |> Binding.oneWay(fun _ -> System.Drawing.Color.Transparent)
                    "WvVisibility" |> Binding.oneWay(fun (m, (i, t)) -> 
                        if i = m.SelectedId then Visibility.Visible else Visibility.Hidden)
                ]))
        ]
```
> code in the commit that the problem first shows up  

Behavior description: 
init 6 tabs and views
| index | 0 | 1 | 2 | 3 | 4 | 5 | 
| --- | --- | --- | --- | --- | --- | --- |
| tabs | tab0 | tab1 | tab2 | tab3 | tab4 | tab5 | 
| uris | bing | bing | bing | bing | sth | bing |

Trying to remove no.3
result:
| index | 0 | 1 | 2 | 3 | 4 | 
| --- | --- | --- | --- | --- | --- |
| tabs | tab0 | tab1 | tab2 | tab4 | tab5 | 
| uris | bing | bing | bing | bing | sth |

The tabs are removed in the right place, but web views do not.

**Comment by RickyYChan** [comment]
functions: 
```fs
[<AutoOpen>]
module IList = 
    open System.Collections.Immutable
    let len = Seq.length
    let add d (x:ImmutableList<_>) = x.Add d 
    let rmat ind (x:ImmutableList<_>) = x.RemoveAt ind 
    let init = ImmutableList.CreateRange
```

**Comment by RickyYChan** [comment]
![image](https://user-images.githubusercontent.com/77863853/139533311-60b252d4-e8e2-40f4-8ac2-96f0bf95771b.png)
> init 
![image](https://user-images.githubusercontent.com/77863853/139533316-8a4b6e32-36c2-4a3f-a4b5-1fb713b98c40.png)
> remove item no.3 of the itemsSource

**Comment by TysonMN** [comment]
Can you share a link to a GitHub repository that reproduces the problem?

**Comment by RickyYChan** [comment]
> Can you share a link to a GitHub repository that reproduces the problem?

I've created a repo to reproduce the problem/bug. Links here. 
https://github.com/RickyYChan/A-terrible-Elmish.WPF-Browser-app 

I build this small project thanks to your PR here. 
https://github.com/elmish/Elmish.WPF/pull/306

**Comment by TysonMN** [comment]
Can you share a screen recording of your reproduction?

I am unsure how to reproduce your problem.  I found this problem though, which might be a different problem (or it might be the same problem and I don't realize it).

![2021-10-31_21-04-50_703](https://user-images.githubusercontent.com/34664007/139611708-8fa8564d-a8fc-42df-bea8-19e4f7c03054.gif)

**Comment by RickyYChan** [comment]
> Can you share a screen recording of your reproduction?
> 
> I am unsure how to reproduce your problem. I found this problem though, which might be a different problem (or it might be the same problem and I don't realize it).
> 
> ![2021-10-31_21-04-50_703](https://user-images.githubusercontent.com/34664007/139611708-8fa8564d-a8fc-42df-bea8-19e4f7c03054.gif)

actually they are same problem
when you discard the tab, tabs and their links should be:
0 1 2 3 4 5
bing bing bing bing disposed(show nothing) bing 
and then the cmd will remove the tab which was disposed, result should be
0 1 2 3 5
bing bing bing bing bing
(removed disposed tab)
but your result is
0 1 2 3 5
bing bing bing bing disposed(show nothing)
(removed last view of tab, which is wrong, but removed the correct tab)
which means the tabs removed correctly(we can check its content), but the last view is always be remived instead of removing the view of selected tab.

**Comment by TysonMN** [comment]
I think your `getId` functions in both `SubModelSeq` bindings might be causing the problem.

Try adding a `Guid` to each tab and using that as the ID.  Alternatively, I think you can use this overload that doesn't require a `getId` function.
https://github.com/elmish/Elmish.WPF/blob/1a4f4384c469ae22f281ce489a811d772ceba5f7/src/Elmish.WPF/Binding.fs#L2991-L2993

Also, I recommend making the type of `SelectedId` optional.

Let me know if you are able to make progress or if you still need help.

**Comment by RickyYChan** [comment]
> I think your `getId` functions in both `SubModelSeq` bindings might be causing the problem.
> 
> Try adding a `Guid` to each tab and using that as the ID. Alternatively, I think you can use this overload that doesn't require a `getId` function.
> 
> https://github.com/elmish/Elmish.WPF/blob/1a4f4384c469ae22f281ce489a811d772ceba5f7/src/Elmish.WPF/Binding.fs#L2991-L2993
> 
> Also, I recommend making the type of `SelectedId` optional.
> 
> Let me know if you are able to make progress or if you still need help.

Appreciate! :) Following your suggestion, I've solved the question I've mentioned. 
since I think it's hard to use that overload, I use guid as an alternative. 
(sometimes we need to use both `'Model` and `seq<'subModel>` but it seems that the overload cannot do that
```fs
"TabSource" |> Binding.subModelSeq(
                (fun () ->  [
                        "TabContent" |> Binding.oneWay(fun t -> t.Content) 
                        "SelectItem" |> Binding.cmd(fun t -> Select t.Guid)
                        "TabBg" |> Binding.oneWay(fun t -> 
                            if t.Guid = m.SelectionId then accent else transparent) // how to use the "m" here?
                    ]))
                |> Binding.mapModel(fun m -> m.Tabs)
                |> Binding.mapMsg(fun (i, msg) -> msg)
```)

There's one more question. 
If I removed a tab just  like this: 
guid: 0 1 2  3 5 (removed 4)
then i want to add a tab. Generally, I think if we map our id to 0 1 2 3 4, everything should be easy if I reset their GUID. 
If not, then the guid of new tab is hard to determine.
So i add an Msg after removing 
```fs
| MapId -> { m with Tabs = m.Tabs |> Seq.mapi(fun i t -> { t with Guid = i }) }, Cmd.none
```
I noticed that this will cause incorrect behavior.

**Comment by RickyYChan** [comment]
By the way:
Using `System.Guid` instead of `int` as the GUID, I built an application that behaves correctly. :)

**Comment by TysonMN** [comment]
> [...] since I think it's hard to use that overload, I use guid as an alternative.

The GUID alternative is probably better anyway.

> sometimes we need to use both `'Model` and `seq<'subModel>` but it seems that the overload cannot do that

It can.  Change

```fsharp
|> Binding.mapModel(fun m -> m.Tabs)
```

to

```fsharp
|> Binding.mapModel(fun m -> m.Tabs |> Seq.map (t -> m, t))
```
