### ISSUE TITLE
Access model instance from view model

### ISSUE THREAD

**Issue by xperiandri** [elmish/Elmish.WPF#442]
**High-level description**

Imagine that we have a few Elmish programs started separately. And you need to pass data from one to another.
Those you need to somehow get the current model of the source Elmish program.

This is how it is doable now.

``` C#
namespace Wpf
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
        public App()
        {
            this.Activated += StartElmish;
        }

        private void StartElmish(object sender, EventArgs e)
        {
            this.Activated -= StartElmish;
            Program.main(MainWindow);

        }

        [STAThread]
        public static void Main()
        {
            var loginWindow = new LoginWindow();
            Login.Program.main(loginWindow);
            if (loginWindow.ShowDialog() != true) return;

            object loginVM = loginWindow.DataContext;
            var field = loginVM.GetType().GetField("currentModel", BindingFlags.NonPublic | BindingFlags.Instance);
            var loginModel = field.GetValue(loginVM) as Login.Program.Model;

            App app = new Microsynth.SlimsReporter.WPF.App();

            app.InitializeComponent();
            app.Run();
        }
    }
}
```

**Proposed solution**
I think that for this scenario we need to introduce `IElmishProgram` interface with the `CurrentModel` property. So that it can be rewritten

``` C#
IElmishProgram loginVM = loginWindow.DataContext as IElmishProgram;
var loginModel = loginVM.CurrentModel as Login.Program.Model;
```

or

``` C#
IElmishProgram<Login.Program.Model> loginVM = loginWindow.DataContext as IElmishProgram<Login.Program.Model>;
var loginModel = loginVM.CurrentModel;
```

**Additional Information**
Elmish.WPF version: 4.0
Target framework version: 5.0

**Comment by TysonMN** [comment]
I think using a command would be the proper way to achieve this

**Comment by xperiandri** [comment]
I fave no idea how you imagine that implementation

**Comment by TysonMN** [comment]
Can you share a GitHub repository with your current solution?  Then I will implement what I am suggesting.

**Comment by xperiandri** [comment]
I have not implemented it yet but if I would do that like this:
``` F#
type IElmishProgram<'model> =
    abstract CurrentModel : 'model

type ViewModel<'model, 'msg> =
...
    interface IElmishProgram<'model> with
        member this.CurrentModel = this.currentModel
```

In Elmish.Uno I also expose `CurrentModel` as an instance property of the `ViewModel` in order to bind a `DataTrigger` to it.
https://github.com/xperiandri/Elmish.Uno/blob/e9f5ebac60e4936e354e240c0b92062be9f3bd02/src/Elmish.Uno/ViewModel.fs#L571
This is useful when my model is a DU and when the case changes I want to know if it changed.

**Comment by TysonMN** [comment]
You can create a binding for such a model and trigger on that

**Comment by TysonMN** [comment]
I am not against this in principle, but I would like to see a completing use case first.
