### ISSUE TITLE
Start an Elmish program with a parameter

### ISSUE THREAD

**Issue by xperiandri** [elmish/Elmish.WPF#443]
**High-level description**

Imagine that we have a few Elmish programs started separately. And you need to pass data from one to another.
Those you need to pass an initial parameter to the destination Elmish program.
Elmish library supports this but Elmish.WPF does not have corresponding functions.

**Expected or desired behavior**
[Here is how it is implemented in Elmish.Uno](https://github.com/xperiandri/Elmish.Uno/blob/e9f5ebac60e4936e354e240c0b92062be9f3bd02/src/Elmish.Uno.Mobile/ViewModelModule.fs#L47)

**Actual behavior**
Starting a program with a parameter is not supported

**Additional Information**
Elmish.WPF version: 4.0
Target framework version: 5.0

**Comment by Evangelink** [comment]
I am probably missing what you want to do but you could capture the data you want to pass through one of the function you pass to Elmish.

```fsharp
 WpfProgram.mkProgramWithCmdMsg
        (init somethingCaptured)
        updateAndLog
        bindings
|> WpfProgram.startElmishLoop window
```

**Comment by TysonMN** [comment]
I am thinking the same as @Evangelink.

I have looked into why Elmish for Fable allows a parameter to be passed in.  I don't recall what I was able to conclude.

Can you share a GitHub repository with an example where you would like to pass in a parameter?

**Comment by xperiandri** [comment]
It is a crutch having that Elmish supports passing an initial parameter to a Program

**Comment by xperiandri** [comment]
I don't have it in a public repo yet but this is how I use it

``` C#
protected override void OnLaunched(LaunchActivatedEventArgs e)
{
	window = Windows.UI.Xaml.Window.Current;
	var rootFrame = window.Content as Frame;
	if (rootFrame.Content == null)
	{
// ---> Elmish app start
		var program = appProgram.Value.Program
		ViewModel.StartLoop(
			Host.ElmConfig, rootFrame, global::Elmish.ProgramModule.runWith, program,
// ---> this can be simplified on .NET5/6 with WinUI ommiting type cast
			(SuperCharge.Elmish.Windows.ApplicationExecutionState)e.PreviousExecutionState);

		// Place the frame in the current Window
		window.Content = rootFrame;
	}
...
}
```

``` F#
// ---> this enum can be accesses natively on .NET5/6 with WinUI 
/// Specifies the execution state of the app.
type ApplicationExecutionState =
    /// The app is not running.
    | NotRunning = 0
    /// The app is running.
    | Running = 1
    /// The app is suspended.
    | Suspended = 2
    /// The app was terminated after being suspended.
    | Terminated = 3
    /// The app was closed by the user.
    | ClosedByUser = 4
```

``` F#
type Program(serviceProvider : IServiceProvider) =

// ---> match state to choose a command to execute after launch
    let init (previousState : ApplicationExecutionState) : Model * Cmd<ProgramMessage<RootMsg, Msg>> =
        match previousState with
        | ApplicationExecutionState.NotRunning -> ...
        ...

    let update msg m : Model * Cmd<ProgramMessage<RootMsg, Msg>> =
        ...

    static let bindings = [
        ...
    ]

// ---> Create program as usuall
    member val Program = Program.mkProgramUno init updateRoot bindings
                         |> Program.withConsoleTrace

```

**Comment by TysonMN** [comment]
Instead of passing the argument into `ViewModel.StartLoop`, you can pass it into `appProgram.Value.Program`.
