### ISSUE TITLE
Cmd.OfAsync.result will be obsoleted in the future

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#444]
This is just a request for help with a slight issue, and it's not at all urgent.

From what I can understand, Cmd.OfAsync.result will [go away at some point in the future](https://github.com/elmish/elmish/issues/207). It was supposedly a bad idea, but I don't see why, considering how I use it.

I use Cmd.OfAsync.result all the time, in functions like this one. (It's from this sample repo that uses Elmish.WPF if anybody want a closer look: https://github.com/BentTranberg/ElmishXmas) I always struggle quite a bit with the basics of Elmish, also this time, so I wonder if I could have a little help finding the right code to replace Cmd.OfAsync.result in this particular use pattern. I am reasonably sure the proper solution will involve Cmd.OfAsync.either, and if that's the case I might be able to figure it out from there on my own, but not very sure.

```
// The types based on source and ideas from the Elmish Book.
type AsyncOperationStatusWithParameter<'a,'r> = Started of 'a | Finished of 'r
type AosParam<'a,'r> = AsyncOperationStatusWithParameter<'a,'r> // Abbreviation
type AsyncOperationStatus<'r> = AsyncOperationStatusWithParameter<unit,'r>
type Aos<'r> = AsyncOperationStatus<'r> // Abbreviation

_

    | DoSomeWork of Aos<Result<int,string>>
_

let private doSomeWork event (m: Model) =
    match event with
    | Started () ->
        { m with StatusText = "Starting." },
            Cmd.OfAsync.result (someWork () |> Async.map (Finished >> DoSomeWork))
    | Finished (Result.Ok value) ->
        { m with StatusText = $"Done, got {value}" }, Cmd.none
    | Finished (Result.Error error) ->
        { m with StatusText = $"Done, but with error {error}" }, Cmd.none

_

    | DoSomeWork event -> doSomeWork event m

_

    "DoSomeWork" |> Binding.cmd (DoSomeWork (Started ()))
```

**Comment by BentTranberg** [comment]
I don't see how I can remove the bug label, or create an issue without the bug label.

**Comment by TysonMN** [comment]
> I don't see how I can remove the bug label, or change it, or create an issue without the bug label.

You can create an issue without a template by clicking "Open a blank issue.".

Even so, I just removed the "bug" tag from the template.

![2021-12-05_14-06-25_702_chrome](https://user-images.githubusercontent.com/34664007/144762157-ec9688a6-d8cc-4627-8811-ec2d9e0aceaf.png)

**Comment by TysonMN** [comment]
I was planning on waiting until they release to figure out how to handle this.

**Comment by Evangelink** [comment]
@BentTranberg I think you could refactor your call as following

```fsharp
Cmd.OfAsync.perform (someWork >> Async.map (Finished >> DoSomeWork)) ()
```

**Comment by BentTranberg** [comment]
Oh, wow! Yes, that works. Thank you.

Now I finally understand that the `Result` in this case goes through the `ofSuccess` of `perform`. It's super obvious, but I just didn't see that possibility. With this in mind, I'll revisit the Cmd.OfAsync.xxxx functions and see what more I can understand about their actual purposes and usefulness.

@TysonMN, I'm closing. Reopen if you want it as a reminder to pursue this further.

**Comment by BentTranberg** [comment]
I'm used to, from other repos, that "Bug" and "Help" are listed as alternatives. I think that confused me. But I didn't find a way to remove the label after I got it wrong. But now I know how to get it right from the start, so this is ok.

**Comment by Evangelink** [comment]
@BentTranberg To add up, if your async method can throw an exception, you may want to use the `either` function for which you will have to pass 2 functions (success + failure cases).

**Comment by BentTranberg** [comment]
Thank you, that will improve my code. I also threw out `Result` from `Aos`, since I didn't quite see what good it did in there. Things seems simpler and not that entangled any more.

The line with `either` is a mouthful, and that pattern will have to be repeated. And so I wonder whether it's possible to wrap that in a helper function. Also, I can only call someWork with one argument now that I no longer use `Cmd.Async.result`, and I'm thinking a helper function could perhaps fix that too.

Please don't feel obliged to help me develop this further. Just sharing in case you're interested.

```
type Aos<'result,'error> =
    | Started
    | Finished of 'result
    | Failed of 'error
```

```
// Can throw.
let someWork () : Async<int> = async {
```

```
let private doSomeWork (event: Aos<int,exn>) (m: Model) : Model * Cmd<Msg> =
    match event with
    | Started ->
        { m with StatusText = "Starting." },
            Cmd.OfAsync.either someWork () (Finished >> DoSomeWork) (Failed >> DoSomeWork)
    | Finished result ->
        { m with StatusText = $"Finished, got {result}" }, Cmd.none
    | Failed ex ->
        { m with StatusText = $"Failed with exception {ex.Message}" }, Cmd.none
```

**Comment by Evangelink** [comment]
It mainly depends upon what you are trying to achieve, I think. 

In one app, I am mixing both `Result` and `either` because returning `Error` means a functional error and the error case of `either` represents an exception occurring (task canceled, server unreachable or anything else). I have a generic `CmdError of exn` msg that I am using for that and as I am reusing the pattern a lot I have created my wrapper around the `either` to have the callers passing only the function, arg and success case (keep in my success can be an `Error`).
