### ISSUE TITLE
What about when you're writing an addin and don't have control?

### ISSUE THREAD

**Issue by WillEhrendreich** [elmish/Elmish.WPF#457]
**High-level description**
I'm exploring writing an addin to Autodesk Inventor, and as such, I'm actually just creating class libraries. 

I tried to have it start elmish.wpf but it complains about no entry point.

**Steps to Reproduce**
I. really.. don't know? unless you also have Inventor, my exact repro won't probably do much good. 

**Expected or desired behavior**
That I would be able to use Elmish.Wpf for my plugin in Inventor. 

**Actual behavior**
it throws an EntryPointNotFound exception.

**Additional Information**
Elmish.WPF version: 4.0.0-beta-42
Target framework version: net48

I'm not sure if this is related, but I couldn't even get to the point where it would call the code below until I installed THE EXACT version of FSharp.Core.dll (4.6.2) and Microsoft.Extensions.Logging.Abstractions (3.1.6) that's referenced by Elmish.WPF. 
I find that really odd. I'm not sure why that would be the case.. usually I'd expect that newer versions of packages would be perfectly fine, but older ones not..

```
  let main (window:Window )=
    let logger =
      LoggerConfiguration()
        .MinimumLevel.Override("Elmish.WPF.Update", Events.LogEventLevel.Verbose)
        .MinimumLevel.Override("Elmish.WPF.Bindings", Events.LogEventLevel.Verbose)
        .MinimumLevel.Override("Elmish.WPF.Performance", Events.LogEventLevel.Verbose)
        .WriteTo.Console()
        .CreateLogger()
    WpfProgram.mkSimple init update bindings
    |> WpfProgram.withLogger (new SerilogLoggerFactory(logger))
    |> WpfProgram.startElmishLoop window
```

I got my addin window to work using PrismLibrary, using no MVU, only MVVM. 

I could do it because PrismLibrary has a way to use a Bootstrapper version of things instead of the whole PrismApplication. I'm not precisely sure what kind of difference there is other than it doesn't require the entry point anymore. If I have to ditch the dream of doing MVU for this I can, but I'd rather not go into OO land as much as possible. Taking on Prism as a MVVM framework would mean.. you know.. MVVM... so.. heavy on the impure.. thing.. haha.

**Comment by TysonMN** [comment]
> I. really.. don't know? unless you also have Inventor, my exact repro won't probably do much good.

Can you share the code anyway?

> I got my addin window to work using PrismLibrary, using no MVU, only MVVM.

Or maybe you could share that code?

In any case, I think what you want to do is possible.

> I'm not sure if this is related, but I couldn't even get to the point where it would call the code below until I installed THE EXACT version of FSharp.Core.dll (4.6.2) and Microsoft.Extensions.Logging.Abstractions (3.1.6) that's referenced by Elmish.WPF.
I find that really odd. I'm not sure why that would be the case.. usually I'd expect that newer versions of packages would be perfectly fine, but older ones not..

I think that is not related. Sorry about that. I can get that fixed and push a new release.

**Comment by WillEhrendreich** [comment]
Hey Thanks for getting back to me so fast!

I apologize, I'm rather new to F# in general, only started playing with it the last couple months, and this is my first real foray into MVU anything. 

ok, so. Uhm.. I'm trying to even figure out what would be relevant? 

```
open System.Windows.Interop
open System.Windows

module ButtonCommands =
  

  let startElmish window =
    Main.main window

  let initAndSetPluginView :Window =
    let v = downcast new MainWindowView()
    Globals.setPluginView v 
    startElmish v
    upcast v

  let makeNewWindow (docWindows:DockableWindows) internalname =   
    let myNewDockWindow = docWindows.Add( Globals.clientId, internalname, Globals.addinName )
    let v = initAndSetPluginView
    let wih = new WindowInteropHelper(v)
    myNewDockWindow.AddChild (wih.Handle)
    myNewDockWindow.Visible <- true
    v.Visibility <- Visibility.Visible
    v.WindowStyle <- WindowStyle.None
    myNewDockWindow

  let InitializeDockWindow (dockWindow:option<DockableWindow>) =
    let dw = 
      match dockWindow with 
      |Some d -> d
      |None-> Globals.setDockWindow (makeNewWindow (Globals.getDockWindows Globals.InvApp) Globals.DockWindowInternalName)     
    setVisible dw
    let pv = Globals.findPluginView
    match pv with
      |Some p -> 
        setVisible p
      |None -> initAndSetPluginView |> ignore

  let buttonPressed (buttonPressName:string) ( invApp:Inventor.Application)=
    match buttonPressName with
      |Globals.StartPluginButtonInternalName->   
        InitializeDockWindow Globals.DockWindow |> ignore
      |_ -> ()

```
when the button is pressed in inventor, the buttonpressed function gets called. that initilizes a dockable window within inventor, then attempts to create a wpf window, which succeeds, then it tries to pass that on to the code I pasted up there, and that's when it throws the exception. 

all told it seems like my problem has something to do with "startElmishLoop" because in looking at that code it tries to grab the Application.Current, or barring that, it tries to create a new one. 

I don't know how the Appdomain stuff really works, but my guess is if i could wrangle it to point Application.Current at Inventor instead, then perhaps I'd be ok?  But it's read only.

And things are even more complicated than that, because Inventor's method of doing plugins is actually based on a COM interop, so I believe it's even less straightforward because of that. It's certainly a mire to dig through, with way less discoverability on the types, etc. 

Anyway.. any ideas?

**Comment by TysonMN** [comment]
Yes, I have ideas, but I think it will be easier to explain them if you share your code via a link to a GitHub repo containing it.

Do you mind sharing your code in that way?

**Comment by TysonMN** [comment]
> > I'm not sure if this is related, but I couldn't even get to the point where it would call the code below until I installed THE EXACT version of FSharp.Core.dll (4.6.2) and Microsoft.Extensions.Logging.Abstractions (3.1.6) that's referenced by Elmish.WPF.
> > I find that really odd. I'm not sure why that would be the case.. usually I'd expect that newer versions of packages would be perfectly fine, but older ones not..
> 
> I think that is not related. Sorry about that. I can get that fixed and push a new release.

Version [4.0.0-beta-43](https://www.nuget.org/packages/Elmish.WPF/4.0.0-beta-43) is now available with a fix for that problem.

**Comment by WillEhrendreich** [comment]
unfortunately It's my employer's github repo, and I'm not really comfortable making the private repo public, is there some way I could temporarily invite you in or something? I'm not sure about how that works?

**Comment by WillEhrendreich** [comment]
> I'm not sure if this is related, but I couldn't even get to the point where it would call the code below until I installed THE EXACT version of FSharp.Core.dll (4.6.2) and Microsoft.Extensions.Logging.Abstractions (3.1.6) that's referenced by Elmish.WPF.
>         I find that really odd. I'm not sure why that would be the case.. usually I'd expect that newer versions of packages would be perfectly fine, but older ones not..
> 
>     I think that is not related. Sorry about that. I can get that fixed and push a new release.

> Version [4.0.0-beta-43](https://www.nuget.org/packages/Elmish.WPF/4.0.0-beta-43) is now available with a fix for that problem.

![image](https://user-images.githubusercontent.com/55286472/161555635-daf40042-c6f3-473d-b3ab-3837ece3c93b.png)


Is there something else I should be doing to not be bound to the version? I updated the nupkg..

**Comment by WillEhrendreich** [comment]
same result when i grab fsharp.core 4.6.2 and try it without a downgraded Microsoft.Extensions.Logging.Abstractions...

![image](https://user-images.githubusercontent.com/55286472/161558684-321a8066-6c9e-4163-9409-d4870cc9a4f6.png)

**Comment by WillEhrendreich** [comment]
God only knows why, but for some reason the problem was THE LOGGER!

![image](https://user-images.githubusercontent.com/55286472/161629650-5b256bd7-1fac-42fb-96ea-698b81814861.png)

That was a bear to track down.. there was ZERO indication that the logging was to blame, I was stepping through with a fine tooth comb.. lol. 

I'll gladly figure out why that isn't working some other time, but for now, I truly do not care. 

I'm just glad it got discovered. 

.. 

.. 

Ok, on second thought, I am somewhat curious why the logger needs an entry point.. ?  or.. how is this working? Do I have to try to get whatever the ILogger might be from Inventor? Do I spin off a separate console window to debug to? Is that what it really wanted all along?

**Comment by TysonMN** [comment]
> unfortunately It's my employer's github repo, and I'm not really comfortable making the private repo public

And I don't want you to share your employer's code with me.

Can you share a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?

> God only knows why, but for some reason the problem was THE LOGGER!
> ...
> That was a bear to track down...

Great work!

Don't worry about logging for now.  We can figure that out after we figure out your main issue.

**Comment by WillEhrendreich** [comment]
No, that's it, that was the main issue, it totally works now, aside from logging. 

I have ZERO idea why the logger would complain that it doesn't have an entry point and crash, but.. that's what the problem was.   
![giphy](https://user-images.githubusercontent.com/55286472/161773076-0f1dde0e-191c-41f1-994d-46527487bb5e.gif)

**Comment by TysonMN** [comment]
Ah, ok. I will look closely at that and see what I can figure out.

**Comment by TysonMN** [comment]
I don't see any reason why Elmish.WPF should cause that problem.  I also played around a bit trying to reproduce the problem but was unable to do so.

Can you share a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?

**Comment by WillEhrendreich** [comment]
Do you have access to Autodesk Inventor? My guess is it won't be reproduce-able unless it's called in the exact way that Inventor calls an addin. Since I don't know how the Addin system in Inventor works before the "ApplicationAddinServer" interface implementation that is created by the addin author is called, I'm not sure how to reproduce it in isolation..  
I'll gladly make an MRE, I'd love to help and see it solved, but how do we deal with the dependency on the main program?

**Comment by TysonMN** [comment]
> Do you have access to Autodesk Inventor?

I don't.

> I'm not sure how to reproduce it in isolation..

That's ok. It might help if I can see all your code though.
