### ISSUE TITLE
Difficulty getting started from examples and samples

### ISSUE THREAD

**Issue by releek** [elmish/Elmish.WPF#465]
**Problem with examples, samples and current library**
I'm new to this space and keen to use F# for visual output on Windows. I have tried using the example on the GitHub landing page for the project but there seem to be a number of breaking changes that may have been made to the project since it was documented for beginners.

Apologies in advance if I'm not using the examples correctly.

**Getting started example**
```
let main window =
  Program.mkSimpleWpf init update bindings
  |> Program.runElmishLoop window
```

`Program.runElmishLoop` is not defined

when I replace this with

`Program.startElmishLoop`

it generates the error

`Error FS0001 This expression was expected to have type 'ElmConfig' but here has type 'FrameworkElement'`

A look at the library states the function is of the form:
`startElmishLoop: config: ElmConfig -> element: System.Windows.FrameworkElement -> program: Elmish.Program<unit,'model,'msg,Binding<'model,'msg> list> -> unit`

But in the sample projects it is instead of the form:
`startElmishLoop: element: FrameworkElement -> program: WpfProgram<'model, 'msg>`

I'm just getting started and this is all quite confusing. I'm not sure how I should be generating and using the `ElmConfig` or what the difference is between a `Program` and a `WpfProgram`? Also,  `withLogger` also seems to be unavailable on `Program`.

Any help much appreciated.

**Comment by BentTranberg** [comment]
Can this be of help? : https://github.com/BentTranberg/ElmishXmas

**Comment by releek** [comment]
> Can this be of help? : https://github.com/BentTranberg/ElmishXmas

Thanks, this is helpful. Maybe the current documentation needs to be updated to reflect changes to the library's API?

**Comment by TysonMN** [comment]
Yes, the documentation needs updating.  The `master` branch is the prelease of version 4, which still needs work.  If you don't want to struggle with the changes, use the `v3` branch.

Also, feel free to create a PR to improve the documentation on either branch. That would be very helpful.
