### ISSUE TITLE
Visibility binding doesn't work in some samples

### ISSUE THREAD

**Issue by francotiveron** [elmish/Elmish.WPF#543]
**High-level description**
The element to be shown remains hidden

**Steps to Reproduce**
Run the sample and click on the Showing button

**Expected or desired behavior**
Elements should appear

**Actual behavior**
they don't

**Additional Information**
Elmish.WPF version: Elmish.WPF repo Nov 8 2022
Samples: Capabilities, SubModelOpt

**Comment by TysonMN** [comment]
@LyndonGingerich, can you fix this?

**Comment by LyndonGingerich** [comment]
I can't timebox further this week, but I found the additional bugs that the Deselect button is disabled even when there is a selection and that the Selected Index `TextBlock` displays -1 when there is no selection, 1 when A is selected, and 0 when B is selected, when we would expect A to come first.

**Comment by LyndonGingerich** [comment]
Cleaning the solution resolved all issues here mentioned for me. @francotiveron Care to clean yours and try again?
