### ISSUE TITLE
Change order of oneWayLazyWith arguments?

### ISSUE THREAD

**Issue by cmeeren** [elmish/Elmish.WPF#57]
The order of the arguments to `oneWayLazyWith` doesn't sit right with me. The current order (excluding `name` and adjusting type parameter names for clarity) is:

```f#
(equals: 'intermediate -> 'intermediate -> bool)
(get: 'model -> 'intermediate)
(map: 'intermediate -> 'final)
```

(The `oneWayLazy` function is the same, but doesn't have the `equals` parameter.)

Placing `equals` first only benefits partial application usages, which is irrelevant for this function. After having used it some, I find it unnatural to specify the equality check (for the intermediate values) before specifying the getter that maps the model to the intermediate values.

My suggestion is to move `equals` either between `get` and `map`:

```f#
(get: 'model -> 'intermediate)
(equals: 'intermediate -> 'intermediate -> bool)
(map: 'intermediate -> 'final)
```

Or alternatively after `map`:

```f#
(get: 'model -> 'intermediate)
(map: 'intermediate -> 'final)
(equals: 'intermediate -> 'intermediate -> bool)
```

This is, of course a breaking change. We're still on `2.0.0-beta` and this is a relatively new function, so I'm not too concerned about this, but opinions are welcome.

**Comment by JDiLenarda** [comment]
I can’t come with an opinion between `equals -> get -> map` and `get -> map -> equals` but `get -> equals -> map` feels odd in regard of `oneWayLazy`.

**Comment by cmeeren** [comment]
Thanks, I appreciate your opinion. Do you know why it feels odd to you?

**Comment by JDiLenarda** [comment]
`oneWayLazy` is `get -> map` and putting the additional parameter in between looks strange when you’re accustomed on how C# goes with overloaded method (knowing we’re not exactly dealing with overloaded function, of course).

**Comment by cmeeren** [comment]
A fair point, thanks.

**Comment by cmeeren** [comment]
While I see your point with overloading, after testing some more, I find myself leaning towards placing `equals` between `get` and `map`. Consider the following binding with a sizable `map` function (the actual contents are irrelevant) and `equals` placed last:

```f#
"Categories" |> Binding.oneWayLazyWith
  (fun  m -> m.Categories)
  (fun cats ->
    cats
    |> Map.toList
    |> List.map snd
    |> List.map (fun c ->
        { Id = c.Id
          Name = c |> Category.getDisplayName cats |> getVal }
    )
    |> List.sortBy (fun selector -> selector.Name)
  )
  LanguagePrimitives.PhysicalEquality
```

If I were to change the mapping to include another model member, the `equals` parameter is placed so far below `get` that I might forget about it. This will, in this case, produce bugs that are not caught by the compiler.

If `equals` is instead placed right after `get`, their proximity means it's harder to forget to change `equals`. Furthermore, IMHO it makes more sense to say "Here is how you get from A to B, here is how you determine if B has changed, and here is how you get from B to C" instead of "Here is how you get from A to B, here is how you get from B to C, and here is how you determine if B has changed".

**Comment by JDiLenarda** [comment]
As an after though, I realize that my argument falls flat if we consider the `name` parameter. As such, I'd go for keeping the original signature, but having for now never used `oneWayLazyWith` you're insight is surely better than mine.
