### ISSUE TITLE
Feature request: View model member exposed as Action<T>

### ISSUE THREAD

**Issue by LyndonGingerich** [elmish/Elmish.WPF#574]
When working with Elmish.WPF from WPF C# code-behind, I dislike using `ICommand` because it is untyped. `OneWayToSourceT` bindings are quite helpful, but sometimes I want to pass the call to a different part of my app as an `Action<T>`. Then I have to create a lambda manually that takes the new value and sets it. What would you think of implementing a setter binding type that is exposed directly as an `Action<T>`?

**Comment by LyndonGingerich** [comment]
@marner2 Says that using code-behind is a hack and we shouldn't adjust Elmish.WPF to facilitate it. :P

**Comment by TysonMN** [comment]
Indeed.  Typically use code behind only if that is the only solution.
