### ISSUE TITLE
How to update binding after validation

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#584]
**High-level description**
Describe your issue.

**Steps to Reproduce**
Strongly consider linking to a GitHub repository containing an application that reproduces your problem.  Ideally you have tired to obtain a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).  All four of the items in the External Links section in that Wikipedia article are excellent.

**Expected or desired behavior**
Describe what you expected or wanted to happen.

**Actual behavior**
Describe what actually happens.  Consider including a screen recording of the actual behavior via a GIF.  [ShareX](https://getsharex.com/) is one program that can capture a screen recroding and save it to a GIF.

**Additional Information**
Elmish.WPF version: ???
Target framework version: ???

**Comment by awaynemd** [comment]
In Elmish.WPF I am using the following code:

"Copay"         |> Binding.twoWayOpt((fun m ->Some (Copay.value m.Copay)), SetCopay) 
                       > Binding.addValidation(fun m -> match m with
                                                              |{Copay = Copay.InvalidCopay d} -> ["Invalid Copay"]
                                                              | _ -> []

Where "Copay" is the bound property to WPF and  the model defines Copay as:
 Copay: Copay.T

  module Copay = 
        type CopayData = { copay: string}
        type T =  
            | ValidCopay of CopayData
            | InvalidCopay of CopayData
       
        let formatMaskTextBox (s:string) = Regex.Replace( s, @"[^0-9.]","")

        let (|IsCopay|_|) (s:string) = if Regex.IsMatch(s,@"^\d{1,3}.\d{1,2}$") then Some (IsCopay s) else None

        // Define the constructor
        let create (ss: string option) = 
            match ss with
            |None -> InvalidCopay {copay = ""}
            |Some s -> match formatMaskTextBox s with
                       | IsCopay  t -> t |> float |> (fun d -> ValidCopay {copay = sprintf"%3.2f" d})  
                       | _ -> InvalidCopay {copay = s}
            

        // Define deconstructors/ unwrap.  Using "dot" notation to decompose the record.
        let value (f:T) = match f with
                          | ValidCopay d -> d.copay
                          | InvalidCopay d -> d.copay  

        let valueOption (f:T) = match f with
                                | ValidCopay d -> Some d.copay
                                | InvalidCopay d -> None

and SetCopay is:
 |SetCopay p                        -> {m with Copay = Copay.create p}, Cmd.ofMsg InvalidatePolicy 

All works correctly to validate an input digital payment. However, the "get" of the binding is executed only once before the
validation code reformats the copay. Hence, the wpf display does not show the "reformatted" input. 

Is there anyway to force the binding to update AFTER the validation code is run?

Thanks

**Comment by marner2** [comment]
Can you format your question better? I'm not seeing your validation code.

To try to answer the question generally, though, remember that Elmish.WPF utilizes an MVU architecture. The `View` only updates after an `Update` is applied to the `Model`. So any updates to the `Model` that aren't through an `Update` message will not be seen by the `View` until some other `Update` happens (the binding in this case is the `View`).

**Comment by awaynemd** [comment]
@marner2  Thank you for your response.  I don't see how to reformat the above without copy/paste ? The validation code  is being performed with the "match" statement  just below the "Copay" binding.  

As to your answer, I'm hopeful there is an override (of some sort) that would allow the  ".addValidtion" to trigger an update???

**Comment by marner2** [comment]
`Binding.addValidation` doesn't actually modify the underlying binding. It sets a parallel error object that WPF error templates can read and display (think of it like an extra bit of information attached to the `"CoPay"` binding). See [Data Validation -> Providing Visual Feedback in the WPF docs about Bindings](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/data/?view=netdesktop-7.0#providing-visual-feedback) for more information on how that works.

If you're wanting to modify the actual value in the model so that the `"CoPay"` binding updates, you would need to do that by modifying the model inside the `Update` function.
