### ISSUE TITLE
WPF Helpers: GetFocusedElement, GetSelectedElement(s), DragDrop, etc. :: A global approach ::

### ISSUE THREAD

**Issue by YkTru** [elmish/Elmish.WPF#594]
I know this is a common topic/problem in MVVM, but I still can't get my head around it, so beware, I may sound confused. (when I say "log", I mean in-app TextBlock logging, not Serilog)

- Is it a good idea to make a **"WPF Helper" module** to help with various harder to accomplish MVVM task? (get focuses/selected element for logging, set the border color of an element in a file to depend on an element in **another** file etc.)
- Does this [Elmish sample](https://github.com/elmish/Elmish.WPF/blob/master/src/Samples/EventBindingsAndBehaviors.Core/Program.fs) can be made as a **function (service)** so we won't have to repeat "GotFocus/LostFocus etc." for each element needed such behaviors? (idem for logging)
- Again with a "global approach" in mind, would you advise to make a **global anonymous style** (App.xaml) targeting x:Type UIElement (or FrameworkElement?) where I can put **behaviors** in a template (eg.: "LogWhenSelected/Focused", "ChangeBorderColorOnExternalEvent", "DragDropBehavior", etc)?

Could you provide advices on how to organize such a module + some code too please?

Thank you

**Comment by YkTru** [comment]
I've just found this which might be of interest: https://github.com/umairsyed613/Serilog.Sinks.WPF, but seems dead

And yesterday I tried some things using: [FocusManager]("https://learn.microsoft.com/en-us/dotnet/api/system.windows.input.focusmanager.getfocusedelement?view=windowsdesktop-8.0") but to no avail (I'm confused on how to "connect" the F# function using the FocusManager in my Core project (which can't acces the WPF project) to the WPF one; should I use a behavior somewhere with "GotFocus" as EventName that dispatch a "GetFocusedElement" Msg to update the "FocusedObject" field? But where to put that behavior, **maybe I could make in App.xaml a style that target all x:Type UIElement/FrameworkElement where I can put that behavior in a template**?.. but I would have to downcast somewhere I guess depending on the focused element? Damn... I'm so confused... I hate that "Can't access UI" paradigm sometimes..)

**Comment by TysonMN** [comment]
My impression is that these issues are all independent of Elmish.WPF.  Therefore, I don't think it would be a good idea to have helpers in Elmish.WPF for them.

My first recommendation would be to write the code you want and organize it in a reusable way.  If this became a large amount of code, then consider using an existing library that provides much of the same functionality.
