### ISSUE TITLE
[Sample] "SubModelSelectedItem" StaticVM equivalent? (+ a new sample proposition)

### ISSUE THREAD

**Issue by YkTru** [elmish/Elmish.WPF#613]
Hello,

From this [sample](https://raw.githubusercontent.com/elmish/Elmish.WPF/master/src/Samples/SubModelSelectedItem.Core/Program.fs), I can't get a Static VM version to work.

I tried looking at the source code:
```
 static member subModelSelectedItem
      (subModelSeqBindingName : string,
       get : 'model -> 'id voption,
       set : 'id voption -> 'model -> 'msg)
      : string -> Binding<'model, 'msg> =
    Binding.SubModelSelectedItem.vopt subModelSeqBindingName
    >> Binding.addLazy (=)
    >> Binding.mapModel get
    >> Binding.mapMsgWithModel set
    >> Binding.addCaching
```

But I'm not sure how to translate the equivalent (especially **subModelSeqBindingName** : string)

Here's what I've got now:
**DynamicVM**
`SelectedEntity“ |> Binding.subModelSelectedItem(”Entities”, (fun m -> m.Selected), Select)
`

**StaticVM**
```
    let selectedComponent_Binding =
        Binding.SubModelSelectedItem.vopt •???• 
        >> Binding.addLazy (=)
        >> Binding.mapModel m.Selected
        >> Binding.mapMsgWithModel •???• (why not just “mapMsg”? what's the difference?)
        >> Binding.addCaching
        >> Binding.boxT •???• (is this correct?)
```

Thank you very much

**[edit]** proposition for a [new sample](https://github.com/elmish/Elmish.WPF/issues/613#issuecomment-2354645350) using Static VM + how to deal wit Union of different components (DataTemplateSelector, IValueConverter, SubModelSelectedItem)

**Comment by YkTru** [comment]
@marner2 My intuitive guess would be to replace "subModelSeqBindingName : string" by ViewModelArgs is that right? 

Should a SubModelSelectedItemT be added to the library, or is there another way around by composing?

@xperiandri? (I havent found any equivalent in [ElmishUno](https://github.com/unoplatform/Elmish.Uno/blob/uno/src/Elmish.WPF/Binding.fs) )

**Comment by xperiandri** [comment]
Looks like it is not implemented correctly in ElmishUno
You need to modify `subModelSelectedItem` according to `subModelOpt`

**Comment by xperiandri** [comment]
Maybe you avoid its usage as `subModelSelectedItem` description suggests?

**Comment by YkTru** [comment]
Do you mean this part?
```
  ///   Only use this if you are unable to use some kind of <c>SelectedValue</c>
  ///   or
  ///   <c>SelectedIndex</c> property with a normal <see cref="twoWay" />
  ///   binding. This binding is less type-safe. It will throw when initializing
  ///   the bindings if <paramref name="subModelSeqBindingName" />
  ///   does not correspond to a <see cref="subModelSeq" /> binding, and it will
  ///   throw at runtime if the inferred <c>'id</c> type does not match the
  ///   actual ID type used in that binding.
```

I didn't think of another way since I was trying to stick to the same API as the sample but for a static Vm, what would you suggest instead?

**Comment by YkTru** [comment]
(I'll make a PR instead)

**Comment by YkTru** [comment]
**[update]** In a desperate attempt, I tried to only bind to a single element as in the SubModelSelectedItem sample but still, at runtime, when I select any TextBoxA the border of the ListView goes red and nothing happens.
```
    type Model = {
        Id: Guid
        Components: Components list
        SelectedComponent: Guid option

        ATextBoxes: TextBoxA.Model list //# single Model

        TextBoxA_Model: TextBoxA.Model
        TextBoxB_Model: TextBoxB.Model
        TextBoxC_Model: TextBoxC.Model
    }

```
```
    // Sample: "SelectedEntity" |> Binding.subModelSelectedItem("Entities", (fun m -> m.Selected), Select)    
    let findTextBoxAById id components =
        components
        |> List.choose (function
            | Form.TextBoxA a when a.Id = id -> Some a
            | _ -> None)

    let selectedTextBoxAItem_Binding =
        Binding.SubModelSeqKeyedT.id TextBoxA_VM _.Id
        >> Binding.mapModel (fun (model: Form.Model) ->
            match model.SelectedComponent with
            | Some selectedId -> 
                findTextBoxAById selectedId model.Components
            | None -> []
        )
        >> Binding.mapMsg (fun (guid, msg) -> Form.Select (Some guid))    

```
   ```
 member _.SelectedAItem
        with get() = base.Get() selectedTextBoxAItem_Binding
        and set(v) = base.Set(v) selectedTextBoxAItem_Binding

```
```
<ListView
    Height="400"
    HorizontalContentAlignment="Center"
    ItemsSource="{Binding Components}"
    SelectedItem="{Binding SelectedAItem, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}">
```

**Comment by marner2** [comment]
I don't have much time to review stuff in too much detail at the moment, but remember that in general "old-style" bindings work with the new static view models. They just cast your property to `obj` which only matters for intellisense. The `subModelSeqBindingName` argument would in this case be the actual name of the list property (use `nameof` if you can).

I can review this in more detail at a later point. Let me know if this helps.

I had originally avoided migrating this binding because of weird caveats with types, and the fact that the old one works just fine beings it's kind of a band-aid the way it is.

**Comment by YkTru** [comment]
@marner2 Yes, please! Could you only review some parts of the [Program.fs](https://github.com/YkTru/Test_SubModelSelectedItem/blob/master/test_subModelSelectedItem.Core/Program.fs) file where I've marked with "###"? It’s only a few lines. In fact, here are the specific parts I’m struggling with:
```fs 
module Form =

// Each has only a "Guid" and "Name" field
type Components =
    | TextBoxA of TextBoxA.Model
    | TextBoxB of TextBoxB.Model
    | TextBoxC of TextBoxC.Model

type Model = {
    Id: Guid
    Components: Components list
    SelectedComponent: Guid option
    
    (...)
}
```

```fs 
[<AllowNullLiteral>] type TextBoxA_VM (args) = inherit ViewModelBase<TextBoxA.Model, TextBoxA.Msg>(args)

member _.Name = base.Get() (Binding.OneWayT.id >> Binding.mapModel _.Name )
(...) ```

```fs 
[<AllowNullLiteral>] type Form_VM (args) = inherit ViewModelBase<Form.Model, Form.Msg>(args)

// "SelectedEntity" |> Binding.subModelSelectedItem("Entities", (fun m -> m.Selected), Select)

// I intuitively went with this, but ###I have absolutely no idea what to put as VM since I have 3 VM kinds (DU)..###
let selectedComponent_Binding =
    Binding.SubModelSeqKeyedT.id (*???*) _.Id
    >> Binding.addLazy (=)
    >> Binding.mapModel (fun (model: Form.Model) -> model.SelectedComponent)
    >> Binding.mapMsg Form.Select
```

If you have time, here are my struggles (how to deal with the DU + StaticVM is quite confusing to me honestly):

**[Q1]** Should I **pattern match Components** to get the different TextBoxABC_VMs?

**[Q2]** Or should I **make a Component_VM** that wraps the other VMs because Entities = Components? (Here I might sound totally confused—I know, because I totally am!)

**[Q3]-** **What code would you write** if you were to make it a Static binding (is it possible using the current API)? 

**[Q4]** And for the **"old-style bindings"** when you say: "The subModelSeqBindingName argument would in this case be the actual name of the list property (use nameof if you can).", what code would you write exactly? Because when I try (probably not in the right way), I get all sorts of confusing compiler errors.

HUGE thanks—I’ve wasted over 20 hours just trying to understand and make this work! I hope I'm not too demanding, I should be fit for a while afterwards.

**Comment by YkTru** [comment]
[update] I finally was able to pattern match submodels on a parent model, using a mix ("band-aid" of static and dynamic bindings. (I haven't pushed yet, since I want to add a DataTemplateSelector)

@marner2: Do you think it would be worth opening a PR to propose this as a sample once I add the DataTemplateSelector? It could demonstrate some ElmishWPF techniques on how to build a basic form designer using pattern matching for different components/submodels. (In fact, I think it would be a good extension of the subModelSelectItem sample without adding too much complexity or cognitive overload.)

Whenever you have time, you could update the "old-style" bindings in the PR to an entirely newer/modern static bindings style? (if I understood well, https://github.com/elmish/Elmish.WPF/issues/606#issuecomment-2179504498?

"In fact, I'm tempted to remove the model ones as you can always introduce it with a call to Bindings.mapMsgWithModel and just disregard the original msg (which is the obj parameter).
I'll try to look at that in more detail in the next few weeks, as I have time."

Thank you

**Comment by YkTru** [comment]
(I made a [PR](https://github.com/elmish/Elmish.WPF/pull/614))
