### ISSUE TITLE
-deleted-

### ISSUE THREAD

**Issue by YkTru** [elmish/Elmish.WPF#617]
**High-level description**
Describe your issue.

**Steps to Reproduce**
Strongly consider linking to a GitHub repository containing an application that reproduces your problem.  Ideally you have tired to obtain a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example).  All four of the items in the External Links section in that Wikipedia article are excellent.

**Expected or desired behavior**
Describe what you expected or wanted to happen.

**Actual behavior**
Describe what actually happens.  Consider including a screen recording of the actual behavior via a GIF.  [ShareX](https://getsharex.com/) is one program that can capture a screen recroding and save it to a GIF.

**Additional Information**
Elmish.WPF version: ???
Target framework version: ???

**Comment by TysonMN** [comment]
@et1975, can you delete this issue?  (Doing so requires org admin permissions.)
