### ISSUE TITLE
DataGrid.ItemSource SubModelSeq binding SelectedItem problem

### ISSUE THREAD

**Issue by rchybicki** [elmish/Elmish.WPF#63]
I'm moving my code to the new Elmish.WPF version and I'm having a problem making a DataGrid behave. The problem is related to the DataGrid tracking the SelectedItem (or SelectedIndex, or SelectedValue, the symptom is the same): 

If you bind a SubModelSeq to a DataGrid.ItemSource and let the rows have a TwoWay binding to the elements, the DataGrid will lose the SelectedItem as soon as any change happens. So if you select a cell to edit it, the row gets selected, you type one letter (in case of a UpdateSourceTrigger=PropertyChanged binding), the row loses the selection. 

The data flow works nicely both ways through model changes and messages, but the selection being lost, besides the fact that you might need to know the selected item as I do, also causes UI problems, the DataGridCells don't leave edit mode properly because of it.

For the Elmish approach, using a TwoWay SelectedValue Binding + SelectedValuePath that points to the Id on a DataGrid looks perfect, the values should be able to change and the datagrid should match the items by comparing ids, but it doesn't work, the DataGrid still loses the selection after each update.

I found a suggestion, that having the same GetHashCode on the item before and after the edit would solve the problem, but since the ViewModels are updated and not replaced that should already be true, right?

If the cause and solution are non-obvious, I will prepare a reproduction example.

**Comment by cmeeren** [comment]
As you say, the view model for each item should not be replaced, only modified. I see the behavior you describe in the SubModelCollection sample in this repo; I'll have a look at it.

**Comment by cmeeren** [comment]
Turned out to be a very simple fix. Releasing as 2.0.0-beta-5 shortly.

**Comment by rchybicki** [comment]
That was fast! Working perfectly now. Thank you, much appreciated.
