### ISSUE TITLE
Error on adding NuGet Package (2.0.0-beta-6)

### ISSUE THREAD

**Issue by goost** [elmish/Elmish.WPF#67]
Hey,

trying to add Elmish.WPF to a F# ConsoleApplication (.NET Framework 4.7.2) following the Quick Start in the Readme.
Nuget breaks with error
"Unable to find a version of 'Elmish' that is compatible with 'Elmish.WPF 2.0.0-beta-6 constraint: Elmish (>= 3.0.0-prerelease)'."

Manually installing latest pre-release Elmish (3.0.0-beta-2) does not solve the error, NuGet tells me the version of Elmish is not compatible.
What am I doing wrong?

**Comment by cmeeren** [comment]
Confirmed, also reproduces on a .NET Core 2.1 console app.

@et1975 any idea what's wrong? In Elmish.WPF's `package.dependencies` I have `nuget Elmish >= 3 prerelease`. As per the error message, shouldn't `constraint: Elmish (>= 3.0.0-prerelease)` be compatible with `Elmish 3.0.0-beta-2`?

**Comment by cmeeren** [comment]
I also notice that Elmish.WPF's `FSharp.Core` dependency has version constraint `>= 0.0.0`. That's very weird, because AFAIK with `nuget FSharp.Core redirects: force, lowest_matching: true` in the `paket.dependencies` it should be limited by the corresponding constraint in `Elmish`.

**Comment by goost** [comment]
Okay, thanks!
Is there a time frame, when the pre-releases are going to become releases?
Paket unfortunately did not work out for me, but installing via NuGet is broken for the moment.

**Comment by cmeeren** [comment]
There is currently no time frame for a final `2.0` release, though AFAIK the only hard requirement at the moment is that all dependencies (e.g. `Elmish`) must be out of prerelease before we can release a non-prerelease package.

Why didn't paket work out for you?

**Comment by cmeeren** [comment]
@et1975 this may be key:

> Warning NU1605 Detected package downgrade: Elmish from 3.0.0-prerelease to 3.0.0-beta-2

Do you have any idea why that warning appears, given this line for Elmish.WPF's dependency to Elmish?

https://github.com/elmish/Elmish.WPF/blob/dd631813786db1cf2c473ab51d85e68f0f704d82/paket.dependencies#L5

There [nothing incorrect here](https://fsprojects.github.io/Paket/nuget-dependencies.html#Prereleases) as far as I can see.

**Comment by et1975** [comment]
`Elmish >= 3 prerelease` might be semantically higher than `Elmish >= 3.0.0-beta-2`, I'm not sure which rules nuget goes by. I know `beta-` suffix can be tricky, but I need to indicate "here be dragons", things may break. I was waiting of Fable side to report how 3.0 is working out before doing a stable, but I haven't seen anything yet.

**Comment by cmeeren** [comment]
Hopefully this will be fixed in 2.0.0-beta-7 (#68).

**Comment by goost** [comment]
Thank you all for taking time to help!

**Comment by cmeeren** [comment]
Does it work correctly in 2.0.0-beta-7?

**Comment by cmeeren** [comment]
Thanks!
