### ISSUE TITLE
.net framework 4.5.2

### ISSUE THREAD

**Issue by JordanMarr** [elmish/Elmish.WPF#71]
I am unable to install to a .net 4.5.2 project via NuGet.  I was able to get it working by upgrading the project 4.6.1.  It looks like Elmish does not work with 4.5.2.  

It would be nice if the Elmish.WPF NuGet package had a hard dependency on 4.6.1 so that installing into a 4.5.2 project was disallowed in the first place.  Or maybe even a note on the README.md saying that 4.5.2 is not supported would be helpful.

**Comment by cmeeren** [comment]
The nuget package does indeed target .NET 4.6.1. You say that you were unable to install into a 4.5.2 project; it sounds to me like things then are working exactly like they should. :)

I'll add a note to the readme, though.
