### ISSUE TITLE
Checkboxes erroneously shown as failing validation

### ISSUE THREAD

**Issue by BillHally** [elmish/Elmish.WPF#78]
### Description

Using the latest version (2.0.0-beta-9) of Elmish.WPF, if you bind to a `DataGridCheckBoxColumn` in a `DataGrid`, then changing its  value results in an error being displayed by the validation template:

![screenshot](https://github.com/BillHally/Elmish.WPF.DataGridCheckBoxColumnIssue/raw/master/Screenshot0.png)

#### Repro steps

1. Create a `DataGridCheckBoxColumn` whose `Binding` is set to a 2-way Elmish.WPF binding.

1. Click to change the value of the `CheckBox`

An example script can be found in the repository [BillHally/Elmish.WPF.DataGridCheckBoxColumnIssue](https://github.com/BillHally/Elmish.WPF.DataGridCheckBoxColumnIssue). 

#### Expected behavior

CheckBox is displayed without incorrectly indicating that validation has failed.

#### Actual behavior

CheckBox *is* displayed incorrectly indicating that validation has failed.

#### Known workarounds

You could probably set a custom validation template that ignores errors (I've not tried).

#### Related information 

This is caused by [ViewModel.TrySetValue](https://github.com/elmish/Elmish.WPF/blob/5895b83da23beaec93dbd2f6b89b4e243fb8981c/src/Elmish.WPF/ViewModel.fs#L313) returning `false`. The reason it does so seems to be to avoid an [updating issue](https://github.com/elmish/Elmish.WPF/issues/10#issuecomment-416703094).

However, I've performed some tests with the script I linked to above, and it seems that this issue was fixed by the addition of this changeset ["adding UI thread synchronization option for .NET"](https://github.com/elmish/elmish/commit/07c021c0403188e7c16678e08ba0d9c79f6dbe50) to Elmish.

Consequently, I think that `TrySetValue` [should be changed to return true](https://github.com/BillHally/Elmish.WPF/commit/db90171bb71328ca80bb02afcd54b53298c8ecdc) when passed a binder whose name it recognises.

Making this change would resolve:

* [TwoBinding updating issue #74](https://github.com/elmish/Elmish.WPF/issues/74) (providing that `UpdateSourceTrigger` is set to `PropertyChanged`)
* [The error reported in issue #10](https://github.com/elmish/Elmish.WPF/issues/10#issue-238384835)

I'll send a pull request for the relevant changes.

**Comment by cmeeren** [comment]
> However, I've performed some tests with the script I linked to above, and it seems that this issue was fixed by the addition of this changeset ["adding UI thread synchronization option for .NET"](https://github.com/elmish/elmish/commit/07c021c0403188e7c16678e08ba0d9c79f6dbe50) to Elmish.

Ooh, nice! Yes, that makes sense.

**Comment by BillHally** [comment]
Thanks for responding so quickly!

**Comment by cmeeren** [comment]
You say that this also resolves 

> TwoBinding updating issue #74 (providing that UpdateSourceTrigger is set to PropertyChanged)

But wasn't the point of that issue that it only applied to `LostFocus`?

**Comment by BillHally** [comment]
I'm not sure why I thought it only fixed it when UpdateSourceTrigger is set to PropertyChanged. I've just tested it again, and (unless I'm misunderstanding what the expected behavior is) it behaves sensibly regardless of what it's set to.

**Comment by cmeeren** [comment]
Yes, you're right, I tested and it's fixed.

Thanks again!
