### ISSUE TITLE
How to build & view samples

### ISSUE THREAD

**Issue by wilsoncg** [elmish/Elmish.WPF#85]
I'm trying to build & open the sample view projects, but using my fresh VisualStudio 2019 is unable to load the projects:

> D:\Projects\fsharp\Elmish.WPF\src\Samples\NewWindow.Views\NewWindow.Views.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.
>
> Detailed Information:
> Project "C:\Program Files (x86)\Microsoft VisualStudio\2019\Enterprise\MSBuild\16.0\Bin\Microsoft.CSharp.targets" was not imported by "C:\Program Files\dotnet\sdk\2.2.203\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" at (41,3), due to the file not existing.

I have dotnet core sdk 2.2.203 installed so I don't think that's the issue:
> dotnet --info
> .NET Core SDKs installed:
>  2.2.203 [C:\Program Files\dotnet\sdk]

I have added the .net 4.7.1 SDK to my VisualStudio 2019 using the VS installer, but no luck. I also tried running the fake build script, but notice it intentionally does not build the sample View projects:

```fsharp
Target.create "Build" (fun _ ->
  // Building XAML projects (such as the sample view projects) doesn't work
  // yet using DotNet.build, so we skip those.
  !! "src/Elmish.WPF/*.*proj"
  |> Seq.iter (DotNet.build id)
)
```

What else am I missing?

Also, when I get a working build for viewing the samples I would be happy to add my steps somewhere, possibly to the Readme file or somewhere else?

**Comment by cmeeren** [comment]
There's a line in the csproj files referencing the targets,where you have to change 15.0 to Current. I haven't fixed it in the repo yet because I don't know if it makes things break for VS 2017.

**Comment by wilsoncg** [comment]
Nice one 👍
