### ISSUE TITLE
Cmd.batch does not work

### ISSUE THREAD

**Issue by mugisoba** [elmish/Elmish.WPF#88]
Hello,

I notice the weird behavior of `Elmish.WPF` & `Cmd.batch`.

```fsharp
type Msg =
  | Increment
  | Increment100Times

let update msg m =
  match msg with
  | Increment -> { m with Count = m.Count + 1 }, Cmd.none
  | Increment100Times -> m, Cmd.batch [ for _ in 1..100 -> Cmd.ofMsg Increment ] 
```

Increment100Times works with `Elmish-React` but not with `Elmish.WPF`.

* `Elmish-React` returns Count 100, as I expected.
* `Elmish.WPF` returns 27 :confused:

Any hint on how to do this?

Thanks.

**Comment by mugisoba** [comment]
hmm, Cmd.batch and init function works fine.

I guess something wrong with update + Cmd.batch.

```fsharp
let init () =
  { Count = 0 },
    Cmd.batch [ for _ in 1..100 -> Cmd.ofMsg Increment ] 

let update msg m =
  match msg with
  | Increment -> { m with Count = m.Count + 1 }, Cmd.none
```

**Comment by cmeeren** [comment]
I can confirm this behaviour. @et1975 this seems like an Elmish thing. Do you have any input?

For your convenience, please see the attached repro solution: [Repro.zip](https://github.com/elmish/Elmish.WPF/files/3221071/Repro.zip)

**Comment by et1975** [comment]
Please give elmish 3.0.1 a spin.

**Comment by mugisoba** [comment]
Thank you for your quick fixing!
New elmish 3.0.1 works perfectly 🍻
