### ISSUE TITLE
Update Loop Extremely Slow With Large ViewModel

### ISSUE THREAD

**Issue by ChernayaKoshka** [elmish/Elmish.WPF#91]
Hello,

I currently have a project that needs to load an extremely large data set into the ViewModel so that it can then be bound to a DataGrid. Each item that is bound to the data grid has a variety of sub-items that need to be displayed when clicked. So, I bound the selected item to a `SelectedItem` field of the ViewModel. This setup works fantastically, except when the data set is is very large. Then, it can take 3+ seconds to update the ViewModel and display the changes in the application.

I am curious if this is a known issue and if there are any fixes you can potentially suggest for my project. I have created a minimal and reproducible sample below, which uses the latest version of Elmish.WPF available on Nuget.org as of 6/21/19.

[Elmish.WPFPerformanceIssue.zip](https://github.com/elmish/Elmish.WPF/files/3315821/Elmish.WPFPerformanceIssue.zip)

I appreciate your assistance, thank you!

**Comment by cmeeren** [comment]
Hi! Thanks for the repro solution. I'm getting married tomorrow so I'll get back to this later this summer.

**Comment by ChernayaKoshka** [comment]
Congratulations!! There is no rush :)

**Comment by cmeeren** [comment]
Hi again!

I tried running the sample but got no window. Anyway, just from the code I can see what's probably wrong. You're using `Binding.oneWay` for a very large list of items. You must use a lazy binding, such as `oneWayLazy`, or perhaps even better in this example, `oneWaySeqLazy`:

```f#
"Items" |> Binding.oneWaySeqLazy(
  (fun m -> m.Items),
  refEq,
  id,
  (=),
  (fun item -> item.Name))
```

As for the sub-items, I would generally recommend that you don't have a `Name`/`Details` properties in your actual model, for two reasons. Firstly, this forces UI concerns on your domain model, and secondly, if you use `Binding.subModelSeq` or similar instead, you are free to use the same optimization techniques (e.g. lazy bindings) for the sub-items as for the parent-level items.

**Comment by ChernayaKoshka** [comment]
Hello,

`oneWaySeqLazy` is incredible! My items open up instantly and the window appears **much** faster. I read the intellisense documentation for `oneWaySeqLazy`, but I guess I'm failing to understand precisely how it works. Would you mind explaining how it works and why I would want to use it vs. `Binding.subModelSeq` vs. alternatives?

Rest assured, I'm not using UI-specific pieces in my ViewModel for my actual production tool :)

Thank you so much for your assistance!

**Comment by cmeeren** [comment]
All the `subModel` bindings are used for specifying separate bindings for the items in a collection. You can bind a collection to a list of domain entities in your model, and for each entity, you can specify separate bindings. Check the relevant sample(s) in this repo. :) In MVVM terms, `subModel` is for when you bind an `ItemsSource` or similar to a list of "sub"-ViewModels.

`oneWaySeqLazy` is just a special-case `oneWay` where you have "simple" values in your collection that should be used directly (no separate bindings for each sub-item). For example, if you have a list of thousands of primitive values that should be displayed in a list. If you use `oneWay`, the UI receives a fresh list on each update and must redraw the whole thing. If you use `oneWaySeqLazy`, then not only is it lazy (as described in `oneWayLazy`), but it's backed by a persistent `ObservableCollection` that is only updated as needed on each iteration. Again, see the relevant sample(s) in this repo. :)
