### ISSUE TITLE
Cmd.ofAsync blocks UI thread as of 2.0.0-beta-6

### ISSUE THREAD

**Issue by ChernayaKoshka** [elmish/Elmish.WPF#92]
Hello,

I have been using Elmish.WPF version 2.0.0-beta-5 for the past year to develop a pretty heavy developer-facing program. Yesterday, I decided it was about time to update to the latest version of Elmish.WPF. However, upon doing so, the messages I have that use `Cmd.ofAsync` (`Cmd.OfAsync.either` in later versions of Elmish) began to block the UI meaning that the progress indicators don't appear / update. 

I did some research into why this might be and it appears related to dd631813786db1cf2c473ab51d85e68f0f704d82 where the update loop was moved onto the UI thread. Unfortunately, Elmish starts the `Async` operations using `Async.StartImmediate` which means that they will block the UI thread in Elmish.WPF version 2.0.0-beta-6 and up.

Is there a new recommended pattern to prevent long-running operations (which will need to return a message) from blocking the UI thread?

I have also attached a [minimal reproducible example](https://github.com/elmish/Elmish.WPF/files/3477453/MinReproExample.zip). The solution in the `Delayed` folder is using the latest version of Elmish.WPF whereas the solution in the `Working` folder is using Elmish.WPF version 2.0.0-beta-5.

I appreciate your assistance.

**Comment by et1975** [comment]
Mea culpa, this needs to be addressed in Elmish. As you observed in the previous version the dispatch loop was running on a mailbox thread under .NET runtime and could make use of `StartImmediate`, but now it needs to run on the thread pool.

**Comment by TimLariviere** [comment]
@ChernayaKoshka You could use `do! Async.SwitchToThreadPool()` to make sure your long running operation does not block the UI thread.

```
async {
    do! Async.SwitchToThreadPool()
    // Your long running operation
}
```

@et1975 We have the same behavior in Fabulous, but in my opinion `StartImmediate` is good.
Switching threads can be costly (even more so on cheaper devices).

Given most of the times `Async` is exclusively used for I/O operations, it makes sense to "not switch" to a new thread from the thread pool by default.

**Comment by et1975** [comment]
Thanks for suggestion, Tim. However, to me this is a leftover from the days
elmish only ran on JS runtime and everything about async was faked.
From the API perspective, it doesn't satisfy "the least surprise"
principle: if user wanted to execute on the dispatch thread there would be
no reason to use OfAsync to begin with and if blocking for async seemed
like a good idea one could Async.RunSynchrnously. IMO IO is the perfect
reason to want execute on the threadpool and not block the UI.

**Comment by ChernayaKoshka** [comment]
Hello @et1975 ,

The longest operation I have pulls a massive data set from the local sqlite database and populates the UI with the result after transforming it. This operation can take anywhere from instantaneously to ~30 seconds depending on the size of the data set. The pattern I am using is something along the lines of:

1. Sending of a message `LoadData` which then sets up the async call and returns the model with a progress bar
2. After the processing has been completed, it kicks off a `SetData` message to populate the data set in the UI and remove the progress bar

@TimLariviere using `do! Async.SwitchToThreadPool()` fixed my issue. However, I would agree with @et1975 in that the behavior was quite surprising, to say the least.

**Comment by cmeeren** [comment]
Closing this since it's not Elmish.WPF, but please continue discussing. (I tried transferring the issue to elmish/elmish, but I think that requires write access to the repo, which I don't have.)

On a side note, it's nice to know that someone is actually using Elmish.WPF for real stuff!

**Comment by et1975** [comment]
> pulls a massive data set from the local sqlite database

Tim's point is that if you are using async APIs and awaiting on the resulting tasks (`Async.AwaitTask` probably?) it should not be blocking the dispatch thread for long - something like request preparation would still take some time, but it would be relativeley tiny and the bulk of the total time would be scheduled as continuation on the threadpool. What do you use to make the requests if you don't mind me asking?

**Comment by ChernayaKoshka** [comment]
I am using `System.Data.SQLite` for my database access. But, the database access piece was not what took the longest amount of time. The validation/transformations that happened afterwards took the longest time. They can take so long, I had wrapped them in an `async { ... }` block to prevent them from blocking the UI and allowing the progress bar to show up and show progress by using `cmd.ofAsync`.

Basically, the bulk processing was done in the first `async { ... }` block, which causes the UI to lock up due to `cmd.OfAsync.either` using  `Async.StartImmediate` and the dispatcher being moved to the UI thread. I guess at this point that my main piece of confusion was assuming that `cmd.OfAsync.either` would result in the operation taking place on a different thread (and that was technically true until later Elmish updates).

**Comment by et1975** [comment]
Ok, that's about what I imagined. I think I'm going to change the `OfAsync` functions to `Async.Start` and reintroduce `StartImmediate` under `OfAsyncImmediate` module for cheap ops like kicking off the IO.

**Comment by cmeeren** [comment]
Is `OfAsyncImmediate` really necessary? Sure, context switching is "expensive", but is it really compared to IO in the context of WPF apps?

**Comment by et1975** [comment]
I think maybe Tim's point is not so much that it's expensive (but on lower-end ARM that well might be true), as it is wasteful in case of cheap async IO kick off. From Elmish perspective the change in the behavior between 2.x and 3.x is an oversight, but I think both deserve a first-class support.

**Comment by et1975** [comment]
Released as 3.0.5.

**Comment by cmeeren** [comment]
@et1975 I'm getting some problems when using 3.0.5 in [cmeeren/fable-elmish-electron-material-ui-demo](https://github.com/cmeeren/fable-elmish-electron-material-ui-demo). I'm getting the following warnings:

```
  WARNING in ./src/Renderer/SnackbarLib.fs
  Module Warning (from ./node_modules/fable-loader/index.js):
  C:/Users/Christer/Source/Repos/fable-elmish-electron-material-ui-demo/.fable/Fable.Elmish.3.0.5/cmd.fs(160,31): (160,42) warning FABLE: Async.Start will behave as StartImmediate - Inline call from ../../src/Renderer/SnackbarLib.fs(88,2)
   @ ./src/Renderer/Snackbars.fs 2:0-232 20:62-90 27:63-93 30:19-26 53:29-38 61:20-23 61:24-40 61:87-93 75:62-69
   @ ./src/Renderer/App.fs
   @ ./src/Renderer/Entry.fs
   @ ./src/Renderer/Renderer.fsproj
   @ multi ./src/Renderer/Renderer.fsproj ./src/Renderer/scss/main.scss

  WARNING in ./src/Renderer/Snackbars.fs
  Module Warning (from ./node_modules/fable-loader/index.js):
  C:/Users/Christer/Source/Repos/fable-elmish-electron-material-ui-demo/.fable/Fable.Elmish.3.0.5/cmd.fs(160,31): (160,42) warning FABLE: Async.Start will behave as StartImmediate - Inline call from ../../src/Renderer/Snackbars.fs(47,16)
   @ ./src/Renderer/App.fs 9:0-173 91:312-333 104:301-324 107:98-105 148:32-41 201:42-49
   @ ./src/Renderer/Entry.fs
   @ ./src/Renderer/Renderer.fsproj
   @ multi ./src/Renderer/Renderer.fsproj ./src/Renderer/scss/main.scss
```

They cause the compilation to halt, which stops Electron from opening. So it seems impossible for me to use 3.0.5 for that project at the moment.

**Comment by et1975** [comment]
Probably why I implemented it with StartImmediate originally... *sigh*
I don't see why it needs to be a warning though, it doesnt warn that there
are no threads and everything async is in fact sync. @alfonsogarciacaro any
chance of dropping that warning?

**Comment by cmeeren** [comment]
Off topic, but is there anywhere I can read more about async/promise in Fable? I can't remember reading that everything async is sync, so I'd like to understand it better.

**Comment by et1975** [comment]
> any official documentation on async/promise in Fable?

I don't recall seeing one, so I go by what I know of JS:
- as far as JS code is concerned it's always running in a singe-threaded environment
- true parallelism only exists in the runtime itself and is not visible to the JS consumers
- runtime APIs that used to take completion callbacks in the past are now defined as `Promise`, which is a monadic interface over the callbacks.
- so, while the code may run concurrently it is pre-emptively thingle-threaded

I haven't looked at `async` impl details, but from the above we can surmise that `async` implementation schedules completions either as callbacks with 0 timeout and the runtime allocates a slice of time to run things concurently (but not in parallel), or unwraps and executes the bindings immediately as the warning would suggest. 

Having layed this out I think I can modify the Fable version to be more like true `async` and schedule a 0-timeout call to `Async.StartImmediate`.

**Comment by alfonsogarciacaro** [comment]
AFAIK, the only difference between `Async.Start` and `Async.StartImmediate` is the latter guarantees that the async continuation will return to the thread that is spawning the asynchronous continuation (which is specially important for the UI thread). I wanted to remark that `Async.Start` won't start a new thread as this is not possible (or at least not easy) in JS.

But you're right @et1975 that `async` behavior in Fable has already other gotchas, as it's just translated as callbacks (and in fact can run synchronously if no true asynchronous native API is called). So in principle removing the warning should not be a huge issue. Votes? :)

**Comment by alfonsogarciacaro** [comment]
BTW, I do think it's a good idea to use `Async.Start` in .NET as the whole point of Elmish commands is they don't block the UI and Elmish already takes care of calling the `view` (and also `update`) function in the UI thread.

**Comment by cmeeren** [comment]
@et1975 any chance to have a look at this? Re. my [earlier comment](https://github.com/elmish/Elmish.WPF/issues/92#issuecomment-520182030).

**Comment by et1975** [comment]
I have, I can can publish a version where it just defaults to immediate
version under Fable today. I was hoping to mimic .net behavior by
scheduling async as 0 timeout callback, but since Fable core 3 dropped the
browser types I no longer have access to an ergonomic timer api and going
through System.Timers is... ugly. I'll publish something today though.

**Comment by cmeeren** [comment]
Thanks!

**Comment by et1975** [comment]
Try 3.0.6?

**Comment by cmeeren** [comment]
Works perfectly, thanks!

Regarding tests, note that the "error" in this case is a compiler warning.

**Comment by alfonsogarciacaro** [comment]
@et1975 You mean `setTimeout`, etc? You should be able to access them in the Fable.Core.JS module: https://github.com/fable-compiler/Fable/blob/eb25f3c6c76f09ef293a204c9597f0ff52a01392/src/Fable.Core/Fable.Core.JS.fs#L315-L318

**Comment by et1975** [comment]
Ah, good to know, thanks!
