### ISSUE TITLE
Obsolete TODO comment?

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#95]
There is a [TODO comment](https://github.com/elmish/Elmish.WPF/blob/992daf7e2dfa679a34bceffe31745fd87bed90eb/src/Samples/SubModelSeq/Program.fs#L165-L167) in the SubModelSeq example:
```
// TODO: moving up/down must be done at the correct level of hierarchy;
// currently if the hierarchy is A (B, C), D (where B and C are children of A)
// then D must be moved up three times before it's placed before A
```

I played around with this example, but I didn't find any bugs.  Everything seems to me to be working as expected.

Should this comment be removed?  If so, I can make a PR for that.

**Comment by cmeeren** [comment]
Thanks for the heads-up! I tested and it seems to work fine. No idea why, but the bug was uninteresting enough in the first place (in the context of it only being a simple demo to show unrelated stuff), so I won't spend more time thinking about it.

I removed the comment while I was at it.

**Comment by bender2k14** [comment]
Oh, you are too quick.  I just reproduce the problem.

The list of all counters needs to be `[A, B, C, D]` in that order with `B` and `C` children of `A`.  Actually, just `[A, B, C]` with 'B' a child of `A' suffices.

More specifically,
1. Run the application
2. Let the one exiting counter be `A`
2. Add a child counter `B` to `A`
3. Add a counter `C` without a parent via the button at the top
4. Click the up arrow button on counter `C`

Expected behavior:
`C` is the top counter

Actual behavior:
View is unchanged.  The model changed though from `[A, B, C]` to `[A, C, B]`.

**Comment by cmeeren** [comment]
Ah, the order in which you add them is important.

I reverted the commit now.

Again, since the bug isn't really relevant to what's being demoed, I don't really care that much about it. If you want the challenge of finding a good solution to it (that doesn't needlessly complicate the demo), feel free to have a go at it, but do it for yourself, not for me. :)
